# /* About */
# /* $Id$ */

[title]
Introduksjon

[text]
Dette er phpVideoPro versjon {version}, (c) 2001 Itzchak Rehberg, alle rettigheter
(og linker) er reservert. Inspirert av min favoritt programvare for dette formlet,
VideoPro (c) 1991-1994 Bernd Rickers, startet jeg utviklingen av min egen programvare
for hndtering av video - da p den ene side Videopro kun var tilgjengelig som en DOS
basert 'clipper' applikasjon, og p den andre siden nye viktige egenskaper som st°tte
for DVD og lydformater som Dolby Digital 5.1 manglet, og Bernd stoppet utviklingen i
1994. Jeg valgte PHP ikke kun med tanke p platformuavhengighet, men p denne mten
ville jeg ha tilgang p informasjonen uavhengig av hvor jeg befinner meg, i verste
fall ved  bes°ke en internet cafe :-)
[text]
P dette stadiet er phpVideoPro beregnet for enkeltbrukere. Dette kan endre seg i
framtidige versjoner - men ikke forvent flerbruker egenskaper i den nermeste framtiden...

[title]
Egenskaper

[text]
S hvikle egenskaper har phpVideoPro tilgjengelig? Som video hndterings programmvare
er den selvf°lgelig beregnet til  hndtere dine (private) filmsamling (den har ikke
som mlsetning  hndtere en video butikk, der mange kopier av det samme mediaet kan
eksistere). Du kan andre og legge til, vise en liste som inneholder alle filmene
eller vise en liste av tilgjengelig rom p dine video kassetter - og phpVideoPro
skiller mellom DVD, kj°pte/komersielle videoer (Original VideoTapes, OVT), videoer
som er innspilt selv (Recorded VideoTapes, RTV). Filter funkjoner hjelper deg i 
velge et bestemt utvalg av filmer og finne spesielle filmer i en st°rre samling.
[text]
Nye tjenester er planlagt, og utviklingen foregr fortl°pende. Perioden mellom nye
utgivelser er ikke konstant og vil trolig ikke bli det i framtiden - da "dette er
kun en hobby", og det er mye annent som krever min oppmerksomhet :) Men s lenge
jeg ikke har lagt til alle tjenestene <b>jeg</b> trenger (se doc/2do), kan du vµre
trygg p at det altid vil vµre en ny utgave tilgjengelig i l°pet av noen f uker!
So jeg avslutter med min standard ansvarsfraskrivelse: "Dette er kun en hobby, jeg
kan ikke love noe - jeg ber kun om at du holer kontakten...."
[text]
<div align=right>Itzchak Rehberg, August 2001</div>

[eof]

