<? /* list of actors, directors, composers */
 ?>
<? /* $Id$ */ ?>

[title]
Liste av Skuespillere, Regiss°rer og Komponister

[text]
Mens vi ikke glemmer <A HREF="{PHP_SELF}?topic=set_filter">filter reglene</A>,
vil disse meny valgene vise en liste av akt°rer og ansatte i filmer. Ved 
klikke p MediaNr, kan du vise/redigere detaljer i den filmen (se
<A HREF="{PHP_SELF}?topic=add_entry">rediger</A> eller legge in en ny film).

[eof]

