# /* add_entry */
# /* $Id$ */

[title]
Introduksjon

[text]
Ved † benytte deyye meny valget kan du legge til nye elementer i din video database.
De fleste feltene er selvforklarende, men det er noen f† som krever litt forklaring
(utenom det faktum at den tomme tekst boksen p† toppen er ment † inneholde tittelen
p† filmen ;):

[title]
MediaType

[text]
<IMG SRC="{base_url}help/img/mtype_nr.png" ALT="del av 'nytt element' meny: mediatype" ALIGN=LEFT HSPACE=5>
Feltet "MediaType" (markert med r°dt i bildet som er vist) tilbyr en liste av
tilgjengelige media typer † velge mellom. Dette feltet trenger i seg selv ingen
forklaring, tror jeg - men jeg vil gjerne rette oppmerksomheten mot de andre to
feltene der et to-delt MediaNr skal skrives inn (markert med bl† farge). Den f°rste
delen st†r for det fysiske mediaet, f.eks. kassett eller disk. Det andre delen
refererer til filmen p† dette mediaet. La oss si at du har tatt opp to filmer p†
kassett nr 20, s† er den f°rste filmen 20-1 og den andre filmen er 20-2.

[text]
La oss si at du har nettopp tatt opp to filmer p† en tom kassett, og n† °nsker
du † registrere dem i databasen. Er du sikker p† at du husker det siste fysiske
MediaNr du opprettet? Den gr°nne boksen hjelper deg i † finne ut det siste
opprettede nummeret <b> for hver media type</b>! Du kan †pne det for † se innholdet.
I denne prosessen har det ingen betydning hvilken verdi du har valgt - den gr°nne
boksen er kun til informasjon, og verdien er ikke lagret i databasen.

[text]
Men et siste ord om den bl† merket MediaNr: Kombinasjonen av tallene lagt inn her,
m.a.o. det fysiske mediaet samt den logiske enheten, sammen med den valgte MediaType,
m† vµre unikt i databasen. Det er, f. eks, kun ‚n DVD nr. 1 i din video samling, den
neste DVD burde vµre nr. 2, etc. Dette programmet er ikke beregnet til bruk for
administrasjon av video butikker eller komersielle video bibliotek, men kun til bruk for
personlige samlinger. :)

[title]
Opptaksdato

[text]
For n† f°lger dato feltet f°lgende format: Fire siffer for †r, et minus tegn,
to siffer for m†ned, minus tegn, og to siffer for dag (dette resultere i en
verdi som har formatet -MM-DD). For nye elementer i databasen, dette feltet
blir automatisk fylt inn med dagens dato. Jeg vil beholde dette systemet for n†
da det er tilstrekkelig for mitt eget form†l - og s† fremt ingen ber om en endring
vil det ikke bli endret :)

[title]
Kategorier

[text]
Kategorien som er valgt i den f°rste boksen vil bli vist sammen med filemns hoved
informasjon i listene. uansett, dersom du s°ker etter en film (for tiden ved † benytte
filter funksjonene) spesifier en kategori, alle tre kategorier vil bli benyttet,

[title]
Bemanning

[text]
Vµr p†passelig med † fylle inn riktig informasjon i feltene her: Det f°rste er
alltid for etternavn, og det f°rste er alltid for fornavn. Navn p† bemanningen
er ikke lagret sammen med fil informasjonen, men i separate tabeller. I film
informasjonen eksisterer det kun en referanse - s† dersom du senere s°ker etter
en bestemt person kan du f† problemer dersom navnet ikke er riktig fyllt inn. P†
<A HREF="http://www.qumran.org/homes/izzy/">demo siden</A>, har jeg allerede sett
eksempler p† at begge navn er lagt inn i ett felt, kun for † lagre to personer i
en definisjon. Selvf°lgelig <b>kan</b> du gj°re dette, men det er ikke den m†ten
jeg planlagt bruken, og noen tjenester programmet tilbyr har ikke tenkt p† denne
muligheten.

[text]
Vidre, det er ett felt "i liste" som kan krysses av ved hvert navn, . Dette
refererer ogs† til en nyttig tjeneste: Det vil bli mulig † liste f.eks. alle
skuespillere sammen med tittelen p† filmer de har spillt i. Ved † benytte dette
feltet kan du velge om denne filmen skal vises for den spesifike skuespilleren.
Dersom f.eks. din favoritt skuespiller n† spiller veldig seri°se roller, men
spillte i mere tvilsomme filmer tidligere som du har tatt opp for, humm, la oss
si av nysgjerrighet, men ikke °nsker at andre skal vite om det (ved † lese en
utskrift av databasen). Bare fjern merket i boksen, og skuespilleren  vil ikke
vises sammen med tittelen i skuespiller listen.

[eof]

