# /* medialist */
# /* $Id$ */

[title]
Liste av registrerte mediaer

[text]
Dette viser en liste som inneholder alle filmer lagret i databasen, normalt
sortert etter MediaType og MediaNr. Du kan endre rekkef°lgen ved † trykke p†
toppen av den tabell kolonnen du °nser at sorteringen skal vµre basert p†.
Dersom du har satt opp filtere, som er brukt til † velge disse elementene - s†
vil kun du filmene som korresponderer med filteret bli vist.

[text]
I denne versjonen kan en liste bli veldig lang; evnen til † begrense antall
elementer som blir vist er ikke tilgjengelig anda, men kan bli introdusert i
en senere versjon.

[text]
Fra denne listen kan du velge et enkelt element for † vise detaljer, og fra
den detalj skjermen kan du velge † <A HREF="{PHP_SELF}?topic=add_entry">rediger</A>
eller † slette et element.

[eof]

