# /* no_such_topic */
# /* $Id$ */

[title]
Emnet ble ikke funnet

[text]
Beklager - det eksisterer for tiden ingen hjelp for dette emnet, eller en feil
har oppst†tt, eller du har funnet en feil i programvaren. Det siste er tilfelle
dersom du kan finne hjelp for dette emnet via hjelpe indeksen. I s† tilfelle,
vennligst send en beskjed til <A HREF="mailto:izzysoft@qumran.org">utvikleren</a>;
Denne spr°e utvikleren leser normalt ikke hjelpesidene, og finner sikkert ikke
slike feil :-)

[eof]

