# /* absolute taperest */
# /* $Id$ */

[title]
 finne ledig rom for opptak

[text]
Funksjonaliteten for  lete etter gjenvµrende tid er ment som et hjelpemiddel
for  finne ledig kapasitet for dine opptakbare mediaer (for n kassetter - RVT).
Du blir f°rst presentert med en liten skjerm der du blir bedt om  skrive inn den
minimums tiden du har behov for. Etter dette vil du f en liste av alle mediaer
som fyller di skriteriene du har definert, sammen med informasjon om hvilke filmer
som er p disse kassettene, deres kategori, og ledig kapasitet. Den ledige
kapasiteten er mlt i "normal play", s dersom du planlegger  ta opp noe i
"long play" modus, kan du fordoble den tiden som er vist.
[text]
Det er to meny valg for gjenvµrende tid: <b>filtrert</b> betyr at kun media som
inneholderminst en film som fyller kriteriene satt i 
<A HREF="{PHP_SELF}?topic=set_filter">filter reglene</a> er vist, mens <b>totalt</b>
ignorerer filter kriteriene.

[eof]

