# /* About */
# /* $Id$ */

[title]
Intro

[text]
Om du har för många DVDs och videokassetter att hantera, då behöver du ett bättre 
system! Det är exakt därför som phpVideoPro skapades. Detta program är allt du
behöver för att få din gigantiska samling under kontroll. Informationen blir mycket lätt-
tillgänglig!

[title]
Historia

[text]
PhpVideoPro var inspirerat av Bernd Rickers' VideoPro, som är tillgänglig i ett
DOS-baserat inklistringsprogram (senast släppt 1994) så väl som i en Windows-
version (med början cirka 1993 - detta är nu känt under namnet Video-5, se
<A HREF="http://www.bernd.rickers.de.vu/" TARGET="_blank">Bernds hemsida</A>
för detaljer). PhpVideoPro var designat med hjälp av PHP p g a flerplattforms-
möjligheter och fördelen med att kunna ha sin information tillgänglig varsomhelst, 
närsomhelst. 

[title]
Funktioner

[text]
Detta program tillåter dig att lägga till och ändra noteringar då det behövs. PhpVideoPro kan 
konfigureras till att visa din katalog på begäran. Du kan kolla på dina föremål i en lista
som innehåller alla dina noteringar eller så kan du be programmet att visa en lista 
på tillgängligt ledigt utrymme på dina egengjorda videokassettband. Du kan kolla in detajler på en
specifik notering, eller visa en lista på alla filmer med en viss skådespelare - bara för att
nämna några exempel.
[text]
Så du kan hålla reda på vad som är vad och vad du tänker lägga till i din 
garderob av skatter! Filter-funktioner hjälper dig att sortera genom din katalog
genom att skapa underkategorier och hitta speciella noteringar inom din alltid-förökande
samling.
[text]
Även fast du eventuellt har tillräckligt med kassetter och DVDs för att göra din
egen version av Blockbuster, så var inte phpVideoPro designat för att servera videobutiker. 
Den senaste versionen var inte skapad för att logga flera kopior av samma föremål. Vad programmet gör,
däremot, är att urskilja DVDs, original-videokassetter och kassetterna du
spelade in själv. Mer följer.

[title]
Framtiden

[text]
Nya funktioner är planerade, och utveckling fortsätter fortfarande. Frekvensen av nya
versioner är inte särskilt stadig och troligtvis kommer det aldrig att bli så - eftersom "det endast är en
hobby", och för att det är så många andra som kräver min närvaro :) Men så länge som
jag inte har lagt till alla funktioner som <b>I</b> behövs (se doc/2do), så kan du vara säker
på att det alltid kommer att finnas en fräsch version tillgänglig inom de närmaste kommande veckorna!
Så jag avslutar med min standard-fras: "Detta är bara en hobby, så jag kan inte lova dig
något - Jag bara ber dig att stanna kvar där du är..."
[text]
<div align=right>Itzchak Rehberg, September 2001</div>

[eof]
