<? /* lista på skådespelare, regissörer, kompositörer */
 ?>
<? /* $Id$ */ ?>

[title]
Lista på skådespelare, regissörer och kompositörer

[text]
Medan jag observerade <A HREF="{PHP_SELF}?topic=set_filter">filterreglerna</A>,
så visade dessa meny-föremål en lista på personalmedlemmar ordnade efter deras namn,
enbart listandes dem du definierat att vara "i listan" för filmerna. Genom att klicka
på MediaNr, kan du visa/redigera detaljer om filmen (se
<A HREF="{PHP_SELF}?topic=add_entry">redigera</A> eller lägg till en ny notering).

[text]
Medan denna lista kan bli en aning lång, så är den uppdelad på flera sidor. Du kan
definiera maximala antalet datasets per sida, genom att använda föremålet "*display_limit#"
på <A HREF="{PHP_SELF}?topic=configuration">*configuration#</A> menyn.

[eof]
