# /* medialist */
# /* $Id$ */

[title]
Lista på registrerad media

[text]
Detta visar en lista som innehåller alla filmer lagrade i din databas, per default
sorterat efter MediaType och MediaNr. Du kan ändra ordningen med föremål som visas
bara genom att klicka på tabellhuvudet i kolumnen du vill sortera efter. Om du
måste sätta upp lite filter, används dessa för att välja noteringar - så i detta fall
endast filmer som matchar filtren, visas.
[text]
Eftersom denna lista kan bli ganska lång, delar vi upp den på flera sidor. Hur många
rader med data som ska visas per sida, kan du konfigurera via föremålet
"*display_limit#" på <A HREF="{PHP_SELF}?topic=configuration">*configuration#</A>-sidan.
[text]
Från denna lista, kan du välja enstaka föremål att visa detaljerna för, och
från den detaljskärmen kan du avgöra att <A HREF="{PHP_SELF}?topic=add_entry">ändra</A>
eller tillochmed ta bort noteringen.

[eof]


