#
# list of languages and their keys
#

INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('aa','Afar','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('ab','аҧсуа бысжѡа','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('af','Afrikaans','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('am','አማርኛ','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('an','Aragonés','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('ar','عربي,','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('as','Assamese','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('av','Авар','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('ay','Aymar','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('az','Azərbaycanca','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('ba','Башҡорт','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('be','Беларуская','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('bg','Български','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('bh','भोजपुरी','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('bi','Bislama','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('bn','Bengali / Bangla','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('bo','Tibetan','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('br','Ar brezhoneg','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('bs','Bosanski','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('ca','Català','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('ce','Нохчийн','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('ch','Chamoru','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('co','Corsu','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('cr','Nehiyaw','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('cs','Čeština','UTF-8','No','0','1');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('cv','Чӑваш','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('cy','Cymraeg','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('da','Dansk','UTF-8','No','0','1');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('de','Deutsch','UTF-8','No','1','1');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('dv','Dhivehi','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('dz','Bhutani','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('ee','Eve','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('el','Ελληνικά','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('en','English','UTF-8','Yes','1','1');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('eo','Esperanto','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('es','Español','UTF-8','No','1','1');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('et','Eesti','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('eu','Euskara','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('fa','Fārsī','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('ff','Fulfulde','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('fi','Suomalainen','UTF-8','No','0','1');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('fj','Na Vosa Vakaviti','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('fo','Føroyskt','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('fr','Français','UTF-8','No','1','1');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('fy','Frysk','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('ga','Gaeilge na hÉireann','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('gd','Gàidhlig','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('gl','Gallego','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('gn','Avañe\'ẽ','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('gu','Gujarati','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('gv','Gaelg','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('ha','هَوُسَ','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('hi','हिन्दी','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('ho','Hiri Motu','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('hr','Hrvatski','UTF-8','No','0','1');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('hu','Magyar','UTF-8','No','0','1');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('hy','Հայերեն','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('hz','Otsiherero','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('ia','Interlingua','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('ie','Interlingue','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('ig','Igbo','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('ik','Iñupiak','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('in','Bahasa Indonesia','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('io','Ido','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('is','Íslensku','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('it','Italiano','UTF-8','No','1','1');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('iw','עברית','UTF-8','No','0','1');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('ja','日本語','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('ji','יידיש','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('jw','Basa Jawi','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('ka','ქართული','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('kk','қазақша','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('kl','Kalaallisut','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('km','Cambodian','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('kn','Kannada','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('ko','한국어','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('ks','कश्मीरी','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('ku','Kurdî ','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('kw','Kernewek','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('ky','Кыргызча','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('la','Latina','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('lb','Lëtzebuergesch','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('lg','Luganda','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('li','Limburgs','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('ln','Lingala','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('lo','ພາສາລາວ','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('lt','Lietuvių','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('lv','Latviešu','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('mg','Malagasy','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('mh','Ebon','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('mi','Māori','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('mk','Македонски','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('ml','Malayalam','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('mn','Монгол','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('mo','Moldoveana','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('mr','मराठी','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('ms','Bahasa Melayu','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('mt','Malti','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('my','Burmese','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('na','Nauru','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('ne','नेपाली','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('nl','Nederlands','UTF-8','No','0','1');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('no','Norsk','UTF-8','No','0','1');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('nv','Diné bizaad','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('ny','Chi Chewa','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('oc','Occitan','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('om','Oromoo','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('or','Oriya','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('pa','पंजाबी','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('pi','पािऴ','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('pl','Polski','UTF-8','No','0','1');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('pt','Português','UTF-8','No','0','1');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('qu','Runa Simi','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('rm','Rumantsch','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('rn','Kirundi','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('ro','Limba Română','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('ru','Русский','UTF-8','No','1','1');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('rw','Kinyarwanda','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('sa','संस्कृत','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('sc','Sardu','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('sd','सिनधि','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('se','Sámegiella','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('sg','Sängö','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('sh','Serbo-Croatian','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('si','Singhalese','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('sk','Slovenský','UTF-8','No','0','1');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('sl','Slovenščina','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('sm','Gagana Samoa','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('sn','chiShona','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('so','Soomaaliga','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('sq','Shqip','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('sr','Српски','UTF-8','No','0','1');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('ss','Siswati','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('st','Sesotho','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('su','Basa Sunda','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('sv','Svenska','UTF-8','No','0','1');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('sw','Kiswahili','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('ta','Tamil','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('te','Tegulu','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('tg','Тоҷикӣ','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('th','ภาษาไทย','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('ti','Tigrinya','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('tk','Türkmençe','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('tl','Tagalog','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('tn','Setswana','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('to','Tonga','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('tr','Türkçe','UTF-8','No','0','1');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('ts','Xitsonga','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('tt','Tatar','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('tw','Twi','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('ty','Reo Mā\`ohi','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('uk','Українська','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('ur','اردو','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('uz','Ўзбек','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('vi','Việt ngữ','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('vk','Vaijskäskhä','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('vo','Volapuk','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('wa','Walon','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('wo','Wolof','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('xh','isiXhosa','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('yo','Yorùbá','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('zh','中文','UTF-8','No','0','0');
INSERT INTO languages (lang_id,lang_name,charset,available,audio,subtitle) VALUES ('zu','isiZulu','UTF-8','No','0','0');
