#
# list of languages and their keys
#

INSERT INTO languages VALUES ('aa','Afar','UTF-8','No','0','0');
INSERT INTO languages VALUES ('ab','аҧсуа бысжѡа','UTF-8','No','0','0');
INSERT INTO languages VALUES ('af','Afrikaans','UTF-8','No','0','0');
INSERT INTO languages VALUES ('am','አማርኛ','UTF-8','No','0','0');
INSERT INTO languages VALUES ('an','Aragonés','UTF-8','No','0','0');
INSERT INTO languages VALUES ('ar','عربي,','UTF-8','No','0','0');
INSERT INTO languages VALUES ('as','Assamese','UTF-8','No','0','0');
INSERT INTO languages VALUES ('av','Авар','UTF-8','No','0','0');
INSERT INTO languages VALUES ('ay','Aymar','UTF-8','No','0','0');
INSERT INTO languages VALUES ('az','Azərbaycanca','UTF-8','No','0','0');
INSERT INTO languages VALUES ('ba','Башҡорт','UTF-8','No','0','0');
INSERT INTO languages VALUES ('be','Беларуская','UTF-8','No','0','0');
INSERT INTO languages VALUES ('bg','Български','UTF-8','No','0','0');
INSERT INTO languages VALUES ('bh','भोजपुरी','UTF-8','No','0','0');
INSERT INTO languages VALUES ('bi','Bislama','UTF-8','No','0','0');
INSERT INTO languages VALUES ('bn','Bengali / Bangla','UTF-8','No','0','0');
INSERT INTO languages VALUES ('bo','Tibetan','UTF-8','No','0','0');
INSERT INTO languages VALUES ('br','Ar brezhoneg','UTF-8','No','0','0');
INSERT INTO languages VALUES ('bs','Bosanski','UTF-8','No','0','0');
INSERT INTO languages VALUES ('ca','Català','UTF-8','No','0','0');
INSERT INTO languages VALUES ('ce','Нохчийн','UTF-8','No','0','0');
INSERT INTO languages VALUES ('ch','Chamoru','UTF-8','No','0','0');
INSERT INTO languages VALUES ('co','Corsu','UTF-8','No','0','0');
INSERT INTO languages VALUES ('cr','Nehiyaw','UTF-8','No','0','0');
INSERT INTO languages VALUES ('cs','Čeština','UTF-8','No','0','1');
INSERT INTO languages VALUES ('cv','Чӑваш','UTF-8','No','0','0');
INSERT INTO languages VALUES ('cy','Cymraeg','UTF-8','No','0','0');
INSERT INTO languages VALUES ('da','Dansk','UTF-8','No','0','1');
INSERT INTO languages VALUES ('de','Deutsch','UTF-8','No','1','1');
INSERT INTO languages VALUES ('dv','Dhivehi','UTF-8','No','0','0');
INSERT INTO languages VALUES ('dz','Bhutani','UTF-8','No','0','0');
INSERT INTO languages VALUES ('ee','Eve','UTF-8','No','0','0');
INSERT INTO languages VALUES ('el','Ελληνικά','UTF-8','No','0','0');
INSERT INTO languages VALUES ('en','English','UTF-8','No','1','1');
INSERT INTO languages VALUES ('eo','Esperanto','UTF-8','No','0','0');
INSERT INTO languages VALUES ('es','Español','UTF-8','No','1','1');
INSERT INTO languages VALUES ('et','Eesti','UTF-8','No','0','0');
INSERT INTO languages VALUES ('eu','Euskara','UTF-8','No','0','0');
INSERT INTO languages VALUES ('fa','Fārsī','UTF-8','No','0','0');
INSERT INTO languages VALUES ('ff','Fulfulde','UTF-8','No','0','0');
INSERT INTO languages VALUES ('fi','Suomalainen','UTF-8','No','0','1');
INSERT INTO languages VALUES ('fj','Na Vosa Vakaviti','UTF-8','No','0','0');
INSERT INTO languages VALUES ('fo','Føroyskt','UTF-8','No','0','0');
INSERT INTO languages VALUES ('fr','Français','UTF-8','No','1','1');
INSERT INTO languages VALUES ('fy','Frysk','UTF-8','No','0','0');
INSERT INTO languages VALUES ('ga','Gaeilge na hÉireann','UTF-8','No','0','0');
INSERT INTO languages VALUES ('gd','Gàidhlig','UTF-8','No','0','0');
INSERT INTO languages VALUES ('gl','Gallego','UTF-8','No','0','0');
INSERT INTO languages VALUES ('gn','Avañe\'ẽ','UTF-8','No','0','0');
INSERT INTO languages VALUES ('gu','Gujarati','UTF-8','No','0','0');
INSERT INTO languages VALUES ('gv','Gaelg','UTF-8','No','0','0');
INSERT INTO languages VALUES ('ha','هَوُسَ','UTF-8','No','0','0');
INSERT INTO languages VALUES ('hi','हिन्दी','UTF-8','No','0','0');
INSERT INTO languages VALUES ('ho','Hiri Motu','UTF-8','No','0','0');
INSERT INTO languages VALUES ('hr','Hrvatski','UTF-8','No','0','1');
INSERT INTO languages VALUES ('hu','Magyar','UTF-8','No','0','1');
INSERT INTO languages VALUES ('hy','Հայերեն','UTF-8','No','0','0');
INSERT INTO languages VALUES ('hz','Otsiherero','UTF-8','No','0','0');
INSERT INTO languages VALUES ('ia','Interlingua','UTF-8','No','0','0');
INSERT INTO languages VALUES ('ie','Interlingue','UTF-8','No','0','0');
INSERT INTO languages VALUES ('ig','Igbo','UTF-8','No','0','0');
INSERT INTO languages VALUES ('ik','Iñupiak','UTF-8','No','0','0');
INSERT INTO languages VALUES ('in','Bahasa Indonesia','UTF-8','No','0','0');
INSERT INTO languages VALUES ('io','Ido','UTF-8','No','0','0');
INSERT INTO languages VALUES ('is','Íslensku','UTF-8','No','0','0');
INSERT INTO languages VALUES ('it','Italiano','UTF-8','No','1','1');
INSERT INTO languages VALUES ('iw','עברית','UTF-8','No','0','1');
INSERT INTO languages VALUES ('ja','日本語','UTF-8','No','0','0');
INSERT INTO languages VALUES ('ji','יידיש','UTF-8','No','0','0');
INSERT INTO languages VALUES ('jw','Basa Jawi','UTF-8','No','0','0');
INSERT INTO languages VALUES ('ka','ქართული','UTF-8','No','0','0');
INSERT INTO languages VALUES ('kk','қазақша','UTF-8','No','0','0');
INSERT INTO languages VALUES ('kl','Kalaallisut','UTF-8','No','0','0');
INSERT INTO languages VALUES ('km','Cambodian','UTF-8','No','0','0');
INSERT INTO languages VALUES ('kn','Kannada','UTF-8','No','0','0');
INSERT INTO languages VALUES ('ko','한국어','UTF-8','No','0','0');
INSERT INTO languages VALUES ('ks','कश्मीरी','UTF-8','No','0','0');
INSERT INTO languages VALUES ('ku','Kurdî ','UTF-8','No','0','0');
INSERT INTO languages VALUES ('kw','Kernewek','UTF-8','No','0','0');
INSERT INTO languages VALUES ('ky','Кыргызча','UTF-8','No','0','0');
INSERT INTO languages VALUES ('la','Latina','UTF-8','No','0','0');
INSERT INTO languages VALUES ('lb','Lëtzebuergesch','UTF-8','No','0','0');
INSERT INTO languages VALUES ('lg','Luganda','UTF-8','No','0','0');
INSERT INTO languages VALUES ('li','Limburgs','UTF-8','No','0','0');
INSERT INTO languages VALUES ('ln','Lingala','UTF-8','No','0','0');
INSERT INTO languages VALUES ('lo','ພາສາລາວ','UTF-8','No','0','0');
INSERT INTO languages VALUES ('lt','Lietuvių','UTF-8','No','0','0');
INSERT INTO languages VALUES ('lv','Latviešu','UTF-8','No','0','0');
INSERT INTO languages VALUES ('mg','Malagasy','UTF-8','No','0','0');
INSERT INTO languages VALUES ('mh','Ebon','UTF-8','No','0','0');
INSERT INTO languages VALUES ('mi','Māori','UTF-8','No','0','0');
INSERT INTO languages VALUES ('mk','Македонски','UTF-8','No','0','0');
INSERT INTO languages VALUES ('ml','Malayalam','UTF-8','No','0','0');
INSERT INTO languages VALUES ('mn','Монгол','UTF-8','No','0','0');
INSERT INTO languages VALUES ('mo','Moldoveana','UTF-8','No','0','0');
INSERT INTO languages VALUES ('mr','मराठी','UTF-8','No','0','0');
INSERT INTO languages VALUES ('ms','Bahasa Melayu','UTF-8','No','0','0');
INSERT INTO languages VALUES ('mt','Malti','UTF-8','No','0','0');
INSERT INTO languages VALUES ('my','Burmese','UTF-8','No','0','0');
INSERT INTO languages VALUES ('na','Nauru','UTF-8','No','0','0');
INSERT INTO languages VALUES ('ne','नेपाली','UTF-8','No','0','0');
INSERT INTO languages VALUES ('nl','Nederlands','UTF-8','No','0','1');
INSERT INTO languages VALUES ('no','Norsk','UTF-8','No','0','1');
INSERT INTO languages VALUES ('nv','Diné bizaad','UTF-8','No','0','0');
INSERT INTO languages VALUES ('ny','Chi Chewa','UTF-8','No','0','0');
INSERT INTO languages VALUES ('oc','Occitan','UTF-8','No','0','0');
INSERT INTO languages VALUES ('om','Oromoo','UTF-8','No','0','0');
INSERT INTO languages VALUES ('or','Oriya','UTF-8','No','0','0');
INSERT INTO languages VALUES ('pa','पंजाबी','UTF-8','No','0','0');
INSERT INTO languages VALUES ('pi','पािऴ','UTF-8','No','0','0');
INSERT INTO languages VALUES ('pl','Polski','UTF-8','No','0','1');
INSERT INTO languages VALUES ('pt','Português','UTF-8','No','0','1');
INSERT INTO languages VALUES ('qu','Runa Simi','UTF-8','No','0','0');
INSERT INTO languages VALUES ('rm','Rumantsch','UTF-8','No','0','0');
INSERT INTO languages VALUES ('rn','Kirundi','UTF-8','No','0','0');
INSERT INTO languages VALUES ('ro','Limba Română','UTF-8','No','0','0');
INSERT INTO languages VALUES ('ru','Русский','UTF-8','No','1','1');
INSERT INTO languages VALUES ('rw','Kinyarwanda','UTF-8','No','0','0');
INSERT INTO languages VALUES ('sa','संस्कृत','UTF-8','No','0','0');
INSERT INTO languages VALUES ('sc','Sardu','UTF-8','No','0','0');
INSERT INTO languages VALUES ('sd','सिनधि','UTF-8','No','0','0');
INSERT INTO languages VALUES ('se','Sámegiella','UTF-8','No','0','0');
INSERT INTO languages VALUES ('sg','Sängö','UTF-8','No','0','0');
INSERT INTO languages VALUES ('sh','Serbo-Croatian','UTF-8','No','0','0');
INSERT INTO languages VALUES ('si','Singhalese','UTF-8','No','0','0');
INSERT INTO languages VALUES ('sk','Slovenský','UTF-8','No','0','1');
INSERT INTO languages VALUES ('sl','Slovenščina','UTF-8','No','0','0');
INSERT INTO languages VALUES ('sm','Gagana Samoa','UTF-8','No','0','0');
INSERT INTO languages VALUES ('sn','chiShona','UTF-8','No','0','0');
INSERT INTO languages VALUES ('so','Soomaaliga','UTF-8','No','0','0');
INSERT INTO languages VALUES ('sq','Shqip','UTF-8','No','0','0');
INSERT INTO languages VALUES ('sr','Српски','UTF-8','No','0','1');
INSERT INTO languages VALUES ('ss','Siswati','UTF-8','No','0','0');
INSERT INTO languages VALUES ('st','Sesotho','UTF-8','No','0','0');
INSERT INTO languages VALUES ('su','Basa Sunda','UTF-8','No','0','0');
INSERT INTO languages VALUES ('sv','Svenska','UTF-8','No','0','1');
INSERT INTO languages VALUES ('sw','Kiswahili','UTF-8','No','0','0');
INSERT INTO languages VALUES ('ta','Tamil','UTF-8','No','0','0');
INSERT INTO languages VALUES ('te','Tegulu','UTF-8','No','0','0');
INSERT INTO languages VALUES ('tg','Тоҷикӣ','UTF-8','No','0','0');
INSERT INTO languages VALUES ('th','ภาษาไทย','UTF-8','No','0','0');
INSERT INTO languages VALUES ('ti','Tigrinya','UTF-8','No','0','0');
INSERT INTO languages VALUES ('tk','Türkmençe','UTF-8','No','0','0');
INSERT INTO languages VALUES ('tl','Tagalog','UTF-8','No','0','0');
INSERT INTO languages VALUES ('tn','Setswana','UTF-8','No','0','0');
INSERT INTO languages VALUES ('to','Tonga','UTF-8','No','0','0');
INSERT INTO languages VALUES ('tr','Türkçe','UTF-8','No','0','1');
INSERT INTO languages VALUES ('ts','Xitsonga','UTF-8','No','0','0');
INSERT INTO languages VALUES ('tt','Tatar','UTF-8','No','0','0');
INSERT INTO languages VALUES ('tw','Twi','UTF-8','No','0','0');
INSERT INTO languages VALUES ('ty','Reo Mā\`ohi','UTF-8','No','0','0');
INSERT INTO languages VALUES ('uk','Українська','UTF-8','No','0','0');
INSERT INTO languages VALUES ('ur','اردو','UTF-8','No','0','0');
INSERT INTO languages VALUES ('uz','Ўзбек','UTF-8','No','0','0');
INSERT INTO languages VALUES ('vi','Việt ngữ','UTF-8','No','0','0');
INSERT INTO languages VALUES ('vk','Vaijskäskhä','UTF-8','No','0','0');
INSERT INTO languages VALUES ('vo','Volapuk','UTF-8','No','0','0');
INSERT INTO languages VALUES ('wa','Walon','UTF-8','No','0','0');
INSERT INTO languages VALUES ('wo','Wolof','UTF-8','No','0','0');
INSERT INTO languages VALUES ('xh','isiXhosa','UTF-8','No','0','0');
INSERT INTO languages VALUES ('yo','Yorùbá','UTF-8','No','0','0');
INSERT INTO languages VALUES ('zh','中文','UTF-8','No','0','0');
INSERT INTO languages VALUES ('zu','isiZulu','UTF-8','No','0','0');
