<? /* list of actors, directors, composers */
 ?>
<? /* $Id$ */ ?>

<H2 Align=Center>Liste der Schauspieler, Regisseure und Komponisten</H2>

<Table Width=90% Align=Center>
 <TR><TD>
  <P Align=Justify>Unter Berücksichtigung der
   <A HREF="<?=$PHP_SELF?>?topic=set_filter">Filterregeln</A> wird über diesen
   Menüpunkt eine Liste der jeweiligen Personen zusammen mit den Filmen, mit
   denen sie erfaßt wurden, angezeigt - sofern im betreffenden Film angegeben
   wurde, daß diese Person für diesen in der Liste aufgeführt werden soll
   (siehe zu <A HREF="<?=$PHP_SELF?>?topic=add_entry">Editieren</A> bzw.
   Erfassen eines Datensatzes). Durch klicken auf die MediaNr gelangt man
   zur Detailansicht, von der aus der Eintrag sodann bearbeitet oder auch
   gelöscht werden kann.</P>
 </TD></TR>
</Table>

