# /* How to create a new language file */
# /* $Id$ */

[title]
*intro#

[text]
Nicht zufrieden mit den vorhandenen Übersetzungen? Sind sie unvollständig? Oder
fehlen sie gar allesamt? Hier ist nun endlich der richtige Platz, um diesem
Problem relativ bequem bei zu kommen. phpVideoPro führt einfach durch die
notwendigen Schritte - und zum Schluss gipfelt das ganze in einer Sprachdatei
für phpVideoPro, die dann bitte an mich zu schicken ist :-)

[title]
*sel_target_lang#

[text]
Auf dieser ersten Seite ist die Sprache auszuwählen, deren Übersetzungen
bearbeitet werden sollen. Sind für diese Sprache bereits Übersetzungen in der
Datenbank vorhanden, werden diese auf den folgenden Seiten mit geladen. Niemand
sollte sich an dieser Stelle von der Tatsache irritieren lassen, dass alle
Sprachen den Zeichensatz "UTF-8" benutzen: Das ist so beabsichtigt und soll
auch so bleiben! Aber keine Sorge, Browser und Webserver sorgen in Zusammenarbeit
schon dafür, dass der lokale Zeichensatz ordnungsgemäß umgewandelt wird.

[title]
*admin_translations#

[text]
Nun kann mit der Bearbeitung der Übersetzungen begonnen werden. Vor dem Wechsel
auf die nächste Seite (mittels der bereits von anderen Listen, wie z.B. der
"*medialist#", bekannten Steuerelemente) sollte nicht vergessen werden, etwaige
Änderungen mittels des "*update#" Buttons zu speichern.

[title]
Fertig?

[text]
Dann wird es Zeit, die vollbrachte Arbeit in eine Datei zu sichern (hierfür ist
der Link "*save_lang_file#" am Ende der Seite vorgesehen). Damit steht sie nun
auch für neue Installationen zur Verfügung. Eine nette Geste wäre es an dieser
Stelle überdies, eine Kopie der Datei an den Autor von phpVideoPro, zu schicken
(EMail Adresse siehe <code>doc/README</code>): wer an meiner Arbeit so
kostengünstig teilhaben kann, hat so eine einfache Möglichkeit, "Dankeschön" zu
sagen - und andere Benutzer von phpVideoPro wird es sicher freuen, aktuelle
Übersetzungen in der nächsten Release vor zu finden :-)

[eof]
