# /* How to create a new language file */
# /* $Id$ */

[title]
*intro#

[text]
Nicht zufrieden mit den vorhandenen Übersetzungen? Sind sie unvollständig? Oder
fehlen sie gar allesamt? Hier ist nun endlich der richtige Platz, um diesem
Problem relativ bequem bei zu kommen. phpVideoPro führt einfach durch die
notwendigen Schritte - und zum Schluss gipfelt das ganze in einer Sprachdatei
für phpVideoPro, die dann bitte an mich zu schicken ist :-)

[title]
*sel_target_lang#

[text]
Auf dieser ersten Seite ist die Sprache auszuwählen, deren Übersetzungen
bearbeitet werden sollen. Sind für diese Sprache bereits Übersetzungen in der
Datenbank vorhanden, werden diese auf den folgenden Seiten mit geladen. Mit der
Sprache wird auch der zu verwendende Zeichensatz ausgewählt, sofern er phpVideoPro
bekannt ist - andernfalls wird "ISO-8859-1" (= Latin-1) angenommen.

[title]
*admin_translations#

[text]
Handelt es sich bei der zu bearbeitenden Sprache um eine, die einen abweichenden
Zeichensatz verwendet, sollte auf dieser Seite zunächst über den Link
"*save_lang_file" am Ende der Seite die (unfertige) Sprachdatei gesichert, der
Zeichensatz in selbiger korrigiert (in der Zeile, die mit "UPDATE" beginnt) und
über die Seite "*admin# -&gt; *configuration#" neu eingelesen werden. Ebenso
ist es in vielen Fällen an dieser Stelle sinnvoll, die zu bearbeitende Sprache
auch als "Primäre Sprache" (über "*edit# -&gt; *preferences#") auszuwählen.

[text]
Nun kann mit der Bearbeitung der Übersetzungen begonnen werden. Vor dem Wechsel
auf die nächste Seite (mittels der bereits von anderen Listen, wie z.B. der
"*medialist#", bekannten Steuerelemente) sollte nicht vergessen werden, etwaige
Änderungen mittels des "*update#" Buttons zu speichern.

[title]
Fertig?

[text]
Dann wird es Zeit, die vollbrachte Arbeit in eine Datei zu sichern (wiederum
über den Link "*save_lang_file#" am Ende der Seite). Damit steht sie nun auch
für neue Installationen zur Verfügung. Eine nette Geste wäre es an dieser Stelle
überdies, eine Kopie der Datei an mich, den <A HREF="mailto:izzysoft@qumran.org">Autor</A>
von phpVideoPro, zu schicken: wer an meiner Arbeit so kostengünstig teilhaben
kann, hat so eine einfache Möglichkeit, "Dankeschön" zu sagen - und andere
Benutzer von phpVideoPro wird es sicher freuen, aktuelle Übersetzungen in der
nächsten Release vor zu finden :-)

[eof]
