# /* How to create a new language file */
# /* $Id$ */

[title]
Wie erstelle ich eine Sprachdatei für meine Muttersprache?

[text]
Dies ist leichter, als mancher denken mag – es sind nur wenige Schritte nötig:
[text]
<OL>
 <LI>Zunächst ist ein LogIn als Administrator erforderlich.</LI>
 <LI>Nun ist im Menü der Punkt "*admin# -&gt; *admin_translations#"
     auszuwählen…</LI>
 <LI>…und hier die gewünschte Zielsprache. Ein "Klick" auf "*submit#" führt
     dann direkt zur Bearbeitung der Übersetzungen.</LI>
 <LI>Sofern auf einer Seite Änderungen erfolgt sind, müssen diese (pro Seite)
     mittels des "*update#" Buttons gespeichert werden.</LI>
 <LI>Alles fertig? Dann gilt es nur noch, die Übersetzungen in eine Datei zu
     sichern.</LI>
</OL>

[text]
(für detailliertere Ausführungen siehe
<a href={PHP_SELF}?topic=admin_translations>*admin_translations#</a>).
So, und jetzt würde ich mich freuen, eine Kopie dieser Datei zu erhalten, um sie
in zukünftigen Versionen von phpVideoPro verwenden zu können!

[title]
Die vorhandenen Übersetzungen für meine Sprache gefallen mir nicht…

[text]
Kein Problem. Siehe oben - gleiche Prozedur :-)

[eof]
