<? /* list of labels */
 ?>
<? /* $Id$ */ ?>

[title]
Druck von Etiketten

[text]
Hier läßt sich eine Liste von Etiketten erstellen. Die Anzahl der Etiketten
auf der Ergebnisseite hängt von der Anzal der ausgefüllten, nicht der vorhandenen
Zeilen ab (wenn also nur zwei Zeilen ausgefüllt wurden, gibt es auch nur zwei
Etiketten - und nicht etwa zwei ausgefüllte und drei leere :)

[text]
Die Regeln sind hier recht einfach: für jedes gewünschte Etikett sind der
Medientyp, die Nummer des Mediums und die zu verwendende Etiketten-Vorlage
anzugeben. Nachdem das Formular dann mit dem "*create#" Button abgeschickt
wurde, sollten die gewünschten Labels angezeigt werden und lassen sich sodann
mittels der Druckfunktion des Browsers zu Papier bringen.

[eof]

