# /* medium */
# /* $Id$ */

[title]
Media information

[text]
Diese Seite gibt einen Überblick über die Daten des ausgewählten Mediums.
Das beinhaltet die auf dem Medium gespeicherten Filme ebenso wie Angaben
zum Besitzer und Standort. Weitere Informationen sind verfügbar - abhängig
davon, welche Features vom jeweiligen Medientyp unterstützt werden (wie z.B.
RegionalCodes).

[text]
Im Editiermodus lassen sich einige dieser Daten ändern. Nur der Besitzer
desselben kann das Medium einem anderen Nutzer derselben
phpVideoPro-Installation übereignen.

[text]
Die Bedeutung der meisten Felder erklärt sich von selbst. Nicht alle lassen
sich bearbeiten - so lässt sich zum Beispiel der Sachverhalt, ob ein Medium
RegionalCodes unterstützt, nur global für den Medientyp einstellen (und nicht
für jedes Medium separat).

[eof]
