# /* medialist */
# /* $Id$ */

[title]
Liste erfaßter Medien

[text]
Auf dieser Seite wird eine Liste mit allen Filmen aus der Datenbank angezeigt,
die den definierten Filterregeln entsprechen. Standardmäßig ist diese nach
MedienTyp und MediaNr sortiert - diese Sortierung läßt sich jedoch einfach
durch einen Klick auf den Kopf der Spalte, nach der man gern sortieren möchte,
ändern.

[text]
In der gegenwärtigen Version kann diese Liste ziemlich lang werden -
insbesondere, wenn bereits größere Datenmengen erfaßt, jedoch keine
Filterregeln definiert wurden. Eine Einschränkung der Anzeige auf eine
bestimmte Anzahl von Datensätzen ist derzeit leider noch nicht möglich - steht
aber bereits auf der Aufgabenliste für eine zukünftige Version von phpVideoPro.

[text]
Aus dieser Liste heraus gelangt man mittels eines Mausklicks auf die MediaNr
zur Detailansicht des betreffenden Films, von wo aus man den entsprechenden
Eintrag sodann <A HREF="{PHP_SELF}?topic=add_entry">editieren</A> oder auch
löschen kann.

[eof]

