# /* medialist */
# /* $Id$ */

[title]
Liste erfaßter Medien

[text]
Auf dieser Seite wird eine Liste mit allen Filmen aus der Datenbank angezeigt,
die den definierten Filterregeln entsprechen. Standardmäßig ist diese nach
MedienTyp und MediaNr sortiert - diese Sortierung läßt sich jedoch einfach
durch einen Klick auf den Kopf der Spalte, nach der man gern sortieren möchte,
ändern.

[text]
Da diese Liste ziemlich lang werden könnte, wird ihre Ausgabe auf mehrere
Seiten unterteilt. Wie viele Datensätze pro Seite angezeigt werden sollen,
läßt sich über den Punkt "*display_limit#" im Menü
<A HREF="{PHP_SELF}?topic=configuration">*configuration#</A> einstellen.

[text]
Aus dieser Liste heraus gelangt man mittels eines Mausklicks auf die MediaNr
zur Detailansicht des betreffenden Films, von wo aus man den entsprechenden
Eintrag sodann <A HREF="{PHP_SELF}?topic=add_entry">editieren</A> oder auch
löschen kann.

[eof]

