<? /* no_such_topic */
 ?>
<? /* $Id$ */ ?>

<H2 Align=Center>Thema nicht gefunden</H2>

<Table Width=90% Align=Center>
 <TR><TD>
  <P Align=Justify>Zu diesem Thema ist leider keine Hilfe verfügbar - oder es
   ist ein Fehler aufgetreten. Läßt sich das Thema über den
   <A HREF="<?=$PHP_SELF?>">Hilfe Index</A> auffinden, trifft letzteres zu.
   In diesem Fall bitte ich um eine Nachricht mit genauer Beschreibung an
   <A HREF="mailto:izzysoft@qumran.org">mich</a>; diese verrückten
   Programmierer lesen im Normalfall ihre eigenen Hilfeseiten nämlich eher
   selten, und entdecken solche Fehler daher eher nie :-)</P>
 </TD></TR>
</Table>

