# /* no_such_topic */
# /* $Id$ */

[title]
Thema nicht gefunden

[text]
Zu diesem Thema ist leider keine Hilfe verfügbar - oder es ist ein Fehler
aufgetreten. Läßt sich das Thema über den <A HREF="{PHP_SELF}">Hilfe Index</A>
auffinden, trifft letzteres zu. In diesem Fall bitte ich um eine Nachricht mit
genauer Beschreibung an mich; diese verrückten Programmierer lesen im
Normalfall ihre eigenen Hilfeseiten nämlich eher selten, und entdecken solche
Fehler daher eher nie :-)

[eof]

