# /* medialist */
# /* $Id$ */

[title]
*intro#

[text]
Beim ersten Aufruf von phpVideoPro erscheint zunächst diese Seite. Von hier
aus - wie auch von fast jeder anderen Seite des Programmes - kann das
"Drop-Down" Menü zur Navigation verwendet werden. Und wie hier, so steht auch
auf den meisten anderen Seiten eine kontext-sensitive Hilfe zur Verfügung. Wer
(noch) nicht mit phpVideoPro vertraut ist, und sich daher zunächst einen
Überblick verschaffen will, kann dazu auch den Hilfe-Index verwenden.

[title]
Das Formular

[text]
Das kleine Formular auf dieser Seite dient der schnellen Navigation direkt
zu einem Datensatz - sofern dessen *MediaNr# bekannt ist. Zunächst ist dazu
der Medientyp in der Auswahlbox zu selektieren, und dann anschließend
zumindest der erste Teil der *MediaNr# einzugeben. Sodann bringt einen ein
"Klick" auf den <i>*view#</i> Button auf die "nächste Seite".

[text]
Wurde die *MediaNr# vollständig eingegeben, ist dies die Detailansicht für
den ausgewählten Film. Andernfalls wird eine Übersicht aller Filme auf dem
betreffenden Medium angezeigt, von der aus die einzelnen Einträge sich dann
direkt anspringen lassen.

[eof]
