# /* medialist */
# /* $Id$ */

[title]
*db_stats#

[text]
Diese Seite gibt einen Einblick in die Statistik der Datenbank. Eine
"Interaktion" ist hier nicht möglich, daher gibt es eigentlich auch nichts zu
erklären... Dennoch ein paar Worte:

[text]
Die Statistiken sind zweigeteilt. Der erste Block gibt einfach nur die "Summen"
aus, während der zweite eine Art "Hitliste" darstellt. Die Punkte sprechen
hier eigentlich für sich selbst; nur eine Kleinigkeit zum Ranking der Kategorien
gäbe es zu nennen: hier wird nur die Hauptkategorie ("*category# 1") ausgewertet;
diese sollte einen Film am besten beschreiben. Alles andere "arbeitet wie
gewohnt".

[eof]
