<? /* absolute taperest */
 ?>
<? /* $Id$ */ ?>

<Table Width=90% Align=Center>
 <TR><TD>
  <P Align=Justify>Mittels dieses Features läßt sich freier Platz in
   spezifizierter Größe lokalisieren - natürlich nur auf Medien, auf denen
   auch aufgenommen werden kann (derzeit nur RVT, "Recordable Video Tapes").
   Zunächst muß das benötigte Minimum an freiem Speicherplatz in ein
   Formular eingegeben werden. Ist dieses Formular versendet, wird entweder
   eine Liste mit all den Bändern angezeigt, auf denen mindestens der
   angegebene Platz verfügbar ist, zusammen mit der Information, welche
   Filme welcher Kategorie bereits auf diesen Bändern aufgenommen wurden sowie
   dem tatsächlich auf diesem Medium verfügbaren Speicherplatz - oder aber
   ein Hinweis, daß kein betreffendes Band in der Datenbank zu finden ist.
   Der "freie Platz" wird für normale Geschwindigkeit gerechnet - bei LongPlay
   kann diese Angabe daher verdoppelt werden.</P>
  <P Align=Justify>Es gibt zwei Möglichkeiten, diese Liste aufzurufen:
   <b>gefiltert</b> bedeutet, daß die definierten
   <A HREF="<?=$PHP_SELF?>?topic=set_filter">Filterregeln</A> Anwendung
   finden - <b>absolut</b> hingegen, daß diese unberücksichtigt bleiben.</P>
 </TD></TR>
</Table>

