<? /* absolute taperest */
 ?>
<? /* $Id$ */ ?>

[title]
Ermittlung von freiem Aufnahmeplatz

[text]
Mittels dieses Features läßt sich freier Platz in spezifizierter Größe
lokalisieren - natürlich nur auf Medien, auf denen auch aufgenommen werden kann.
Zunächst muss das benötigte Minimum an freiem Speicherplatz in ein Formular
eingegeben werden. Ist dieses Formular versendet, wird entweder eine Liste mit
all den Bändern angezeigt, auf denen mindestens der angegebene Platz verfügbar
ist, zusammen mit der Information, welche Filme welcher Kategorie bereits auf
diesen Medien aufgenommen wurden sowie dem tatsächlich auf diesem Medium
verfügbaren Speicherplatz - oder aber ein Hinweis, daß kein betreffendes Medium
in der Datenbank zu finden ist. Der "freie Platz" wird für normale
Geschwindigkeit gerechnet - bei LongPlay kann diese Angabe daher verdoppelt
werden.

[text]
Es gibt zwei Möglichkeiten, diese Liste aufzurufen: <b>gefiltert</b> bedeutet,
daß die definierten <A HREF="{PHP_SELF}?topic=filter">Filterregeln</A>
Anwendung finden - <b>absolut</b> hingegen, daß diese unberücksichtigt bleiben.

[eof]

