# /* About */
# /* $Id$ */

[title]
About phpVideoPro

[text]
<DIV ALIGN="center"><A HREF="{pvp->projectpage}" TARGET="izzysoft">phpVideoPro</A> v{version},
&copy; 2001-2009 by <A HREF="http://www.izzysoft.de/" TARGET="izzysoft">Itzchak
Rehberg</A></DIV>

[text]
<DIV ALIGN="center">This is free and open sourced software (<A TARGET="wiki"
HREF="http://en.wikipedia.org/wiki/Free_and_open_source_software">FOSS</A>),
which is protected by the <A HREF="http://en.wikipedia.org/wiki/Gpl"
TARGET="wiki">GPL</A>.</DIV>

[eof]

