<? /* list of actors, directors, composers */
 ?>
<? /* $Id$ */ ?>

<H2 Align=Center>Lists of Actors, Directors and Composers</H2>

<Table Width=90% Align=Center>
 <TR><TD>
  <P Align=Justify>While observing the filter rules, these menue items
   display a list of staff members ordered by their names, listing only those
   you defined to be "in list" for the movies. By clicking on the MediaNr,
   you can view/edit details of that movie.</P>
 </TD></TR>
</Table>

