<? /* list of actors, directors, composers */
 ?>
<? /* $Id$ */ ?>

[title]
Lists of Actors, Directors and Composers

[text]
While observing the <A HREF="{PHP_SELF}?topic=set_filter">filter rules</A>,
these menue items display a list of staff members ordered by their names,
listing only those you defined to be "in list" for the movies. By clicking on
the MediaNr, you can view/edit details of that movie (see
<A HREF="{PHP_SELF}?topic=add_entry">edit</A> or add a new entry).

[text]
Since this list can become quite long, it is split to multiple pages. You can
define the maximum number of datasets per page, using the item "*display_limit#"
on the "<A HREF="{PHP_SELF}?topic=configuration">*configuration#</A>" menu.

[eof]

