<? /* $Id$ */ ?>

[title]
*intro#

[text]
Many movies are available in different languages, concerning the synchronization
as well as possible subtitles. Especially with DVDs, there can be more than one
language available for the movie. phpVideoPro provides a field for audio as
well as one for subtitle tracks to store this information.

[text]
Now when it comes to edit the movies entry, how we deal with the languages?
Since there are more than hundred languages available, listing them all would
result in a quite long list which would not be easy to handle! But under normal
circumstances, even with a larger collection, the number of languages really
used is much smaller and contains maybe about 10 languages for audio and about
20 for subtitles - so we can restrict the list.

[text]
Still, what languages are in which list depends very much on the person owning
the collection (where (s)he lives, what languages (s)he prefers when bying or
recording movies etc.pp.), so there is no general rule we could apply. Hence I
left this decision to you, the user (or in this case better: administrator).

[title]
The list

[text]
Here all available languages are listed together with some information
concerning the language and phpVideoPro. In short, what do the columns mean?
<ul>
 <li><b>ID</b>: this is the international code used for this language</li>
 <li><b>*name#</b>: the name of the language</li>
 <li><b>*locale#</b>: whether you have the translations (for menus, dialogs
     etc.) of this language installed</li>
 <li><b>*audio_ts#</b>: whether this language is enabled for audio tracks</li>
 <li><b>*subtitle#</b>: whether this language is enabled for subtitle tracks</li>
</ul>
The icon in the last column allows you to edit the selected language concerning
the availability for audio and subtitle tracks. A "click" on this icon will
lead you to the...

[title]
Edit screen

[text]
The two sets of radio buttons allow you to en- or disable the given language
for audio resp. subtitle tracks. After changing these settings as required,
press the "<i>*update#</i>" button to save the changes. This will also bring
you back to the list at the page where you left it to call the edit screen.

[eof]
