<? /* administration of categories */
 ?>
<? /* $Id$ */ ?>

[title]
Administration of categories

[text]
Here you can edit the categories. If you don't like the translation, just
enter a different one into the "*category#" column. If you want to add a new
category, just fill in your data into the last (empty) line of the table.

[text]
One remaining risk is, that with the next update of phpVideoPro you might get
lost of those translations. To prevent this, edit the internal name in the
"*cat_internal_name#" column. It's always a good idea to stay to the rule that
an internal category name has to start with "cat_". However, you theoretically
may enter whatever you like - but then it may conflict with some other
translations, and your update may fail (either the category update on this
screen, since a similiar "key" already exists within the translations table,
or sometime later when you upgrade to a newer version, since <B>I</B>
decided to use the same term). Thus you prevent trouble if you follow my rules :)

[eof]

