<? /* administration of categories */ ?>
<? /* $Id$ */ ?>

[title]
*intro#

[text]
Disk types and RegionCodes always apply to the entire medium: This is why you
can't <b><i>edit</i></b> them together with a movie. You either set these values
when creating the first entry for a medium, or with this little screen.

[title]
*disk_type#

[text]
The disk type consists of one or two parts: the type itself and sometimes the
disk size. Both together help you to find out e.g. whether your (or s.o. elses)
player does support this medium, since e.g. some players don't support DVD-R
or self-burned media at all. Moreover, different disk types support different
features (such as e.g. RegionCodes for DVDs), plus for backups you can
immediately see if they can be easily done by a 1:1 copy.

[title]
*region_code#

[text]
When setting up the region code(s), there are technically no limitations
concerning their count. There are some disks supporting more than one (but not
all) regions, so I made it a "multiple choice" option. However, if you have DVDs
that support all region codes (called "code free"), you should only check the
box for RC 0, which means "code free" - no need to check 1 to 6 as well then.

[eof]
