<? /* credits to all who helped at this project */ ?>
<? /* $Id$ */ ?>

[title]
Intro

[text]
To not forget all those who support the project - hope I didn't forget somebody:
<BR>&nbsp;

[title]
Development Crew

[text]
<UL>
 <LI>The Beta-Testers and Bug-Reporters, especially Peter Bieringer for testing
     and help with PostgreSQL, and Michael Hasselberg for pointing out Bugs (if
     there were a "most reported award", it would belong to him!) plus inventing
     the new PostScript based label engine</LI>
 <LI>all the language support files generators: Tsvetanka Stoyanova for
     Bulgarian, Annette for French, Alessandro Danti and Jason Reaper for
     Italian, Knut Fjellheim for Norwegian, Leszek Boroch and Jacek Wolski for
     Polish, Tom Albers for Dutch, Tony Granberg for Swedish, Pablo Sanchez and
     Jaime Valdés-Pagés for Spanish, Denis Shvidkiy for Russian, Shalom Pollack
     for Hebrew (he deserves a very special credit for his hard work and
     patience - took us some special lessons with this special and holy
     tongue!)</LI>
 <LI>SourceForge and Freshmeat for hosting the project (well, and some other
     sites promoting it)</LI>
</UL>

[title]
Pre-Requisites

[text]
<UL>
 <LI>the Zend Team for giving us PHP, the MySQL and PostgreSQL teams for the
     databases</LI>
 <LI>Linus Torvalds (and all the Linux teams) for the development and runtime
     platform</LI>
</UL>

[title]
General

[text]
Of course I like to say "thank you" to all the other supporters I may have
forgotten at this place. If you know anybody you think should be mentioned here,
just drop me a note and I think about it :)

[eof]
