# /* How to create a new language file */
# /* $Id$ */

[title]
How can I create a language file for my native language?

[text]
It is not that difficult as you might think (in fact, right now it is the
easiest part of the "how to"s today), and requires only a few steps:
[text]
<OL>
 <LI>Log in as administrator</LI>
 <LI>Via the menu, go to "*admin# -&gt; *admin_translations#"</LI>
 <LI>Select the language you want to edit and click on "*submit#"</LI>
 <LI>Edit the phrases on the following pages. Make sure to hit the
     "*update#" button on each page when you changed anything or added some new
     translation.</LI>
 <LI>When you're finally done with the last page, you may want to save your
     results to disk.</LI>
</OL>

[text]
(see <a href={PHP_SELF}?topic=admin_translations>*admin_translations#</a> for
more details).
[text]
Now I would appreciate if you send me the resulting file to include it with
future versions of phpVideoPro!

[title]
The phrases for my language seem not suitable to me...

[text]
See above - the steps are exactly the same :-)

[eof]
