<? /* list of labels */
 ?>
<? /* $Id$ */ ?>

[title]
Label printing

[text]
Here you can print a list of labels. The amount of labels printed on the page
is defined by the media ids you enter, not by the lines in this form (so if you
fill in the first two lines only, you will just obtain two labels on the
result page - not two complete and three empty ones ;)

[text]
The rules for this page are very easy: chose the media type, media id and the
label template to use for each label you want to have included within the result
set, and then hit the button labeled "*create#" - your list of labels should
appear.

[eof]

