<? /* medialist */
 ?>
<? /* $Id$ */ ?>

<H2 Align=Center>MediaList</H2>

<Table Width=90% Align=Center>
 <TR><TD>
  <P Align=Justify>This displays a list containing all movies stored in your
   database, per default sorted by MediaType and MediaNr. You may change
   the order of items displayed just by clicking on the table header of the
   column you want to sort by. If you have set up some filters, they are used
   to select these entries - so in this case only movies matching the filters
   are displayed.</P>
  <P Align=Justify>In this current version, a list can become quite long; the
   ability to limit the number of entries displayed is not available yet, but
   may be introduced by a future version.</P>
  <P Align=Justify>From within this list, you can select a single item to
   display details of, and from within that detail screen you may decide to
   edit or even delete the entry.</P>
 </TD></TR>
</Table>

