# /* medialist */
# /* $Id$ */

[title]
List of registered media

[text]
This displays a list containing all movies stored in your database, per default
sorted by MediaType and MediaNr. You may change the order of items displayed
just by clicking on the table header of the column you want to sort by. If you
have set up some filters, they are used to select these entries - so in this
case only movies matching the filters are displayed.
[text]
In this current version, a list can become quite long; the ability to limit the
number of entries displayed is not available yet, but may be introduced by a
future version.
[text]
From within this list, you can select a single item to display details of, and
from within that detail screen you may decide to <A HREF="{PHP_SELF}?topic=add_entry">edit</A>
or even delete the entry.

[eof]

