# /* medium */
# /* $Id$ */

[title]
Media information

[text]
This page gives you an overview of the selected medium, displaying all
details which are important for it. This includes the list of movies stored
on this medium, but also information on who is the owner, and where it is
normally stored. Furthermore, additional information may be available if the
given media type supports it, such as the *region_code# the medium is
restricted to.

[text]
When in edit mode, you can change some or all of these data. If you are the
owner of the medium, you can transfer the ownership to any other user of this
phpVideoPro installation. The other fields should be self explanatory.

[text]
However, some fields cannot be changed here - such as if the medium is
(re)writeable or if it supports *region_code#. All this is to be set globally
for the affected media types, and not for the single medium.

[eof]
