# /* medium */
# /* $Id$ */

[title]
Media information

[text]
This page gives you an overview of the selected medium, displaying all
details which are important for it. This includes the list of movies stored
on this medium, but also information on who is the owner, and where it is
normally stored. Furthermore, additional information may be available if the
given media type supports it, such as the *region_code# the medium is
restricted to.

[text]
When in edit mode, you can change some or all of these data. If you are the
owner of the medium, you can transfer the ownership to any other user of this
phpVideoPro installation. The other fields should be self explanatory.

[text]
However, some fields cannot be changed here - such as if the medium is
(re)writeable or if it supports *region_code#. All this is to be set globally
for the affected media types, and not for the single medium.

[title]
Disk types and RegionCodes

[text]
Disk types and RegionCodes always apply to the entire medium: This is why you
can't <b><i>edit</i></b> them together with a movie. You either set these values
when creating the first entry for a medium, or with this little screen.

[title]
*disk_type#

[text]
The disk type consists of one or two parts: the type itself and sometimes the
disk size. Both together help you to find out e.g. whether your (or s.o. elses)
player does support this medium, since e.g. some players don't support DVD-R
or self-burned media at all. Moreover, different disk types support different
features (such as e.g. RegionCodes for DVDs), plus for backups you can
immediately see if they can be easily done by a 1:1 copy.

[title]
*region_code#

[text]
When setting up the region code(s), there are technically no limitations
concerning their count. There are some disks supporting more than one (but not
all) regions, so I made it a "multiple choice" option. However, if you have DVDs
that support all region codes (called "code free"), you should only check the
box for RC 0, which means "code free" - no need to check 1 to 6 as well then.


[eof]
