<? /* medialist */
 ?>
<? /* $Id$ */ ?>

<H2 Align=Center>MediaList</H2>

<Table Width=90% Align=Center>
 <TR><TD>
  <P Align=Justify>This displays a list containing all movies stored in your
   database, sorted by MediaType and MediaNr (for now, this is the only
   sorting available. Some future version may provide different sortings as
   well as the ability to limit the number of entries displayed). If you have
   set up some filters, they are used to select these entries - so in this
   case only movies matching the filters are displayed.</P>
  <P Align=Justify>From within this list, you can select a single item to
   display details of, and from within that detail screen you may decide to
   edit or even delete the entry.</P>
 </TD></TR>
</Table>

