# /* no_such_topic */
# /* $Id$ */

[title]
Topic not found

[text]
Sorry - there's no help available for this topic yet, or some error occured, or
you may have found a bug (misspelling in code). The latter is the case if you
find help on this topic via the help index. In this case, please drop a note to
the <A HREF="mailto:izzysoft@qumran.org">author</a>; that crazy programmer
normally does not read the help pages and thus possibly never finds out about
this fact :-)

[eof]

