<? /* no_such_topic */
 ?>
<? /* $Id$ */ ?>

<H2 Align=Center>Topic not found</H2>

<Table Width=90% Align=Center>
 <TR><TD>
  <P Align=Justify>Sorry - there's no help available for this topic yet, or
   some error occured, or you may have found a bug (misspelling in code). The
   latter is the case if you find help on this topic via the help index. In
   this case, please drop a note to the <A HREF="mailto:izzysoft@qumran.org">author</a>;
   that crazy programmer normally does not read the help pages and thus
   possibly never finds out about this fact :-)</P>
 </TD></TR>
</Table>

