# /* medialist */
# /* $Id$ */

[title]
*intro#

[text]
This page is displayed when you just started phpVideoPro. From here, as from
almost any other page, you can use the drop-down menu to navigate through the
database and application functions. As here, on most pages there is context
sensitive help available. If you are not (yet) familiar with phpVideoPro and
first want to get an overview of its functions, you may want to use the help
index.

[title]
The "Jump" form

[text]
The tiny form on this page lets you quickly navigate to any movie record in the
database - provided you know where to look for it ;) Select the type of media
from the drop-down box, and enter at least the first part of the *MediaNr#,
then press the <i>*view#</i> button.

[text]
In case you entered both parts of the *MediaNr# in the input fields, you should
now be brought directly to the requested record - provided it exists. If you
only entered the first part of the *MediaNr#, phpVideoPro will display a list
of all movies on the specified medium.

[eof]

