# /* medialist */
# /* $Id$ */

[title]
*db_stats#

[text]
This page just displays database statistics - there's not much you can do about.
However, some explanation should be given:

[text]
Statistics are split into two parts. The first block simply counts the numbers,
the second tries to give a ranking. Almost everything speaks for itself; just
a few words about the categories in the ranking block: here only the first
category assigned to a movie is evaluated ("*category# 1"), since this should
be the one to describe the movie best. Everything else should "work as
expected".

[eof]

