# /* absolute taperest */
# /* $Id$ */

[title]
Finding free space to record

[text]
The tape rest feature is intended to let you find free space on your recordable
media. You are first presented a small form to input the minimum of free time
you require, and after you filled out and submitted that form, you will get a
list of all media matching your criterium, together with information about what
movies are already on this medium, their main category, and the amount of free
space on these media. The free time is measured for "normal play", so if you
plan to record something in "LongPlay" mode, you may double the amount of free
time displayed.
[text]
Now here are two menue items for tape rest: <b>filtered</b> means, only media
containing at least one movie matching the <A HREF="{PHP_SELF}?topic=set_filter">filter
rules</A> are displayed, while <b>absolute</b> ignores the filter settings.

[eof]

