<? /* absolute taperest */
 ?>
<? /* $Id$ */ ?>

<H2 Align=Center>MediaList</H2>

<Table Width=90% Align=Center>
 <TR><TD>
  <P Align=Justify>The tape rest feature is intended to let you find free
   space on your recordable media (i.e. for now tapes - RVT). You are first
   presented a small form to input the minimum of free time you require,
   and after you filled out and submitted that form, you will get a list of
   all media matching your criterium, together with information about what
   movies are already on this tape, their main category, and the amount of
   free space on these media. The free time is measured for "normal play",
   so if you plan to record something in "LongPlay" mode, you may double
   the amount of free time displayed.</P>
  <P Align=Justify>Now here are two menue items for tape rest: <b>filtered</b>
   means, only media containing at least one movie matching the filter
   rules are displayed, while <b>absolute</b> ignores the filter settings.</P>
 </TD></TR>
</Table>

