<?

/* $Id$ */

$base_url   = "/homes/izzy/software/pvp-demo/";
// the root directory of phpVideoPro
$base_path  = "/web/htdocs/homes/izzy/software/pvp-demo/";

// database settings
$database["type"]      = "mysql";  // mysql|pgsql
$database["host"]      = "horeb";
//$database["host"]      = "localhost";
$database["database"]  = "video_demo";
$database["user"]      = "guest";
$database["password"]  = "";

// some default settings
$defaults["scolor"] = 2; // 1=b/w, 2=color, 3=3d - if you didn't change sth. :)
?>