<?

/* $Id$ */

$base_url   = "/local/phpvideo/";
// the root directory of phpVideoPro

// database settings
$database["host"]      = "linux";
$database["host"]      = "localhost";
$database["database"]  = "video_demo";
//$database["database"]  = "videopro";
$database["database"]  = "video_dummy";
$database["user"]      = "root";
$database["password"]  = "achat";

// some default settings
$defaults["scolor"] = "Farbe"; // most movies today have more than two colors ;)

?>