# /* About */
# /* $Id$ */

[title]
Intro

[text]
Dit is phpVideoPro versie {version}, (c) 2001 by Itzchak Rehberg, alle rechten
voorbehouden. Geïnspireerd door mijn favoriete software voor dit doel, 
VideoPro (c) 1991-1994 van Bernd Rickers, ben ik gestart met de ontwikkeling van
mijn eigen Video beheer programma. Bernd is gestopt met de ontwikkeling van VideoPro 
in 1994, sindsdien was VideoPro slechts beschikbaar als DOS gebaseerde clipper 
applicatie en ontbraken er belangrijke zaken zoals ondersteuning voor DVD en 
geluidsformaten zoals Dolby Digital 5.1. 
Ik heb gekozen om phpVideoPro te ontwikkelen in PHP omdat dit een platform 
onafhankelijke programmeertaal is en omdat ik dan altijd in staat ben om de gegevens
in te zien. Al zal dat in het ergste geval in een internet café zijn.

[text]
Op dit moment is phpVideoPro niet geschikt om met meerdere gebruikers tegelijk 
de gegevens te bekijken. Dit zou kunnen veranderen in een toekomstige versie,
maar verwacht dit niet op erg korte termijn.

[title]
Mogelijkheden

[text]
Welke mogelijkheden phpVideoPro heeft? Als video beheer software is het uiteraard
geschikt om de (privé) video verzameling te beheren (het is niet de bedoeling geweest
om het te ontwikkelen voor een videoverhuurwinkel, waar dezelfde videofilm meerdere 
malen in het assortiment kan zijn opgenomen).
U kunt videofilms toevoegen en veranderen, een lijst met alle videofilms afdrukken,
bekijken hoeveel ruimte er nog vrij is op uw videobanden. In phpVideoPro kun je aangeven 
of een film op DVD, een Voorbespeelde videoband (dat zijn degene die gekocht zijn of die 
je als cadeau gekregen hebt) en Onbespeelde videoband (dat zijn degene die de films bevatten 
die je zelf hebt opgenomen). Daarnaast helpen de filter functies om bepaalde selecties te 
maken of om een speciale videofilm te vinden, zelfs in grotere verzamelingen.
  
[text]
Nieuwe mogelijkheden zijn gepland en de ontwikkeling gaat nog steeds door. Nieuwe versies
verschijnen niet erg regelmatig en zullen er waarschijnlijk niet snel zijn - dit omdat het
slechts een hobby is en er zoveel anderen zijn die mij met enige regelmaat willen zien ;-)
Maar zolang nog niet alle plannen zijn verwezenlijkt (zie doc/2do), kun je er verzekerd
van zijn dat er binnen een aantal weken weer een nieuwe versie zal zijn. Ik sluit af met 
mijn standaard spreuk: "Dit is slechts een hobby, I beloof niets - ik kan slechts vragen
om rustig af te wachten..." 
 
[text]
<div align=right>Itzchak Rehberg, Augustus 2001</div>

[eof]

