<? /* list of actors, directors, composers */
 ?>
<? /* $Id$ */ ?>

[title]
Overzicht van Acteurs, Regisseurs en Composers

[text]
Binnen de selectie die gemaakt is door de 
<A HREF="{PHP_SELF}?topic=set_filter">filters</A>,
geven deze menu items een overzicht van de acteurs, regisseurs en composers 
gesorteerd op alfabet, echter alleen degene die genoemd zijn bij de films en
waarbij er een vinkje staat in het aankruisvakje 'in lijst'.
Door het klikken op het medianummer, kun je de details zien van die film 
(zie <A HREF="{PHP_SELF}?topic=add_entry">wijzigen</A> of toevoegen van een 
nieuwe film).

[eof]

