# /* How to create a new template set */
# /* $Id$ */

[title]
Hoe creëer ik mijn eigen template?

[text]
Net als de help en taal bestanden, is dit ook een kwestie van het maken van een
subdirectory en het kopiëren en wijzigen van wat bestanden:

[text]
<OL>
<LI>Verzin een leuke naam voor de nieuwe templates. Als voorbeeld gebruik ik nu even 
"babylon5".
<LI>Ga naar de templates directory en creëer een subdirectory met deze naam.
<LI>Kopieer de bestanden uit de 'templates/default' naar deze directory en verander
deze zoals jij dat graag wilt. De tekens &#123;brazes&#125; 
zijn plekken waar de gegevens straks worden samengevoegd in de template. Deze moeten
dus blijven bestaand. De rest kan allemaal weg.
<LI>Als je klaar bent kun je naar de configuratie pagina gaan ("*edit# -&gt; *configuration#") 
en de template activeren. phpVideoPro vind de templates automatisch, zodat je hem meteen 
hier kunt selecteren
</OL>

[eof]
