# /* medialist */
# /* $Id$ */

[title]
Lijst van geregistreerde media

[text]
Dit genereert een lijst met alle films die opgeslagen zijn in de database,
standaard op volgorde van Mediumtype en Mediumnummer. Deze volgorde is te 
wijzigen door in de tabelkop op de kolom te klikken waarop gesorteerd moet
worden. Indien er enkele filters bestaan, dan worden deze toegepast om de 
gewenste films te selecteren. 

[text]
In de huidige versie, de lijst kan behoorlijk lang worden. De mogelijkheid
om het aantal films te beperken tot een bepaald aantal is nog niet beschikbaar,
maar zal in een toekomstige versie geïntroduceerd worden.

[text]
Vanuit deze lijst kun je een film selecteren om de details te zien. Vanaf daar
kun je besluiten om de film te <A HREF="{PHP_SELF}?topic=add_entry">wijzigen</A>
of om de film te verwijderen.

[eof]
