# /* set_filter */
# /* $Id$ */

[title]
Introductie

[text]
Beide menu items, "*set_filter#" en "*unset_filter#", roepen hetzelfde 
formulier op, met een klein verschil. "*unset_filter#" zal alle filters
eerst verwijderen, zodat met een nieuw filter kunt opzetten.

[title]
Filter regels

[text]
<H4>Tekst geplaatst in hetzelfde veld.</H4>
<OL>

 <li><b>Tekst die een min/max waarde aangeeft</b><br>
     Deze teksten worden aan elkaar geknoopt met een 'and'. Dit houdt in
dat als je een "Min 60" en een "Max 90" bij de lengte velden aangeeft, dan zoek je
dus een film met een duur van 60 tot 90 minuten. Indien je slechts één waarde 
opgeeft dan wordt er uiteraard rekening gehouden met slechts deze voorwaarde.
 <li><b>Titel</b><br>
	Hier kun je een <i>deel</i> van de titel opgeven. Indien je dus 'hard' opgeeft,
dan krijg je Beatles' "A Hard Day's Night" en "Die Hard" terug.
 <li><b>Andere items</b><br>
	Alle andere velden worden aan elkaar geknoopt met een 'or', Dus indien je DVD 
en Onbespeelde videoband aanvinkt, dan krijg je alle DVD's en alle onbespeelde videobanden
in de overzichten te zien.</OL>

[text]
<H4>Tekst geplaatst in verschillende velden</H4>
Deze worden aan elkaar geknoopt door middel van 'and', dus indien je DVD aanvinkt en 
"Science Fiction" als categorie, dan resulteert dit in alle 'Science Fiction'-dvd's.
[eof]

