# /* absolute taperest */
# /* $Id$ */

[title]
Vrije ruimte vinden om op te nemen

[text]
De 'vrije ruimte'-functie is bedoeld om voldoende ruimte te vinden op een band.
Je krijgt eerst een klein formulier te zien waar je de minimale vrije ruimte opgeeft
die je nodig hebt. Je krijgt dan een lijst van alle beschikbare banden met die ruimte.
Daarbij wordt direct de andere films vermeld die op deze band staan. De beschikbare
ruimte is gebaseerd op 'normale afspeelsnelheid', dus indien je een film gaat opnemen
op 'langzame snelheid (Longplay), dan moet je de gepresenteerde vrije ruimte verdubbelen.

[text]
Er zijn twee menu items voor 'vrije ruimte'. Gefilterd betekent dat alleen de banden
worden getoond die voldoen aan het opgegeven 
<A HREF="{PHP_SELF}?topic=set_filter">filter</A>, terwijl <b>absoluut</b> de filter
instellingen negeert.

[eof]
