<?
 ##############################################################################
 # phpVideoPro                               (c) 2001,2002 by Itzchak Rehberg #
 # written by Itzchak Rehberg <izzysoft@qumran.org>                           #
 # http://www.qumran.org/homes/izzy/                                          #
 # -------------------------------------------------------------------------- #
 # This program is free software; you can redistribute and/or modify it       #
 # under the terms of the GNU General Public License (see doc/LICENSE)        #
 # -------------------------------------------------------------------------- #
 # Prepare some stylesheet information (use defaults)                         #
 ##############################################################################
 
 $colors["page_background"]  = "#6699ff";
 $colors["table_background"] = "#ffffff";
 $colors["th_background"]    = "#ffff99";
 include("../templates/default/default.css");
?>