# ========================================================
# English Translation phrases for phpVideoPro
# ========================================================

INSERT INTO lang (message_id,lang,content) VALUES ('not_yet_implemented','en','Sorry - not yet implemented.');
INSERT INTO lang VALUES('medium','en','Medium');
INSERT INTO lang VALUES('nr','en','Nr');
INSERT INTO lang VALUES('title','en','Title');
INSERT INTO lang VALUES('length','en','Length');
INSERT INTO lang VALUES('year','en','Year');
INSERT INTO lang VALUES('date_rec','en','Date Aquired');
INSERT INTO lang VALUES('category','en','Category');
INSERT INTO lang VALUES('medialist','en','Medialist');
INSERT INTO lang VALUES('enter_min_free','en','Enter minimum of free space on medium to display:');
INSERT INTO lang VALUES('display','en','Display');
INSERT INTO lang VALUES('free_space_on_media','en','Following media have at least %1 minutes of free space available:');
INSERT INTO lang VALUES('free','en','Free');
INSERT INTO lang VALUES('content','en','Content');
INSERT INTO lang VALUES('filter_setup','en','Filter Setup');
INSERT INTO lang VALUES('mediatype','en','MediaType');
INSERT INTO lang VALUES('screen','en','Screen Format');
INSERT INTO lang VALUES('picture','en','Color Format');
INSERT INTO lang VALUES('tone','en','Tone Format');
INSERT INTO lang VALUES('longplay','en','LongPlay');
INSERT INTO lang VALUES('fsk','en','PG');
INSERT INTO lang VALUES('actor','en','Actor');
INSERT INTO lang VALUES('actors','en','Actors');
INSERT INTO lang VALUES('director','en','Director');
INSERT INTO lang VALUES('directors','en','Directors');
INSERT INTO lang VALUES('composer','en','Composer');
INSERT INTO lang VALUES('music','en','Composer');
INSERT INTO lang VALUES('min','en','min');
INSERT INTO lang VALUES('max','en','max');
INSERT INTO lang VALUES('s/w','en','b/w');
INSERT INTO lang VALUES('farbe','en','Color');
INSERT INTO lang VALUES('3d','en','3D');
INSERT INTO lang VALUES('edit_entry','en','Edit entry %1');
INSERT INTO lang VALUES('view_entry','en','View entry %1');
INSERT INTO lang VALUES('add_entry','en','Add entry');
INSERT INTO lang VALUES('unknown','en','unknown');
INSERT INTO lang VALUES('country','en','Country');
INSERT INTO lang VALUES('medianr','en','MediaNr');
INSERT INTO lang VALUES('highest_db_entries','en','highest entries in db');
INSERT INTO lang VALUES('no','en','No');
INSERT INTO lang VALUES('yes','en','Yes');
INSERT INTO lang VALUES('medialength','en','MediaLength');
INSERT INTO lang VALUES('minute_abbrev','en','min');
INSERT INTO lang VALUES('source','en','Source');
INSERT INTO lang VALUES('staff','en','Staff');
INSERT INTO lang VALUES('name','en','Name');
INSERT INTO lang VALUES('first_name','en','First Name');
INSERT INTO lang VALUES('in_list','en','in List');
INSERT INTO lang VALUES('comments','en','Comments');
INSERT INTO lang VALUES('cancel','en','Cancel');
INSERT INTO lang VALUES('create','en','Create');
INSERT INTO lang VALUES('update','en','Update');
INSERT INTO lang VALUES('edit','en','Edit');
INSERT INTO lang VALUES('delete','en','Delete');
INSERT INTO lang VALUES('invalid_media_nr','en','The MediaNr you specified is either incomplete or invalid. You must specify a <b>number</b> in <b>both</b> MediaNr fields.');
INSERT INTO lang VALUES('warning','en','warning');
INSERT INTO lang VALUES('of_aquiration','en','of aquiration');
INSERT INTO lang VALUES('wrong_date','en','The date %1 you specified (%2) is invalid. When entering a date here, please follow the syntax "YYYY-MM-DD", where "YYYY" stands for the year (four-digit), "MM" for the month and "DD" for the day (both two-digit). If you want no date in here, just leave this field blank (or set it to "0000-00-00").');
INSERT INTO lang VALUES('incomplete_date','en','If you do not know the exact date, but - for example - only that you aquired it in the year 2000, substitute zeros for the unknown data - in our example the date should look like "2000-00-00".');
INSERT INTO lang VALUES('dupe_id_entered','en','There is already an entry in the database for the entered media ID. Please hit the "Back" button of your browser and correct your input. Hint: There is a Select-Box next to the input box you specified the media number in. This select box tells you the highest existing movie id. Normally it is a good choice for a new media to increase the first (four-digit) number by one, or for a new movie on the same media, increase the second (two-digit) number by one.');
INSERT INTO lang VALUES('create_success','en','Entry created successfully');
INSERT INTO lang VALUES('update_failed','en','Failed to update entry');
INSERT INTO lang VALUES('update_success','en','Entry updated successfully');
INSERT INTO lang VALUES('about','en','About');
INSERT INTO lang VALUES('history','en','History');
INSERT INTO lang VALUES('view','en','View');
INSERT INTO lang VALUES('deleting_entry','en','Deleting entry %1');
INSERT INTO lang VALUES('free_space_title','en','Free space on media');
INSERT INTO lang VALUES('filter','en','Filter');
INSERT INTO lang VALUES('set_filter','en','Set Filter');
INSERT INTO lang VALUES('unset_filter','en','UnSet Filter');
INSERT INTO lang VALUES('taperest_absolute','en','TapeRest (absolute)');
INSERT INTO lang VALUES('taperest_filtered','en','TapeRest (filtered)');
INSERT INTO lang VALUES('help','en','Help');
INSERT INTO lang VALUES('general','en','General');
INSERT INTO lang VALUES('sure_to_delete','en','Are you sure you want to delete all data for %1');
INSERT INTO lang VALUES('nobody_named','en','There\'s no other movie by a %1 named %2 %3 in this db, so I remove this entry from the %1\'s table.');
INSERT INTO lang VALUES('compose_person','en','composer');
INSERT INTO lang VALUES('director_person','en','director');
INSERT INTO lang VALUES('check_completed','en','Check completed');
INSERT INTO lang VALUES('delete_remaining','en','now deleting remaining data for this movie from db');
INSERT INTO lang VALUES('ok','en','OK');
INSERT INTO lang VALUES('not_ok','en','Failed');
INSERT INTO lang VALUES('recalc_free','en','Re-calculating remaining free space on this medium');
INSERT INTO lang VALUES('tapelist_update_failed','en','Failed updating tape list');
INSERT INTO lang VALUES('no_entry_in_tapelist','en','Failed - no entry found in tape list');
INSERT INTO lang VALUES('finnished','en','Finnished');
INSERT INTO lang VALUES('time_left','en','%1 minutes left');
INSERT INTO lang VALUES('configuration','en','Configuration');
INSERT INTO lang VALUES('index','en','Index');
INSERT INTO lang VALUES('intro','en','Intro');
INSERT INTO lang VALUES('menues','en','Menues');
INSERT INTO lang VALUES('back','en','Back');
INSERT INTO lang VALUES('close','en','Close');
INSERT INTO lang VALUES('help_about','en','Help about');
INSERT INTO lang VALUES('actors_list','en','List of Actors');
INSERT INTO lang VALUES('directors_list','en','List of Directors');
INSERT INTO lang VALUES('music_list','en','List of Composers');
INSERT INTO lang VALUES('no_entries_found','en','No entries found');
INSERT INTO lang VALUES('no_space_of','en','There was no medium with a minimum of %1 min of free space found in the database.');

