# ========================================================
# Polish Translation phrases for phpVideoPro
# by Leszek Boroch borek@ajax.umcslublin.pl
# iso-8859-2
# ========================================================
# 15/08/2002 Updated translation by Jacek Wolski jrtwolski@poczta.onet.pl

UPDATE languages SET charset='iso-8859-2' WHERE lang_id='pl';
INSERT INTO lang (message_id,lang,content) VALUES ('not_yet_implemented','pl','Niestety, jeszcze nie zaimplementowane.');
INSERT INTO lang VALUES('medium','pl','no¶nik');
INSERT INTO lang VALUES('nr','pl','Nr');
INSERT INTO lang VALUES('title','pl','Tytu³');
INSERT INTO lang VALUES('length','pl','D³ugo¶æ');
INSERT INTO lang VALUES('year','pl','Rok');
INSERT INTO lang VALUES('date_rec','pl','Data nabycia');
INSERT INTO lang VALUES('category','pl','Kategoria');
INSERT INTO lang VALUES('medialist','pl','Lista no¶ników');
INSERT INTO lang VALUES('enter_min_free','pl','Podaj minimaln± ilo¶æ miejsca na no¶niku do pokazania:');
INSERT INTO lang VALUES('display','pl','Wy¶wietl');
INSERT INTO lang VALUES('free_space_on_media','pl','Ten no¶nik ma conajmniej %1 minutê(y) wolnej przestrzeni:');
INSERT INTO lang VALUES('free','pl','Wolny');
INSERT INTO lang VALUES('content','pl','Zawarto¶æ');
INSERT INTO lang VALUES('filter_setup','pl','Ustawienia Filtra');
INSERT INTO lang VALUES('mediatype','pl','Typ No¶nika');
INSERT INTO lang VALUES('screen','pl','Format Obrazu');
INSERT INTO lang VALUES('picture','pl','Format Koloru');
INSERT INTO lang VALUES('tone','pl','Format D¼wiêku');
INSERT INTO lang VALUES('longplay','pl','LongPlay');
INSERT INTO lang VALUES('fsk','pl','PG');
INSERT INTO lang VALUES('actor','pl','Aktor');
INSERT INTO lang VALUES('actors','pl','Aktorzy');
INSERT INTO lang VALUES('director','pl','Re¿yser');
INSERT INTO lang VALUES('directors','pl','Re¿yserzy');
INSERT INTO lang VALUES('composer','pl','Kompozytor');
INSERT INTO lang VALUES('music','pl','Muzyka');
INSERT INTO lang VALUES('min','pl','min');
INSERT INTO lang VALUES('max','pl','max');
INSERT INTO lang VALUES('s/w','pl','cz.b.');
INSERT INTO lang VALUES('farbe','pl','Kolor');
INSERT INTO lang VALUES('3d','pl','3D');
INSERT INTO lang VALUES('edit_entry','pl','Edycja wpisu %1');
INSERT INTO lang VALUES('view_entry','pl','Podgl±d wpisu %1');
INSERT INTO lang VALUES('add_entry','pl','Dodanie wpisu');
INSERT INTO lang VALUES('unknown','pl','nieznany');
INSERT INTO lang VALUES('country','pl','Kraj');
INSERT INTO lang VALUES('medianr','pl','Nr no¶nika');
INSERT INTO lang VALUES('highest_db_entries','pl','najwy¿szy numer w bazie');
INSERT INTO lang VALUES('no','pl','Nie');
INSERT INTO lang VALUES('yes','pl','Tak');
INSERT INTO lang VALUES('medialength','pl','D³ugo¶æ no¶nika');
INSERT INTO lang VALUES('minute_abbrev','pl','min');
INSERT INTO lang VALUES('source','pl','¬ród³o');
INSERT INTO lang VALUES('staff','pl','Staff');
INSERT INTO lang VALUES('name','pl','Nazwa');
INSERT INTO lang VALUES('first_name','pl','Imiê');
INSERT INTO lang VALUES('in_list','pl','na li¶cie');
INSERT INTO lang VALUES('comments','pl','Komentarz');
INSERT INTO lang VALUES('cancel','pl','Anuluj');
INSERT INTO lang VALUES('create','pl','Utwórz');
INSERT INTO lang VALUES('update','pl','Zastosuj');
INSERT INTO lang VALUES('edit','pl','Edytuj');
INSERT INTO lang VALUES('delete','pl','Kasuj');
INSERT INTO lang VALUES('invalid_media_nr','pl','Podany Nr no¶nika jest nieprawid³owy lub niekompletny. Nale¿y podaæ <b>numer</b> w <b>obu</b> polach NrNo¶nika.');
INSERT INTO lang VALUES('warning','pl','Ostrze¿enie');
INSERT INTO lang VALUES('of_aquiration','pl','nabycie');
INSERT INTO lang VALUES('wrong_date','pl','Wprowadzona data %1 jest (%2) nieprawid³owa. Datê nale¿y wprowadziæ w formacie "YYYY-MM-DD", gdzie "RRRR" to rok (cztery cyfry), "MM" to miesi±c, a "DD" to dzieñ (po dwie cyfry). Pole mo¿e byæ puste (lub ustawione na "0000-00-00").');
INSERT INTO lang VALUES('incomplete_date','pl','Je¶li nie znasz dok³adnej daty, ale np. tylko rok nabycia 2000, zamieñ na zera w nieznanej dacie - np. "2000-00-00".');
INSERT INTO lang VALUES('dupe_id_entered','pl','Jest ju¿ pozycja w bazie danych dla podanego identyfikatora no¶nika. Naci¶nij przycisk "Wstecz" w twojej przegl±darce i popraw dane. Podpowied¼: Jest okienko wybory obok okna wprowadzania numeru no¶nika. Okno wyboru podaje najwy¿szy istniej±cy numer no¶nika - mo¿na podaæ numer o jeden wiêkszy');
INSERT INTO lang VALUES('create_success','pl','Wpis utworzony');
INSERT INTO lang VALUES('update_failed','pl','Nieudane uaktualnianie wpisu');
INSERT INTO lang VALUES('update_success','pl','Wpis uaktualniony');
INSERT INTO lang VALUES('about','pl','O programie');
INSERT INTO lang VALUES('history','pl','Historia');
INSERT INTO lang VALUES('view','pl','Widok');
INSERT INTO lang VALUES('deleting_entry','pl','Usuwanie wpisu %1');
INSERT INTO lang VALUES('free_space_title','pl','Wolna przestrzeñ na no¶niku');
INSERT INTO lang VALUES('filter','pl','Filtr');
INSERT INTO lang VALUES('set_filter','pl','W³±cz filtr');
INSERT INTO lang VALUES('unset_filter','pl','Wy³±cz filtr');
INSERT INTO lang VALUES('taperest_absolute','pl','Miejsce kasety (absolutne)');
INSERT INTO lang VALUES('taperest_filtered','pl','Miejsce kasety (odfiltrowane)');
INSERT INTO lang VALUES('help','pl','Pomoc');
INSERT INTO lang VALUES('general','pl','Ogólne');
INSERT INTO lang VALUES('sure_to_delete','pl','Czy chcesz skasowaæ wszystkie dane dla %1');
INSERT INTO lang VALUES('nobody_named','pl','Brak filmu %1 nazwanego %2 %3 w tej bazie danych, wiêc usunê t± pozycjê z tabeli %1.');
INSERT INTO lang VALUES('compose_person','pl','kompozytor');
INSERT INTO lang VALUES('director_person','pl','re¿yser');
INSERT INTO lang VALUES('check_completed','pl','Kontrola zakoñczona');
INSERT INTO lang VALUES('delete_remaining','pl','kasujê pozosta³e dane dla tego filmu z bazy danych');
INSERT INTO lang VALUES('ok','pl','OK');
INSERT INTO lang VALUES('not_ok','pl','Wyst±pi³ b³±d');
INSERT INTO lang VALUES('recalc_free','pl','Ponowne obliczanie pozosta³ego wolnego miejsca na tym no¶niku');
INSERT INTO lang VALUES('tapelist_update_failed','pl','Wyst±pi³ b³±d podczas aktualizacji listy kaset');
INSERT INTO lang VALUES('no_entry_in_tapelist','pl','Wyst±pi³ b³±d - brak pozycji na li¶cie kaset');
INSERT INTO lang VALUES('finnished','pl','Zakoñczone');
INSERT INTO lang VALUES('time_left','pl','Pozosta³o(a) %1 min');
INSERT INTO lang VALUES('configuration','pl','Konfiguracja');
INSERT INTO lang VALUES('index','pl','Indeks');
INSERT INTO lang VALUES('intro','pl','Intro');
INSERT INTO lang VALUES('menues','pl','Menu');
INSERT INTO lang VALUES('back','pl','Wstecz');
INSERT INTO lang VALUES('close','pl','Zamknij');
INSERT INTO lang VALUES('help_about','pl','Pomoc na temat');
INSERT INTO lang VALUES('actors_list','pl','Lista aktorów');
INSERT INTO lang VALUES('directors_list','pl','Lista re¿yserów');
INSERT INTO lang VALUES('music_list','pl','Lista kompozytorów');
INSERT INTO lang VALUES('no_entries_found','pl','Nic nie znaleziono');
INSERT INTO lang VALUES('no_space_of','pl','Brak no¶nika z minimalnym wolnym czasem %1 min w bazie danych.');
INSERT INTO lang VALUES('howto','pl','Jak to zrobiæ...');
INSERT INTO lang VALUES('howto_lang','pl','Jak stworzyæ plik z nowym jêzykiem');
INSERT INTO lang VALUES('howto_help','pl','Jak stworzyæ nowy plik pomocy');
INSERT INTO lang VALUES('howto_templates','pl','Jak stworzyæ nowy zestaw szablonów');
INSERT INTO lang VALUES('language_settings','pl','Ustawienia jêzykowe');
INSERT INTO lang VALUES('scan_new_lang_files','pl','Poszukiwanie nowych plików jêzykowych');
INSERT INTO lang VALUES('scan_new_lang_comment','pl','(je¶li umieszczono nowe pliki jêzykowe w katalogu setup)');
INSERT INTO lang VALUES('select_add_lang','pl','Dodatkowe jêzyki do zainstalowania');
INSERT INTO lang VALUES('select_add_lang_comment','pl','(Jêzyk angielski jest zawsze dostêpny. Inne zainstalowane jêzyki mo¿na sprawdziæ poni¿ej)');
INSERT INTO lang VALUES('no_add_lang','pl','Brak dodatkowych jêzyków.');
INSERT INTO lang VALUES('refresh_lang','pl','Od¶wie¿enie jêzyka');
INSERT INTO lang VALUES('refresh_lang_comment','pl','(ponowne wprowadzenie pliku jêzyka do bazy)');
INSERT INTO lang VALUES('none','pl','¯aden');
INSERT INTO lang VALUES('select_primary_lang','pl','Wybór jêzyka podstawowego');
INSERT INTO lang VALUES('select_primary_lang_comment','pl','(brakuj±ce frazy bêd± w jêzyku Angielskim)');
INSERT INTO lang VALUES('use_charset','pl','U¿ywana tablica znaków');
INSERT INTO lang VALUES('use_charset_comment','pl','(istotne dla kodowania znaków)');
INSERT INTO lang VALUES('colors','pl','Kolory');
INSERT INTO lang VALUES('page_bg','pl','T³o strony');
INSERT INTO lang VALUES('table_bg','pl','T³o tabeli');
INSERT INTO lang VALUES('th_bg','pl','T³o nag³ówków tabeli');
INSERT INTO lang VALUES('feedback_ok','pl','Odpowied¼ "OK"');
INSERT INTO lang VALUES('feedback_err','pl','Odpowied¼ "B³±d"');
INSERT INTO lang VALUES('template_set','pl','Szablon');
INSERT INTO lang VALUES('start_pvp','pl','Start phpVideoPro');
INSERT INTO lang VALUES('hit_back_to_correct','pl','Wci¶nij "Wstecz" w celu poprawy b³êdu.');
INSERT INTO lang VALUES('goto_entry','pl','Bezpo¶rednio do wpisu:');
INSERT INTO lang VALUES('start_page','pl','Strona startowa');
INSERT INTO lang VALUES('invalid_fsk','pl','Warto¶æ PG ("%1") jest nieprawid³owa. PG oznacza Rodzicielski Przewodnik, np. od ilu lat film jest dozwolony.');
INSERT INTO lang VALUES('counter_start_stop','pl','Licznik Start/Stop');
INSERT INTO lang VALUES('other_pages','pl','Inne strony');
INSERT INTO lang VALUES('commercials','pl','Reklamy');
INSERT INTO lang VALUES('cut_off','pl','wyciête');
INSERT INTO lang VALUES('display_limit','pl','Limit Wy¶wietlania');
INSERT INTO lang VALUES('display_limit_comment','pl','(ile linii wy¶wietlaæ na stronê dla list)');
INSERT INTO lang VALUES('print_label','pl','Drukuj plakietkê:');
INSERT INTO lang VALUES('howto_label','pl','Jak stworzyæ/skonfigurowaæ szablony plakietek');
INSERT INTO lang VALUES('label','pl','Plakietka');
INSERT INTO lang VALUES('print','pl','Drukuj');
INSERT INTO lang VALUES('medialist_num','pl','Lista no¶ników w porz±dku numerycznym');
INSERT INTO lang VALUES('medialist_alpha','pl','Lista no¶ników w porz±dku alfabetycznym');
INSERT INTO lang VALUES('lines_per_page','pl','Linii na stronê');
INSERT INTO lang VALUES('lines_per_page_comment','pl','Okre¶la liczbê linii na drukowanej stronie (dla funkcji drukuj±cej).');
INSERT INTO lang VALUES('date_format','pl','Format daty');
INSERT INTO lang VALUES('date_format_comment','pl','Okre¶la jaki format u¿ywaæ do wy¶wietlania daty.');
INSERT INTO lang VALUES('listgen','pl','Generator List');
INSERT INTO lang VALUES('list','pl','Lista');
INSERT INTO lang VALUES('format','pl','Format');
INSERT INTO lang VALUES('line_count','pl','Linii');
INSERT INTO lang VALUES('catlist_alpha','pl','Lista no¶ników w porz±dku alfabetycznym, posortowana wg kategorii');
INSERT INTO lang VALUES('lists','pl','Listy');
INSERT INTO lang VALUES('labels','pl','Plakietki');
INSERT INTO lang VALUES('cat_adventure','pl','Przygodowe');
INSERT INTO lang VALUES('cat_action','pl','Kino akcji');
INSERT INTO lang VALUES('cat_agents','pl','Agenci');
INSERT INTO lang VALUES('cat_bible','pl','Biblijne');
INSERT INTO lang VALUES('cat_biography','pl','Biograficzne');
INSERT INTO lang VALUES('cat_stage','pl','Scena');
INSERT INTO lang VALUES('cat_documentary','pl','Dokumentalne');
INSERT INTO lang VALUES('cat_drama','pl','Sztuki');
INSERT INTO lang VALUES('cat_fantasy','pl','Fantazy');
INSERT INTO lang VALUES('cat_party','pl','Party');
INSERT INTO lang VALUES('cat_scary','pl','Lekki horror');
INSERT INTO lang VALUES('cat_history','pl','Historyczne');
INSERT INTO lang VALUES('cat_horror','pl','Horror');
INSERT INTO lang VALUES('cat_judaica','pl','Judaica');
INSERT INTO lang VALUES('cat_camera','pl','Camera');
INSERT INTO lang VALUES('cat_catastrophe','pl','Katastroficzne');
INSERT INTO lang VALUES('cat_children','pl','Dla dzieci');
INSERT INTO lang VALUES('cat_comedy','pl','Komedie');
INSERT INTO lang VALUES('cat_concert','pl','Koncerty');
INSERT INTO lang VALUES('cat_war','pl','Filmy wojenne');
INSERT INTO lang VALUES('cat_crime','pl','Krymina³');
INSERT INTO lang VALUES('cat_love','pl','Romanse');
INSERT INTO lang VALUES('cat_fairytale','pl','Bajki');
INSERT INTO lang VALUES('cat_melodrama','pl','Melodramaty');
INSERT INTO lang VALUES('cat_monumental','pl','Monumentalne');
INSERT INTO lang VALUES('cat_musical','pl','Musical');
INSERT INTO lang VALUES('cat_music','pl','Muzyka');
INSERT INTO lang VALUES('cat_videoclip','pl','Wideoklipy');
INSERT INTO lang VALUES('cat_musicmovie','pl','Filmy muzyczne');
INSERT INTO lang VALUES('cat_nature','pl','Przyrodnicze');
INSERT INTO lang VALUES('cat_opera','pl','Opery');
INSERT INTO lang VALUES('cat_operetta','pl','Operetki');
INSERT INTO lang VALUES('cat_problem','pl','Problemowe');
INSERT INTO lang VALUES('cat_report','pl','Reporta¿e');
INSERT INTO lang VALUES('cat_satire','pl','Satyryczne');
INSERT INTO lang VALUES('cat_misc','pl','Ró¿ne');
INSERT INTO lang VALUES('cat_sf','pl','Science Fiction');
INSERT INTO lang VALUES('cat_show','pl','Show');
INSERT INTO lang VALUES('cat_spy','pl','Filmy Szpiegowskie');
INSERT INTO lang VALUES('cat_thriller','pl','Thriller');
INSERT INTO lang VALUES('cat_animal','pl','Zwierzê');
INSERT INTO lang VALUES('cat_animals','pl','Zwierzêta');
INSERT INTO lang VALUES('cat_travesty','pl','Travesty');
INSERT INTO lang VALUES('cat_vacation','pl','Wakacje');
INSERT INTO lang VALUES('cat_xmas','pl','Bo¿e Narodzenie');
INSERT INTO lang VALUES('cat_western','pl','Western');
INSERT INTO lang VALUES('cat_westerncomedy','pl','Western-Komedia');
INSERT INTO lang VALUES('cat_cartoon','pl','Film rysunkowy');
