# ========================================================
# Norwegian Language File created by phpVideoPro v0.4.6p6
# Original by Knut Fjellheim <knutfjellheim@hotmail.com>
# ========================================================

UPDATE pvp_languages SET charset='UTF-8' WHERE lang_id='no';
INSERT INTO pvp_lang VALUES ('about','no','Om phpVideoPro','');
INSERT INTO pvp_lang VALUES ('actor','no','Skuespiller','');
INSERT INTO pvp_lang VALUES ('actors','no','Skuespillere','');
INSERT INTO pvp_lang VALUES ('actors_list','no','Liste av Skuespillere','');
INSERT INTO pvp_lang VALUES ('add_entry','no','Legg til element','');
INSERT INTO pvp_lang VALUES ('back','no','Tilbake','');
INSERT INTO pvp_lang VALUES ('cancel','no','Avbryt','');
INSERT INTO pvp_lang VALUES ('category','no','Kategori','');
INSERT INTO pvp_lang VALUES ('close','no','Lukk','');
INSERT INTO pvp_lang VALUES ('colors','no','Farger','');
INSERT INTO pvp_lang VALUES ('comments','no','Kommentarer','');
INSERT INTO pvp_lang VALUES ('composer','no','Komponist','');
INSERT INTO pvp_lang VALUES ('compose_person','no','komponist','');
INSERT INTO pvp_lang VALUES ('configuration','no','Konfigurering','');
INSERT INTO pvp_lang VALUES ('content','no','Innhold','');
INSERT INTO pvp_lang VALUES ('country','no','Land','');
INSERT INTO pvp_lang VALUES ('create','no','Opprett','');
INSERT INTO pvp_lang VALUES ('create_success','no','Elementet ble opprettet.','');
INSERT INTO pvp_lang VALUES ('date_rec','no','Opptaksdato','');
INSERT INTO pvp_lang VALUES ('delete','no','Slett','');
INSERT INTO pvp_lang VALUES ('delete_remaining','no','nå slettes den resterende informasjonen for denne filmen fra databasen','');
INSERT INTO pvp_lang VALUES ('deleting_entry','no','Sletter element %1','');
INSERT INTO pvp_lang VALUES ('director','no','Regissør','');
INSERT INTO pvp_lang VALUES ('directors','no','Regissører','');
INSERT INTO pvp_lang VALUES ('directors_list','no','Liste av Regissører','');
INSERT INTO pvp_lang VALUES ('director_person','no','regissør','');
INSERT INTO pvp_lang VALUES ('display','no','Vis','');
INSERT INTO pvp_lang VALUES ('dupe_id_entered','no','Det er allerede et element i databasen for den media ID som er valgt. Vennligst trykk \"Back\" knappen på din nettleser og korriger informasjonen. Hint: Det er et felt ved siden av der du spesifiserte media ID. Detet feltet forteller deg den høyeste film ID. Normalt er det å anbefale å øke det første (fire siffer) tallet med en, eller for em ny film på samme media, øk det andre tallet (to siffer) med en.','');
INSERT INTO pvp_lang VALUES ('edit','no','Redigere','');
INSERT INTO pvp_lang VALUES ('edit_entry','no','Rediger element %1','');
INSERT INTO pvp_lang VALUES ('enter_min_free','no','Tast inn minimum vist ledig kapasitet på mediaet:','');
INSERT INTO pvp_lang VALUES ('farbe','no','Farge','');
INSERT INTO pvp_lang VALUES ('filter','no','Filter','');
INSERT INTO pvp_lang VALUES ('filter_setup','no','Filter Konfigurering','');
INSERT INTO pvp_lang VALUES ('finnished','no','Ferdig','');
INSERT INTO pvp_lang VALUES ('first_name','no','Første Navn','');
INSERT INTO pvp_lang VALUES ('free','no','Ledig','');
INSERT INTO pvp_lang VALUES ('free_space_on_media','no','Følgende media har minst %1 minutter av ledig kapasitet:','');
INSERT INTO pvp_lang VALUES ('free_space_title','no','Ledig kapasitet på mediaet','');
INSERT INTO pvp_lang VALUES ('fsk','no','Aldersgrense','');
INSERT INTO pvp_lang VALUES ('general','no','Generell','');
INSERT INTO pvp_lang VALUES ('help','no','Hjelp','');
INSERT INTO pvp_lang VALUES ('help_about','no','Hjelp om','');
INSERT INTO pvp_lang VALUES ('highest_db_entries','no','siste element i databasen er','');
INSERT INTO pvp_lang VALUES ('history','no','Historie','');
INSERT INTO pvp_lang VALUES ('howto','no','Hvordan man...','');
INSERT INTO pvp_lang VALUES ('howto_help','no','Hvordan man lager en ny hjelpefil','');
INSERT INTO pvp_lang VALUES ('howto_lang','no','Hvordan man lager en ny språkfil','');
INSERT INTO pvp_lang VALUES ('howto_templates','no','Hvordan man lager en ny språkmal','');
INSERT INTO pvp_lang VALUES ('incomplete_date','no','Dersom du ikke kjenner den nøyaktige datoen, men - for eksempel - kun at du har anskaffer den i  år 2000, estatt nuller for den ukjente datoen - i vårt eksempel skulle datoen se slik ut \"2000-00-00\".','');
INSERT INTO pvp_lang VALUES ('index','no','Indeks','');
INSERT INTO pvp_lang VALUES ('intro','no','Introduksjon','');
INSERT INTO pvp_lang VALUES ('invalid_media_nr','no','Det MediaNr du spesifiserte er enten ikke komplett eller ikke gyldig. Du må spesifisere et <b>nummer</b> i <b>begge</b> MediaNr feltene.','');
INSERT INTO pvp_lang VALUES ('in_list','no','i Liste','');
INSERT INTO pvp_lang VALUES ('language_settings','no','Språkoppsett','');
INSERT INTO pvp_lang VALUES ('length','no','Lengde','');
INSERT INTO pvp_lang VALUES ('medialength','no','MediaLengde','');
INSERT INTO pvp_lang VALUES ('medialist','no','Medialiste','');
INSERT INTO pvp_lang VALUES ('medium','no','Media','');
INSERT INTO pvp_lang VALUES ('menues','no','Menyer','');
INSERT INTO pvp_lang VALUES ('music','no','Komponister','');
INSERT INTO pvp_lang VALUES ('music_list','no','Liste av Komponister','');
INSERT INTO pvp_lang VALUES ('name','no','Navn','');
INSERT INTO pvp_lang VALUES ('no','no','Nei','');
INSERT INTO pvp_lang VALUES ('nobody_named','no','Det er ikke noen annen film av en %1 som heter %2 %3 i denne databasen, så jeg sletter dette elementet fra %1 tabellen.','');
INSERT INTO pvp_lang VALUES ('none','no','Ingen','');
INSERT INTO pvp_lang VALUES ('not_ok','no','Ikke vellykket','');
INSERT INTO pvp_lang VALUES ('not_yet_implemented','no','Beklager - ikke implementert.','');
INSERT INTO pvp_lang VALUES ('no_add_lang','no','Ingen nye språk er tilgjengelig.','');
INSERT INTO pvp_lang VALUES ('no_entries_found','no','Ingen elementer ble funnet','');
INSERT INTO pvp_lang VALUES ('no_entry_in_tapelist','no','Ikke vellykket -ingen elementer ble funnet i kassett listen','');
INSERT INTO pvp_lang VALUES ('no_space_of','no','Det var ingen media med et minimum av %1 minutter med ledig kapasitet funnet i databasen.','');
INSERT INTO pvp_lang VALUES ('of_aquiration','no','anskaffet','');
INSERT INTO pvp_lang VALUES ('page_bg','no','Side Bakgrunn','');
INSERT INTO pvp_lang VALUES ('picture','no','Farge Format','');
INSERT INTO pvp_lang VALUES ('recalc_free','no','Beregner ledig kapasitet for dette mediaet på nytt','');
INSERT INTO pvp_lang VALUES ('refresh_lang','no','Oppdater språk','');
INSERT INTO pvp_lang VALUES ('refresh_lang_comment','no','(legg fraser fra språk filen inn i databasen på nytt)','');
INSERT INTO pvp_lang VALUES ('s/w','no','s/v','');
INSERT INTO pvp_lang VALUES ('scan_new_lang_comment','no','(Dersom du laget din egen språkfil og la den i setup katalogen, vil dette fortelle phpVideoPro å søke etter den)','');
INSERT INTO pvp_lang VALUES ('scan_new_lang_files','no','Søk etter nye språkfiler?','');
INSERT INTO pvp_lang VALUES ('screen','no','Skjerm Format','');
INSERT INTO pvp_lang VALUES ('select_add_lang','no','Velg hvilket språk som skal installeres','');
INSERT INTO pvp_lang VALUES ('select_add_lang_comment','no','(Engelsk er allerede installert og vil altid være installert - se neste innslag. For andre språk som allerede er installert, se neste innslag også.)','');
INSERT INTO pvp_lang VALUES ('select_primary_lang','no','Velg hovedspråk','');
INSERT INTO pvp_lang VALUES ('select_primary_lang_comment','no','(fraser som ikke eksisterer vil altid bli erstattet med en engelsk frase)','');
INSERT INTO pvp_lang VALUES ('set_filter','no','Sett Filter','');
INSERT INTO pvp_lang VALUES ('source','no','Kilde','');
INSERT INTO pvp_lang VALUES ('staff','no','Bemanning','');
INSERT INTO pvp_lang VALUES ('sure_to_delete','no','Er du sikker på at du ønsker å slette all data for %1','');
INSERT INTO pvp_lang VALUES ('table_bg','no','Tabell Bakgrunn','');
INSERT INTO pvp_lang VALUES ('tapelist_update_failed','no','Kunne ikke oppdatere kassett listen','');
INSERT INTO pvp_lang VALUES ('taperest_absolute','no','Gjenværende tid(totalt)','');
INSERT INTO pvp_lang VALUES ('taperest_filtered','no','Gjenværende tid(filtrert)','');
INSERT INTO pvp_lang VALUES ('template_set','no','Velg mal for utseende','');
INSERT INTO pvp_lang VALUES ('th_bg','no','Tabell Topp Bakgrunn','');
INSERT INTO pvp_lang VALUES ('time_left','no','%1 minutt igjen','');
INSERT INTO pvp_lang VALUES ('title','no','Tittel','');
INSERT INTO pvp_lang VALUES ('tone','no','Lyd Format','');
INSERT INTO pvp_lang VALUES ('unknown','no','ukjent','');
INSERT INTO pvp_lang VALUES ('unset_filter','no','Fjern Filter','');
INSERT INTO pvp_lang VALUES ('update','no','Oppdater','');
INSERT INTO pvp_lang VALUES ('update_failed','no','Kunne ikke oppdatere elementet','');
INSERT INTO pvp_lang VALUES ('update_success','no','Elementet ble oppdatert','');
INSERT INTO pvp_lang VALUES ('use_charset','no','Benytt tegnsett','');
INSERT INTO pvp_lang VALUES ('use_charset_comment','no','(dette er viktig for tegnsett koding)','');
INSERT INTO pvp_lang VALUES ('view','no','Vis','');
INSERT INTO pvp_lang VALUES ('view_entry','no','Vis element %1','');
INSERT INTO pvp_lang VALUES ('warning','no','advarsel','');
INSERT INTO pvp_lang VALUES ('wrong_date','no','Datoen %1 du spesifiserte (%2) er ugyldig. Når du oppgir en dato, vennligst benytt formatet \"ÅÅÅÅ-MM-DD\", der \"ÅÅÅÅ\" står for årstallet (fire siffer), \"MM\" for måned og \"DD\" for dag (begge to siffer). Dersom du ikke ønsker noen dato her kan du la feltene stå tomme (eller sett dem til \"0000-00-00\").','');
INSERT INTO pvp_lang VALUES ('year','no','År','');
INSERT INTO pvp_lang VALUES ('yes','no','Ja','');
