# ========================================================
# Spanish Language File created by phpVideoPro v0.5.4p2
# ========================================================

UPDATE pvp_languages SET charset='UTF-8' WHERE lang_id='es';
INSERT INTO pvp_lang VALUES ('about','es','En cuanto a','');
INSERT INTO pvp_lang VALUES ('actions','es','Acciones','');
INSERT INTO pvp_lang VALUES ('actors','es','Actores','');
INSERT INTO pvp_lang VALUES ('actors_list','es','Lista de Actores','');
INSERT INTO pvp_lang VALUES ('actor_persons','es','Actores','');
INSERT INTO pvp_lang VALUES ('add_access','es','Puede añadir nueva información','');
INSERT INTO pvp_lang VALUES ('add_access_short','es','añadir','');
INSERT INTO pvp_lang VALUES ('add_entry','es','Añadir información','');
INSERT INTO pvp_lang VALUES ('add_user','es','Añadir usuario','');
INSERT INTO pvp_lang VALUES ('admin_access','es','Acceder al los menús de admininistrador','');
INSERT INTO pvp_lang VALUES ('admin_cats','es','Administrar Categorías','');
INSERT INTO pvp_lang VALUES ('admin_disktypes','es','Editar el Tipo de Disco','');
INSERT INTO pvp_lang VALUES ('admin_filter','es','Configuración de los filtros por defecto','');
INSERT INTO pvp_lang VALUES ('admin_movietech','es','Editar datos tecnicos de la pelicula','');
INSERT INTO pvp_lang VALUES ('admin_orphans','es','Eliminación de entradas huérfana','');
INSERT INTO pvp_lang VALUES ('admin_printers','es','Editar los impresores','');
INSERT INTO pvp_lang VALUES ('admin_pstemplates','es','Editar el Templete PSLabel','');
INSERT INTO pvp_lang VALUES ('admin_sessions','es','Administrar la Sesiónes','');
INSERT INTO pvp_lang VALUES ('admin_translations','es','Editar las Traducciones','');
INSERT INTO pvp_lang VALUES ('admin_useredit','es','Editar la Cuenta del Usuario','');
INSERT INTO pvp_lang VALUES ('admin_users','es','Administar las Cuentas de Usuarios','');
INSERT INTO pvp_lang VALUES ('back','es','Atras','');
INSERT INTO pvp_lang VALUES ('backup_db','es','Copia de reserva de la base de datos','');
INSERT INTO pvp_lang VALUES ('backup_db_complete','es','Crear copia de eserva de la base de datos completa (incl. datos técnicos y preferencias) ','');
INSERT INTO pvp_lang VALUES ('backup_db_moviedel','es','Crear copia de reserva de datos relevantes solamente a películas, e insertar una instrucción de eliminar datos vetustos, antes de la inserción de la instrucción de  para (copia de reserva) datos nuevos. ','');
INSERT INTO pvp_lang VALUES ('backup_db_movies','es','Crear copia de reserva de datos relevantes solamente a películas (peliculas, actores, (etc.)','');
INSERT INTO pvp_lang VALUES ('backup_db_runscript','es','¿Desea crear la escritura ahora?','');
INSERT INTO pvp_lang VALUES ('cancel','es','Cancelar','');
INSERT INTO pvp_lang VALUES ('categories','es','Categorías','');
INSERT INTO pvp_lang VALUES ('category','es','Categoría','');
INSERT INTO pvp_lang VALUES ('catlist_alpha','es','Lista de medio en orden alfabético, y sorteada por categoría','');
INSERT INTO pvp_lang VALUES ('cat_action','es','Acción','');
INSERT INTO pvp_lang VALUES ('cat_adventure','es','Aventura','');
INSERT INTO pvp_lang VALUES ('cat_agents','es','Agentes','');
INSERT INTO pvp_lang VALUES ('cat_animals','es','Animales','');
INSERT INTO pvp_lang VALUES ('cat_bible','es','Bíblia','');
INSERT INTO pvp_lang VALUES ('cat_biography','es','Biográfia','');
INSERT INTO pvp_lang VALUES ('cat_camera','es','Camara','');
INSERT INTO pvp_lang VALUES ('cat_cartoon','es','Caricatura','');
INSERT INTO pvp_lang VALUES ('cat_catastrophe','es','Catástrofe','');
INSERT INTO pvp_lang VALUES ('cat_children','es','Infantes','');
INSERT INTO pvp_lang VALUES ('cat_comedy','es','Comedia','');
INSERT INTO pvp_lang VALUES ('cat_concert','es','Concierto','');
INSERT INTO pvp_lang VALUES ('cat_crime','es','Crimen','');
INSERT INTO pvp_lang VALUES ('cat_documentary','es','Documentación','');
INSERT INTO pvp_lang VALUES ('cat_fairytale','es','Cuentos de Hadas','');
INSERT INTO pvp_lang VALUES ('cat_fantasy','es','Fantasía','');
INSERT INTO pvp_lang VALUES ('cat_handle_empty','es','El nombre para esta categoría no puede estar en blanco. Por favor regrése y arregle esto par la categoría %1.','');
INSERT INTO pvp_lang VALUES ('cat_history','es','História','');
INSERT INTO pvp_lang VALUES ('cat_internal_name','es','Nombre','');
INSERT INTO pvp_lang VALUES ('cat_judaica','es','Judaico','');
INSERT INTO pvp_lang VALUES ('cat_love','es','Películas de amor','');
INSERT INTO pvp_lang VALUES ('cat_misc','es','Misceláneo','');
INSERT INTO pvp_lang VALUES ('cat_monumental','es','Monumental','');
INSERT INTO pvp_lang VALUES ('cat_music','es','Música','');
INSERT INTO pvp_lang VALUES ('cat_musical','es','Musicál','');
INSERT INTO pvp_lang VALUES ('cat_musicmovie','es','Películas Musicáles','');
INSERT INTO pvp_lang VALUES ('cat_nature','es','Naturaleza','');
INSERT INTO pvp_lang VALUES ('cat_operetta','es','Opereta','');
INSERT INTO pvp_lang VALUES ('cat_party','es','Fiesta','');
INSERT INTO pvp_lang VALUES ('cat_problem','es','Problema','');
INSERT INTO pvp_lang VALUES ('cat_report','es','Reportaje','');
INSERT INTO pvp_lang VALUES ('cat_satire','es','Satírica','');
INSERT INTO pvp_lang VALUES ('cat_scary','es','Peliculas de Miedo','');
INSERT INTO pvp_lang VALUES ('cat_sf','es','Ciencia Ficción','');
INSERT INTO pvp_lang VALUES ('cat_show','es','Espectáculo','');
INSERT INTO pvp_lang VALUES ('cat_spy','es','Películas de Espionaje','');
INSERT INTO pvp_lang VALUES ('cat_stage','es','Escenario','');
INSERT INTO pvp_lang VALUES ('cat_thriller','es','Intriga','');
INSERT INTO pvp_lang VALUES ('cat_trans_update_failed','es','Falló la actualización para las traducciones en la siguiente categoría: %1','');
INSERT INTO pvp_lang VALUES ('cat_travesty','es','Travestía','');
INSERT INTO pvp_lang VALUES ('cat_update_failed','es','Falló la actualización en las siguientes categorías: %1','');
INSERT INTO pvp_lang VALUES ('cat_vacation','es','Vacación','');
INSERT INTO pvp_lang VALUES ('cat_videoclip','es','Video corto','');
INSERT INTO pvp_lang VALUES ('cat_war','es','Películas de Guerra','');
INSERT INTO pvp_lang VALUES ('cat_western','es','Oeste','');
INSERT INTO pvp_lang VALUES ('cat_westerncomedy','es','Comedia del Oeste','');
INSERT INTO pvp_lang VALUES ('cat_xmas','es','Navideñas','');
INSERT INTO pvp_lang VALUES ('change_disktype','es','Cámbie el disco por tipo %1','');
INSERT INTO pvp_lang VALUES ('change_media_length','es','Cámbiar el largo del medio','');
INSERT INTO pvp_lang VALUES ('change_media_length_for','es','Por favor ingrese la capacidad para %1','');
INSERT INTO pvp_lang VALUES ('change_nr','es','Cambiar el tipo de Numero del Medio/TipoMedio a %1','');
INSERT INTO pvp_lang VALUES ('change_rc','es','Cámbie el Código de Region','');
INSERT INTO pvp_lang VALUES ('change_rc_for','es','Cámbie el Código de Region a %1','');
INSERT INTO pvp_lang VALUES ('check_completed','es','Comprobación completa','');
INSERT INTO pvp_lang VALUES ('check_media_delete','es','Comprobando si el medio esta vacío','');
INSERT INTO pvp_lang VALUES ('close','es','Cerrar','');
INSERT INTO pvp_lang VALUES ('colors','es','Colores','');
INSERT INTO pvp_lang VALUES ('comments','es','Comentarios','');
INSERT INTO pvp_lang VALUES ('commercials','es','Comerciales','');
INSERT INTO pvp_lang VALUES ('composer','es','Compositor','');
INSERT INTO pvp_lang VALUES ('compose_person','es','compositor','');
INSERT INTO pvp_lang VALUES ('compose_persons','es','Compositores','');
INSERT INTO pvp_lang VALUES ('configuration','es','Configuración','');
INSERT INTO pvp_lang VALUES ('config_media','es','Peliculas y Medio','');
INSERT INTO pvp_lang VALUES ('confirm_delete','es','¿Esta seguro que desea eliminar este registro?','');
INSERT INTO pvp_lang VALUES ('confirm_userdelete','es','Está al eliminar al usuario #%1','');
INSERT INTO pvp_lang VALUES ('content','es','Contenido','');
INSERT INTO pvp_lang VALUES ('cookies','es','\"Cookies\"','');
INSERT INTO pvp_lang VALUES ('counter_start_stop','es','Comienze/Pare el contador','');
INSERT INTO pvp_lang VALUES ('countries','es','Países','');
INSERT INTO pvp_lang VALUES ('country','es','País','');
INSERT INTO pvp_lang VALUES ('create','es','Crear','');
INSERT INTO pvp_lang VALUES ('create_success','es','Entrada creada correctamente','');
INSERT INTO pvp_lang VALUES ('credits','es','Créditos','');
INSERT INTO pvp_lang VALUES ('cut_off','es','desconectar','');
INSERT INTO pvp_lang VALUES ('data_access','es','Acceso a los datos','');
INSERT INTO pvp_lang VALUES ('date_format','es','Formato de fecha','');
INSERT INTO pvp_lang VALUES ('date_format_comment','es','Formato para mostrar la fecha.','');
INSERT INTO pvp_lang VALUES ('date_rec','es','Fecha de adquisición','');
INSERT INTO pvp_lang VALUES ('day','es','Día','');
INSERT INTO pvp_lang VALUES ('db_stats','es','Estadísticas','');
INSERT INTO pvp_lang VALUES ('delete','es','Eliminar','');
INSERT INTO pvp_lang VALUES ('delete_lang','es','Eliminar un lenguaje','');
INSERT INTO pvp_lang VALUES ('delete_lang_comment','es','Eliminar toda las frases de un lenguaje especifico de la base de datos. Esto no eliminará el archivo del lenguaje, así podrá reingresar las frases nuevamente mas tarde (si usted mismo no remueve el archivo).','');
INSERT INTO pvp_lang VALUES ('delete_orphans','es','Eliminando %1 huérfana(s):','');
INSERT INTO pvp_lang VALUES ('delete_remaining','es','Ahora se están eliminando los datos sobrantes  de la película en la BD.','');
INSERT INTO pvp_lang VALUES ('deleting_entry','es','Eliminando entrada %1','');
INSERT INTO pvp_lang VALUES ('del_access','es','Puede eliminar entradas','');
INSERT INTO pvp_lang VALUES ('del_access_short','es','Elim.','');
INSERT INTO pvp_lang VALUES ('desc_admin_orphans','es','\"Entradas huérfanas\" son datos sin asignación, ejemplo: Actores, directores y/o compositores que están en la BD y no están relacionados con alguna película. Son típicamente el resultado de cambiar un nombre mal escrito después de haberlo guardado - pero nunca el resultado de haber eliminado entradas de películas. Por lo tanto, es una buena idea el eliminar esas entradas huérfanas: Primero para liberar recursos,  y segundo ayuda a prevenir una bajada de recursos de la BD.','');
INSERT INTO pvp_lang VALUES ('desc_backup_db','es','Siempre es bueno tener una copia de reserva a mano. De esta manera, todos sus datos que haya guardado en la BD son extraídos, y un archivo con el comando \"SQL\" es creado. Puede usar dicho archivo en cualquier momento para llenar una base de datos que esté vacía (ej: Para duplicación). Asegúrese de no usar una copia de reserva de una versión mas reciente, con una copia más vetusta de phpVideoPro - ¡Esto puede crear problemas!<BR>','');
INSERT INTO pvp_lang VALUES ('directors','es','Directores','');
INSERT INTO pvp_lang VALUES ('directors_list','es','Lista de directores','');
INSERT INTO pvp_lang VALUES ('director_persons','es','Directores','');
INSERT INTO pvp_lang VALUES ('disktype_add_failed','es','Disculpe. No se pudo añadir el tipo de disco nuevo.','');
INSERT INTO pvp_lang VALUES ('disktype_change','es','Cámbie el tipo de disco','');
INSERT INTO pvp_lang VALUES ('disktype_contains_media','es','Este tipo de disco no puede ser eliminado en este momento, ya que el siguiente medio todavía lo esta refiriendo.','');
INSERT INTO pvp_lang VALUES ('disktype_name_empty','es','El nombre del tipo de disco no puede estar en blanco. Por favor regrese y corrija este para el tipo de disco #%1','');
INSERT INTO pvp_lang VALUES ('disktype_update_failed','es','Disculpe. No se pudo actualizar el siguiente tipo de disco #s: %1','');
INSERT INTO pvp_lang VALUES ('disk_size','es','Tamaño de disco','');
INSERT INTO pvp_lang VALUES ('disk_type','es','Tipo de disco','');
INSERT INTO pvp_lang VALUES ('display','es','Despliegue','');
INSERT INTO pvp_lang VALUES ('display_limit','es','Limite de pantalla','');
INSERT INTO pvp_lang VALUES ('display_limit_comment','es','(Cuantas lineas se mostrarán por página para las listas)','');
INSERT INTO pvp_lang VALUES ('dl_pvp_latest','es','Versión D/L mas reciente','');
INSERT INTO pvp_lang VALUES ('dupes','es','Entradas duplicadas','');
INSERT INTO pvp_lang VALUES ('dupe_id_entered','es','Ya existe una entrada en la BD para el identificador del medio ingresado. Oprima Atrás (\"Back\") en el navegador (\"Browser\") y corrija lo que ingresó. Sugerencia: Hay una cajilla para seleccionar, al lado del campo donde especificó el numero de medio. Esta cajilla le informará el número identificador de película mas alto. Normalmente es una buena elección para un medio nuevo, el incrementar por uno el primer número de 4 dígitos, o para una nueva película en el mismo tipo de medio, incrementar por uno el segundo numero de 2 dígitos.','');
INSERT INTO pvp_lang VALUES ('dupe_titles_found','es',' %1 Título(s) encontrado(s)con posibles duplicados:','');
INSERT INTO pvp_lang VALUES ('edit','es','Editar','');
INSERT INTO pvp_lang VALUES ('edit_entry','es','Editar entrada %1','');
INSERT INTO pvp_lang VALUES ('enable_cookies','es','¿Activar \"cookies\"?','');
INSERT INTO pvp_lang VALUES ('enable_cookies_comment','es','¿Desea manejar las preferencias del usuario (ej. filtros) utlizando \"cookies\"?','');
INSERT INTO pvp_lang VALUES ('ended_sessions','es','Sesión termidada.','');
INSERT INTO pvp_lang VALUES ('enter_min_free','es','Ingrese el espacio libre mínimo que será mostrado para el medio:','');
INSERT INTO pvp_lang VALUES ('enter_new_medianr','es','Por favor ingrese el MediaNr para este %1.','');
INSERT INTO pvp_lang VALUES ('expire_cookies','es','Vida de los \"cookies\".','');
INSERT INTO pvp_lang VALUES ('expire_cookies_comment','es','¿Cuanto debe durar un \"cookie\" en el navegador (\"Browser\") del usuario?','');
INSERT INTO pvp_lang VALUES ('filter','es','Filtro','');
INSERT INTO pvp_lang VALUES ('filter_setup','es','Configuración del Filtro','');
INSERT INTO pvp_lang VALUES ('finnished','es','Completado','');
INSERT INTO pvp_lang VALUES ('first_name','es','Primer Nombre','');
INSERT INTO pvp_lang VALUES ('format','es','Formato','');
INSERT INTO pvp_lang VALUES ('free','es','Libre','');
INSERT INTO pvp_lang VALUES ('free_space_on_media','es','Los siguientes medios tienen por lo menos %1 minutos de espacio disopnible:','');
INSERT INTO pvp_lang VALUES ('free_space_title','es','Espacio libre en el medio.','');
INSERT INTO pvp_lang VALUES ('goto_entry','es','Ir directamente a la entrada:','');
INSERT INTO pvp_lang VALUES ('graphic_file','es','Archivo de Imagenes','');
INSERT INTO pvp_lang VALUES ('help','es','Ayuda','');
INSERT INTO pvp_lang VALUES ('help_about','es','Ayuda en cuanto a','');
INSERT INTO pvp_lang VALUES ('highest_db_entries','es','Entradas mas altas en la BD','');
INSERT INTO pvp_lang VALUES ('history','es','Historia','');
INSERT INTO pvp_lang VALUES ('hit_back_to_correct','es','Oprima \"Atras\" (Back) para corregir el error.','');
INSERT INTO pvp_lang VALUES ('hour','es','Hora','');
INSERT INTO pvp_lang VALUES ('hours','es','Horas','');
INSERT INTO pvp_lang VALUES ('howto','es','Como...','');
INSERT INTO pvp_lang VALUES ('howto_help','es','Como crear un archivo de ayuda','');
INSERT INTO pvp_lang VALUES ('howto_label','es','Como crear/configurar un templete de etiquetas','');
INSERT INTO pvp_lang VALUES ('howto_lang','es','Como crear un arhivo de lenguaje nuevo ','');
INSERT INTO pvp_lang VALUES ('howto_templates','es','Como crear un grupo de templete nuevo.','');
INSERT INTO pvp_lang VALUES ('incomplete_date','es','Si no sabe la fecha exacta, pero por ejemplo, sólo sabe que lo adquirió en el año 2000, substituya con ceros los datos desconocidos. - ejemplo: \"00\" \"00\" \"2000\".','');
INSERT INTO pvp_lang VALUES ('index','es','Indice','');
INSERT INTO pvp_lang VALUES ('info_common','es','Información común','');
INSERT INTO pvp_lang VALUES ('info_common_info','es','<DIV ALIGN=\"center\">Esta es la versión %1 de phpVideoPro, funcionando en %2.</DIV>','');
INSERT INTO pvp_lang VALUES ('info_noupdate','es','<DIV ALIGN=\"center\"> La versión instalada de phpVideoPro (%1) es reciente - no hay nuevas versiones disponibles para descargar. Para descargar el archivo de la versión instalada, por favor vaya a <A HREF=http://projects.izzysoft.de/progs/get_update.php?program=pvp\" TARGET=\"_blank\">este eslabón</A>.</DIV>','');
INSERT INTO pvp_lang VALUES ('info_update','es','Actualizar información','');
INSERT INTO pvp_lang VALUES ('invalid_fsk','es','El valor ingresado en PG (\"%1\") no es válido. PG significa Guia Parentesco, es decir, la edad mínima que se necesita para tener acceso a esta película.','');
INSERT INTO pvp_lang VALUES ('invalid_media_nr','es','El Numero de Medio especificado esta incompleto o no es válido. Debe especificar un <b>número</b> dentro de <b>ambos</b> campos de Numero de Medio.','');
INSERT INTO pvp_lang VALUES ('in_list','es','en la lista','');
INSERT INTO pvp_lang VALUES ('is_rw','es','se puede volver a escribir','');
INSERT INTO pvp_lang VALUES ('label','es','Etiqueta','');
INSERT INTO pvp_lang VALUES ('labels','es','Etiquetas','');
INSERT INTO pvp_lang VALUES ('labeltype','es','Tipo de Etiqueta','');
INSERT INTO pvp_lang VALUES ('language_settings','es','Configuraciónes de lenguaje','');
INSERT INTO pvp_lang VALUES ('last_entry','es','Ultima entrada','');
INSERT INTO pvp_lang VALUES ('last_medianr','es','Actualmente el numero más alto para este tipo de medio es:','');
INSERT INTO pvp_lang VALUES ('layout_label','es','Escoger esquema','');
INSERT INTO pvp_lang VALUES ('left_offset','es','Compensación - Márgen Izquierdo','');
INSERT INTO pvp_lang VALUES ('length','es','Largo','');
INSERT INTO pvp_lang VALUES ('lines_per_page','es','Lineas por página','');
INSERT INTO pvp_lang VALUES ('lines_per_page_comment','es','Esto es para que la función de imprimir pueda determinar cuantas líneas de texto caben en una hoja de papel.','');
INSERT INTO pvp_lang VALUES ('line_count','es','Líneas','');
INSERT INTO pvp_lang VALUES ('list','es','Lista','');
INSERT INTO pvp_lang VALUES ('listgen','es','Generador de Listados','');
INSERT INTO pvp_lang VALUES ('lists','es','Listas','');
INSERT INTO pvp_lang VALUES ('login','es','Inicio de Sesión','');
INSERT INTO pvp_lang VALUES ('login_failed','es','Su inicio falló. Quizas ingresó mal su contraseña, o la cuenta de ususario solicitada no existe.<P/>','');
INSERT INTO pvp_lang VALUES ('login_required','es','Sus privilegios no son suficientes para la acción solicitada. Puede iniciar la sesión con una cuenta apropiada.<P/>','');
INSERT INTO pvp_lang VALUES ('logout_user','es','Iniciado como \"%1\". <A HREF=\"%2\">Cerrar sesión</A>','');
INSERT INTO pvp_lang VALUES ('longplay','es','Larga Duración','');
INSERT INTO pvp_lang VALUES ('lower_left_corner','es','Esquina Derecha, abajo (x/y)','');
INSERT INTO pvp_lang VALUES ('max','es','max.','');
INSERT INTO pvp_lang VALUES ('max_fontsize','es','Tamaño máximo de Tipografia','');
INSERT INTO pvp_lang VALUES ('media','es','Medio','');
INSERT INTO pvp_lang VALUES ('medialength','es','Duración del medio','');
INSERT INTO pvp_lang VALUES ('medialist','es','Lista de los Medios','');
INSERT INTO pvp_lang VALUES ('medialist_alpha','es','Lista de los medios en orden alfabético.','');
INSERT INTO pvp_lang VALUES ('medialist_num','es','Lista de los medio en orden numérico','');
INSERT INTO pvp_lang VALUES ('medianr','es','Numero de Medio','');
INSERT INTO pvp_lang VALUES ('mediatype','es','Tipo de Medio','');
INSERT INTO pvp_lang VALUES ('media_change','es','Cambie el Numero de Medio','');
INSERT INTO pvp_lang VALUES ('media_copy','es','Copie datos al Numero de Medio','');
INSERT INTO pvp_lang VALUES ('medium','es','Médium','');
INSERT INTO pvp_lang VALUES ('medium_deleted','es','No hay mas peliculas en este médium - médium removido.','');
INSERT INTO pvp_lang VALUES ('medium_not_deleted','es','Médium no fue removido.','');
INSERT INTO pvp_lang VALUES ('medium_overview','es','Repaso para %1','');
INSERT INTO pvp_lang VALUES ('menues','es','Menús','');
INSERT INTO pvp_lang VALUES ('month','es','Mes','');
INSERT INTO pvp_lang VALUES ('movies','es','Películas','');
INSERT INTO pvp_lang VALUES ('movies_left_in_cat','es','La categoría %1 todavía contiene %2 película(s), por lo tanto no podrá ser removida. Disculpe.','');
INSERT INTO pvp_lang VALUES ('movies_left_reference','es','Esta entrada no puede ser eliminada. Hay %1 película(s) en la BD que tienen referencia a estas.','');
INSERT INTO pvp_lang VALUES ('movie_color_default','es','Color por defecto del formato de una película.','');
INSERT INTO pvp_lang VALUES ('movie_color_default_comment','es','Este será usado como formato pre-establecido para color para una nueva entrada.','');
INSERT INTO pvp_lang VALUES ('movie_onlabel_default','es','Información por defecto para la etiqueta ','');
INSERT INTO pvp_lang VALUES ('movie_onlabel_default_comment','es','Por defecto para las entradas nuevas: ¿la información para esta película deberá ser incluida cuando la(s) etiqueta(s) de este medio sean generadas?','');
INSERT INTO pvp_lang VALUES ('movie_tone_default','es','Formato de sonido por defecto de una película.','');
INSERT INTO pvp_lang VALUES ('movie_tone_default_comment','es','Este será usado como formato pre-establecido para sonido de una nueva entrada.','');
INSERT INTO pvp_lang VALUES ('music','es','Compositor','');
INSERT INTO pvp_lang VALUES ('music_list','es','Lista de compositores','');
INSERT INTO pvp_lang VALUES ('name','es','Nombre','');
INSERT INTO pvp_lang VALUES ('never','es','nunca','');
INSERT INTO pvp_lang VALUES ('new_disktype','es','Nuevo Tipo de Disco .','');
INSERT INTO pvp_lang VALUES ('new_medianr','es','Nuevo Numero de Medio','');
INSERT INTO pvp_lang VALUES ('new_movie_on','es','Nuevo %1','');
INSERT INTO pvp_lang VALUES ('nobody_named','es','No hay una película por %1 que se llame %2 %3 en esta BD, por lo tanto se eliminó esta entrada de la tabla %1.','');
INSERT INTO pvp_lang VALUES ('none','es','Ningún','');
INSERT INTO pvp_lang VALUES ('not_ok','es','Falló','');
INSERT INTO pvp_lang VALUES ('not_yet_implemented','es','Disculpe. Todavía no ha sido implementado.','');
INSERT INTO pvp_lang VALUES ('no_add_lang','es','No hay lenguajes adicionales disponibles.','');
INSERT INTO pvp_lang VALUES ('no_entries_found','es','No se encontraron entradas','');
INSERT INTO pvp_lang VALUES ('no_entry_in_tapelist','es','Falló - no se encontraron entradas en la lista de cintas.','');
INSERT INTO pvp_lang VALUES ('no_orphans_found','es','¡Enhorabuena! No tienes esqueletos en tu gabinete. ¿Algo más?','');
INSERT INTO pvp_lang VALUES ('no_space_of','es','No hay un médium con un mínimo de %1 min de espacio libre en la BD.','');
INSERT INTO pvp_lang VALUES ('of_aquiration','es','de adquisición','');
INSERT INTO pvp_lang VALUES ('old_sessions','es','Sesiones vetustas antes de <INPUT NAME=\"%1\" VALUE=\"\" CLASS=\"yesnobutton\"> días.','');
INSERT INTO pvp_lang VALUES ('orig_disktype','es','Tipo de Disco original','');
INSERT INTO pvp_lang VALUES ('orig_medianr','es','Numero de Medio original','');
INSERT INTO pvp_lang VALUES ('orig_trans','es','Traducción Original (%1)','');
INSERT INTO pvp_lang VALUES ('orphans_found','es','Se encontraron %1 huérfano(s):','');
INSERT INTO pvp_lang VALUES ('other_pages','es','Otras páginas','');
INSERT INTO pvp_lang VALUES ('password','es','Contraseña','');
INSERT INTO pvp_lang VALUES ('password_retype','es','Ingrese Nuevamente la Contraseña','');
INSERT INTO pvp_lang VALUES ('picture','es','Formato del color','');
INSERT INTO pvp_lang VALUES ('preferences','es','Preferencias','');
INSERT INTO pvp_lang VALUES ('print','es','Imprimír','');
INSERT INTO pvp_lang VALUES ('printer','es','Impresora','');
INSERT INTO pvp_lang VALUES ('printer_add_failed','es','Ocurrio un error al añadir esta impresora.','');
INSERT INTO pvp_lang VALUES ('printer_add_success','es','Impresora añadida con exito.','');
INSERT INTO pvp_lang VALUES ('printer_comment','es','Si desea imprimir en los formularios (usados para etiquetas PS), necesitamos la compensación márgenes exactos de su impresora.','');
INSERT INTO pvp_lang VALUES ('printer_name','es','Nombre','');
INSERT INTO pvp_lang VALUES ('printer_upd_failed','es','Actualización falló para las siguientes impresoras: %1','');
INSERT INTO pvp_lang VALUES ('print_label','es','Imprimir etiqueta:','');
INSERT INTO pvp_lang VALUES ('pslabel','es','Etiqueta PS','');
INSERT INTO pvp_lang VALUES ('pstpl_name','es','Nombre de Templete','');
INSERT INTO pvp_lang VALUES ('pstpl_type','es','Tipo de Templete','');
INSERT INTO pvp_lang VALUES ('read_access','es','Puede reviasr entradas','');
INSERT INTO pvp_lang VALUES ('read_access_short','es','ver','');
INSERT INTO pvp_lang VALUES ('recalc_free','es','Recalculando el espacio libre disponible en este medio','');
INSERT INTO pvp_lang VALUES ('refresh_lang','es','Refrescar lista de lenguaje','');
INSERT INTO pvp_lang VALUES ('refresh_lang_comment','es','Ingrese nuevamente las frases del archivo del idioma a la BD','');
INSERT INTO pvp_lang VALUES ('region_code','es','Código De Región','');
INSERT INTO pvp_lang VALUES ('remove_empty_media','es','Remover el medio vacío','');
INSERT INTO pvp_lang VALUES ('remove_empty_media_comment','es','¿Desea remover el medio del mantenimiento de espacio libre, cuando la última película sea eliminada del mismo?','');
INSERT INTO pvp_lang VALUES ('reset','es','Reiniciar','');
INSERT INTO pvp_lang VALUES ('rw_media','es','Medio Editable','');
INSERT INTO pvp_lang VALUES ('rw_media_comment','es','Medio para el cual se mantendrá espacio libre (ya que usted graba ellos).','');
INSERT INTO pvp_lang VALUES ('s/w','es','B/N','');
INSERT INTO pvp_lang VALUES ('save_lang_file','es','Guarde la traducción objetiva al archivo','');
INSERT INTO pvp_lang VALUES ('scan_new_lang_comment','es','(Si creó sus propios archivos de lenguajes y los puso adentro del directorio \"setup\", esto le dirá a phpVideoPro donde encontrarlos)','');
INSERT INTO pvp_lang VALUES ('scan_new_lang_files','es','¿Escanear para nuevos archivos de lenguajes?','');
INSERT INTO pvp_lang VALUES ('screen','es','Formato de pantalla','');
INSERT INTO pvp_lang VALUES ('search','es','Búsqueda','');
INSERT INTO pvp_lang VALUES ('search_movie','es','Búsqueda De Película','');
INSERT INTO pvp_lang VALUES ('select_add_lang','es','Seleccióne un lenguaje adicional a instalar','');
INSERT INTO pvp_lang VALUES ('select_add_lang_comment','es','(Inglés ya está instalado y siempre lo estará - vea el siguiente ítem. Para otros lenguajes ya instalados, también vea el siguiente ítem.)','');
INSERT INTO pvp_lang VALUES ('select_primary_lang','es','Seleccione lenguaje principal','');
INSERT INTO pvp_lang VALUES ('select_primary_lang_comment','es','(para las frases que falten, siempre habrá un por defecto en inglés)','');
INSERT INTO pvp_lang VALUES ('sel_target_lang','es','Seleccione el lenguaje objetivo (al cual traducir):','');
INSERT INTO pvp_lang VALUES ('session','es','Sesión','');
INSERT INTO pvp_lang VALUES ('session_expired','es','Su sesión ha expirado - inicie nuevamente.','');
INSERT INTO pvp_lang VALUES ('session_purgetime','es','¿Despues de cuanto tiempo sin uso se considerará inactiva una sesión ?','');
INSERT INTO pvp_lang VALUES ('session_purgetime_comment','es','¿Cuanto tiempo debe mentenerse valida una sesión sin actividad?','');
INSERT INTO pvp_lang VALUES ('sess_dla','es','Accedido último','');
INSERT INTO pvp_lang VALUES ('sess_end','es','Terminó','');
INSERT INTO pvp_lang VALUES ('sess_id','es','ID de sesión','');
INSERT INTO pvp_lang VALUES ('sess_ip','es','IP Remoto','');
INSERT INTO pvp_lang VALUES ('sess_start','es','Comenzó','');
INSERT INTO pvp_lang VALUES ('set_filter','es','Activar Filtro','');
INSERT INTO pvp_lang VALUES ('site_info','es','Información del Sitio','');
INSERT INTO pvp_lang VALUES ('site_info_comment','es','¿Qué información del sitio se mostrara en la barra del título del navegador (\"Browser\")?','');
INSERT INTO pvp_lang VALUES ('source','es','Origen','');
INSERT INTO pvp_lang VALUES ('staff','es','Equipo','');
INSERT INTO pvp_lang VALUES ('start_page','es','Página Inicial','');
INSERT INTO pvp_lang VALUES ('start_pvp','es','Iniciar phpVideoPro','');
INSERT INTO pvp_lang VALUES ('stats','es','Estadísticas','');
INSERT INTO pvp_lang VALUES ('stat_categories','es','Categorías (usadas/todas)','');
INSERT INTO pvp_lang VALUES ('stat_counts','es','Contadores','');
INSERT INTO pvp_lang VALUES ('stat_ranks','es','Clasificación','');
INSERT INTO pvp_lang VALUES ('submit','es','Sumisión','');
INSERT INTO pvp_lang VALUES ('sure_to_delete','es','¿Está seguro que desea borrar todos los datos de %1 ?','');
INSERT INTO pvp_lang VALUES ('tapelist_update_failed','es','Error al actualizar la lista de cintas','');
INSERT INTO pvp_lang VALUES ('taperest_absolute','es','Espacio libre en todo el medio (sin aplicar filtros)','');
INSERT INTO pvp_lang VALUES ('taperest_filtered','es','Espacio libre en todo el medio (aplicando filtros)','');
INSERT INTO pvp_lang VALUES ('target_trans','es','Traducciones para su lenguaje objeto (%1)','');
INSERT INTO pvp_lang VALUES ('techdata','es','Datos Técnicos','');
INSERT INTO pvp_lang VALUES ('template_file','es','Archivo de Templete','');
INSERT INTO pvp_lang VALUES ('template_set','es','Colección de Templete','');
INSERT INTO pvp_lang VALUES ('time_left','es','Queda(n) %1 minuto(s)','');
INSERT INTO pvp_lang VALUES ('title','es','Título','');
INSERT INTO pvp_lang VALUES ('tone','es','Formato del Tono','');
INSERT INTO pvp_lang VALUES ('top_offset','es','Compensación de Márgenes - Arriba','');
INSERT INTO pvp_lang VALUES ('trans_code','es','Código de Traducción','');
INSERT INTO pvp_lang VALUES ('trans_sample','es','Eslabón a la Muestra','');
INSERT INTO pvp_lang VALUES ('unit','es','Unidad','');
INSERT INTO pvp_lang VALUES ('unknown','es','Desconocido','');
INSERT INTO pvp_lang VALUES ('unset_filter','es','Desactivar Filtro','');
INSERT INTO pvp_lang VALUES ('update','es','Actualizar','');
INSERT INTO pvp_lang VALUES ('update_failed','es','Falló el actualizar la entrada','');
INSERT INTO pvp_lang VALUES ('update_success','es','Entrada actualizada correctamente','');
INSERT INTO pvp_lang VALUES ('upd_access','es','Es posible que atualize entradas ya existentes','');
INSERT INTO pvp_lang VALUES ('upd_access_short','es','act','');
INSERT INTO pvp_lang VALUES ('upper_right_corner','es','Esquina, arribaa la Derecha -  (x/y)','');
INSERT INTO pvp_lang VALUES ('user','es','Usuario','');
INSERT INTO pvp_lang VALUES ('user_deleted','es','El usuario #%1, \"%2\" (%3) fue eliminado con éxito','');
INSERT INTO pvp_lang VALUES ('user_delete_failed','es','La eliminación del usuario #%1, \"%2\" (%3) falló','');
INSERT INTO pvp_lang VALUES ('user_delete_report','es','Resultados del proceso de eliminar al usuario','');
INSERT INTO pvp_lang VALUES ('user_update_failed','es','Actualización falló para los siguientes usuarios: %1','');
INSERT INTO pvp_lang VALUES ('view','es','Véa','');
INSERT INTO pvp_lang VALUES ('view_entry','es','Véa entrada %1','');
INSERT INTO pvp_lang VALUES ('warning','es','Aviso','');
INSERT INTO pvp_lang VALUES ('week','es','Semana','');
INSERT INTO pvp_lang VALUES ('welcome','es','Bienvenido a phpVideoPro','');
INSERT INTO pvp_lang VALUES ('wrong_date','es','La fecha %1 especificada (%2) no es válida. El formato de las fechas es: por favor ingrese el día en el primer, el mes en el segundo, y el año en el tercer campo, sólo utilizando dígitos. Si no está seguro de alguna fecha exacta, ingrese ceros en los campos en duda: ej. \"00\" \"02\" \"2002\" significa \"algún día de  Febrero del 2002\", or \"00\" \"00\" \"0000\" significa \"alguna vez\".','');
INSERT INTO pvp_lang VALUES ('year','es','Año','');
INSERT INTO pvp_lang VALUES ('yes','es','Sí','');
