# ========================================================
# Russian Translation phrases for phpVideoPro
# by Denis Shvidkiy
# ========================================================

UPDATE languages SET charset='koi8-r' WHERE lang_id='ru';
INSERT INTO lang VALUES('medium','ru','Носитель');
INSERT INTO lang VALUES('nr','ru','©');
INSERT INTO lang VALUES('title','ru','Название');
INSERT INTO lang VALUES('length','ru','Продолжительность');
INSERT INTO lang VALUES('year','ru','Год');
INSERT INTO lang VALUES('category','ru','Категория');
INSERT INTO lang VALUES('free','ru','Свободно');
INSERT INTO lang VALUES('content','ru','Содержимое');
INSERT INTO lang VALUES('filter_setup','ru','Настройки фильтра');
INSERT INTO lang VALUES('mediatype','ru','ТипНосителя');
INSERT INTO lang VALUES('screen','ru','Формат экрана');
INSERT INTO lang VALUES('picture','ru','Формат цвета');
INSERT INTO lang VALUES('actor','ru','Актер');
INSERT INTO lang VALUES('actors','ru','Актеры');
INSERT INTO lang VALUES('director','ru','Режиссер');
INSERT INTO lang VALUES('directors','ru','Режиссеры');
INSERT INTO lang VALUES('composer','ru','Композитор');
INSERT INTO lang VALUES('music','ru','Композитор');
INSERT INTO lang VALUES('min','ru','мин.');
INSERT INTO lang VALUES('max','ru','макс.');
INSERT INTO lang VALUES('s/w','ru','ч/б');
INSERT INTO lang VALUES('farbe','ru','Цвет');
INSERT INTO lang VALUES('edit_entry','ru','Редактировать запись %1');
INSERT INTO lang VALUES('view_entry','ru','Просмотреть запись %1');
INSERT INTO lang VALUES('add_entry','ru','Добавить запись');
INSERT INTO lang VALUES('unknown','ru','неизвестно');
INSERT INTO lang VALUES('country','ru','Страна');
INSERT INTO lang VALUES('no','ru','Нет');
INSERT INTO lang VALUES('yes','ru','Да');
INSERT INTO lang VALUES('minute_abbrev','ru','мин.');
INSERT INTO lang VALUES('name','ru','Имя');
INSERT INTO lang VALUES('comments','ru','Комментарии');
INSERT INTO lang VALUES('cancel','ru','Отменить');
INSERT INTO lang VALUES('create','ru','Создать');
INSERT INTO lang VALUES('update','ru','Обновить');
INSERT INTO lang VALUES('edit','ru','Редактировать');
INSERT INTO lang VALUES('delete','ru','Удалить');
INSERT INTO lang VALUES('warning','ru','предупреждение');
INSERT INTO lang VALUES('wrong_date','ru','Указанная Вами дата %1 неверна (%2). Для ввода даты используйте только цифры. В первом поле задается день, во втором месяц и в третьем год. Если Вы не знаете точную дату, введите нули, например, "00" "02" "2002" - "февраль 2002", или "00" "00" "0000" -  "когда-либо".');
INSERT INTO lang VALUES('create_success','ru','Запись успешно создана');
INSERT INTO lang VALUES('update_failed','ru','Ошибка при обновлении записи');
INSERT INTO lang VALUES('update_success','ru','Обновление прошло успешно');
INSERT INTO lang VALUES('about','ru','О...');
INSERT INTO lang VALUES('history','ru','История');
INSERT INTO lang VALUES('view','ru','Просмотр');
INSERT INTO lang VALUES('deleting_entry','ru','Удаление записи %1');
INSERT INTO lang VALUES('free_space_title','ru', 'Свободного места на носителе');
INSERT INTO lang VALUES('filter','ru','Фильтр');
INSERT INTO lang VALUES('set_filter','ru','Задать фильтр');
INSERT INTO lang VALUES('unset_filter','ru','Сбросить фильтр');
INSERT INTO lang VALUES('help','ru','Помощь');
INSERT INTO lang VALUES('compose_person','ru','композитор');
INSERT INTO lang VALUES('director_person','ru','режиссер');
INSERT INTO lang VALUES('check_completed','ru','Проверка завершена');
INSERT INTO lang VALUES('not_ok','ru','Ошибка');
INSERT INTO lang VALUES('finnished','ru','Завершено');
INSERT INTO lang VALUES('time_left','ru','%1 минут осталось');
INSERT INTO lang VALUES('configuration','ru','Настройки');
INSERT INTO lang VALUES('index','ru','Индекс');
INSERT INTO lang VALUES('intro','ru','Интро');
INSERT INTO lang VALUES('menues','ru','Меню');
INSERT INTO lang VALUES('back','ru','Назад');
INSERT INTO lang VALUES('close','ru','Закрыть');
INSERT INTO lang VALUES('help_about','ru','Помощь о...');
INSERT INTO lang VALUES('actors_list','ru','Список актеров');
INSERT INTO lang VALUES('directors_list','ru','Список режиссеров');
INSERT INTO lang VALUES('music_list','ru','Список композиторов');
INSERT INTO lang VALUES('no_entries_found','ru','Записи не найдены');
INSERT INTO lang VALUES('howto','ru','Как...');
INSERT INTO lang VALUES('howto_lang','ru','Как создать файл с новым языком интерфейса');
INSERT INTO lang VALUES('howto_help','ru','Как создать файл помощи');
INSERT INTO lang VALUES('language_settings','ru','Настройки языка');
INSERT INTO lang VALUES('scan_new_lang_files','ru','Искать файлы с новыми языками?');
INSERT INTO lang VALUES('refresh_lang','ru','Обновить язык');
INSERT INTO lang VALUES('none','ru','Ни один');
INSERT INTO lang VALUES('select_primary_lang','ru','Выберите основной язык');
INSERT INTO lang VALUES('colors','ru','Цвета');
INSERT INTO lang VALUES('start_pvp','ru','Запустить phpVideoPro');
INSERT INTO lang VALUES('hit_back_to_correct','ru','Нажмите кнопку "Назад", чтобы исправить ошибку.');
INSERT INTO lang VALUES('start_page','ru','Начальная страница');
INSERT INTO lang VALUES('counter_start_stop','ru','Счетчик Старт/Стоп');
INSERT INTO lang VALUES('other_pages','ru','Другие страницы');
INSERT INTO lang VALUES('print_label','ru','Печать наклейкиl:');
INSERT INTO lang VALUES('label','ru','Наклейка');
INSERT INTO lang VALUES('print','ru','Печать');
INSERT INTO lang VALUES('lines_per_page','ru','Строк на странице');
INSERT INTO lang VALUES('date_format','ru','Формат даты');
INSERT INTO lang VALUES('date_format_comment','ru','Формат для отобрадения даты.');
INSERT INTO lang VALUES('listgen','ru','Генератор списка');
INSERT INTO lang VALUES('list','ru','Список');
INSERT INTO lang VALUES('format','ru','Формат');
INSERT INTO lang VALUES('line_count','ru','Строки');
INSERT INTO lang VALUES('lists','ru','Списки');
INSERT INTO lang VALUES('labels','ru','Наклейки');
INSERT INTO lang VALUES('cat_adventure','ru','Приключения');
INSERT INTO lang VALUES('cat_action','ru','Боевик');
INSERT INTO lang VALUES('cat_bible','ru','Библия');
INSERT INTO lang VALUES('cat_biography','ru','Биография');
INSERT INTO lang VALUES('cat_documentary','ru','Документация');
INSERT INTO lang VALUES('cat_drama','ru','Драма');
INSERT INTO lang VALUES('cat_fantasy','ru','Фэнтэзи');
INSERT INTO lang VALUES('cat_history','ru','История');
INSERT INTO lang VALUES('cat_horror','ru','Ужасы');
INSERT INTO lang VALUES('cat_judaica','ru','Евреи');
INSERT INTO lang VALUES('cat_catastrophe','ru','Катастрофа');
INSERT INTO lang VALUES('cat_children','ru','Детский');
INSERT INTO lang VALUES('cat_comedy','ru','Комедия');
INSERT INTO lang VALUES('cat_concert','ru','Концерт');
INSERT INTO lang VALUES('cat_war','ru','Военные фильмы');
INSERT INTO lang VALUES('cat_love','ru','Любовные истории');
INSERT INTO lang VALUES('cat_melodrama','ru','Мелодрама');
INSERT INTO lang VALUES('cat_musical','ru','Музыкальный');
INSERT INTO lang VALUES('cat_music','ru','Музыка');
INSERT INTO lang VALUES('cat_videoclip','ru','Видеок клип');
INSERT INTO lang VALUES('cat_musicmovie','ru','Музыкальные фильмы');
INSERT INTO lang VALUES('cat_nature','ru','Природа');
INSERT INTO lang VALUES('cat_opera','ru','Опера');
INSERT INTO lang VALUES('cat_operetta','ru','Оперетта');
INSERT INTO lang VALUES('cat_problem','ru','Проблема');
INSERT INTO lang VALUES('cat_report','ru','Репораж');
INSERT INTO lang VALUES('cat_satire','ru','Сатира');
INSERT INTO lang VALUES('cat_misc','ru','Разное');
INSERT INTO lang VALUES('cat_sf','ru','Научная фантастика');
INSERT INTO lang VALUES('cat_show','ru','Шоу');
INSERT INTO lang VALUES('cat_spy','ru','Шпионские фильмы');
INSERT INTO lang VALUES('cat_thriller','ru','Триллер');
INSERT INTO lang VALUES('cat_animal','ru','Животное');
INSERT INTO lang VALUES('cat_animals','ru','Животные');
INSERT INTO lang VALUES('cat_travesty','ru','Пародия');
INSERT INTO lang VALUES('cat_xmas','ru','Рождественский');
INSERT INTO lang VALUES('cat_western','ru','Вестерн');
INSERT INTO lang VALUES('cat_westerncomedy','ru','Комедия-вестерн');
INSERT INTO lang VALUES('cat_cartoon','ru','Мультфильм');
INSERT INTO lang VALUES('db_stats','ru','Статистика');
INSERT INTO lang VALUES('movies','ru','Фильмы');
INSERT INTO lang VALUES('media','ru','Носитель');
INSERT INTO lang VALUES('compose_persons','ru','Композиторы');
INSERT INTO lang VALUES('director_persons','ru','Режиссеры');
INSERT INTO lang VALUES('actor_persons','ru','Актеры');
INSERT INTO lang VALUES('categories','ru','Категории');
INSERT INTO lang VALUES('countries','ru','Страны');
INSERT INTO lang VALUES('stat_categories','ru','Катагории (использованные/все)');
INSERT INTO lang VALUES('stats','ru','Статистика');
INSERT INTO lang VALUES('dl_pvp_latest','ru','Загрузить последнюю версию');
INSERT INTO lang VALUES('info_update','ru','Обновить информацию');
INSERT INTO lang VALUES('info_common','ru','Общая информация');
INSERT INTO lang VALUES('orig_medianr','ru','исходный НомерНосителя');
INSERT INTO lang VALUES('new_medianr','ru','новый НомерНосителя');
INSERT INTO lang VALUES('media_copy','ru','Копировать данные на НомерНосителя');
INSERT INTO lang VALUES('media_change','ru','Изменить НомерНосителя');
INSERT INTO lang VALUES('check_media_delete','ru','Проверка  if носитель is пуст');
INSERT INTO lang VALUES('change_media_length_for','ru','Пожалуйста введите объем для %1');
INSERT INTO lang VALUES('admin_cats','ru','Категории администратора');
INSERT INTO lang VALUES('admin','ru','Админ');
INSERT INTO lang VALUES('enable_cookies','ru','Включить cookies?');
INSERT INTO lang VALUES('expire_cookies','ru','Время жизни cookies');
INSERT INTO lang VALUES('session','ru','Сессия');
INSERT INTO lang VALUES('day','ru','День');
INSERT INTO lang VALUES('week','ru','Неделя');
INSERT INTO lang VALUES('month','ru','Месяц');
INSERT INTO lang VALUES('preferences','ru','Настройки');
INSERT INTO lang VALUES('user','ru','Пользователь');
INSERT INTO lang VALUES('login','ru','Логин');
INSERT INTO lang VALUES('data_access','ru','Доступ к данным');
INSERT INTO lang VALUES('read_access','ru','Может просматривать записи');
INSERT INTO lang VALUES('read_access_short','ru','чит');
INSERT INTO lang VALUES('add_access','ru','Может добавлять новые записи');
INSERT INTO lang VALUES('add_access_short','ru','доб');
INSERT INTO lang VALUES('upd_access','ru','Может изменять существующие записи');
INSERT INTO lang VALUES('upd_access_short','ru','изм');
INSERT INTO lang VALUES('del_access','ru','Может удалять записи');
INSERT INTO lang VALUES('del_access_short','ru','уд');
INSERT INTO lang VALUES('admin_access','ru','Имеет доступ к меню администратора');
INSERT INTO lang VALUES('admin_access_short','ru','адм');
INSERT INTO lang VALUES('add_user','ru','Добавить пользователя');
INSERT INTO lang VALUES('actions','ru','Действия');
INSERT INTO lang VALUES('password','ru','Пароль');
INSERT INTO lang VALUES('password_retype','ru','Еще раз пароль');
INSERT INTO lang VALUES('admin_useredit','ru','Редактировать пользовательскую запись');
INSERT INTO lang VALUES('confirm_userdelete','ru','You are about to delete user #%1');
INSERT INTO lang VALUES('confirm_userdeletion','ru','Вы действительно хотите удалить пользователя "%1" (%2)?');
INSERT INTO lang VALUES('user_delete_report','ru','Результат удаления пользователя');
INSERT INTO lang VALUES('user_deleted','ru','Успешно удален пользователь #%1, "%2" (%3)');
INSERT INTO lang VALUES('user_delete_failed','ru','Ошибка удаления пользователя #%1, "%2" (%3)');
INSERT INTO lang VALUES('submit','ru','Подтвердить');
INSERT INTO lang VALUES('welcome','ru','Добро пожаловать в phpVideoPro');
INSERT INTO lang VALUES('never','ru','никогда');
INSERT INTO lang VALUES('hour','ru','Час');
INSERT INTO lang VALUES('hours','ru','Часов');
INSERT INTO lang VALUES('search','ru','Поиск');
