# ========================================================
# German Translation phrases for phpVideoPro
# ========================================================

UPDATE languages SET charset='iso-8859-1' WHERE lang_id='de';
INSERT INTO lang (message_id,lang,content) VALUES ('not_yet_implemented','de','Sorry - leider noch nicht verfügbar.');
INSERT INTO lang VALUES('medium','de','Medium');
INSERT INTO lang VALUES('nr','de','Nr');
INSERT INTO lang VALUES('title','de','Titel');
INSERT INTO lang VALUES('length','de','Länge');
INSERT INTO lang VALUES('year','de','Jahr');
INSERT INTO lang VALUES('date_rec','de','Aufnahmedatum');
INSERT INTO lang VALUES('category','de','Kategorie');
INSERT INTO lang VALUES('medialist','de','Medienliste');
INSERT INTO lang VALUES('enter_min_free','de','Mindestgröße des freien Platzes in Minuten:');
INSERT INTO lang VALUES('display','de','Anzeigen');
INSERT INTO lang VALUES('free_space_on_media','de','Auf folgenden Medien sind noch mindestens %1 Minuten frei:');
INSERT INTO lang VALUES('free','de','Frei');
INSERT INTO lang VALUES('content','de','Inhalt');
INSERT INTO lang VALUES('filter_setup','de','Filter Setup');
INSERT INTO lang VALUES('mediatype','de','MedienTyp');
INSERT INTO lang VALUES('screen','de','Bildformat');
INSERT INTO lang VALUES('picture','de','Farbformat');
INSERT INTO lang VALUES('tone','de','Tonformat');
INSERT INTO lang VALUES('longplay','de','LongPlay');
INSERT INTO lang VALUES('fsk','de','FSK');
INSERT INTO lang VALUES('staff','de','Besetzung');
INSERT INTO lang VALUES('actor','de','Schauspieler');
INSERT INTO lang VALUES('actors','de','Schauspieler');
INSERT INTO lang VALUES('director','de','Regie');
INSERT INTO lang VALUES('directors','de','Regie');
INSERT INTO lang VALUES('composer','de','Musik');
INSERT INTO lang VALUES('music','de','Musik');
INSERT INTO lang VALUES('min','de','min');
INSERT INTO lang VALUES('max','de','max');
INSERT INTO lang VALUES('s/w','de','s/w');
INSERT INTO lang VALUES('farbe','de','Farbe');
INSERT INTO lang VALUES('3d','de','3D');
INSERT INTO lang VALUES('edit_entry','de','Bearbeite Datensatz %1');
INSERT INTO lang VALUES('view_entry','de','Anzeige des Datensatzes %1');
INSERT INTO lang VALUES('add_entry','de','Neuer Datensatz');
INSERT INTO lang VALUES('unknown','de','unbekannt');
INSERT INTO lang VALUES('country','de','Land');
INSERT INTO lang VALUES('medianr','de','MediaNr');
INSERT INTO lang VALUES('highest_db_entries','de','letzte DB-Einträge');
INSERT INTO lang VALUES('no','de','Nein');
INSERT INTO lang VALUES('yes','de','Ja');
INSERT INTO lang VALUES('medialength','de','Bandlänge');
INSERT INTO lang VALUES('minute_abbrev','de','min');
INSERT INTO lang VALUES('source','de','Quelle');
INSERT INTO lang VALUES('name','de','Name');
INSERT INTO lang VALUES('first_name','de','Vorname');
INSERT INTO lang VALUES('in_list','de','in Liste');
INSERT INTO lang VALUES('comments','de','Anmerkungen');
INSERT INTO lang VALUES('cancel','de','Abbrechen');
INSERT INTO lang VALUES('create','de','Erstellen');
INSERT INTO lang VALUES('update','de','Aktualisieren');
INSERT INTO lang VALUES('edit','de','Bearbeiten');
INSERT INTO lang VALUES('delete','de','Löschen');
INSERT INTO lang VALUES('invalid_media_nr','de','Die angegebene MediaNr ist entweder unvollständig oder ungültig. Es muß eine <b>Zahl</b> in <b>beiden</b> MediaNr Feldern eingegeben werden.');
INSERT INTO lang VALUES('warning','de','Warnung');
INSERT INTO lang VALUES('of_aquiration','de','der Aufnahme');
INSERT INTO lang VALUES('wrong_date','de','Das angegebene Datum %1 (%2) ist ungültig. Bitte geben Sie den Tag in das erste, den Monat in das zweite und das Jahr in das dritte Datumsfeld ein, und verwenden Sie ausschließlich Ziffern. Ist Ihnen der Wert für eines oder mehrere der Felder unbekannt (Sie wissen z.B. nur noch, dass Sie das Medium irgendwann im Februar 2002 erworben haben, erinnern sich jedoch nicht genau an den Tag), tragen Sie hierfür Nullen ein (im genannten Beispiel "00" im Tagesfeld, "02" im Monats- und "2002" im Jahresfeld).');
INSERT INTO lang VALUES('incomplete_date','de','Ist das exakte Datum nicht bekannt (sondern z.B. nur die Jahreszahl "2000"), sind die unbekannten Werte durch Nullen zu ersetzen - im genannten Beispiel entspräche das den Eingaben "00" "00" "2000".');
INSERT INTO lang VALUES('hit_back_to_correct','de','Bitte auf den "Zurück" Button des Browsers klicken, um die Eingabe zu korrigieren.');
INSERT INTO lang VALUES('dupe_id_entered','de','Es existiert bereits ein Datensatz mit der angegebenen MediaNr in der Datenbank. Zur Korrektur der Eingabe bitte den "Zurück" Button des Browsers betätigen. Hinweis: direkt neben dem Eingabefeld für die MediaNr befindet sich eine Auswahlbox. Diese gibt die höchste vergebene ID für jedes Medium an. Normalerweise ist es eine gute Idee, für ein neues Medium die erste (vierstellige) Zahl, bzw. für einen neuen Film auf dem gleichen Medium die zweite (zweistellige) Zahl um 1 zu erhöhen.');
INSERT INTO lang VALUES('create_success','de','Datensatz erfolgreich erstellt');
INSERT INTO lang VALUES('update_failed','de','Datensatz konnte nicht aktualisiert werden');
INSERT INTO lang VALUES('update_success','de','Datensatz erfolgreich aktualisiert');
INSERT INTO lang VALUES('about','de','About');
INSERT INTO lang VALUES('history','de','History');
INSERT INTO lang VALUES('deleting_entry','de','Lösche Datensatz %1');
INSERT INTO lang VALUES('free_space_title','de','Verfügbarer Platz auf Medien');
INSERT INTO lang VALUES('filter','de','Filter');
INSERT INTO lang VALUES('set_filter','de','Filter setzen');
INSERT INTO lang VALUES('unset_filter','de','Filter löschen');
INSERT INTO lang VALUES('view','de','Anzeigen');
INSERT INTO lang VALUES('taperest_absolute','de','Bandrest (absolut)');
INSERT INTO lang VALUES('taperest_filtered','de','Bandrest (gefiltert)');
INSERT INTO lang VALUES('help','de','Hilfe');
INSERT INTO lang VALUES('general','de','Allgemein');
INSERT INTO lang VALUES('sure_to_delete','de','Alle Daten für %1 werden gelöscht! Fortfahren');
INSERT INTO lang VALUES('nobody_named','de','Es gibt keinen weiteren Film unter Mitwirkung von %1 %2 %3 in der Datenbank - dieser Name wird also aus der Tabelle gelöscht.');
INSERT INTO lang VALUES('compose_person','de','Komponist');
INSERT INTO lang VALUES('director_person','de','Regisseur');
INSERT INTO lang VALUES('check_completed','de','Prüfung abgeschlossen');
INSERT INTO lang VALUES('delete_remaining','de','alle verbleibenden Daten dieses Films werden nun gelöscht');
INSERT INTO lang VALUES('ok','de','OK');
INSERT INTO lang VALUES('not_ok','de','Fehler');
INSERT INTO lang VALUES('recalc_free','de','Berechne freien Platz auf dem Medium');
INSERT INTO lang VALUES('tapelist_update_failed','de','Liste mit verfügbarer Restzeit konnte nicht aktualisiert werden');
INSERT INTO lang VALUES('no_entry_in_tapelist','de','Fehlgeschlagen - kein Eintrag in Restzeit-Liste');
INSERT INTO lang VALUES('finnished','de','Fertig');
INSERT INTO lang VALUES('time_left','de','%1 Minuten frei');
INSERT INTO lang VALUES('configuration','de','Konfiguration');
INSERT INTO lang VALUES('index','de','Index');
INSERT INTO lang VALUES('intro','de','Einleitung');
INSERT INTO lang VALUES('menues','de','Menüs');
INSERT INTO lang VALUES('back','de','Zurück');
INSERT INTO lang VALUES('close','de','Schließen');
INSERT INTO lang VALUES('help_about','de','Hilfe zum Thema');
INSERT INTO lang VALUES('actors_list','de','Liste der Schauspieler');
INSERT INTO lang VALUES('directors_list','de','Liste der Regisseure');
INSERT INTO lang VALUES('music_list','de','Liste der Komponisten');
INSERT INTO lang VALUES('no_entries_found','de','Kein Datensatz gefunden');
INSERT INTO lang VALUES('no_space_of','de','Es konnte kein Medium mit mindestens %1 Minuten freiem Platz in der Datenbank gefunden werden.');
INSERT INTO lang VALUES('howto','de','HowTo\'s');
INSERT INTO lang VALUES('howto_lang','de','Wie erstelle ich eine neue Sprachdatei?');
INSERT INTO lang VALUES('howto_help','de','Wie erstelle ich eine Hilfedatei?');
INSERT INTO lang VALUES('howto_templates','de','Wie erstelle ich ein neues Template Set?');
INSERT INTO lang VALUES('language_settings','de','Spracheinstellungen');
INSERT INTO lang VALUES('scan_new_lang_files','de','Nach neuen Sprachdateien suchen?');
INSERT INTO lang VALUES('scan_new_lang_comment','de','(Nach Bereitstellung neuer Sprachdateien im Setup-Verzeichnis veranlaßt dies phpVideoPro, diese zu aktivieren)');
INSERT INTO lang VALUES('select_add_lang','de','Zusätzliche Sprache installieren');
INSERT INTO lang VALUES('select_add_lang_comment','de','(Englisch ist bereits installiert und wird generell benötigt - siehe nächster Punkt. Bezüglich anderer bereits installierter Sprachen: siehe ebenfalls nächster Punkt.)');
INSERT INTO lang VALUES('no_add_lang','de','Keine zusätzliche Sprache verfügbar.');
INSERT INTO lang VALUES('refresh_lang','de','Übersetzungen erneut einlesen');
INSERT INTO lang VALUES('refresh_lang_comment','de','(alte Übersetzungen löschen und Sprachdatei erneut importieren)');
INSERT INTO lang VALUES('none','de','Keine');
INSERT INTO lang VALUES('select_primary_lang','de','Primäre Sprache auswählen');
INSERT INTO lang VALUES('select_primary_lang_comment','de','(Bei fehlenden Übersetzungen erfolgt ein Fall-Back zur Englischen Sprache)');
INSERT INTO lang VALUES('colors','de','Farben');
INSERT INTO lang VALUES('feedback_ok','de','Positive Abfrage-Ergebnisse');
INSERT INTO lang VALUES('feedback_err','de','Negative Abfrage-Ergebnisse');
INSERT INTO lang VALUES('template_set','de','Template Set');
INSERT INTO lang VALUES('start_pvp','de','phpVideoPro starten');
INSERT INTO lang VALUES('goto_entry','de','Zeige folgenden Eintrag an:');
INSERT INTO lang VALUES('start_page','de','Startseite');
INSERT INTO lang VALUES('invalid_fsk','de','Der eingegebene Wert für FSK ("%1") ist ungültig.<br>FSK steht für Freiwillige Selbst-Kontrolle und gibt das Mindestalter an, ab dem der Film zur Betrachtung freigegeben ist.');
INSERT INTO lang VALUES('counter_start_stop','de','Zähler Start/Stop');
INSERT INTO lang VALUES('other_pages','de','Andere Seiten');
INSERT INTO lang VALUES('commercials','de','Werbung');
INSERT INTO lang VALUES('cut_off','de','entfernt');
INSERT INTO lang VALUES('display_limit','de','Datensätze pro Seite');
INSERT INTO lang VALUES('display_limit_comment','de','(gibt an, wie viele Zeilen pro Seite bei Listen angezeigt werden sollen)');
INSERT INTO lang VALUES('print_label','de','Etikett drucken:');
INSERT INTO lang VALUES('howto_label','de','Wie erstelle/konfiguriere ich Vorlagen für Labels?');
INSERT INTO lang VALUES('label','de','Etikett');
INSERT INTO lang VALUES('print','de','Drucken');
INSERT INTO lang VALUES('medialist_num','de','Numerisch sortierte Medienliste');
INSERT INTO lang VALUES('medialist_alpha','de','Alphabetisch sortierte Medienliste');
INSERT INTO lang VALUES('lines_per_page','de','Zeilen pro Seite');
INSERT INTO lang VALUES('lines_per_page_comment','de','Dieser Wert gibt an, wieviele Textzeilen auf ein Blatt Papier passen (für den Listendruck).');
INSERT INTO lang VALUES('date_format','de','Datumsformat');
INSERT INTO lang VALUES('date_format_comment','de','Gibt an, in welchem Format Datumsangaben angezeigt werden sollen.');
INSERT INTO lang VALUES('listgen','de','Listengenerator');
INSERT INTO lang VALUES('list','de','Liste');
INSERT INTO lang VALUES('format','de','Format');
INSERT INTO lang VALUES('line_count','de','Zeilen');
INSERT INTO lang VALUES('catlist_alpha','de','Nach Kategorien sortierte alphabetische Medienliste');
INSERT INTO lang VALUES('lists','de','Listen');
INSERT INTO lang VALUES('labels','de','Etiketten');
INSERT INTO lang VALUES('cat_adventure','de','Abenteuer');
INSERT INTO lang VALUES('cat_action','de','Action');
INSERT INTO lang VALUES('cat_agents','de','Agentenfilm');
INSERT INTO lang VALUES('cat_bible','de','Bibelfilm');
INSERT INTO lang VALUES('cat_biography','de','Biografie');
INSERT INTO lang VALUES('cat_stage','de','Bühnenstück');
INSERT INTO lang VALUES('cat_documentary','de','Dokumentarfilm');
INSERT INTO lang VALUES('cat_drama','de','Drama');
INSERT INTO lang VALUES('cat_fantasy','de','Fantasy');
INSERT INTO lang VALUES('cat_party','de','Feier');
INSERT INTO lang VALUES('cat_scary','de','Gruselfilm');
INSERT INTO lang VALUES('cat_history','de','Historie');
INSERT INTO lang VALUES('cat_horror','de','Horror');
INSERT INTO lang VALUES('cat_judaica','de','Judaistik');
INSERT INTO lang VALUES('cat_camera','de','Kamera');
INSERT INTO lang VALUES('cat_catastrophe','de','Katastrophe');
INSERT INTO lang VALUES('cat_children','de','Kinder');
INSERT INTO lang VALUES('cat_comedy','de','Komödie');
INSERT INTO lang VALUES('cat_concert','de','Konzert');
INSERT INTO lang VALUES('cat_war','de','Kriegsfilm');
INSERT INTO lang VALUES('cat_crime','de','Krimi');
INSERT INTO lang VALUES('cat_love','de','Liebesfilm');
INSERT INTO lang VALUES('cat_fairytale','de','Märchen');
INSERT INTO lang VALUES('cat_melodrama','de','Melodrama');
INSERT INTO lang VALUES('cat_monumental','de','Monumentalfilm');
INSERT INTO lang VALUES('cat_musical','de','Musical');
INSERT INTO lang VALUES('cat_music','de','Musik');
INSERT INTO lang VALUES('cat_videoclip','de','Videoclip');
INSERT INTO lang VALUES('cat_musicmovie','de','Musikfilm');
INSERT INTO lang VALUES('cat_nature','de','Naturfilm');
INSERT INTO lang VALUES('cat_opera','de','Oper');
INSERT INTO lang VALUES('cat_operetta','de','Operette');
INSERT INTO lang VALUES('cat_problem','de','Problemfilm');
INSERT INTO lang VALUES('cat_report','de','Reportage');
INSERT INTO lang VALUES('cat_satire','de','Satire');
INSERT INTO lang VALUES('cat_misc','de','Sonstige');
INSERT INTO lang VALUES('cat_sf','de','Science Fiction');
INSERT INTO lang VALUES('cat_show','de','Show');
INSERT INTO lang VALUES('cat_spy','de','Spionage');
INSERT INTO lang VALUES('cat_thriller','de','Thriller');
INSERT INTO lang VALUES('cat_animal','de','Tier');
INSERT INTO lang VALUES('cat_animals','de','Tierfilm');
INSERT INTO lang VALUES('cat_travesty','de','Travestie');
INSERT INTO lang VALUES('cat_vacation','de','Urlaub');
INSERT INTO lang VALUES('cat_xmas','de','Weihnachten');
INSERT INTO lang VALUES('cat_western','de','Western');
INSERT INTO lang VALUES('cat_westerncomedy','de','Western-Komödie');
INSERT INTO lang VALUES('cat_cartoon','de','Zeichentrick');
INSERT INTO lang VALUES('db_stats','de','Statistiken');
INSERT INTO lang VALUES('stat_counts','de','Summen');
INSERT INTO lang VALUES('stat_ranks','de','Ranking');
INSERT INTO lang VALUES('movies','de','Filme');
INSERT INTO lang VALUES('media','de','Medien');
INSERT INTO lang VALUES('compose_persons','de','Komponisten');
INSERT INTO lang VALUES('director_persons','de','Regisseure');
INSERT INTO lang VALUES('actor_persons','de','Schauspieler');
INSERT INTO lang VALUES('categories','de','Kategorien');
INSERT INTO lang VALUES('countries','de','Länder');
INSERT INTO lang VALUES('stat_categories','de','Kategorien (benutzt/alle)');
INSERT INTO lang VALUES('stats','de','Statistiken');
INSERT INTO lang VALUES('dl_pvp_latest','de','D/L neueste Version');
INSERT INTO lang VALUES('info_update','de','Update Information');
INSERT INTO lang VALUES('info_noupdate','de','<DIV ALIGN="center">Die installierte Version von phpVideoPro (%1) ist auf dem aktuellen Stand - es steht keine neue Version zum Download zur Verfügung. Für den Download des Tarballs der installierten Version bitte <A HREF="http://www.qumran.org/homes/izzy/software/get_update.php?program=pvp" TARGET="_blank">diesem Link</A> folgen.</DIV>');
INSERT INTO lang VALUES('info_common','de','Allgemeine Information');
INSERT INTO lang VALUES('info_common_info','de','<DIV ALIGN="center">Dies ist Version %1 von phpVideoPro, installiert auf %2.</DIV>');
INSERT INTO lang VALUES('change_nr','de','Ändere die MediaNr / den MediaTyp für %1');
INSERT INTO lang VALUES('orig_medianr','de','ursprüngliche MediaNr');
INSERT INTO lang VALUES('new_medianr','de','neue MediaNr');
INSERT INTO lang VALUES('media_copy','de','Kopiere Daten zu MediaNr');
INSERT INTO lang VALUES('media_change','de','Ändere MediaNr');
INSERT INTO lang VALUES('check_media_delete','de','Prüfe auf leeres Medium');
INSERT INTO lang VALUES('medium_deleted','de','Keine weiteren Filme auf dem Medium - Medium entfernt');
INSERT INTO lang VALUES('medium_not_deleted','de','Medium nicht entfernt');
INSERT INTO lang VALUES('change_media_length','de','Anpassen der Medienkapazität');
INSERT INTO lang VALUES('change_media_length_for','de','Auf welche Größe (in Minuten) soll die Kapazität von %1 gesetzt werden:');
INSERT INTO lang VALUES('admin_cats','de','Administration der Kategorien');
INSERT INTO lang VALUES('cat_internal_name','de','Handle');
INSERT INTO lang VALUES('cat_update_failed','de','Aktualisierung fehlgeschlagen für folgende Kategorien: %1');
INSERT INTO lang VALUES('cat_trans_update_failed','de','Aktualisierung der Übersetzungen für folgende Kategorien fehlgeschlagen: %1');
INSERT INTO lang VALUES('movies_left_in_cat','de','Die Kategorie %1 enthält noch %2 Film(e) und kann daher nicht gelöscht werden.');
INSERT INTO lang VALUES('admin_orphans','de','Verwaiste Einträge entfernen');
INSERT INTO lang VALUES('desc_admin_orphans','de','Verwaiste Einträge sind Daten ohne Zuordnung. Hier handelt es sich dabei um Schauspieler, Regisseure bzw. Komponisten, die keinem Film zugeordnet sind. Diese "Waisenkinder" entstehen z.B., wenn ein "Schreibfehler" bei einem Namen nachträglich korrigiert - nicht jedoch, wenn ein Film aus dem Bestand entfernt wird. Sie sollten von daher entfernt werden: dies spart zum einen Platz in der Datenbank, und hilft zum anderen, ein unnötiges "Ausbremsen" zu vermeiden.');
INSERT INTO lang VALUES('orphans_found','de','%1 verwaiste Einträge gefunden:');
INSERT INTO lang VALUES('no_orphans_found','de','Glückwunsch! Keine Leiche (mehr?) im Keller.');
INSERT INTO lang VALUES('delete_orphans','de','Lösche %1 verwaiste Einträge:');
INSERT INTO lang VALUES('backup_db','de','Datenbank Backup');
INSERT INTO lang VALUES('desc_backup_db','de','Ein Backup ist immer eine gute Sache (sicher ist sicher :). Über dieses Formular kann der Inhalt der Datenbank gesichert werden. Es wird ein SQL Script erstellt, welches dann bei Bedarf wieder in eine (leere) Datenbank eingespielt werden kann. Gut geeignet zum Beispiel, um die Daten einer Filmsammlung zu duplizieren und auf einem weiteren Rechner zu installieren. Wichtig: nie das Backup einer neueren Version mit einer älteren Version von phpVideoPro verwenden - das kann Nebenwirkungen haben!<BR><DIV ALIGN="center"><B>Soll das Script jetzt erstellt werden?</B></DIV>');
INSERT INTO lang VALUES('dupes','de','Duplikate Einträge');
INSERT INTO lang VALUES('dupe_titles_found','de','Es wurden %1 Titel mit möglichen Duplikaten gefunden:');
INSERT INTO lang VALUES('rw_media','de','Editierbare Medien');
INSERT INTO lang VALUES('rw_media_comment','de','Medien, für die eine Restzeit-Anzeige verwaltet werden soll.');
INSERT INTO lang VALUES('remove_empty_media','de','Leere Medien entfernen');
INSERT INTO lang VALUES('remove_empty_media_comment','de','Sollen Medien aus der Restzeittabelle entfernt werden, wenn der letzte Film davon gelöscht wurde?');
INSERT INTO lang VALUES('movie_tone_default','de','Default Tonformat eines Films');
INSERT INTO lang VALUES('movie_tone_default_comment','de','Wenn ein neuer Eintrag angelegt wird, ist dies die Voreinstellung für das Tonformat.');
INSERT INTO lang VALUES('movie_color_default','de','Default Farbformat eines Films');
INSERT INTO lang VALUES('movie_color_default_comment','de','Wenn ein neuer Eintrag angelegt wird, ist dies die Voreinstellung für das Farbformat.');
INSERT INTO lang VALUES('site_info_comment','de','für die Anzeige in der Titelbar');
INSERT INTO lang VALUES('movie_onlabel_default','de','Defaulteinstellung Etiketten-Info');
INSERT INTO lang VALUES('movie_onlabel_default_comment','de','Defaulteinstellung für neue Einträge: Sollen Informationen für diesen Film auf Etiketten für dieses Medium erscheinen?');
INSERT INTO lang VALUES('config_media','de','Medien und Filme');
INSERT INTO lang VALUES('cookies','de','Kekse');
INSERT INTO lang VALUES('enable_cookies','de','Cookies aktivieren?');
INSERT INTO lang VALUES('enable_cookies_comment','de','Sollen benutzerspezifische Einstellungen (z.B. Filter) über Cookies verwaltet werden?');
INSERT INTO lang VALUES('expire_cookies','de','Haltbarkeitsdatum der Kekse');
INSERT INTO lang VALUES('expire_cookies_comment','de','Wie lange sollen die Cookies auf dem Rechner des Benutzers gespeichert bleiben?');
INSERT INTO lang VALUES('day','de','Tag');
INSERT INTO lang VALUES('week','de','Woche');
INSERT INTO lang VALUES('month','de','Monat');
INSERT INTO lang VALUES('preferences','de','Einstellungen');
INSERT INTO lang VALUES('admin_filter','de','Default Filtereinstellung');
INSERT INTO lang VALUES('admin_users','de','Benutzerverwaltung');
INSERT INTO lang VALUES('user','de','Benutzer');
INSERT INTO lang VALUES('data_access','de','Datenzugriff');
INSERT INTO lang VALUES('read_access_short','de','les');
INSERT INTO lang VALUES('add_user','de','Benutzer hinzufügen');
INSERT INTO lang VALUES('actions','de','Aktionen');
INSERT INTO lang VALUES('user_update_failed','de','Aktualisierung fehlgeschlagen für folgende Benutzer: %1');
