# ==========================================================
# Dutch Language File created by phpVideoPro v0.6.8
# Original by Tom Albers (for v0.2)
# revised and extensively updated by Ron Dekker (for v0.6.8)
# ==========================================================

UPDATE languages SET charset='UTF-8' WHERE lang_id='nl';
INSERT INTO lang VALUES ('about','nl','Over...',' ');
INSERT INTO lang VALUES ('actions','nl','Akties',' ');
INSERT INTO lang VALUES ('actor','nl','Acteur',' ');
INSERT INTO lang VALUES ('actors','nl','Acteurs',' ');
INSERT INTO lang VALUES ('actors_list','nl','Lijst van acteurs',' ');
INSERT INTO lang VALUES ('actor_persons','nl','Acteurs',' ');
INSERT INTO lang VALUES ('add_access','nl','Toevoegen nieuwe gegevens',' ');
INSERT INTO lang VALUES ('add_access_short','nl','Toevoegen',' ');
INSERT INTO lang VALUES ('add_entry','nl','Toevoegen',' ');
INSERT INTO lang VALUES ('add_user','nl','Nieuwe gebruiker',' ');
INSERT INTO lang VALUES ('admin_access','nl','Admin rechten',' ');
INSERT INTO lang VALUES ('admin_avlang','nl','Wijzig beschikbaarheid talen voor audio en ondertiteling ',' ');
INSERT INTO lang VALUES ('admin_cats','nl','Administratie categorien',' ');
INSERT INTO lang VALUES ('admin_disktypes','nl','Wijzig disktypes',' ');
INSERT INTO lang VALUES ('admin_filter','nl','Standaard filter settings',' ');
INSERT INTO lang VALUES ('admin_movietech','nl','Wijzig technische film gegevens',' ');
INSERT INTO lang VALUES ('admin_orphans','nl','Verwijder wees items',' ');
INSERT INTO lang VALUES ('admin_printers','nl','Wijzig printers',' ');
INSERT INTO lang VALUES ('admin_pstemplates','nl','Wijzig PSLabel template',' ');
INSERT INTO lang VALUES ('admin_sessions','nl','Beheer sessies',' ');
INSERT INTO lang VALUES ('admin_translations','nl','Wijzig vertaling',' ');
INSERT INTO lang VALUES ('admin_useredit','nl','Wijzig gebruikers account',' ');
INSERT INTO lang VALUES ('admin_users','nl','Beheer gebruikers accounts',' ');
INSERT INTO lang VALUES ('back','nl','Terug',' ');
INSERT INTO lang VALUES ('backup_compress','nl','Activeer compressie',' ');
INSERT INTO lang VALUES ('backup_db_complete','nl','Volledige database backup. (Incl. technische data en instellingen)',' ');
INSERT INTO lang VALUES ('backup_db_movie_internal','nl','Backup alle films in phpVideoPro formaat',' ');
INSERT INTO lang VALUES ('backup_file_corrupt','nl','Het geselecteerde backup bestand is beschadigd',' ');
INSERT INTO lang VALUES ('backup_file_unreadable','nl','Geen leesrechten op het backup bestand (Controleer de rechten van het bestan\")',' ');
INSERT INTO lang VALUES ('cancel','nl','Annuleer',' ');
INSERT INTO lang VALUES ('categories','nl','Categorieën',' ');
INSERT INTO lang VALUES ('category','nl','Categorie',' ');
INSERT INTO lang VALUES ('catlist_alpha','nl','Alfabetische medialijst gesorteerd op categorie ',' ');
INSERT INTO lang VALUES ('cat_action','nl','Aktie',' ');
INSERT INTO lang VALUES ('cat_adventure','nl','Aventuur',' ');
INSERT INTO lang VALUES ('cat_agents','nl','Politie',' ');
INSERT INTO lang VALUES ('cat_animal','nl','Dier',' ');
INSERT INTO lang VALUES ('cat_animals','nl','Dieren',' ');
INSERT INTO lang VALUES ('cat_animation','nl','Annimatie',' ');
INSERT INTO lang VALUES ('cat_bible','nl','Bijbel',' ');
INSERT INTO lang VALUES ('cat_biography','nl','Biografie',' ');
INSERT INTO lang VALUES ('cat_cartoon','nl','Tekenfilm',' ');
INSERT INTO lang VALUES ('cat_catastrophe','nl','catastrofe',' ');
INSERT INTO lang VALUES ('cat_children','nl','Kinderen',' ');
INSERT INTO lang VALUES ('cat_comedy','nl','Komedie',' ');
INSERT INTO lang VALUES ('cat_crime','nl','Misdaad',' ');
INSERT INTO lang VALUES ('cat_documentary','nl','Documantaire',' ');
INSERT INTO lang VALUES ('cat_fairytale','nl','Sprookjes',' ');
INSERT INTO lang VALUES ('cat_family','nl','Familie',' ');
INSERT INTO lang VALUES ('cat_fantasy','nl','Fantasie',' ');
INSERT INTO lang VALUES ('cat_handle_empty','nl','Categorie moet ingevuld zijn, ga terug en wijzig de invoer voor categorie #%1.',' ');
INSERT INTO lang VALUES ('cat_history','nl','Historie',' ');
INSERT INTO lang VALUES ('cat_judaica','nl','Jodendom',' ');
INSERT INTO lang VALUES ('cat_love','nl','Romantiek',' ');
INSERT INTO lang VALUES ('cat_misc','nl','Overigen',' ');
INSERT INTO lang VALUES ('cat_monumental','nl','Monumentaal',' ');
INSERT INTO lang VALUES ('cat_music','nl','Muziek',' ');
INSERT INTO lang VALUES ('cat_musicmovie','nl','Muziekfilm',' ');
INSERT INTO lang VALUES ('cat_nature','nl','Natuur',' ');
INSERT INTO lang VALUES ('cat_problem','nl','Probleem',' ');
INSERT INTO lang VALUES ('cat_spy','nl','Spionnenfilm',' ');
INSERT INTO lang VALUES ('cat_trans_update_failed','nl','Update mislukt voor de vertaling van de volgende categorieën: %1',' ');
INSERT INTO lang VALUES ('cat_travesty','nl','Travestie','');
INSERT INTO lang VALUES ('cat_update_failed','nl','Update mislukt voor de volgende categorieën: %1',' ');
INSERT INTO lang VALUES ('cat_vacation','nl','Vakantie',' ');
INSERT INTO lang VALUES ('cat_war','nl','Oorlogsfilm',' ');
INSERT INTO lang VALUES ('cat_westerncomedy','nl','Komische western',' ');
INSERT INTO lang VALUES ('cat_xmas','nl','Kerstfilm',' ');
INSERT INTO lang VALUES ('change_disktype','nl','Wijzig Disk Type voor %1',' ');
INSERT INTO lang VALUES ('change_media_length','nl','Wijzig Media lengte',' ');
INSERT INTO lang VALUES ('change_media_length_for','nl','Voer de capaciteit in voor %1',' ');
INSERT INTO lang VALUES ('change_nr','nl','Wijzig MediaNr/MediaType voor %1',' ');
INSERT INTO lang VALUES ('change_rc','nl','Wijzig de RegioCode',' ');
INSERT INTO lang VALUES ('change_rc_for','nl','Wijzig de RegioCode voor %1',' ');
INSERT INTO lang VALUES ('check_completed','nl','Controle gereed',' ');
INSERT INTO lang VALUES ('check_media_delete','nl','Controleer of het medium leeg is',' ');
INSERT INTO lang VALUES ('clean_restore','nl','Schoon of verwijder de oude data voor het starten van de restore',' ');
INSERT INTO lang VALUES ('close','nl','Sluit',' ');
INSERT INTO lang VALUES ('colors','nl','Kleuren',' ');
INSERT INTO lang VALUES ('comments','nl','Opmerkingen',' ');
INSERT INTO lang VALUES ('commercials','nl','Reclame',' ');
INSERT INTO lang VALUES ('composer','nl','Componist',' ');
INSERT INTO lang VALUES ('compose_person','nl','componist',' ');
INSERT INTO lang VALUES ('compose_persons','nl','Componisten',' ');
INSERT INTO lang VALUES ('configuration','nl','Configuratie',' ');
INSERT INTO lang VALUES ('config_media','nl','Films en Media',' ');
INSERT INTO lang VALUES ('confirm_delete','nl','Wilt u werkelijk dit record verwijderen?',' ');
INSERT INTO lang VALUES ('confirm_prilang','nl','Wilt u werkelijk de standaard taal voor alle (nieuwe) gebruikers wijzigen? ',' ');
INSERT INTO lang VALUES ('confirm_userdelete','nl','U gaat de volgende gebruiker verwijderen #%1',' ');
INSERT INTO lang VALUES ('confirm_userdeletion','nl','Wilt u werkelijk de volgende gebruiker verwijderen  \"%1\" (%2)?',' ');
INSERT INTO lang VALUES ('content','nl','Inhoud',' ');
INSERT INTO lang VALUES ('counter_start_stop','nl','Teller Start/Stop',' ');
INSERT INTO lang VALUES ('countries','nl','Landen',' ');
INSERT INTO lang VALUES ('country','nl','Land',' ');
INSERT INTO lang VALUES ('create','nl','Aanmaken',' ');
INSERT INTO lang VALUES ('create_success','nl','Item succesvol opgeslagen!',' ');
INSERT INTO lang VALUES ('credits','nl','Verdiensten','');
INSERT INTO lang VALUES ('cut_off','nl','Afgelopen op',' ');
INSERT INTO lang VALUES ('data_access','nl','Data toegang',' ');
INSERT INTO lang VALUES ('date_format','nl','Datum formaat',' ');
INSERT INTO lang VALUES ('date_format_comment','nl','Welk formaat gebruiken voor de datum.',' ');
INSERT INTO lang VALUES ('date_rec','nl','Datum opname/koop',' ');
INSERT INTO lang VALUES ('day','nl','Dag',' ');
INSERT INTO lang VALUES ('db_stats','nl','Statistieken',' ');
INSERT INTO lang VALUES ('delete','nl','Verwijderen',' ');
INSERT INTO lang VALUES ('delete_lang','nl','Verwijder taal',' ');
INSERT INTO lang VALUES ('delete_lang_comment','nl','Verwijder alle regels voor een specifieke taal in de database. Het bestand blijft bestaan zodat u zelf nog regels kunt toevoegen. (Let dat je zelf niet bestand verwijderd). ',' ');
INSERT INTO lang VALUES ('delete_orphans','nl','Verwijder %1 wees/wezen',' ');
INSERT INTO lang VALUES ('delete_remaining','nl','Verwijderen van de overgebleven gegevens van de film uit de database',' ');
INSERT INTO lang VALUES ('deleting_entry','nl','Verwijder item %1',' ');
INSERT INTO lang VALUES ('del_access','nl','Mag items verwijderen',' ');
INSERT INTO lang VALUES ('desc_admin_orphans','nl','\"Wees items\" is data zonder verwijzing. Bijv. Acteurs en componisten die geen link hebben naar een film. Dit komt meestal door verkeerd gespelde invoer die, nadat het is opgeslagen, weer gewijzigd wordt. Het verwijderen zal nooit leiden tot het verwijderen van de film. Het is het beste om deze wezen te verwijderen. Het spaart ruimte en voorkomt dat de database traag wordt. ',' ');
INSERT INTO lang VALUES ('desc_backup_db','nl','Het is verstandig om altijd een backup van de database te hebben. Het heeft de voorkeur om uw eigen tools hiervoor te gebruiken.
 (<code>mysql_dump</code>, code>pgsql_dump</code> etc.)
 In dit geval kan het zijn dat uw database staat op een server waar u geen shell toegang heeft. Kies daarom nu voor een \"Complete Backup\". Het slaat uw gehele database op als een SQL script<BR>Wilt u alleen de filmdata om die bijv. te gebruiken in een andere database, kies dan  alleen voor de films in het interne phpVideoPro formaat. U kunt op deze manier zelfs migreren tussen MySQL en PostgreSQL. Het terugzetten van een volledige backup van een oudere versie van phpVideoPro naar een recentere versie zal leiden tot het updaten (achteraf) van de database. De interne phpVideoPro backup is compatibel tussen de versies. (Toekomsige versies is nog niet zeker)<BR>U kunt de backup comprimeren als uw installatie van PHP is gecompileerd met gzip ondersteuning. Activeer de compressie box om tot 90% te besparen op de bestands grootte.<BR>    
 ',' ');
INSERT INTO lang VALUES ('director','nl','Regisseur',' ');
INSERT INTO lang VALUES ('directors','nl','Regisseurs',' ');
INSERT INTO lang VALUES ('directors_list','nl','Overzicht van regisseurs',' ');
INSERT INTO lang VALUES ('director_person','nl','regisseur',' ');
INSERT INTO lang VALUES ('director_persons','nl','Producer',' ');
INSERT INTO lang VALUES ('disktype_add_failed','nl','Sorry, ik kan de nieuwe disktype niet toevoegen.',' ');
INSERT INTO lang VALUES ('disktype_change','nl','Wijzig DiskType',' ');
INSERT INTO lang VALUES ('disktype_contains_media','nl','Dit disktype kan momenteel niet verwijderd worden omdat de volgende media er nog naar refereren.',' ');
INSERT INTO lang VALUES ('disktype_name_empty','nl','De naam voor een disktype mag niet leeg zijn. Ga terug en pas het aan voor disk type #%1.',' ');
INSERT INTO lang VALUES ('disktype_update_failed','nl','Sorry, ik kan het volgende disktype niet bijwerken #s: %1',' ');
INSERT INTO lang VALUES ('disk_size','nl','Disk Grootte',' ');
INSERT INTO lang VALUES ('display','nl','Toon',' ');
INSERT INTO lang VALUES ('display_limit','nl','Toon limiet',' ');
INSERT INTO lang VALUES ('display_limit_comment','nl','(hoeveel regels per pagina voor het overzicht)',' ');
INSERT INTO lang VALUES ('dl_pvp_latest','nl','Download de laatse versie',' ');
INSERT INTO lang VALUES ('dupes','nl','Dubbele items',' ');
INSERT INTO lang VALUES ('dupe_id_entered','nl','Er is al een film opgeslagen onder dit mediumnummer. Ga terug en pas dit aan. Tip: Er is een Selectie veld naast het invoerveld waar het media nummer. Dit selectie veld geeft aan het hoogste bestaande film id. Het is een juiste keuze om bij nieuwe media de eerste vier getallen met een te verhogen. Voor een nieuwe film op bestaande media verhoogt u de tweede twee getallen met een. ',' ');
INSERT INTO lang VALUES ('dupe_titles_found','nl','Gevonden %1 titel(s) die mogelijk dubbel zijn.',' ');
INSERT INTO lang VALUES ('edit','nl','Wijzig',' ');
INSERT INTO lang VALUES ('edit_entry','nl','Wijzig item %1',' ');
INSERT INTO lang VALUES ('enable_cookies','nl','Activeren cookies?',' ');
INSERT INTO lang VALUES ('enable_cookies_comment','nl','Moeten de gebruikersinstellingen (bijv. filters) geregeld worden via cookies?',' ');
INSERT INTO lang VALUES ('ended_sessions','nl','Beëindigde sessies',' ');
INSERT INTO lang VALUES ('enter_min_free','nl','Hoeveel ruimte moet er minimaal vrij zijn:',' ');
INSERT INTO lang VALUES ('enter_new_medianr','nl','Voer het MediaNr in voor deze nieuwe %1',' ');
INSERT INTO lang VALUES ('expire_cookies','nl','Levensduur coockies',' ');
INSERT INTO lang VALUES ('expire_cookies_comment','nl','Hoe lang mag een cookie actief blijven in de browser van de gebruiker ',' ');
INSERT INTO lang VALUES ('farbe','nl','Kleur',' ');
INSERT INTO lang VALUES ('filter_setup','nl','Filter configuratie',' ');
INSERT INTO lang VALUES ('finnished','nl','Gereed',' ');
INSERT INTO lang VALUES ('first_name','nl','Voornaam',' ');
INSERT INTO lang VALUES ('format','nl','Formaat',' ');
INSERT INTO lang VALUES ('free','nl','Vrij',' ');
INSERT INTO lang VALUES ('free_space_on_media','nl','De volgende mediums hebben minimaal %1 vrije ruimte:',' ');
INSERT INTO lang VALUES ('free_space_title','nl','Vrije ruimte op medium',' ');
INSERT INTO lang VALUES ('fsk','nl','OudersControle OC (Min-Max leeftijd)',' ');
INSERT INTO lang VALUES ('general','nl','Algemeen',' ');
INSERT INTO lang VALUES ('goto_entry','nl','Ga direct naar:',' ');
INSERT INTO lang VALUES ('graphic_file','nl','Imagebestand',' ');
INSERT INTO lang VALUES ('help_about','nl','Help over',' ');
INSERT INTO lang VALUES ('highest_db_entries','nl','Hoogste items in database',' ');
INSERT INTO lang VALUES ('history','nl','Geschiedenis',' ');
INSERT INTO lang VALUES ('hit_back_to_correct','nl','Druk op de \"Terug\" knop om de fout te herstellen.',' ');
INSERT INTO lang VALUES ('hour','nl','Uur',' ');
INSERT INTO lang VALUES ('hours','nl','Uren',' ');
INSERT INTO lang VALUES ('howto','nl','Hoe...',' ');
INSERT INTO lang VALUES ('howto_help','nl','How maak ik een nieuw help bestand',' ');
INSERT INTO lang VALUES ('howto_label','nl','Hoe maak of configureer ik label templates',' ');
INSERT INTO lang VALUES ('howto_lang','nl','Hoe maak ik een nieuw taal bestand',' ');
INSERT INTO lang VALUES ('howto_templates','nl','Hoe maak ik een nieuwe template',' ');
INSERT INTO lang VALUES ('imdb_url','nl','Welke IMDB site te gebruiken',' ');
INSERT INTO lang VALUES ('imdb_url_comment','nl','De Intenet Movie DataBase geeft informatie over veel films. Er zijn ook landen sites beschikbaar. Zo is de Nederlande site geschikt om te zoeken naar Nederlandse films. De Amerikaanse site is het beste voor Engelse films. Kies een site die het beste past bij de films in uw database.',' ');
INSERT INTO lang VALUES ('imp_errors','nl','Importeren van %2 record(s) gestopt met %1 fout(en).',' ');
INSERT INTO lang VALUES ('imp_success','nl','Importeren van %1 record(s) is succesvol gereed.',' ');
INSERT INTO lang VALUES ('incomplete_date','nl','Indien je niet de exacte datum weet, maar bijvoorbeeld alleen dat u het hebt opgenomen inhet jaar 2000, pas dan alleen het jaar gedeelte in de datum aan.',' ');
INSERT INTO lang VALUES ('info_common','nl','Algemende informatie',' ');
INSERT INTO lang VALUES ('info_common_info','nl','<DIV ALIGN=\"center\">Dit is versie %1 van phpVideoPro, draaiend op %2.</DIV> ',' ');
INSERT INTO lang VALUES ('info_noupdate','nl','<DIV ALIGN=\"center\">De geinstaleerde versie van phpVideoPro (%1) is actueel - er is geen recentere versie beschikbaar om te downloaden. Om de tarball van de geinstalleerde versie te downloaden klik op <A HREF=\"http://www.qumran.org/homes/izzy/software/get_update.php?program=pvp\" TARGET=\"_blank\">this link</A>.</DIV>',' ');
INSERT INTO lang VALUES ('info_update','nl','Bijwerken informatie',' ');
INSERT INTO lang VALUES ('intro_usage','nl','<P>Hier is informatie voor nieuwe  gebruikers:<ul><li>Navigatie is altijd mogelijk via de menubalk die bijna boven elk scherm is</li><li>Bijna alle schermen hebben een helppagina. U kunt die openen via het help menu of, indien aanwezig, via het \"?\" icoontje.</li><li>Via onderstaand scherm kunt u direct springen naar een film, als u het media nummer weet. Gebruik anders de \"Medialijst\" van het menu item \"Overzicht\" of de \"Zoek\" functie uit het menu item \"Wijzig\".</li></ul></P>','');
INSERT INTO lang VALUES ('intro_usage_skip','nl','<P>Wilt u deze introductie tekst niet meer dan kunt u die uitschakelen via een optie in het instellingen scherm. Zie \"Wijzig\" menu.</P>','');
INSERT INTO lang VALUES ('intro_usage_title','nl','Introductie voor nieuwe gebruikers','');
INSERT INTO lang VALUES ('invalid_backup_dir','nl','De geconfigureerde backup directory bestaat niet.','');
INSERT INTO lang VALUES ('invalid_fsk','nl','De waarde van %1 is ongelig. OC betekend  \"Ouder Controlee\", ofwel de minimum leeftijd waaronder men geen toegang heeft tot deze film.',' ');
INSERT INTO lang VALUES ('invalid_media_nr','nl','Het ingevoerde MediaNr is opgeldig of incompleet. U moet een <b>nummer</b> in <b>beide</b> MediaNr velden invullen.',' ');
INSERT INTO lang VALUES ('in_list','nl','In overzicht',' ');
INSERT INTO lang VALUES ('is_rw','nl','herschrijfbaar',' ');
INSERT INTO lang VALUES ('label','nl','Etiket','');
INSERT INTO lang VALUES ('labels','nl','Etiketten',' ');
INSERT INTO lang VALUES ('labeltype','nl','Etiket Type',' ');
INSERT INTO lang VALUES ('language_settings','nl','Taal instellingen',' ');
INSERT INTO lang VALUES ('last_entry','nl','Laatste item',' ');
INSERT INTO lang VALUES ('last_medianr','nl','Het hoogste nummer voor dit media type is momenteel:',' ');
INSERT INTO lang VALUES ('layout_label','nl','Kies layout',' ');
INSERT INTO lang VALUES ('left_offset','nl','Linkermarge',' ');
INSERT INTO lang VALUES ('length','nl','Lengte',' ');
INSERT INTO lang VALUES ('lines_per_page','nl','Regels per pagina',' ');
INSERT INTO lang VALUES ('lines_per_page_comment','nl','Dit is voor de printer functionaliteit om te bepalen hoeveel regels er op he papier passen.',' ');
INSERT INTO lang VALUES ('line_count','nl','Regels',' ');
INSERT INTO lang VALUES ('list','nl','Overzicht',' ');
INSERT INTO lang VALUES ('listgen','nl','Overzichten',' ');
INSERT INTO lang VALUES ('lists','nl','Overzichten',' ');
INSERT INTO lang VALUES ('locale','nl','Lokaal',' ');
INSERT INTO lang VALUES ('login','nl','Login naam',' ');
INSERT INTO lang VALUES ('login_failed','nl','Login mislukt. Verkeerde naam of wachtwoord gebruikt of de gebruiker bestaat niet.',' ');
INSERT INTO lang VALUES ('login_required','nl','Uw rechten zijn onvoldoende voor de gewenste actie. U kunt nu opnieuw inloggen als een andere gebruiker met de juiste rechten.<P />',' ');
INSERT INTO lang VALUES ('logout_user','nl','Ingelogd als\"%1\". <A HREF=\"%2\">afmelden</A>',' ');
INSERT INTO lang VALUES ('longplay','nl','Lange speelduur','');
INSERT INTO lang VALUES ('lower_left_corner','nl','Linkeronderhoek (x/y)',' ');
INSERT INTO lang VALUES ('max_fontsize','nl','Max Fontgrootte',' ');
INSERT INTO lang VALUES ('medialength','nl','MediaLengte',' ');
INSERT INTO lang VALUES ('medialist','nl','Medialijst',' ');
INSERT INTO lang VALUES ('medialist_alpha','nl','Media overzicht in alfabetische volgorde',' ');
INSERT INTO lang VALUES ('medialist_num','nl','Media overzicht op nummer volgorde',' ');
INSERT INTO lang VALUES ('media_change','nl','Wijzig MediaNr',' ');
INSERT INTO lang VALUES ('media_copy','nl','Kopieer data naar MediaNr',' ');
INSERT INTO lang VALUES ('medium_deleted','nl','Geen films meer op dit medium - medium verwijderd',' ');
INSERT INTO lang VALUES ('medium_not_deleted','nl','Medium niet verwijderd',' ');
INSERT INTO lang VALUES ('medium_overview','nl','Overzicht voor %1',' ');
INSERT INTO lang VALUES ('menues','nl','Menus',' ');
INSERT INTO lang VALUES ('month','nl','Maand',' ');
INSERT INTO lang VALUES ('movies','nl','Films',' ');
INSERT INTO lang VALUES ('movies_left_in_cat','nl','Categorie %1 bevat nog steeds %2 film(s). Verwijderen kan niet, sorry. ',' ');
INSERT INTO lang VALUES ('movies_left_reference','nl','Deze regel kan niet verwijderd worden. Er is/zijn nog steeds %1 film(s) in de database die er naar verwijzen.',' ');
INSERT INTO lang VALUES ('movie_color_default','nl','Standaard kleurformaat voor een film',' ');
INSERT INTO lang VALUES ('movie_color_default_comment','nl','Dit is de standaard kleurinstelling voor een nieuwe entry',' ');
INSERT INTO lang VALUES ('movie_onlabel_default','nl','Standaard label info',' ');
INSERT INTO lang VALUES ('movie_onlabel_default_comment','nl','Standaard voor nieuwe items: moet de informatie van deze film gebruikt worden wanneer labels voor dit medium gemaakt worden?',' ');
INSERT INTO lang VALUES ('movie_tone_default','nl','Standaard geluidstype voor een film. ',' ');
INSERT INTO lang VALUES ('movie_tone_default_comment','nl','Dit zal gebruikt worden als standaard geluidstype voor een nieuw item',' ');
INSERT INTO lang VALUES ('music','nl','Componist',' ');
INSERT INTO lang VALUES ('music_list','nl','Overzicht van componisten',' ');
INSERT INTO lang VALUES ('name','nl','Naam',' ');
INSERT INTO lang VALUES ('never','nl','nooit',' ');
INSERT INTO lang VALUES ('new_disktype','nl','Nieuw disk Type',' ');
INSERT INTO lang VALUES ('new_medianr','nl','Nieuw MediaNr',' ');
INSERT INTO lang VALUES ('new_movie_on','nl','Nieuw %1',' ');
INSERT INTO lang VALUES ('no','nl','Nee',' ');
INSERT INTO lang VALUES ('nobody_named','nl','Er is geen andere film met %1 naam %2 %3 in dit bestand. Dit item zal verwijderd worden uit de %1 tabel.',' ');
INSERT INTO lang VALUES ('none','nl','Geen',' ');
INSERT INTO lang VALUES ('not_logged_in','nl','Niet aangemeld',' ');
INSERT INTO lang VALUES ('not_ok','nl','Mislukt',' ');
INSERT INTO lang VALUES ('not_yet_implemented','nl','Sorry - nog niet geimplementeerd.',' ');
INSERT INTO lang VALUES ('no_add_lang','nl','Geen aanvullend taalbestand gevonden.',' ');
INSERT INTO lang VALUES ('no_backup_avail','nl','Geen backupbestand beschikbaar om van te restoren',' ');
INSERT INTO lang VALUES ('no_entries_found','nl','Geen items gevonden',' ');
INSERT INTO lang VALUES ('no_entry_in_tapelist','nl','Helaas, geen item gevonden in tapelijst.',' ');
INSERT INTO lang VALUES ('no_orphans_found','nl','Gefeliciteerd, geen losse records meer gevonden.',' ');
INSERT INTO lang VALUES ('no_restore_file','nl','Sorry, het geselecteerde bestand bestaat niet meer!',' ');
INSERT INTO lang VALUES ('no_space_of','nl','Er is geen medium gevonden met %1 minuten vrije ruimte in de database',' ');
INSERT INTO lang VALUES ('of_aquiration','nl','aankoop/opname',' ');
INSERT INTO lang VALUES ('old_sessions','nl','Sessies ouder dan <INPUT NAME=\"%1\" VALUE=\"\" CLASS=\"yesnobutton\"> dagen',' ');
INSERT INTO lang VALUES ('orig_disktype','nl','Orgineel Disk Type',' ');
INSERT INTO lang VALUES ('orig_medianr','nl','orgineel MediaNr','');
INSERT INTO lang VALUES ('orig_trans','nl','Orginele vertaling (%1)','');
INSERT INTO lang VALUES ('orphans_found','nl','Gevonden %1 wees/wezen','');
INSERT INTO lang VALUES ('other_pages','nl','Overige pagina\'s','');
INSERT INTO lang VALUES ('page_bg','nl','Pagina achtergrond',' ');
INSERT INTO lang VALUES ('password','nl','Wachtwoord','');
INSERT INTO lang VALUES ('password_retype','nl','Voer wachtwoord opnieuwe in','');
INSERT INTO lang VALUES ('picture','nl','Kleurformaat',' ');
INSERT INTO lang VALUES ('preferences','nl','Instellingen','');
INSERT INTO lang VALUES ('printer_add_failed','nl','Er is een fout opgetreden bij het toevoegen van deze printer.','');
INSERT INTO lang VALUES ('printer_comment','nl','Als u op formulieren wilt printen (zoals bij PS Labels), dan moeten wij de juiste marges weten','');
INSERT INTO lang VALUES ('printer_name','nl','Naam','');
INSERT INTO lang VALUES ('printer_upd_failed','nl','Bijwerken mislukt voor de volgende printers: %1','');
INSERT INTO lang VALUES ('pstpl_name','nl','Template naam','');
INSERT INTO lang VALUES ('pstpl_type','nl','Template type','');
INSERT INTO lang VALUES ('read_access','nl','Mag items bekijken','');
INSERT INTO lang VALUES ('read_access_short','nl','lr','');
INSERT INTO lang VALUES ('recalc_free','nl','Vrije ruimte aan het herberekenen voor dit medium.',' ');
INSERT INTO lang VALUES ('refresh_lang','nl','Overschrijf taalbestand',' ');
INSERT INTO lang VALUES ('refresh_lang_comment','nl','(Indien er een wijziging heeft plaats gevonden in het taalbestand (wellicht doordat u een taalfout heeft gevonden), dan kunt u hier het taalbestand opnieuw laten inlezen)',' ');
INSERT INTO lang VALUES ('region_code','nl','RegioCode','');
INSERT INTO lang VALUES ('remove_empty_media','nl','Verwijderen lege media','');
INSERT INTO lang VALUES ('remove_empty_media_comment','nl','Moet media verwijderd worden als de laatste film verwijderd is?','');
INSERT INTO lang VALUES ('restore_db_movie_internal','nl','Terugzetten van films van een PVP backupbestand','');
INSERT INTO lang VALUES ('rw_media','nl','Wijzigbare Media','');
INSERT INTO lang VALUES ('rw_media_comment','nl','Media om vrije ruimte voor te reserveren, omdat u er op opgenomen hebt','');
INSERT INTO lang VALUES ('s/w','nl','z/w',' ');
INSERT INTO lang VALUES ('save_lang_file','nl','Sla vertaling op in en bestand','');
INSERT INTO lang VALUES ('scan_new_lang_comment','nl','(Indien u een nieuw taalbestand hebt gemaakt en  die in de setup directory heeft geplaatst, dan kunt u hiermee phpVideoPro er naar laten zoeken)',' ');
INSERT INTO lang VALUES ('scan_new_lang_files','nl','Zoeken naar nieuwe taalbestanden?',' ');
INSERT INTO lang VALUES ('screen','nl','Beeldformaat',' ');
INSERT INTO lang VALUES ('search','nl','Zoek','');
INSERT INTO lang VALUES ('search_movie','nl','ZoekFilm','');
INSERT INTO lang VALUES ('select_add_lang','nl','Selecteer additioneel taalbestand',' ');
INSERT INTO lang VALUES ('select_add_lang_comment','nl','(Als er na het scannen additionele taalbestanden gevonden zijn, kunt u die hier selecteren. Deze zullen dan worden geinstelleerd.)',' ');
INSERT INTO lang VALUES ('select_primary_lang','nl','Selecteer taal',' ');
INSERT INTO lang VALUES ('select_primary_lang_comment','nl','(Voor niet vertaalde delen, zal er worden teruggevallen op het engels.)',' ');
INSERT INTO lang VALUES ('sel_target_lang','nl','Kies doeltaal om naar te vertalen:','');
INSERT INTO lang VALUES ('session','nl','Sessie','');
INSERT INTO lang VALUES ('session_expired','nl','Uw sessie is verlopen, log svp opnieuw in.','');
INSERT INTO lang VALUES ('session_purgetime','nl','Na hoeveel tijd mag een inactive sessie vervallen?','');
INSERT INTO lang VALUES ('session_purgetime_comment','nl','Hoelang mag een sessie actief blijven zonder activiteiten?','');
INSERT INTO lang VALUES ('sess_dla','nl','Laatst actief','');
INSERT INTO lang VALUES ('sess_end','nl','Beëindigd','');
INSERT INTO lang VALUES ('sess_id','nl','Sessie ID','');
INSERT INTO lang VALUES ('sess_start','nl','Gestart','');
INSERT INTO lang VALUES ('set_filter','nl','Filter instellen',' ');
INSERT INTO lang VALUES ('site_info_comment','nl','Welke site info moet op de titelbalk van de browser','');
INSERT INTO lang VALUES ('skip_intro','nl','Nieuwkomers informatie overslaan?','');
INSERT INTO lang VALUES ('skip_intro_comment','nl','Introductie tekst overslaan op de startpagina?','');
INSERT INTO lang VALUES ('source','nl','Bron',' ');
INSERT INTO lang VALUES ('staff','nl','Staf',' ');
INSERT INTO lang VALUES ('start_page','nl','Start pagina',' ');
INSERT INTO lang VALUES ('state_active','nl','actief','');
INSERT INTO lang VALUES ('state_inactive','nl','inactief','');
INSERT INTO lang VALUES ('stats','nl','Statikstieken','');
INSERT INTO lang VALUES ('stat_categories','nl','Categorieen (alles)','');
INSERT INTO lang VALUES ('stat_counts','nl','Telling','');
INSERT INTO lang VALUES ('stat_ranks','nl','Hoogte','');
INSERT INTO lang VALUES ('submit','nl','Verstuur','');
INSERT INTO lang VALUES ('subtitle','nl','Ondertiteling','');
INSERT INTO lang VALUES ('sure_to_delete','nl','Weet u zeker dat u alles wilt verwijderen van %1',' ');
INSERT INTO lang VALUES ('table_bg','nl','Tabel achtergrond',' ');
INSERT INTO lang VALUES ('tapelist_update_failed','nl','Het is niet gelukt om het bijtewerken',' ');
INSERT INTO lang VALUES ('taperest','nl','Beheren overblijvende tijd','');
INSERT INTO lang VALUES ('taperest_absolute','nl','Vrije ruimte (totaal)',' ');
INSERT INTO lang VALUES ('taperest_filtered','nl','Vrije ruimte (met filter)',' ');
INSERT INTO lang VALUES ('target_trans','nl','Vertaling voor uw taal (%1)','');
INSERT INTO lang VALUES ('techdata','nl','Technische data','');
INSERT INTO lang VALUES ('template_file','nl','Template bestand','');
INSERT INTO lang VALUES ('template_set','nl','Template',' ');
INSERT INTO lang VALUES ('th_bg','nl','Tabelkoppen achtergrond',' ');
INSERT INTO lang VALUES ('time_left','nl','%1 minuten beschikbaar',' ');
INSERT INTO lang VALUES ('title','nl','Titel',' ');
INSERT INTO lang VALUES ('tone','nl','Geluidsformaat',' ');
INSERT INTO lang VALUES ('top_offset','nl','Bovenmarge','');
INSERT INTO lang VALUES ('trans_code','nl','Te vertalen data','');
INSERT INTO lang VALUES ('unit','nl','Eenheid','');
INSERT INTO lang VALUES ('unknown','nl','Onbekend',' ');
INSERT INTO lang VALUES ('unset_filter','nl','Filter opnieuw instellen',' ');
INSERT INTO lang VALUES ('update','nl','Aanpassen',' ');
INSERT INTO lang VALUES ('update_failed','nl','Bijwerken items mislukt',' ');
INSERT INTO lang VALUES ('update_success','nl','Items succesvol opgeslagen!',' ');
INSERT INTO lang VALUES ('upd_access','nl','Mag bestaande items bijwerken','');
INSERT INTO lang VALUES ('upper_right_corner','nl','Rechterbovenhoek (x/y)','');
INSERT INTO lang VALUES ('user','nl','Gebruiker','');
INSERT INTO lang VALUES ('user_deleted','nl','Succesvol verwijder gebruiker #%1, \"%2\" (%3)','');
INSERT INTO lang VALUES ('user_delete_failed','nl','Verwijderen van gebruiker #%1, \"%2\" (%3) mislukt','');
INSERT INTO lang VALUES ('user_delete_report','nl','Resultaat van het verwijderen van gebruikers','');
INSERT INTO lang VALUES ('user_update_failed','nl','Bijwerken mislukt voor de volgende gebruikers: %1','');
INSERT INTO lang VALUES ('view','nl','Beeld',' ');
INSERT INTO lang VALUES ('view_entry','nl','Bekijk item %1',' ');
INSERT INTO lang VALUES ('warning','nl','waarschuwing',' ');
INSERT INTO lang VALUES ('welcome','nl','Welkom bij phpVideoPro','');
INSERT INTO lang VALUES ('wrong_date','nl','De datum %1 die je hebt opgegeven (%2) is ongeldig. De datum moet op de volgende manier  worden ingevoerd: \"JJJJ-MM-DD\"',' ');
INSERT INTO lang VALUES ('year','nl','Jaar',' ');
INSERT INTO lang VALUES ('yes','nl','Ja',' ');
