# ========================================================
# French Language File created by phpVideoPro v0.4.6p5
# ========================================================

UPDATE languages SET charset='iso-8859-1' WHERE lang_id='fr';
INSERT INTO lang VALUES ('about','fr','Sur');
INSERT INTO lang VALUES ('actor','fr','Acteur');
INSERT INTO lang VALUES ('actors','fr','Acteurs');
INSERT INTO lang VALUES ('actors_list','fr','List des charactéres');
INSERT INTO lang VALUES ('add_entry','fr','Date nouvel');
INSERT INTO lang VALUES ('back','fr','Retour');
INSERT INTO lang VALUES ('cancel','fr','Interrupt');
INSERT INTO lang VALUES ('category','fr','Categorie');
INSERT INTO lang VALUES ('cat_biography','fr','Biographie');
INSERT INTO lang VALUES ('cat_children','fr','Enfants');
INSERT INTO lang VALUES ('cat_history','fr','Histoire');
INSERT INTO lang VALUES ('cat_vacation','fr','Vacances');
INSERT INTO lang VALUES ('check_completed','fr','Teste complet');
INSERT INTO lang VALUES ('close','fr','Fermer');
INSERT INTO lang VALUES ('colors','fr','Couleurs');
INSERT INTO lang VALUES ('comments','fr','Critique');
INSERT INTO lang VALUES ('commercials','fr','Merchandise');
INSERT INTO lang VALUES ('composer','fr','Composition');
INSERT INTO lang VALUES ('compose_person','fr','Componist');
INSERT INTO lang VALUES ('configuration','fr','Configuration');
INSERT INTO lang VALUES ('content','fr','Index');
INSERT INTO lang VALUES ('counter_start_stop','fr','Conter Start/Stop');
INSERT INTO lang VALUES ('country','fr','pays');
INSERT INTO lang VALUES ('create','fr','Réalisation');
INSERT INTO lang VALUES ('create_success','fr','Creation succée');
INSERT INTO lang VALUES ('cut_off','fr','remplacé');
INSERT INTO lang VALUES ('date_rec','fr','Date d');
INSERT INTO lang VALUES ('day','fr','Jour');
INSERT INTO lang VALUES ('delete','fr','Remplacer');
INSERT INTO lang VALUES ('delete_remaining','fr','Tous les dates de ce film en va remplacé');
INSERT INTO lang VALUES ('deleting_entry','fr','Remplacer de date %1');
INSERT INTO lang VALUES ('director','fr','Régie');
INSERT INTO lang VALUES ('directors','fr','Régisseurs');
INSERT INTO lang VALUES ('directors_list','fr','List des Regisseures');
INSERT INTO lang VALUES ('director_person','fr','Regisseur');
INSERT INTO lang VALUES ('display','fr','De faire voir');
INSERT INTO lang VALUES ('display_limit_comment','fr','comment a-t-yl des lignes pour le display par suivant per pages');
INSERT INTO lang VALUES ('dupe_id_entered','fr','Il existe déja de date de medium avec le numero donnée de medium en DB. Pressez-vous le buttom \"Retour\" pour corriger l\'enrigistrement, s-il-vous-plait. Attention: directément à coté de la placement pour le texte pour le numero du medium il se trouve d\'une box de value. Cette box de value vous aider trouver de la numero maximum. Normalement c\'est une bonne idée, pour une nouvelle medium d\'augmenté de numero premiere, pour une nouvelle film sur la meme medium d\'augmenté de numero deuxieme en un.');
INSERT INTO lang VALUES ('edit','fr','Éditer');
INSERT INTO lang VALUES ('edit_entry','fr','Edition de date %1');
INSERT INTO lang VALUES ('enter_min_free','fr','La mince de place libre en minute:');
INSERT INTO lang VALUES ('farbe','fr','Couleur');
INSERT INTO lang VALUES ('filter','fr','Filtre');
INSERT INTO lang VALUES ('filter_setup','fr','Mode de chercher');
INSERT INTO lang VALUES ('finnished','fr','Complet');
INSERT INTO lang VALUES ('first_name','fr','Pré-Nom');
INSERT INTO lang VALUES ('free','fr','Libre');
INSERT INTO lang VALUES ('free_space_on_media','fr','À la prochaine medium sont restée %1 minutes libre:');
INSERT INTO lang VALUES ('free_space_title','fr','Place choissable sur les mediums');
INSERT INTO lang VALUES ('general','fr','Pas de specialement');
INSERT INTO lang VALUES ('goto_entry','fr','Annonce le film:');
INSERT INTO lang VALUES ('help','fr','Aide');
INSERT INTO lang VALUES ('help_about','fr','Aide pour le thème');
INSERT INTO lang VALUES ('highest_db_entries','fr','dernier DB-No');
INSERT INTO lang VALUES ('history','fr','Historie');
INSERT INTO lang VALUES ('hit_back_to_correct','fr','Pressez-vous le buttom \"Retour\" pour corriger l\'enrigistrement, s-il-vous-plait.');
INSERT INTO lang VALUES ('howto','fr','HowTo');
INSERT INTO lang VALUES ('howto_help','fr','Comment de figurer d\'une nouvelle record des aides?');
INSERT INTO lang VALUES ('howto_label','fr','Comment à configurer des templates des labels');
INSERT INTO lang VALUES ('howto_lang','fr','Comment de figurer d\'une nouvelle record de langue?');
INSERT INTO lang VALUES ('howto_templates','fr','Comment de figurer d\'une nouvelle set des modéle?');
INSERT INTO lang VALUES ('incomplete_date','fr','En cas d\'inconnue de la date completement remplace avec du numero \"0\".');
INSERT INTO lang VALUES ('intro','fr','Introduction');
INSERT INTO lang VALUES ('invalid_fsk','fr','Le mode donné pour PG (\"%1\") est invalide.<br>PG fait place pour Parentelle Guide mentant l\'age min, de-quelle le film est agreable.');
INSERT INTO lang VALUES ('invalid_media_nr','fr','Le numero de medium comme donné est incomplet ou invalidé. Placez d\'une <b>numero</b> en <b>deux</b> place pour le texte pour le numero de medium, s-il-vous-plait');
INSERT INTO lang VALUES ('in_list','fr','en liste');
INSERT INTO lang VALUES ('language_settings','fr','Configuration de la langue');
INSERT INTO lang VALUES ('length','fr','Longue');
INSERT INTO lang VALUES ('longplay','fr','LongPlay');
INSERT INTO lang VALUES ('medialength','fr','Longue de medium');
INSERT INTO lang VALUES ('medialist','fr','Liste de medium');
INSERT INTO lang VALUES ('medianr','fr','MediaNo');
INSERT INTO lang VALUES ('mediatype','fr','Type de medium');
INSERT INTO lang VALUES ('menues','fr','Menues');
INSERT INTO lang VALUES ('month','fr','Mois');
INSERT INTO lang VALUES ('music','fr','Musique');
INSERT INTO lang VALUES ('music_list','fr','List des Compositeurs');
INSERT INTO lang VALUES ('name','fr','Nom');
INSERT INTO lang VALUES ('never','fr','jamais');
INSERT INTO lang VALUES ('no','fr','Non');
INSERT INTO lang VALUES ('nobody_named','fr','Il n\'existe pas d\'un autre film sour la coopération de %1 %2 %3 en DB. Alors, nous remplacons cet nom dans la tableau.');
INSERT INTO lang VALUES ('none','fr','Non');
INSERT INTO lang VALUES ('not_ok','fr','Faute');
INSERT INTO lang VALUES ('not_yet_implemented','fr','C\'est domage, mais ce ne pas valuées.');
INSERT INTO lang VALUES ('no_add_lang','fr','Il n\'existe pas d\'une autrement langue d\'etre utilisé.');
INSERT INTO lang VALUES ('no_entries_found','fr','Pas de DB trouvé');
INSERT INTO lang VALUES ('no_entry_in_tapelist','fr','Non recherchement en liste');
INSERT INTO lang VALUES ('no_space_of','fr','Non recherchement pour la reste de temps en liste avec min. %1 minutes de place libre en DB');
INSERT INTO lang VALUES ('nr','fr','No');
INSERT INTO lang VALUES ('of_aquiration','fr','d\'enrigistrement');
INSERT INTO lang VALUES ('other_pages','fr','Autre Sites');
INSERT INTO lang VALUES ('page_bg','fr','Fond de la site');
INSERT INTO lang VALUES ('picture','fr','Format de couleur');
INSERT INTO lang VALUES ('print_label','fr','print à label:');
INSERT INTO lang VALUES ('recalc_free','fr','Calculez la place libre sur le medium');
INSERT INTO lang VALUES ('refresh_lang','fr','Traduiresation re-apris');
INSERT INTO lang VALUES ('refresh_lang_comment','fr','(remplacer l\'ancienne traduiresation et re-importer)');
INSERT INTO lang VALUES ('s/w','fr','b/n');
INSERT INTO lang VALUES ('scan_new_lang_comment','fr','(Si-vous avez figuré d\'une nouvelle record de langue en index \"setup\" - ce-quelle activé)');
INSERT INTO lang VALUES ('scan_new_lang_files','fr','Chercher pour des nouvelles records de langue?');
INSERT INTO lang VALUES ('screen','fr','Format de vue');
INSERT INTO lang VALUES ('search','fr','Recherche');
INSERT INTO lang VALUES ('select_add_lang','fr','Installisation d\'une autre langue');
INSERT INTO lang VALUES ('select_add_lang_comment','fr','La langue anglais est finalement installé et d\'etre generalement usé. v.p.p.)');
INSERT INTO lang VALUES ('select_primary_lang','fr','Choix de langue primaire');
INSERT INTO lang VALUES ('select_primary_lang_comment','fr','(En cas de la manque d\'une traduiresation il est utilisé la langue anglaise)');
INSERT INTO lang VALUES ('set_filter','fr','Placer de filtre');
INSERT INTO lang VALUES ('staff','fr','Personnel');
INSERT INTO lang VALUES ('start_page','fr','Site de comence');
INSERT INTO lang VALUES ('start_pvp','fr','Commencer phpVideoPro');
INSERT INTO lang VALUES ('stats','fr','Statistique');
INSERT INTO lang VALUES ('stat_counts','fr','Nombres');
INSERT INTO lang VALUES ('sure_to_delete','fr','Remplacée tous les dates pour %1?');
INSERT INTO lang VALUES ('table_bg','fr','Fond de tableau');
INSERT INTO lang VALUES ('tapelist_update_failed','fr','La liste avec la available reste de temps ne peut pas actualisée');
INSERT INTO lang VALUES ('taperest_absolute','fr','Reste de band (absolutée)');
INSERT INTO lang VALUES ('taperest_filtered','fr','Reste de band (filtrée)');
INSERT INTO lang VALUES ('template_set','fr','Set de modéle');
INSERT INTO lang VALUES ('th_bg','fr','Fond de tete du tablau');
INSERT INTO lang VALUES ('time_left','fr','%1 minutes reste');
INSERT INTO lang VALUES ('tone','fr','Format de tone');
INSERT INTO lang VALUES ('unknown','fr','non identificée');
INSERT INTO lang VALUES ('unset_filter','fr','Remplacer de filtre');
INSERT INTO lang VALUES ('update','fr','Actualisée');
INSERT INTO lang VALUES ('update_failed','fr','Impossibilité d\'actualisation des dates');
INSERT INTO lang VALUES ('update_success','fr','D\'actualisation succée');
INSERT INTO lang VALUES ('view','fr','Denoncer');
INSERT INTO lang VALUES ('view_entry','fr','Dénonciation de date %1');
INSERT INTO lang VALUES ('warning','fr','D\'Allert');
INSERT INTO lang VALUES ('week','fr','Semaine');
INSERT INTO lang VALUES ('wrong_date','fr','La date donnée %1 (%2) est invalide. Placez la date de jour au premier, la date de mois au deuxieme et la date d\'année en fin. En cas d\'inconnue de la date completement remplace avec du numero \"0\".');
INSERT INTO lang VALUES ('year','fr','Année');
INSERT INTO lang VALUES ('yes','fr','Oui');
