# ========================================================
# Hebrew Language File created by phpVideoPro v0.6.2
# ========================================================

UPDATE pvp_languages SET charset='utf-8' WHERE lang_id='iw';
INSERT INTO pvp_lang VALUES ('about','iw','על','');
INSERT INTO pvp_lang VALUES ('actions','iw','פעולות','');
INSERT INTO pvp_lang VALUES ('actor','iw','שחקן','');
INSERT INTO pvp_lang VALUES ('actors','iw','שחקנים','');
INSERT INTO pvp_lang VALUES ('actors_list','iw','רשימת שחקנים','');
INSERT INTO pvp_lang VALUES ('actor_persons','iw','שחקנים','');
INSERT INTO pvp_lang VALUES ('add_access','iw','יכול לה-וסיף פנקוסים','');
INSERT INTO pvp_lang VALUES ('add_access_short','iw','ה-וסף','');
INSERT INTO pvp_lang VALUES ('add_entry','iw','ה-וסף פנקוס','');
INSERT INTO pvp_lang VALUES ('add_user','iw','ה-וסף משמש','');
INSERT INTO pvp_lang VALUES ('admin','iw','ני-ה-ול','');
INSERT INTO pvp_lang VALUES ('admin_access','iw','יכול להכנס לתפריטי מנהלים','');
INSERT INTO pvp_lang VALUES ('admin_access_short','iw','מנהל','');
INSERT INTO pvp_lang VALUES ('admin_cats','iw','נהל קטגורי-ות','');
INSERT INTO pvp_lang VALUES ('admin_filter','iw','קביעות מסנן אוטומטי-ות','');
INSERT INTO pvp_lang VALUES ('admin_orphans','iw','הסרת פנקוסים מי-ותמים','');
INSERT INTO pvp_lang VALUES ('admin_printers','iw','(Printers) ערוך מדפסות ','');
INSERT INTO pvp_lang VALUES ('admin_pstemplates','iw','PS ערוך טמפלט לתו-ו-י-ות ','');
INSERT INTO pvp_lang VALUES ('admin_sessions','iw','נהל ישיבות','');
INSERT INTO pvp_lang VALUES ('admin_translations','iw','ערוך תרגומים','');
INSERT INTO pvp_lang VALUES ('admin_useredit','iw','ערוך חשבון משמש','');
INSERT INTO pvp_lang VALUES ('admin_users','iw','נהל חשבונות משמש','');
INSERT INTO pvp_lang VALUES ('back','iw','אחורה','');
INSERT INTO pvp_lang VALUES ('backup_db','iw','מאגר מילואים','');
INSERT INTO pvp_lang VALUES ('backup_db_complete','iw','יצר מאגר מילואים--כולל מידע טכני ועדיפויות','');
INSERT INTO pvp_lang VALUES ('backup_db_moviedel','iw','יצר מידע מילואים שייך לסרטים ו-החדר מצות מוחק למידע ישן קודם למצות הכנס למידע מילואים חדש','');
INSERT INTO pvp_lang VALUES ('backup_db_movies','iw','יצר מילואים רק למידע שייך לסרטים','');
INSERT INTO pvp_lang VALUES ('backup_db_runscript','iw','?תרצה ליצר רשימה עכשי-ו          ','');
INSERT INTO pvp_lang VALUES ('cancel','iw','בטל','');
INSERT INTO pvp_lang VALUES ('categories','iw','קטגוריות','');
INSERT INTO pvp_lang VALUES ('category','iw','קטגוריה','');
INSERT INTO pvp_lang VALUES ('catlist_alpha','iw','רשימת קלטות-תקליטורים לפי סדר אלפבטי, מי-ון בקטגוריות','');
INSERT INTO pvp_lang VALUES ('cat_action','iw','פעולה','');
INSERT INTO pvp_lang VALUES ('cat_adventure','iw','הרפתקה','');
INSERT INTO pvp_lang VALUES ('cat_agents','iw','סוכן','');
INSERT INTO pvp_lang VALUES ('cat_animal','iw','חיה','');
INSERT INTO pvp_lang VALUES ('cat_animals','iw','חיות','');
INSERT INTO pvp_lang VALUES ('cat_bible','iw','מקרא','');
INSERT INTO pvp_lang VALUES ('cat_biography','iw','ביוגרפיה','');
INSERT INTO pvp_lang VALUES ('cat_camera','iw','מצלמה','');
INSERT INTO pvp_lang VALUES ('cat_cartoon','iw','ציור','');
INSERT INTO pvp_lang VALUES ('cat_catastrophe','iw','חורבן','');
INSERT INTO pvp_lang VALUES ('cat_children','iw','ילדים','');
INSERT INTO pvp_lang VALUES ('cat_comedy','iw','קומדיה','');
INSERT INTO pvp_lang VALUES ('cat_concert','iw','קונצרט','');
INSERT INTO pvp_lang VALUES ('cat_crime','iw','פשע','');
INSERT INTO pvp_lang VALUES ('cat_documentary','iw','תיעוד','');
INSERT INTO pvp_lang VALUES ('cat_drama','iw','דרמה','');
INSERT INTO pvp_lang VALUES ('cat_fairytale','iw','אגדות','');
INSERT INTO pvp_lang VALUES ('cat_fantasy','iw','פנטסיה','');
INSERT INTO pvp_lang VALUES ('cat_history','iw','הסטוריה','');
INSERT INTO pvp_lang VALUES ('cat_horror','iw','הורר','');
INSERT INTO pvp_lang VALUES ('cat_internal_name','iw','ידון','');
INSERT INTO pvp_lang VALUES ('cat_judaica','iw','יודאיקה','');
INSERT INTO pvp_lang VALUES ('cat_love','iw','ספורי אהבה','');
INSERT INTO pvp_lang VALUES ('cat_melodrama','iw','מפגעה','');
INSERT INTO pvp_lang VALUES ('cat_misc','iw','שונים','');
INSERT INTO pvp_lang VALUES ('cat_monumental','iw','של מצבה','');
INSERT INTO pvp_lang VALUES ('cat_music','iw','מוסיקה','');
INSERT INTO pvp_lang VALUES ('cat_musical','iw','מוסיקלי','');
INSERT INTO pvp_lang VALUES ('cat_musicmovie','iw','סרטי מוסיקה','');
INSERT INTO pvp_lang VALUES ('cat_nature','iw','טבע','');
INSERT INTO pvp_lang VALUES ('cat_opera','iw','אופרה','');
INSERT INTO pvp_lang VALUES ('cat_operetta','iw','אופרטה','');
INSERT INTO pvp_lang VALUES ('cat_party','iw','משתה','');
INSERT INTO pvp_lang VALUES ('cat_problem','iw','הבעי','');
INSERT INTO pvp_lang VALUES ('cat_report','iw','דו-וח','');
INSERT INTO pvp_lang VALUES ('cat_satire','iw','מהתלה','');
INSERT INTO pvp_lang VALUES ('cat_scary','iw','סרטי פחד','');
INSERT INTO pvp_lang VALUES ('cat_sf','iw','מדע בדיוני','');
INSERT INTO pvp_lang VALUES ('cat_show','iw','תצוגה','');
INSERT INTO pvp_lang VALUES ('cat_spy','iw','סרטי ריגול','');
INSERT INTO pvp_lang VALUES ('cat_stage','iw','במה','');
INSERT INTO pvp_lang VALUES ('cat_thriller','iw','מותחן','');
INSERT INTO pvp_lang VALUES ('cat_trans_update_failed','iw','עדכון של תרגום נכשל להקטגורי-ות הבאות: %1','');
INSERT INTO pvp_lang VALUES ('cat_travesty','iw','חקוי','');
INSERT INTO pvp_lang VALUES ('cat_update_failed','iw','עדכון נכשל להקטגורי-ות הבאות: %1','');
INSERT INTO pvp_lang VALUES ('cat_vacation','iw','חופשה','');
INSERT INTO pvp_lang VALUES ('cat_videoclip','iw','גזיזת ווידאו','');
INSERT INTO pvp_lang VALUES ('cat_war','iw','סרטי מלחמה','');
INSERT INTO pvp_lang VALUES ('cat_western','iw','מערבי','');
INSERT INTO pvp_lang VALUES ('cat_westerncomedy','iw','קומדיה מערבית','');
INSERT INTO pvp_lang VALUES ('cat_xmas','iw','חג המולד','');
INSERT INTO pvp_lang VALUES ('change_media_length','iw','שנה אורך תקליטור או קלטת','');
INSERT INTO pvp_lang VALUES ('change_media_length_for','iw','%1 הכנס אורך תקליטור או קלטת של','');
INSERT INTO pvp_lang VALUES ('change_nr','iw','שנה מספר זה-ו-י/סוג קלטת או תקליטור של %1','');
INSERT INTO pvp_lang VALUES ('check_completed','iw','בדיקה נגמרה','');
INSERT INTO pvp_lang VALUES ('check_media_delete','iw','בודק אם קלטת-תקליטור פנוי','');
INSERT INTO pvp_lang VALUES ('close','iw','סגור','');
INSERT INTO pvp_lang VALUES ('colors','iw','צבעים','');
INSERT INTO pvp_lang VALUES ('comments','iw','הערות','');
INSERT INTO pvp_lang VALUES ('commercials','iw','תעמולות','');
INSERT INTO pvp_lang VALUES ('composer','iw','מלחין','');
INSERT INTO pvp_lang VALUES ('compose_person','iw','מלחין','');
INSERT INTO pvp_lang VALUES ('compose_persons','iw','מלחינים','');
INSERT INTO pvp_lang VALUES ('configuration','iw','מיחשוב','');
INSERT INTO pvp_lang VALUES ('config_media','iw','מיחשוב סרטים ותקליטורים-קלטות','');
INSERT INTO pvp_lang VALUES ('confirm_userdelete','iw','אתה עומד למחוק משמש  מספר %1','');
INSERT INTO pvp_lang VALUES ('content','iw','הרכב','');
INSERT INTO pvp_lang VALUES ('cookies','iw','עוגיתות','');
INSERT INTO pvp_lang VALUES ('counter_start_stop','iw','ממנה התחל/עצור','');
INSERT INTO pvp_lang VALUES ('countries','iw','מדינות','');
INSERT INTO pvp_lang VALUES ('country','iw','מדינה','');
INSERT INTO pvp_lang VALUES ('create','iw','ה-וסף','');
INSERT INTO pvp_lang VALUES ('create_success','iw','פנקוס יצור באופן נכון','');
INSERT INTO pvp_lang VALUES ('credits','iw','הכרות','');
INSERT INTO pvp_lang VALUES ('cut_off','iw','רק בסוף','');
INSERT INTO pvp_lang VALUES ('data_access','iw','קוד כניסה למידע','');
INSERT INTO pvp_lang VALUES ('date_format','iw','רשימת תאריך','');
INSERT INTO pvp_lang VALUES ('date_format_comment','iw','?איך לרשום התאריך','');
INSERT INTO pvp_lang VALUES ('date_rec','iw','תאריך התקבל','');
INSERT INTO pvp_lang VALUES ('day','iw','יום','');
INSERT INTO pvp_lang VALUES ('db_stats','iw','סטיסטיקה','');
INSERT INTO pvp_lang VALUES ('delete','iw','מחק','');
INSERT INTO pvp_lang VALUES ('delete_orphans','iw',':(מוחק %1 יתומ(ים     ','');
INSERT INTO pvp_lang VALUES ('delete_remaining','iw','עכשיו מוחק מהמאגר המידע על סרט זה שנשאר ','');
INSERT INTO pvp_lang VALUES ('deleting_entry','iw','מוחק פנקוס 1%','');
INSERT INTO pvp_lang VALUES ('del_access','iw','יכול למחוק פנקוסים','');
INSERT INTO pvp_lang VALUES ('del_access_short','iw','מחק','');
INSERT INTO pvp_lang VALUES ('desc_admin_orphans','iw','ה\"פנקוסים מי-ותמים\" הם מידע בלי י-ישום. שחקנים ,מנהלים, מלחינים שלא ה-וזכרו בשום סרט. הם, בדרך כלל, תוצאה של שנו-י של שם שלא או-ית נכון בפעם הראשון שנחסך. אלא אף פעם הם לא התוצאות של מחיקת פנקוסים. זה רעיון טוב, לכן, להסר הפנקוסים המי-ותמים כדי, לסיבה אחת, לחסוך שטח וגם, שנית, כדי שלא ילואטו פעולות המאגר ','');
INSERT INTO pvp_lang VALUES ('desc_backup_db','iw',' . י-ו-וצר. עירוב גירסות יגרום לבעי-ות SQL  תמיד רעיון טוב שי-ה-י-ה מאגר מילואים פנו-י. כל המידע ששמרת י-וצא, דרך טופס זה, וקובץ                                                ','');
INSERT INTO pvp_lang VALUES ('director','iw','מנהל','');
INSERT INTO pvp_lang VALUES ('directors','iw','מנהלים','');
INSERT INTO pvp_lang VALUES ('directors_list','iw','רשימת מנהלים','');
INSERT INTO pvp_lang VALUES ('director_person','iw','מנהל','');
INSERT INTO pvp_lang VALUES ('director_persons','iw','מנהלים','');
INSERT INTO pvp_lang VALUES ('display','iw','הצג','');
INSERT INTO pvp_lang VALUES ('display_limit','iw','גבול הצגה','');
INSERT INTO pvp_lang VALUES ('display_limit_comment','iw','(?כמה שורות להצג, לפי עמוד, להרשימה)','');
INSERT INTO pvp_lang VALUES ('dl_pvp_latest','iw',' ה-ורדת מהדורה אחרונה  ','');
INSERT INTO pvp_lang VALUES ('dupes','iw','פנקוסים שוכפלים','');
INSERT INTO pvp_lang VALUES ('dupe_id_entered','iw','קיים כבר פנקוס במאגר לאותה המספר זהוי. נא הכה כפתור אחורה על הברו-וסר ותקן ההכנסה. רמז: יש תיבת בחירה קרוב להתיבה שבה הכנסת המספר זהוי. תיבה זאת מגדת לך המספר זהו-י הכי גבוה לסרט. היא בחירה טובה, לקלטת או תקליטור חדש, להגבי-ה הספרה הראשונה באחד או, לסרט חדש על אותו הקלטת או תקליטור,  להגבה-ה הספרה השני-ה באחד.','');
INSERT INTO pvp_lang VALUES ('dupe_titles_found','iw',':נמצאו %1 פנקוסים אם כותרים שוכפלים','');
INSERT INTO pvp_lang VALUES ('edit','iw','ערוך','');
INSERT INTO pvp_lang VALUES ('edit_entry','iw','ערוך פנקוס %1   ','');
INSERT INTO pvp_lang VALUES ('enable_cookies','iw','?יכל עוגיתות ','');
INSERT INTO pvp_lang VALUES ('enable_cookies_comment','iw','?האם לנהל, דרך העוגיתות, עדיפויות משמש       ','');
INSERT INTO pvp_lang VALUES ('ended_sessions','iw','ישיבות נגמרות','');
INSERT INTO pvp_lang VALUES ('enter_min_free','iw',':הכנס מינימום שטח פנוי על קלטת או תקליטור שיוצג ','');
INSERT INTO pvp_lang VALUES ('expire_cookies','iw',':תקופת חיים לעוגיתות','');
INSERT INTO pvp_lang VALUES ('expire_cookies_comment','iw','?כמה זמן חייב לשרד עוגית בהברווסר','');
INSERT INTO pvp_lang VALUES ('farbe','iw','צבע','');
INSERT INTO pvp_lang VALUES ('filter','iw','סנן','');
INSERT INTO pvp_lang VALUES ('filter_setup','iw','קביעת מסנן','');
INSERT INTO pvp_lang VALUES ('finnished','iw','נגמר','');
INSERT INTO pvp_lang VALUES ('first_name','iw','שם פרטי','');
INSERT INTO pvp_lang VALUES ('format','iw','הגדרה','');
INSERT INTO pvp_lang VALUES ('free','iw','פנוי','');
INSERT INTO pvp_lang VALUES ('free_space_on_media','iw',':קלטות או תקליטורים אם יותר מ%1 דקות פנוי                                                                                      ','');
INSERT INTO pvp_lang VALUES ('free_space_title','iw',':שטח פנוי על קלטת או תקליטור','');
INSERT INTO pvp_lang VALUES ('fsk','iw','רייטינג','');
INSERT INTO pvp_lang VALUES ('general','iw','כללי','');
INSERT INTO pvp_lang VALUES ('goto_entry','iw','לך ישר לפנקוס','');
INSERT INTO pvp_lang VALUES ('graphic_file','iw','קובץ צורה','');
INSERT INTO pvp_lang VALUES ('help','iw','עזרה','');
INSERT INTO pvp_lang VALUES ('help_about','iw','עזרה ועל אודות','');
INSERT INTO pvp_lang VALUES ('highest_db_entries','iw',':מס. הכיגבוהים','');
INSERT INTO pvp_lang VALUES ('history','iw','הסטוריה','');
INSERT INTO pvp_lang VALUES ('hit_back_to_correct','iw','.הכה כפתור אחורה לתקן הטעות','');
INSERT INTO pvp_lang VALUES ('hour','iw','שעה','');
INSERT INTO pvp_lang VALUES ('hours','iw','שעות','');
INSERT INTO pvp_lang VALUES ('howto','iw','...איך ל ','');
INSERT INTO pvp_lang VALUES ('howto_help','iw','איך ליצור קובץ עזרה','');
INSERT INTO pvp_lang VALUES ('howto_label','iw','איך ליצור ולחשב תוויות טמפלטים','');
INSERT INTO pvp_lang VALUES ('howto_lang','iw','איך ליצור קובץ חדש לשפה','');
INSERT INTO pvp_lang VALUES ('howto_templates','iw','איך ליצור זוג טמפלט חדש','');
INSERT INTO pvp_lang VALUES ('incomplete_date','iw','מלא אפסים, אם לא ידוע לך התאריך המדו-יק אלא רק ידוע -למשל- שהשגת אותה בשנת 2000, במקום המידע בספק. התאריך המלא, במשל שלנו, יירשם 2000 00 00','');
INSERT INTO pvp_lang VALUES ('index','iw','אינדקס','');
INSERT INTO pvp_lang VALUES ('info_common','iw','מידע רגיל','');
INSERT INTO pvp_lang VALUES ('info_common_info','iw','<DIV ALIGN=\"center\">זאת ה-יא גרסה %1 של phpVideo Pro .עובד על %2 </div>','');
INSERT INTO pvp_lang VALUES ('info_noupdate','iw','<DIV ALIGN=\"center\">המהדורה המותקנת של phpVideoPro .היא עיתית .אין גרסה יותר מעודכנת :המשך, להורדת הכדור זפת של הגרסה המותקן, אחרי<A HREF=http://projects.izzysoft.de/progs/get_update.php?program=pvp\" TARGET=\"_blank\">this link</a>.</div>','');
INSERT INTO pvp_lang VALUES ('info_update','iw','מידע עדכון','');
INSERT INTO pvp_lang VALUES ('intro','iw','מבוא','');
INSERT INTO pvp_lang VALUES ('invalid_fsk','iw',' בטל הערך שהוכנס ל .PG (\"%1\") מסומן בזה .parental guide .מישה-ו תחת הגיל לא נכנס','');
INSERT INTO pvp_lang VALUES ('invalid_media_nr','iw','.מספר זהוי בטל. נא לפרט מספר בשתי השדות ','');
INSERT INTO pvp_lang VALUES ('in_list','iw','ברשימה','');
INSERT INTO pvp_lang VALUES ('is_rw','iw','ניתן לכתוב עליה שוב','');
INSERT INTO pvp_lang VALUES ('label','iw','תווית','');
INSERT INTO pvp_lang VALUES ('labels','iw','תוויות מיוחדות למדפסת או תוויות רגילות','');
INSERT INTO pvp_lang VALUES ('labeltype','iw',':סוג תווית','');
INSERT INTO pvp_lang VALUES ('lang_iw','iw','עברית','');
INSERT INTO pvp_lang VALUES ('language_settings','iw','קביעת שפות','');
INSERT INTO pvp_lang VALUES ('layout_label','iw','בחר הגדרת תווית','');
INSERT INTO pvp_lang VALUES ('left_offset','iw','שולים שמאלים','');
INSERT INTO pvp_lang VALUES ('length','iw','אורך','');
INSERT INTO pvp_lang VALUES ('lines_per_page','iw','שורות בעמוד','');
INSERT INTO pvp_lang VALUES ('lines_per_page_comment','iw','.זה בשביל פעולות ההדפסה להחליט כמה שורות מתאימות לעמוד אחד   ','');
INSERT INTO pvp_lang VALUES ('line_count','iw','שורות','');
INSERT INTO pvp_lang VALUES ('list','iw','רשימה','');
INSERT INTO pvp_lang VALUES ('listgen','iw','מיצר רשימה','');
INSERT INTO pvp_lang VALUES ('lists','iw','רשימות','');
INSERT INTO pvp_lang VALUES ('login','iw','קוד כניסה','');
INSERT INTO pvp_lang VALUES ('login_failed','iw','הקוד כניסה שלך נכשל. זה בגלל שהקוד מעבר .לא אוית נכון או החשבון המבוקש לא קיים<P/>','');
INSERT INTO pvp_lang VALUES ('login_required','iw',' .אתה לא זכאי לבצע הפעולה הנדרשת .תוכל, אם יש לך חשבון הוסמך, לה-יכנס<P/>','');
INSERT INTO pvp_lang VALUES ('logout_user','iw','</a>!צא<A HREF=\"%2\"> .\"%1\"-נכנסת כ','');
INSERT INTO pvp_lang VALUES ('longplay','iw','(הצגה ארוכה)','');
INSERT INTO pvp_lang VALUES ('lower_left_corner','iw','(x/y) פינה שמאלית תחתונית     ','');
INSERT INTO pvp_lang VALUES ('max','iw','מקסימום','');
INSERT INTO pvp_lang VALUES ('max_fontsize','iw','מידת פונט מקסימלי ','');
INSERT INTO pvp_lang VALUES ('media','iw','תקשורת','');
INSERT INTO pvp_lang VALUES ('medialength','iw','אורך תקליטור או קלטת','');
INSERT INTO pvp_lang VALUES ('medialist','iw','רשימת תקליטורים וקלטות','');
INSERT INTO pvp_lang VALUES ('medialist_alpha','iw','.רשימת קלטות-תקליטורים בסדר אלפבטי','');
INSERT INTO pvp_lang VALUES ('medialist_num','iw','.רשימת תקליטורים-קלטות בסדר ספרותי    ','');
INSERT INTO pvp_lang VALUES ('medianr','iw','מס. קלטת/תקליטור','');
INSERT INTO pvp_lang VALUES ('mediatype','iw','סוג תקליטור או קלטת','');
INSERT INTO pvp_lang VALUES ('media_change','iw','שנה מספר זהוי','');
INSERT INTO pvp_lang VALUES ('media_copy','iw',':העתק מידע למספר זהוי          ','');
INSERT INTO pvp_lang VALUES ('medium','iw','סוג קלטת או תקליטור','');
INSERT INTO pvp_lang VALUES ('medium_deleted','iw','אין עוד סרטים על קלטת או תקליטור. הוסר קלטת או .תקליטור','');
INSERT INTO pvp_lang VALUES ('medium_not_deleted','iw','קלטת או תקליטור לא הוסר','');
INSERT INTO pvp_lang VALUES ('medium_overview','iw','מבט מלמעלה ל%1','');
INSERT INTO pvp_lang VALUES ('menues','iw','תפריטים','');
INSERT INTO pvp_lang VALUES ('min','iw','מינימום','');
INSERT INTO pvp_lang VALUES ('minute_abbrev','iw','דקות','');
INSERT INTO pvp_lang VALUES ('month','iw','חודש','');
INSERT INTO pvp_lang VALUES ('movies','iw','סרטים','');
INSERT INTO pvp_lang VALUES ('movies_left_in_cat','iw','.קטגוריה %1 עדיין הורכב %2 סרט(ים) ואי אפשר למחוק','');
INSERT INTO pvp_lang VALUES ('movie_color_default','iw',':הגדרת צבע ברירית מחדל של סרט','');
INSERT INTO pvp_lang VALUES ('movie_color_default_comment','iw','.זה ישומש להגדרת צבע ברירת מחדל לפנקוס חדש','');
INSERT INTO pvp_lang VALUES ('movie_onlabel_default','iw','הגדרה אוטומטית לתוויות','');
INSERT INTO pvp_lang VALUES ('movie_onlabel_default_comment','iw','?האם לכלל בתווית הקלטת-תקליטור גם מידע על סרט זה','');
INSERT INTO pvp_lang VALUES ('movie_tone_default','iw',':הגדרת קול ברירת מחדל לסרט','');
INSERT INTO pvp_lang VALUES ('movie_tone_default_comment','iw','.זה ישומש להגדרת קול, נקבע מראש, לפנקוס חדש','');
INSERT INTO pvp_lang VALUES ('music','iw','מלחינים','');
INSERT INTO pvp_lang VALUES ('music_list','iw','רשימת מלחינים','');
INSERT INTO pvp_lang VALUES ('name','iw','שם משפחה','');
INSERT INTO pvp_lang VALUES ('never','iw','לעולם','');
INSERT INTO pvp_lang VALUES ('new_medianr','iw','מספר זהוי חדש','');
INSERT INTO pvp_lang VALUES ('no','iw','לא','');
INSERT INTO pvp_lang VALUES ('nobody_named','iw','.אין עוד סרט מעת %1 שנקרא %2 %3 במאגר .לכן, יימחק הפנקוס מהטבלה של %1','');
INSERT INTO pvp_lang VALUES ('none','iw','אף אחד','');
INSERT INTO pvp_lang VALUES ('not_ok','iw','נכשל','');
INSERT INTO pvp_lang VALUES ('not_yet_implemented','iw','עוד לא הוצא לפועל','');
INSERT INTO pvp_lang VALUES ('no_add_lang','iw','לא מוכנות שפות נוספות','');
INSERT INTO pvp_lang VALUES ('no_entries_found','iw','לא נמצאו פנקוסים','');
INSERT INTO pvp_lang VALUES ('no_entry_in_tapelist','iw','.נכשל. אין פנקוס ברשימה.','');
INSERT INTO pvp_lang VALUES ('no_orphans_found','iw','(?טוב. אין עוד שלדים בארון. (יש עוד','');
INSERT INTO pvp_lang VALUES ('no_space_of','iw','אין קלטת או תקליטור במאגר שנשאר עליו המינימום  של %1 .שטח פנוי ','');
INSERT INTO pvp_lang VALUES ('nr','iw','זהוי','');
INSERT INTO pvp_lang VALUES ('of_aquiration','iw','של השגה','');
INSERT INTO pvp_lang VALUES ('ok','iw','בסדר','');
INSERT INTO pvp_lang VALUES ('old_sessions','iw','ישיבה יותר ישנה מ<Input Name \"%1\" VALUE CLASS=\"yesnobutton\">ימים','');
INSERT INTO pvp_lang VALUES ('orig_medianr','iw','מספר זהוי מקורי','');
INSERT INTO pvp_lang VALUES ('orig_trans','iw','תרגום מקורי (%1)','');
INSERT INTO pvp_lang VALUES ('orphans_found','iw',':(נמצאים %1 יתומ(ים','');
INSERT INTO pvp_lang VALUES ('other_pages','iw','עמודים אחרים','');
INSERT INTO pvp_lang VALUES ('password','iw','קוד מעבר','');
INSERT INTO pvp_lang VALUES ('password_retype','iw','הכנס שוב קוד מעבר','');
INSERT INTO pvp_lang VALUES ('picture','iw','הגדרת צבע','');
INSERT INTO pvp_lang VALUES ('preferences','iw','עדיפויות','');
INSERT INTO pvp_lang VALUES ('print','iw','הדפס','');
INSERT INTO pvp_lang VALUES ('printer','iw','מדפסת','');
INSERT INTO pvp_lang VALUES ('printer_add_failed','iw','.קרה שגיאה בה-וספת זאת למדפסת','');
INSERT INTO pvp_lang VALUES ('printer_add_success','iw','.ה-וסף בהצלחה למדפסת','');
INSERT INTO pvp_lang VALUES ('printer_comment','iw','.ההדפסים של המדפסת ,(PS נצטרך, לצורך טפסים (כמו לתוויות','');
INSERT INTO pvp_lang VALUES ('printer_name','iw','שם מדפסת','');
INSERT INTO pvp_lang VALUES ('printer_upd_failed','iw',' %1 :נכשל עדכון למדפסת הבא             ','');
INSERT INTO pvp_lang VALUES ('print_label','iw',':תווית הדפסה','');
INSERT INTO pvp_lang VALUES ('pslabel','iw','PS תווית         ','');
INSERT INTO pvp_lang VALUES ('pstpl_name','iw','מספר טמפלט','');
INSERT INTO pvp_lang VALUES ('pstpl_type','iw','סוג טמפלט','');
INSERT INTO pvp_lang VALUES ('read_access','iw','יכול להסתכל בפנקוסים','');
INSERT INTO pvp_lang VALUES ('read_access_short','iw','קרא','');
INSERT INTO pvp_lang VALUES ('recalc_free','iw','עושה שוב חשבון של שטח פנוי על הקלטת או תקליטור.','');
INSERT INTO pvp_lang VALUES ('refresh_lang','iw','שחזר שפה','');
INSERT INTO pvp_lang VALUES ('refresh_lang_comment','iw','(שחזר בטויים מקובץ שפות למאגר מידע)','');
INSERT INTO pvp_lang VALUES ('remove_empty_media','iw','הסר קלטות-תקליטורים ריקים','');
INSERT INTO pvp_lang VALUES ('remove_empty_media_comment','iw',' האם למחוק, אחרי שנשמד סרט אחרון, קלטות או ?תקליטורים מהתמיכה של שטח פנוי','');
INSERT INTO pvp_lang VALUES ('rw_media','iw',':קלטות-תקליטורים ניתנים לערוך','');
INSERT INTO pvp_lang VALUES ('rw_media_comment','iw',' קלטות-תקליטורים להשאיר עלי-הם שטח פנו-י  : (שתתכוון לקלוט עלי-הם)  ','');
INSERT INTO pvp_lang VALUES ('s/w','iw','לבן/שחור','');
INSERT INTO pvp_lang VALUES ('save_lang_file','iw','שמור תרגומי יעד לקובץ','');
INSERT INTO pvp_lang VALUES ('scan_new_lang_comment','iw','זה יגיד ל .אם יצרת קובץ שפה, איפה לחפש בשבילו ,phpVideoPro','');
INSERT INTO pvp_lang VALUES ('scan_new_lang_files','iw','?בדוק לשפות חדשות','');
INSERT INTO pvp_lang VALUES ('screen','iw','הגדרת מסך','');
INSERT INTO pvp_lang VALUES ('search','iw','חפש','');
INSERT INTO pvp_lang VALUES ('search_movie','iw','חפש סרטים','');
INSERT INTO pvp_lang VALUES ('select_add_lang','iw',':בחר שפות נוספות להתקין','');
INSERT INTO pvp_lang VALUES ('select_add_lang_comment','iw','אנגלית כבר הותקן ותמיד תהי מותקן- עיין בפריט .הבא. ועיין שם גם לשפות אחרות שה-ותקנו','');
INSERT INTO pvp_lang VALUES ('select_primary_lang','iw','בחר שפה ראשונה','');
INSERT INTO pvp_lang VALUES ('select_primary_lang_comment','iw','(.תמיד יהיו, בשביל ביטויים חסרים, מילואים באנגלית)','');
INSERT INTO pvp_lang VALUES ('sel_target_lang','iw',':(בחר שפת יעד (אליה לתרגם','');
INSERT INTO pvp_lang VALUES ('session','iw','ישיבה','');
INSERT INTO pvp_lang VALUES ('session_expired','iw','.ישיבתיך נגמרה! נא להיכנס שוב','');
INSERT INTO pvp_lang VALUES ('session_purgetime','iw','?אחרי איזה שעה, אם יש ישיבה לא אקטיבית, לסגור','');
INSERT INTO pvp_lang VALUES ('session_purgetime_comment','iw','?לכמה זמן להשאיר ישיבה, בלי פעילות משמש, קיימת','');
INSERT INTO pvp_lang VALUES ('sess_dla','iw','זמן כניסה אחרונה','');
INSERT INTO pvp_lang VALUES ('sess_end','iw','זמן גמירת הישיבה','');
INSERT INTO pvp_lang VALUES ('sess_id','iw','זהוי ישיבה','');
INSERT INTO pvp_lang VALUES ('sess_ip','iw','רחוקה IP','');
INSERT INTO pvp_lang VALUES ('sess_start','iw','זמן התחלת ישיבה','');
INSERT INTO pvp_lang VALUES ('set_filter','iw','קבע מסנן','');
INSERT INTO pvp_lang VALUES ('site_info','iw','מידע על עמוד','');
INSERT INTO pvp_lang VALUES ('site_info_comment','iw','?איזה מידע על עמוד להציג בהסורג כותר של הברווסר','');
INSERT INTO pvp_lang VALUES ('source','iw','מקור','');
INSERT INTO pvp_lang VALUES ('staff','iw','תפקיד','');
INSERT INTO pvp_lang VALUES ('start_page','iw','עמוד התחלה','');
INSERT INTO pvp_lang VALUES ('start_pvp','iw',' phpVideoPro התחל','');
INSERT INTO pvp_lang VALUES ('stats','iw','סטיסטיקה','');
INSERT INTO pvp_lang VALUES ('stat_categories','iw','(קטגוריות (הכל/שמוש','');
INSERT INTO pvp_lang VALUES ('stat_counts','iw','ספירות','');
INSERT INTO pvp_lang VALUES ('stat_ranks','iw','דירוג','');
INSERT INTO pvp_lang VALUES ('submit','iw','הכנס','');
INSERT INTO pvp_lang VALUES ('sure_to_delete','iw','?בטוח שתרצה למחוק כל מידע ל%1','');
INSERT INTO pvp_lang VALUES ('tapelist_update_failed','iw','.נכשל עדכון לרשימת סרטים','');
INSERT INTO pvp_lang VALUES ('taperest_absolute','iw','(הנח סרט (לא מסונן','');
INSERT INTO pvp_lang VALUES ('taperest_filtered','iw',')הנח סרט (מסונן','');
INSERT INTO pvp_lang VALUES ('target_trans','iw','(%1) תרגם להשפת יעד','');
INSERT INTO pvp_lang VALUES ('techdata','iw','מידע טכני','');
INSERT INTO pvp_lang VALUES ('template_file','iw','קובץ טמפלט','');
INSERT INTO pvp_lang VALUES ('template_set','iw','סוג טמפלט','');
INSERT INTO pvp_lang VALUES ('time_left','iw','דקות נשאר: %1','');
INSERT INTO pvp_lang VALUES ('title','iw','כותר','');
INSERT INTO pvp_lang VALUES ('tone','iw','מערכת קול','');
INSERT INTO pvp_lang VALUES ('top_offset','iw','שולים עליונים','');
INSERT INTO pvp_lang VALUES ('trans_code','iw','קוד תרגום','');
INSERT INTO pvp_lang VALUES ('trans_sample','iw','קשר לדוגמה','');
INSERT INTO pvp_lang VALUES ('unit','iw','מדה','');
INSERT INTO pvp_lang VALUES ('unknown','iw','לא נודע','');
INSERT INTO pvp_lang VALUES ('unset_filter','iw','בטל מסנן','');
INSERT INTO pvp_lang VALUES ('update','iw','עדכן','');
INSERT INTO pvp_lang VALUES ('update_failed','iw','כשלון בעדכון הפנקס','');
INSERT INTO pvp_lang VALUES ('update_success','iw','עדכון עבר בהצלחה','');
INSERT INTO pvp_lang VALUES ('upd_access','iw','יכול לעדכן פנקוסים קיימים','');
INSERT INTO pvp_lang VALUES ('upd_access_short','iw','עדכון','');
INSERT INTO pvp_lang VALUES ('upper_right_corner','iw','(xy)פינה עליונה ימנית','');
INSERT INTO pvp_lang VALUES ('user','iw','משמש','');
INSERT INTO pvp_lang VALUES ('user_deleted','iw','(%3)\"%2\",%1 .נמחק בהצלחה משמש(ים) מס','');
INSERT INTO pvp_lang VALUES ('user_delete_failed','iw','(%3)\"%2\" ,נכשל מחיקת משמש %1','');
INSERT INTO pvp_lang VALUES ('user_delete_report','iw',':(תוצאות של מחיקת משמש(ים','');
INSERT INTO pvp_lang VALUES ('user_update_failed','iw','עדכון נכשל למשמשים הבאים: %1','');
INSERT INTO pvp_lang VALUES ('view','iw','ראה','');
INSERT INTO pvp_lang VALUES ('view_entry','iw','ראה פנקוס','');
INSERT INTO pvp_lang VALUES ('warning','iw','אזהרה','');
INSERT INTO pvp_lang VALUES ('week','iw','שבוע','');
INSERT INTO pvp_lang VALUES ('welcome','iw','phpVideoProברוך הבא ל','');
INSERT INTO pvp_lang VALUES ('wrong_date','iw','התאריך %1 שנתת לא קיים. נא להכניס, בשביל הכנסת תאריך, היום להשדה הראשון, החודש להשני, והשנה להשלישי. ולשמש רק ספרות. הכנס אפסים, במקרה שאתה לא בטוח על התאריך, להשדה המסופק. דוגמה: 2002 02 00 אומרת איזשה-ו יום בפברואר 2002. או 0000 00 00 אומרת איזשהו יום.','');
INSERT INTO pvp_lang VALUES ('year','iw','שנה','');
INSERT INTO pvp_lang VALUES ('yes','iw','כן','');
