# ========================================================
# Russian Language File created by phpVideoPro v0.8.0p19
# ========================================================

UPDATE languages SET charset='UTF-8' WHERE lang_id='ru';
INSERT INTO lang VALUES ('about','ru','О...','');
INSERT INTO lang VALUES ('actions','ru','Действия','');
INSERT INTO lang VALUES ('actor','ru','Актер','');
INSERT INTO lang VALUES ('actors','ru','Актеры','');
INSERT INTO lang VALUES ('actors_list','ru','Список актеров','');
INSERT INTO lang VALUES ('actor_persons','ru','Актеры','');
INSERT INTO lang VALUES ('add_access','ru','Может добавлять новые записи','');
INSERT INTO lang VALUES ('add_access_short','ru','доб','');
INSERT INTO lang VALUES ('add_entry','ru','Добавить запись','');
INSERT INTO lang VALUES ('add_user','ru','Добавить пользователя','');
INSERT INTO lang VALUES ('admin','ru','Админ','');
INSERT INTO lang VALUES ('admin_access','ru','Имеет доступ к меню администратора','');
INSERT INTO lang VALUES ('admin_access_short','ru','адм','');
INSERT INTO lang VALUES ('admin_avlang','ru','Языки администратора (аудио и субтитры)','');
INSERT INTO lang VALUES ('admin_cats','ru','Категории администратора','');
INSERT INTO lang VALUES ('admin_disktypes','ru','Редактировать тип диска','');
INSERT INTO lang VALUES ('admin_filter','ru','Установки фильтра по умолчанию','');
INSERT INTO lang VALUES ('admin_movietech','ru','Редактировать данные фильма','');
INSERT INTO lang VALUES ('admin_orphans','ru','Удаление осиротевших вхождений','');
INSERT INTO lang VALUES ('admin_printers','ru','Редактировать принтеры','');
INSERT INTO lang VALUES ('admin_pstemplates','ru','Редактировать шаблоны PSLabel ','');
INSERT INTO lang VALUES ('admin_required','ru','Это действие требует административных привилегий!','');
INSERT INTO lang VALUES ('admin_sessions','ru','Управление сессиями','');
INSERT INTO lang VALUES ('admin_translations','ru','Перевод интерфейса','');
INSERT INTO lang VALUES ('admin_useredit','ru','Редактировать пользовательскую запись','');
INSERT INTO lang VALUES ('admin_users','ru','Пользователи','');
INSERT INTO lang VALUES ('audio_ts','ru','Аудио','');
INSERT INTO lang VALUES ('back','ru','Назад','');
INSERT INTO lang VALUES ('backup_compress','ru','позволите сжатие','');
INSERT INTO lang VALUES ('backup_db','ru','Резервная копия БД','');
INSERT INTO lang VALUES ('backup_db_cats','ru','Резервная копия категорий','');
INSERT INTO lang VALUES ('backup_db_complete','ru','Редактировать ВСЮ БД(включая технические данные и и предпочтения)','');
INSERT INTO lang VALUES ('backup_db_moviedel','ru','Откат данных исключительно относящихся к фильму 
 и предложение стереть старые данные перед вставкой новых(сохранённых)данных','');
INSERT INTO lang VALUES ('backup_db_movies','ru','Откат данных исключительно относящихся к фильму
 (фильм,актёры и т.д.)','');
INSERT INTO lang VALUES ('backup_db_movie_internal','ru','Скопируйте все кинофильмы, используя phpVideoPro внутренний формат','');
INSERT INTO lang VALUES ('backup_db_runscript','ru','Хотите создать скрипт сейчас?','');
INSERT INTO lang VALUES ('backup_db_sysconf','ru','Скопируйте системную конфигурацию и стандартые данные','');
INSERT INTO lang VALUES ('backup_file_corrupt','ru','Отобранный резервный файл испорчен - не может восстановить от этого!','');
INSERT INTO lang VALUES ('backup_file_unreadable','ru','Не могу читать резервный файл - удостоверяются, что разрешения файла установлены правильно!','');
INSERT INTO lang VALUES ('bubble_help_enable','ru','Активизировать BubbleHelp?','');
INSERT INTO lang VALUES ('bubble_help_enable_comment','ru','BubbleHelp показывает контекстно-зависимую помощь для некоторых пунктов, если мышь отодвинута их (например на кнопках окна набора шаблона Applicat).','');
INSERT INTO lang VALUES ('button_restore','ru','Восстановить','');
INSERT INTO lang VALUES ('cache_enable','ru','Позволите кэширование браузера/полномочия?','');
INSERT INTO lang VALUES ('cache_enable_comment','ru','Желательно не оставлять данные, а вызывать их заного','');
INSERT INTO lang VALUES ('cancel','ru','Отменить','');
INSERT INTO lang VALUES ('categories','ru','Категории','');
INSERT INTO lang VALUES ('category','ru','Категория','');
INSERT INTO lang VALUES ('catlist_alpha','ru','Список фильмов в алфавитном порядке,сортировка по категориям','');
INSERT INTO lang VALUES ('cat_action','ru','Боевик','');
INSERT INTO lang VALUES ('cat_adventure','ru','Приключения','');
INSERT INTO lang VALUES ('cat_agents','ru','Агентский','');
INSERT INTO lang VALUES ('cat_animal','ru','Животное','');
INSERT INTO lang VALUES ('cat_animals','ru','Животные','');
INSERT INTO lang VALUES ('cat_bible','ru','Библия','');
INSERT INTO lang VALUES ('cat_biography','ru','Биография','');
INSERT INTO lang VALUES ('cat_camera','ru','Домашнее видео','');
INSERT INTO lang VALUES ('cat_cartoon','ru','Мультфильм','');
INSERT INTO lang VALUES ('cat_catastrophe','ru','Катастрофа','');
INSERT INTO lang VALUES ('cat_children','ru','Для детей','');
INSERT INTO lang VALUES ('cat_comedy','ru','Комедия','');
INSERT INTO lang VALUES ('cat_concert','ru','Концерт','');
INSERT INTO lang VALUES ('cat_crime','ru','Криминал','');
INSERT INTO lang VALUES ('cat_documentary','ru','Документация','');
INSERT INTO lang VALUES ('cat_drama','ru','Драма','');
INSERT INTO lang VALUES ('cat_fairytale','ru','Сказки','');
INSERT INTO lang VALUES ('cat_fantasy','ru','Фэнтэзи','');
INSERT INTO lang VALUES ('cat_handle_empty','ru','Пусто','');
INSERT INTO lang VALUES ('cat_history','ru','История','');
INSERT INTO lang VALUES ('cat_horror','ru','Ужасы','');
INSERT INTO lang VALUES ('cat_judaica','ru','Иудаика','');
INSERT INTO lang VALUES ('cat_love','ru','Любовные истории','');
INSERT INTO lang VALUES ('cat_melodrama','ru','Мелодрама','');
INSERT INTO lang VALUES ('cat_misc','ru','Разное','');
INSERT INTO lang VALUES ('cat_monumental','ru','Классика','');
INSERT INTO lang VALUES ('cat_music','ru','Музыка','');
INSERT INTO lang VALUES ('cat_musical','ru','Музыкальный','');
INSERT INTO lang VALUES ('cat_musicmovie','ru','Музыкальные фильмы','');
INSERT INTO lang VALUES ('cat_nature','ru','Природа','');
INSERT INTO lang VALUES ('cat_opera','ru','Опера','');
INSERT INTO lang VALUES ('cat_operetta','ru','Оперетта','');
INSERT INTO lang VALUES ('cat_party','ru','Вечеринка','');
INSERT INTO lang VALUES ('cat_problem','ru','Проблема','');
INSERT INTO lang VALUES ('cat_report','ru','Репортаж','');
INSERT INTO lang VALUES ('cat_satire','ru','Сатира','');
INSERT INTO lang VALUES ('cat_scary','ru','Ужасы','');
INSERT INTO lang VALUES ('cat_sf','ru','Научная фантастика','');
INSERT INTO lang VALUES ('cat_show','ru','Шоу','');
INSERT INTO lang VALUES ('cat_spy','ru','Шпионские фильмы','');
INSERT INTO lang VALUES ('cat_stage','ru','Сцена','');
INSERT INTO lang VALUES ('cat_thriller','ru','Триллер','');
INSERT INTO lang VALUES ('cat_trans_update_failed','ru','Обновление подведенного для переводов следующих категорий: %1','');
INSERT INTO lang VALUES ('cat_travesty','ru','Пародия','');
INSERT INTO lang VALUES ('cat_update_failed','ru','Происходит апдейт файлов в следующих категориях: %1','');
INSERT INTO lang VALUES ('cat_vacation','ru','Отпуск','');
INSERT INTO lang VALUES ('cat_videoclip','ru','Видео клип','');
INSERT INTO lang VALUES ('cat_war','ru','Военные фильмы','');
INSERT INTO lang VALUES ('cat_western','ru','Вестерн','');
INSERT INTO lang VALUES ('cat_westerncomedy','ru','Комедия-вестерн','');
INSERT INTO lang VALUES ('cat_xmas','ru','Рождественский','');
INSERT INTO lang VALUES ('change_disktype','ru','Изменить тип диска для %1','');
INSERT INTO lang VALUES ('change_media_length','ru','Изменить размер носителя','');
INSERT INTO lang VALUES ('change_media_length_for','ru','Пожалуйста введите объем для %1','');
INSERT INTO lang VALUES ('change_nr','ru','Изменить Номер/Тип носителя %1','');
INSERT INTO lang VALUES ('change_rc','ru','Изменить код региона','');
INSERT INTO lang VALUES ('change_rc_for','ru','Изменить код региона на %1','');
INSERT INTO lang VALUES ('check_completed','ru','Проверка завершена','');
INSERT INTO lang VALUES ('check_media_delete','ru','Проверка,не пуст ли носитель','');
INSERT INTO lang VALUES ('clean_restore','ru','Уборка старые данные прежде, чем восстанавливают ','');
INSERT INTO lang VALUES ('close','ru','Закрыть','');
INSERT INTO lang VALUES ('colors','ru','Цвета','');
INSERT INTO lang VALUES ('comments','ru','Комментарии','');
INSERT INTO lang VALUES ('comment_not_string','ru','Введенный комментарий содержит недействительные характеры (чтобы предотвратить кодовую инъекцию, только букбы, цифры и \"-\" позволяются).','');
INSERT INTO lang VALUES ('commercials','ru','Реклама','');
INSERT INTO lang VALUES ('composer','ru','Композиторы','');
INSERT INTO lang VALUES ('compose_person','ru','композитор','');
INSERT INTO lang VALUES ('compose_persons','ru','Композиторы','');
INSERT INTO lang VALUES ('configuration','ru','Настройки','');
INSERT INTO lang VALUES ('config_media','ru','Фильмы и носители','');
INSERT INTO lang VALUES ('confirm_delete','ru','Вы действительно хотите удалить эту запись?','');
INSERT INTO lang VALUES ('confirm_prilang','ru','Вы действительно хотите изменить первичный язык по умолчанию для ВСЕХ (новых) пользователей?','');
INSERT INTO lang VALUES ('confirm_userdelete','ru','Вы сейчас удаляете пользователя #%1','');
INSERT INTO lang VALUES ('content','ru','Содержимое','');
INSERT INTO lang VALUES ('counter_start_stop','ru','Счетчик Старт/Стоп','');
INSERT INTO lang VALUES ('countries','ru','Страны','');
INSERT INTO lang VALUES ('country','ru','Страна','');
INSERT INTO lang VALUES ('create','ru','Создать','');
INSERT INTO lang VALUES ('create_success','ru','Запись успешно создана','');
INSERT INTO lang VALUES ('credits','ru','Отдельная благодарность','');
INSERT INTO lang VALUES ('cut_off','ru','Отключенный','');
INSERT INTO lang VALUES ('data_access','ru','Доступ к данным','');
INSERT INTO lang VALUES ('date_format','ru','Формат даты','');
INSERT INTO lang VALUES ('date_format_comment','ru','Формат для отобрадения даты.','');
INSERT INTO lang VALUES ('date_is_nan','ru','Дата, месяц и год должны быть числовыми!n (то есть только цифры позволяются)','');
INSERT INTO lang VALUES ('date_rec','ru','Дата принята','');
INSERT INTO lang VALUES ('day','ru','День','');
INSERT INTO lang VALUES ('db_stats','ru','Статистика','');
INSERT INTO lang VALUES ('delete','ru','Удалить','');
INSERT INTO lang VALUES ('delete_lang','ru','Удалить язык','');
INSERT INTO lang VALUES ('delete_lang_comment','ru','Удалить все фразы на выбранном языке из базы данных.Вы не удаляете языковой файл,так что вы сможете вставить фразы позднее(если вы не удалите те весь файл)','');
INSERT INTO lang VALUES ('delete_orphans','ru','Удаление  %1 пустой ссылки(ок):','');
INSERT INTO lang VALUES ('delete_remaining','ru','удаление из БД данных, относящихся к этому фильму','');
INSERT INTO lang VALUES ('deleting_entry','ru','Удаление записи %1','');
INSERT INTO lang VALUES ('del_access','ru','Может удалять записи','');
INSERT INTO lang VALUES ('del_access_short','ru','уд','');
INSERT INTO lang VALUES ('desc_admin_orphans','ru','\"Пустые ссылки\" это данные без привязки,то есть: Актёры,режиссёры и/или сценаристы на которых нет ссылки.В основном так получается при изменении неправильно написанного названия фильма после его сохранения - и никогда после удаления данных фильма.Таким образом,полезно удалять эти данные:с одной стороны это сохраняет ресурсы,а с другой предотвращает замедление работы базы данных.','');
INSERT INTO lang VALUES ('desc_admin_orphan_fs','ru','\"Пустые файлы\" это данные без привязки,то есть: иконы, к кому нигде не отнесен в ни от какого фильм. Наиболее вероятные причины для этого:
 <UL><LI>Иконы были восстановлены с запросом поиска IMDB, но тогда не использовались</LI><LI>Отчет был отредактирован, и икона было изменено/удалено</LI><LI>Отчет был удален, и глупое заявление не беспокоилось об иконом</LI><UL>Однако: Если маловероятно, что эти изображения будут назначены на любой отчет фильм, phpVideoPro может удалить перечисленные файлы здесь.','');
INSERT INTO lang VALUES ('desc_backup_db','ru','Всегда полезно делать резервную копию базы данных(БД)С помощью этой формы,все Ваши данные,которые Вы сохранили в БД будут извлечены и одновременно будет создан коммандный файл SQL.Вы всегда сможете с помощью этого файла заполнить пустую БД(или скопировать существующую).Только убедитесь в том,что Вы не используете копию БД для заливки в более раннюю версию  phpVideoPro!!!Это может привести к ошибкам БД!!! ','');
INSERT INTO lang VALUES ('director','ru','Режиссер','');
INSERT INTO lang VALUES ('directors','ru','Режиссеры','');
INSERT INTO lang VALUES ('directors_list','ru','Список режиссеров','');
INSERT INTO lang VALUES ('director_person','ru','Pежиссер','');
INSERT INTO lang VALUES ('director_persons','ru','Режиссеры','');
INSERT INTO lang VALUES ('disktype_add_failed','ru','Простите,не могу добавить новый тип диска','');
INSERT INTO lang VALUES ('disktype_change','ru','Изменить тип диска','');
INSERT INTO lang VALUES ('disktype_contains_media','ru','Невозможно изменить этот тип диска,тк этот фильм ссылается на него до сих пор','');
INSERT INTO lang VALUES ('disktype_name_empty','ru','Имя типа диска не должно быть пустым.Вернитесь и устраните ошибку','');
INSERT INTO lang VALUES ('disktype_update_failed','ru','Простите,не могу обновить тип диска(ов)','');
INSERT INTO lang VALUES ('disk_size','ru','Размер диска','');
INSERT INTO lang VALUES ('disk_type','ru','Тип диска','');
INSERT INTO lang VALUES ('display','ru','Показ','');
INSERT INTO lang VALUES ('display_limit','ru','Предел показа','');
INSERT INTO lang VALUES ('display_limit_comment','ru','(сколько строк списка отображать на экране)','');
INSERT INTO lang VALUES ('dl_pvp_latest','ru','Загрузить последнюю версию','');
INSERT INTO lang VALUES ('dupes','ru','Дубликаты данных','');
INSERT INTO lang VALUES ('dupes_own','ru','Дубликаты данных (свой)','');
INSERT INTO lang VALUES ('dupes_own_strict','ru','Дубликаты данных (свой+точный)','');
INSERT INTO lang VALUES ('dupes_strict','ru','Дубликаты данных (точный)','');
INSERT INTO lang VALUES ('dupe_id_entered','ru','Есть уже отчет в базе данных для введенного MediaID. Пожалуйста поразите \"Назад\" кнопку вашего браузера и исправьте ваш вход. Намек: Есть Коробка выбора рядом с коробкой входа, в которой можно определили MediaNr. Эта коробка выбора говорит самое высокое существующее MediaNr. Обычно хороший выбор для новых фильмы, чтобы увеличить первое число (с четырьмя цифрами) одним, или для нового фильм на тех же самых СМИ, увеличить второе число (с двумя цифрами) одним.','');
INSERT INTO lang VALUES ('dupe_titles_found','ru','Найдено %1 возможно повторяющихся записей  :','');
INSERT INTO lang VALUES ('edit','ru','Редактировать','');
INSERT INTO lang VALUES ('edit_entry','ru','Редактировать запись %1','');
INSERT INTO lang VALUES ('enable_cookies','ru','Включить cookies?','');
INSERT INTO lang VALUES ('enable_cookies_comment','ru','Можно ли настройки пользователя менять при помощи cookies?(или настройки фильтров)?','');
INSERT INTO lang VALUES ('ended_sessions','ru','Завершенные сеансы','');
INSERT INTO lang VALUES ('enter_min_free','ru','Введите минимум свободного пространства на носителе для отображения:','');
INSERT INTO lang VALUES ('enter_new_medianr','ru','Пожалуйста введите номер фильма для нового ','');
INSERT INTO lang VALUES ('error_occured','ru','Ошибка phpVideoPro','');
INSERT INTO lang VALUES ('expire_cookies','ru','Время жизни cookies','');
INSERT INTO lang VALUES ('expire_cookies_comment','ru','Как долго cookies должен выжить в браузере пользователя?','');
INSERT INTO lang VALUES ('farbe','ru','Цвет','');
INSERT INTO lang VALUES ('filter','ru','Фильтр','');
INSERT INTO lang VALUES ('filter_setup','ru','Настройки фильтра','');
INSERT INTO lang VALUES ('finnished','ru','Завершено','');
INSERT INTO lang VALUES ('first_name','ru','Имя','');
INSERT INTO lang VALUES ('fontsize_is_nan','ru','Размер шрифта нужно дать в числовых ценностяхn (то есть только цифры позволяются здесь).','');
INSERT INTO lang VALUES ('format','ru','Формат','');
INSERT INTO lang VALUES ('free','ru','Свободно','');
INSERT INTO lang VALUES ('free_space_on_media','ru','Следующие носители имеют по крайней мере %1 минуту в наличии свободного места:','');
INSERT INTO lang VALUES ('free_space_title','ru','Свободного места на носителе','');
INSERT INTO lang VALUES ('fsk_is_nan','ru','PG нужно дать в числовых ценностяхn (то есть только цифры позволяются здесь). Щелкните изображением информации рядом с PG для большего количества деталей.','');
INSERT INTO lang VALUES ('general','ru','Общее','');
INSERT INTO lang VALUES ('goto_entry','ru','Перейти к записи:','');
INSERT INTO lang VALUES ('grant_filter_desc','ru','Показ делает запись от','');
INSERT INTO lang VALUES ('graphic_file','ru','Графические данные','');
INSERT INTO lang VALUES ('help','ru','Помощь','');
INSERT INTO lang VALUES ('help_about','ru','О','');
INSERT INTO lang VALUES ('help_for_block','ru','Помощь для этого блока','');
INSERT INTO lang VALUES ('hide_cat','ru','Скрывать категорию','');
INSERT INTO lang VALUES ('highest_db_entries','ru','самые высокие вхождения в базе данных','');
INSERT INTO lang VALUES ('history','ru','История','');
INSERT INTO lang VALUES ('hit_back_to_correct','ru','Нажмите кнопку \"Назад\", чтобы исправить ошибку.','');
INSERT INTO lang VALUES ('hour','ru','Час','');
INSERT INTO lang VALUES ('hours','ru','Часов','');
INSERT INTO lang VALUES ('howto','ru','Как...','');
INSERT INTO lang VALUES ('howto_help','ru','Как создать файл помощи','');
INSERT INTO lang VALUES ('howto_label','ru','How to create/configure label templates','');
INSERT INTO lang VALUES ('howto_lang','ru','Как создать файл с новым языком интерфейса','');
INSERT INTO lang VALUES ('howto_templates','ru','Как создавать новый набор шаблона','');
INSERT INTO lang VALUES ('id_is_nan','ru','ID должен быть числовым!n(то есть только цифры позволяются)','');
INSERT INTO lang VALUES ('imdbsearch','ru','Восстановите детали фильма от IMDB','');
INSERT INTO lang VALUES ('imdb_cache_dir','ru','Справочник, чтобы хранить Тайник IMDB','');
INSERT INTO lang VALUES ('imdb_cache_enable','ru','Позволите кэширование данных IMDB?','');
INSERT INTO lang VALUES ('imdb_cache_expire','ru','Произведите чистку тайника IMDB','');
INSERT INTO lang VALUES ('imdb_cache_use','ru','Использование припрятало данные про запас относительно новых запросов?','');
INSERT INTO lang VALUES ('imdb_image_files','ru','IMDB иконыйе файлы','');
INSERT INTO lang VALUES ('imdb_title_search','ru','Искать фильм на IMDB','');
INSERT INTO lang VALUES ('imdb_transfer2edit','ru','Данные передачи к редактирующемуся экрану','');
INSERT INTO lang VALUES ('imdb_tx','ru','Данные, чтобы перейти от IMDB','');
INSERT INTO lang VALUES ('imdb_txwin_autoclose','ru','Автоматически закройте окно поиска на передаче данных?','');
INSERT INTO lang VALUES ('imdb_txwin_autoclose_comment','ru','Когда Вы получили все необходимые данные от IMDB и передали их вашему редактировать форму, окно поиска больше не необходимо. Однако, Вы можете хотеть держать это для ссылки или других причин.','');
INSERT INTO lang VALUES ('imdb_tx_actor','ru','Актеры','');
INSERT INTO lang VALUES ('imdb_tx_cat','ru','Категории','');
INSERT INTO lang VALUES ('imdb_tx_comment','ru','Когда добавление/редактирование фильм с особенностью IMDB: какую информацию Вы хотите передать базе данных phpVideoPro по умолчанию?','');
INSERT INTO lang VALUES ('imdb_tx_comments','ru','Комментарии','');
INSERT INTO lang VALUES ('imdb_tx_country','ru','Страна','');
INSERT INTO lang VALUES ('imdb_tx_director','ru','Режиссер','');
INSERT INTO lang VALUES ('imdb_tx_length','ru','Продолжительность','');
INSERT INTO lang VALUES ('imdb_tx_music','ru','Композиторы','');
INSERT INTO lang VALUES ('imdb_tx_title','ru','Название','');
INSERT INTO lang VALUES ('imdb_tx_year','ru','Год','');
INSERT INTO lang VALUES ('imdb_url','ru','Участок IMDB, чтобы использовать','');
INSERT INTO lang VALUES ('imdb_url2','ru','Альтернативный участок IMDB','');
INSERT INTO lang VALUES ('imp_errors','ru','Импорт %2 отчетов закончился с %1 ошибкой.','');
INSERT INTO lang VALUES ('imp_success','ru','Импорт %1 отчета, успешно законченного.','');
INSERT INTO lang VALUES ('incomplete_date','ru','Если Вы не знаете точную дату, но - например - только, что Вы приобретали это в году 2000, ноли замены для неизвестных данных - в нашем примере, дата должна напомнить \"00\" \"00\" \"2000\".','');
INSERT INTO lang VALUES ('index','ru','Индекс','');
INSERT INTO lang VALUES ('info_common','ru','Общая информация','');
INSERT INTO lang VALUES ('info_common_info','ru','<DIV ALIGN=\"center\">Это phpVideoPro версия %1, бегущего на %2.</DIV>','');
INSERT INTO lang VALUES ('info_noupdate','ru','<DIV ALIGN=\"center\">Установленная версия phpVideoPro (%1) является недавней - нет никакой более новой версии, доступной для разгрузки. Чтобы загружать архив, установленной версии, пожалуйста следуйте за <A HREF=\"http://www.qumran.org/homes/izzy/software/get_update.php?program=pvp\" TARGET=\"_blank\">эта связь</A>.</DIV>','');
INSERT INTO lang VALUES ('info_update','ru','Обновить информацию','');
INSERT INTO lang VALUES ('input_errors_occured','ru','phpVideoPro столкнулся с %1 проблемой, обрабатывая ввод:','');
INSERT INTO lang VALUES ('intro','ru','Интро','');
INSERT INTO lang VALUES ('intro_usage_title','ru','Введение для новых пользователей','');
INSERT INTO lang VALUES ('invalid_backup_dir','ru','Конфигурируемый перечень обеспечения не существует.','');
INSERT INTO lang VALUES ('invalid_media_nr','ru','MediaNr, который определили, является или неполным или недействительным. Должны определить <b>цифры</b> в <b>оба</b> области MediaNr.','');
INSERT INTO lang VALUES ('in_list','ru','в Списке','');
INSERT INTO lang VALUES ('is_rw','ru','перезаписываемый','');
INSERT INTO lang VALUES ('label','ru','Наклейка','');
INSERT INTO lang VALUES ('labels','ru','Наклейки','');
INSERT INTO lang VALUES ('labeltype','ru','Тип наклейки','');
INSERT INTO lang VALUES ('language_settings','ru','Настройки языка','');
INSERT INTO lang VALUES ('lang_ab','ru','Абхазий','');
INSERT INTO lang VALUES ('lang_af','ru','Африкаанс','');
INSERT INTO lang VALUES ('lang_am','ru','Aмхарский','');
INSERT INTO lang VALUES ('lang_ar','ru','Aрабский','');
INSERT INTO lang VALUES ('lang_ay','ru','Aзербайджаний','');
INSERT INTO lang VALUES ('lang_az','ru','Азербайджаний','');
INSERT INTO lang VALUES ('lang_ba','ru','Башкирий','');
INSERT INTO lang VALUES ('lang_be','ru','Белорусский','');
INSERT INTO lang VALUES ('lang_bg','ru','Болгарский','');
INSERT INTO lang VALUES ('lang_bh','ru','Бихари','');
INSERT INTO lang VALUES ('lang_bo','ru','Тибетский','');
INSERT INTO lang VALUES ('lang_br','ru','Бретонский','');
INSERT INTO lang VALUES ('lang_co','ru','Корсиканский','');
INSERT INTO lang VALUES ('lang_cs','ru','Чешский','');
INSERT INTO lang VALUES ('lang_da','ru','Датский','');
INSERT INTO lang VALUES ('lang_de','ru','Немецкий','');
INSERT INTO lang VALUES ('lang_el','ru','Греческий','');
INSERT INTO lang VALUES ('lang_en','ru','Английский','');
INSERT INTO lang VALUES ('lang_eo','ru','Эсперанто','');
INSERT INTO lang VALUES ('lang_es','ru','Испанский','');
INSERT INTO lang VALUES ('lang_et','ru','Эстонский','');
INSERT INTO lang VALUES ('lang_eu','ru','Баск','');
INSERT INTO lang VALUES ('lang_fa','ru','Персидский','');
INSERT INTO lang VALUES ('lang_fi','ru','Финский','');
INSERT INTO lang VALUES ('lang_fj','ru','Фиджи','');
INSERT INTO lang VALUES ('lang_fr','ru','Французский','');
INSERT INTO lang VALUES ('lang_fy','ru','Фризский','');
INSERT INTO lang VALUES ('lang_ga','ru','Ирландский','');
INSERT INTO lang VALUES ('lang_gd','ru','Гэльский','');
INSERT INTO lang VALUES ('lang_gn','ru','Гуарани','');
INSERT INTO lang VALUES ('lang_ha','ru','Хауса','');
INSERT INTO lang VALUES ('lang_hi','ru','Хинди','');
INSERT INTO lang VALUES ('lang_hr','ru','Хорватски','');
INSERT INTO lang VALUES ('lang_hu','ru','Венгрерски','');
INSERT INTO lang VALUES ('lang_hy','ru','Армянский','');
INSERT INTO lang VALUES ('lang_ia','ru','Интерлингва','');
INSERT INTO lang VALUES ('lang_in','ru','Индонезиец','');
INSERT INTO lang VALUES ('lang_is','ru','Исландский','');
INSERT INTO lang VALUES ('lang_it','ru','Итальянский','');
INSERT INTO lang VALUES ('lang_iw','ru','Еврейский','');
INSERT INTO lang VALUES ('lang_ja','ru','Японский','');
INSERT INTO lang VALUES ('lang_ji','ru','Идиш','');
INSERT INTO lang VALUES ('lang_jw','ru','Яванецкий','');
INSERT INTO lang VALUES ('lang_ka','ru','Грузинский','');
INSERT INTO lang VALUES ('lang_kk','ru','Казахский','');
INSERT INTO lang VALUES ('lang_kl','ru','Гринландик','');
INSERT INTO lang VALUES ('lang_km','ru','Кампучиецкий','');
INSERT INTO lang VALUES ('lang_kn','ru','Канадски','');
INSERT INTO lang VALUES ('lang_ko','ru','Корейский','');
INSERT INTO lang VALUES ('lang_ks','ru','Кашимирский','');
INSERT INTO lang VALUES ('lang_ku','ru','Курдский','');
INSERT INTO lang VALUES ('lang_kw','ru','Корнуоллский','');
INSERT INTO lang VALUES ('lang_ky','ru','Киргизский','');
INSERT INTO lang VALUES ('lang_la','ru','Латинский','');
INSERT INTO lang VALUES ('lang_lt','ru','Литовецкий','');
INSERT INTO lang VALUES ('lang_lv','ru','Латышский','');
INSERT INTO lang VALUES ('lang_mg','ru','Малагасийский','');
INSERT INTO lang VALUES ('lang_mi','ru','Маори','');
INSERT INTO lang VALUES ('lang_mk','ru','Македонский','');
INSERT INTO lang VALUES ('lang_ml','ru','Малайялам','');
INSERT INTO lang VALUES ('lang_mn','ru','Монгольский','');
INSERT INTO lang VALUES ('lang_mo','ru','Молдавский','');
INSERT INTO lang VALUES ('lang_mr','ru','Маратхи','');
INSERT INTO lang VALUES ('lang_ms','ru','Малайский','');
INSERT INTO lang VALUES ('lang_mt','ru','Мальтийски','');
INSERT INTO lang VALUES ('lang_my','ru','Бирманецкий','');
INSERT INTO lang VALUES ('lang_na','ru','Науру','');
INSERT INTO lang VALUES ('lang_ne','ru','Непалецкий','');
INSERT INTO lang VALUES ('lang_nl','ru','Голландский','');
INSERT INTO lang VALUES ('lang_no','ru','Норвежский','');
INSERT INTO lang VALUES ('lang_or','ru','Ория','');
INSERT INTO lang VALUES ('lang_pa','ru','Панджаби','');
INSERT INTO lang VALUES ('lang_pi','ru','Пали','');
INSERT INTO lang VALUES ('lang_pl','ru','Польский','');
INSERT INTO lang VALUES ('lang_pt','ru','Португалецкий','');
INSERT INTO lang VALUES ('lang_qu','ru','Кечуа','');
INSERT INTO lang VALUES ('lang_ro','ru','Румынский','');
INSERT INTO lang VALUES ('lang_ru','ru','Русский','');
INSERT INTO lang VALUES ('lang_sa','ru','Санскрит','');
INSERT INTO lang VALUES ('lang_sc','ru','Сардинский','');
INSERT INTO lang VALUES ('lang_sh','ru','Сербско-хорватский','');
INSERT INTO lang VALUES ('lang_si','ru','Сингалецкий','');
INSERT INTO lang VALUES ('lang_sk','ru','Словакский','');
INSERT INTO lang VALUES ('lang_sl','ru','Словенский','');
INSERT INTO lang VALUES ('lang_sm','ru','Самоанский','');
INSERT INTO lang VALUES ('lang_sn','ru','Шона','');
INSERT INTO lang VALUES ('lang_so','ru','Сомалийски','');
INSERT INTO lang VALUES ('lang_sq','ru','Албанский','');
INSERT INTO lang VALUES ('lang_sr','ru','Сербский','');
INSERT INTO lang VALUES ('lang_su','ru','Суданецкий','');
INSERT INTO lang VALUES ('lang_sv','ru','Шведский','');
INSERT INTO lang VALUES ('lang_sw','ru','Суахили','');
INSERT INTO lang VALUES ('lang_ta','ru','Тамильский','');
INSERT INTO lang VALUES ('lang_te','ru','Тегалу','');
INSERT INTO lang VALUES ('lang_tg','ru','Таджик','');
INSERT INTO lang VALUES ('lang_th','ru','Тайландский','');
INSERT INTO lang VALUES ('lang_ti','ru','Тигринья','');
INSERT INTO lang VALUES ('lang_tk','ru','Туркменский','');
INSERT INTO lang VALUES ('lang_tl','ru','Тагальский','');
INSERT INTO lang VALUES ('lang_to','ru','Тонга','');
INSERT INTO lang VALUES ('lang_tr','ru','Турецкий','');
INSERT INTO lang VALUES ('lang_tt','ru','Татарский','');
INSERT INTO lang VALUES ('lang_tw','ru','Твай','');
INSERT INTO lang VALUES ('lang_uk','ru','Украинский','');
INSERT INTO lang VALUES ('lang_ur','ru','Урду','');
INSERT INTO lang VALUES ('lang_uz','ru','Узбекский','');
INSERT INTO lang VALUES ('lang_vi','ru','Вьетнамецкий','');
INSERT INTO lang VALUES ('lang_vo','ru','Волапюк','');
INSERT INTO lang VALUES ('lang_yo','ru','Йоруба','');
INSERT INTO lang VALUES ('lang_zh','ru','Китайский','');
INSERT INTO lang VALUES ('lang_zu','ru','Зулус','');
INSERT INTO lang VALUES ('last_entry','ru','Последний вход','');
INSERT INTO lang VALUES ('last_medianr','ru','Самое высокое число для этого типа носителя - теперь:','');
INSERT INTO lang VALUES ('layout_label','ru','Выбрал Шаблон','');
INSERT INTO lang VALUES ('left_offset','ru','Левое смещение','');
INSERT INTO lang VALUES ('length','ru','Продолжительность','');
INSERT INTO lang VALUES ('lentto','ru','Предоставленный','');
INSERT INTO lang VALUES ('len_is_nan','ru','Отобранная ценность для Длины не является числовой,n но phpVideoPro требует числовой ценности.','');
INSERT INTO lang VALUES ('lines_per_page','ru','Строк на странице','');
INSERT INTO lang VALUES ('lines_per_page_comment','ru','Это - для функций печати, чтобы определить, сколько линий текста соответствует на одном листе бумаги.','');
INSERT INTO lang VALUES ('line_count','ru','Строки','');
INSERT INTO lang VALUES ('list','ru','Список','');
INSERT INTO lang VALUES ('listgen','ru','Генератор списков','');
INSERT INTO lang VALUES ('lists','ru','Списки','');
INSERT INTO lang VALUES ('local_image_files','ru','Местныйе иконыйе файлы','');
INSERT INTO lang VALUES ('login','ru','Логин','');
INSERT INTO lang VALUES ('loginpwd_whitespace','ru','Логин и/или Пароль содержат места. Это не действительно.','');
INSERT INTO lang VALUES ('login_failed','ru','Ошибка! Неверен пароль или указанная учетная запись не существует.<P />','');
INSERT INTO lang VALUES ('login_required','ru','Ваши привилегии не достаточны для требуемого действия. Вы можете логин с соответствующим счетом теперь.','');
INSERT INTO lang VALUES ('logout_user','ru','Зарегистрирован как \"%1\". <A HREF=\"%2\">Выйти</A>','');
INSERT INTO lang VALUES ('lower_left_corner','ru','понизьте левый угол (x/y)','');
INSERT INTO lang VALUES ('max','ru','макс.','');
INSERT INTO lang VALUES ('max_fontsize','ru','Максимальный размер шрифта','');
INSERT INTO lang VALUES ('media','ru','Носитель','');
INSERT INTO lang VALUES ('medialength','ru','Длина носителя','');
INSERT INTO lang VALUES ('medialist','ru','Список носителей','');
INSERT INTO lang VALUES ('medialist_alpha','ru','Список носителей в алфавитном порядке','');
INSERT INTO lang VALUES ('medialist_num','ru','Список носителей в числовом порядке','');
INSERT INTO lang VALUES ('medianr','ru','Номер Носителя','');
INSERT INTO lang VALUES ('medianr_is_nan','ru','MediaNr должен быть числовым n (то есть буквы, и специальные литеры не позволяются).','');
INSERT INTO lang VALUES ('mediatype','ru','Тип Носителя','');
INSERT INTO lang VALUES ('media_change','ru','Изменить Номер Носителя','');
INSERT INTO lang VALUES ('media_copy','ru','Копировать данные на Номер Носителя','');
INSERT INTO lang VALUES ('media_info','ru','Информация носителя','');
INSERT INTO lang VALUES ('medium','ru','Носитель','');
INSERT INTO lang VALUES ('medium_deleted','ru','Нет больше кинофильмов на этой носители - удаленной носитель','');
INSERT INTO lang VALUES ('medium_not_deleted','ru','Носитель не удален','');
INSERT INTO lang VALUES ('medium_no_access','ru','Жаль: Эта носитель или не существует, или пуста, или разрешение получить доступ к его содержанию не даются.','');
INSERT INTO lang VALUES ('medium_overview','ru','Обзор %1','');
INSERT INTO lang VALUES ('menues','ru','Меню','');
INSERT INTO lang VALUES ('min','ru','мин.','');
INSERT INTO lang VALUES ('minute_abbrev','ru','мин.','');
INSERT INTO lang VALUES ('month','ru','Месяц','');
INSERT INTO lang VALUES ('movies','ru','Фильмы','');
INSERT INTO lang VALUES ('movies_left_in_cat','ru','Категория %1 все еще содержит %2 фильм(ы) и следовательно не может быть удалена. Жаль.','');
INSERT INTO lang VALUES ('movies_left_reference','ru','Этот пункт не может быть удален: есть %1 фильм(ы) в ДБ, ссылающемся на это.','');
INSERT INTO lang VALUES ('movie_color_default','ru','Формат цвета фильма по умолчанию','');
INSERT INTO lang VALUES ('movie_color_default_comment','ru','Это будет заданный цветной формат нового входа.','');
INSERT INTO lang VALUES ('movie_lang_default','ru','Звуковой язык по умолчанию для новых фильмов','');
INSERT INTO lang VALUES ('movie_lang_default_comment','ru','Это - язык заданной величины, добавляя новые фильмы.','');
INSERT INTO lang VALUES ('movie_onlabel_default','ru','Стандарт на Label Info','');
INSERT INTO lang VALUES ('movie_onlabel_default_comment','ru','Стандарт для новых пунктов: должен информация для этого кино быть включенным, когда ярлык(и) для этой среды произведен?','');
INSERT INTO lang VALUES ('movie_tone_default','ru','Формат звука фильма по умолчанию','');
INSERT INTO lang VALUES ('movie_tone_default_comment','ru','Это будет заданный звуковой формат нового входа.','');
INSERT INTO lang VALUES ('music','ru','Композитор','');
INSERT INTO lang VALUES ('music_list','ru','Список композиторов','');
INSERT INTO lang VALUES ('name','ru','Имя','');
INSERT INTO lang VALUES ('name_not_string','ru','Одно из введенных названий содержит недействительные характеры (чтобы предотвратить кодовую инъекцию, только букбы, цифры и \"-\" позволяются).','');
INSERT INTO lang VALUES ('never','ru','никогда','');
INSERT INTO lang VALUES ('new_disktype','ru','Новый Дисковый Тип','');
INSERT INTO lang VALUES ('new_medianr','ru','Новый Номер Носителя','');
INSERT INTO lang VALUES ('new_movie_on','ru','Новый %1','');
INSERT INTO lang VALUES ('no','ru','Нет','');
INSERT INTO lang VALUES ('nobody_named','ru','Нет никакого другого фильма с критериями \"%1 названный %2 %3\" в этой БД, так что я удаляю этот пункт из %1\'s стола.','');
INSERT INTO lang VALUES ('none','ru','Ни один','');
INSERT INTO lang VALUES ('not_logged_in','ru','не заявлены','');
INSERT INTO lang VALUES ('not_ok','ru','Ошибка','');
INSERT INTO lang VALUES ('not_yet_implemented','ru','Не реализовано.','');
INSERT INTO lang VALUES ('no_add_lang','ru','Дополнительные языки не доступны.','');
INSERT INTO lang VALUES ('no_backup_avail','ru','Никакой резервный файл, доступный восстановить от.','');
INSERT INTO lang VALUES ('no_delete_permission','ru','Это носитель принадлежит другому пользователю. Удалите разрешение, не предоставлялся, жаль.','');
INSERT INTO lang VALUES ('no_entries_found','ru','Записи не найдены','');
INSERT INTO lang VALUES ('no_entry_in_tapelist','ru','Ошибка: никакой вход, найденный в списке ленты','');
INSERT INTO lang VALUES ('no_orphans_found','ru','Поздравления! У вас, кажется, (больше?) нет никакие \"трупи\" в ДБ.','');
INSERT INTO lang VALUES ('no_restore_file','ru','Жаль: отобранный файл больше не существует!','');
INSERT INTO lang VALUES ('no_space_of','ru','Нет никакого носитель с минимумом свободного места %1 минуты в БД.','');
INSERT INTO lang VALUES ('nr','ru','№','');
INSERT INTO lang VALUES ('of_aquiration','ru','поступление','');
INSERT INTO lang VALUES ('old_sessions','ru','Сессии, старше чем <INPUT NAME=\"%1\" VALUE=\"\" CLASS=\"yesnobutton\"> дни','');
INSERT INTO lang VALUES ('orig_disktype','ru','Оригинальный Дисковый Тип','');
INSERT INTO lang VALUES ('orig_medianr','ru','Исходный Номер Носителя','');
INSERT INTO lang VALUES ('orig_trans','ru','Оригинальный перевод (%1)','');
INSERT INTO lang VALUES ('orphans_found','ru','Найденный %1 сиротой:','');
INSERT INTO lang VALUES ('other_pages','ru','Другие страницы','');
INSERT INTO lang VALUES ('owner','ru','Владелец','');
INSERT INTO lang VALUES ('own_to_user','ru','Передача к','');
INSERT INTO lang VALUES ('password','ru','Пароль','');
INSERT INTO lang VALUES ('password_retype','ru','Еще раз пароль','');
INSERT INTO lang VALUES ('picture','ru','Формат цвета','');
INSERT INTO lang VALUES ('preferences','ru','Настройки','');
INSERT INTO lang VALUES ('print','ru','Печать','');
INSERT INTO lang VALUES ('printer','ru','Принтер','');
INSERT INTO lang VALUES ('printer_add_failed','ru','Ошибка произошла, добавляя этот принтер.','');
INSERT INTO lang VALUES ('printer_add_success','ru','Принтер успешно добавил.','');
INSERT INTO lang VALUES ('printer_name','ru','Имя','');
INSERT INTO lang VALUES ('printer_upd_failed','ru','Обновление терпело неудачу для следующих принтеров: %1','');
INSERT INTO lang VALUES ('print_label','ru','Печать наклейки:','');
INSERT INTO lang VALUES ('pslabel','ru','Наклейки PS','');
INSERT INTO lang VALUES ('pstpl_name','ru','Имя Шаблона','');
INSERT INTO lang VALUES ('pstpl_type','ru','Тип Шаблона','');
INSERT INTO lang VALUES ('read_access','ru','Может просматривать записи','');
INSERT INTO lang VALUES ('read_access_short','ru','чит','');
INSERT INTO lang VALUES ('recalc_free','ru','Перевычисление остающийся свободным местом на этом носителе','');
INSERT INTO lang VALUES ('refresh_lang','ru','Обновить язык','');
INSERT INTO lang VALUES ('refresh_lang_comment','ru','Вставлять фразы от языкового файла в ДБ','');
INSERT INTO lang VALUES ('remove_cat','ru','Удалите категорию','');
INSERT INTO lang VALUES ('remove_empty_media','ru','Удаляй пустые носители','');
INSERT INTO lang VALUES ('remove_empty_media_comment','ru','Носитель должен быть удален от свободного космического обслуживания, когда последний фильм удален из этого?','');
INSERT INTO lang VALUES ('restore_db_internal','ru','Восстановите от резервного файла PVP','');
INSERT INTO lang VALUES ('restore_db_movie_internal','ru','Восстановите фильмы от резервного файла PVP','');
INSERT INTO lang VALUES ('rw_media','ru','Редактируемый носитель','');
INSERT INTO lang VALUES ('rw_media_comment','ru','Носители, чтобы поддержать свободное место (так как делать запись на них).','');
INSERT INTO lang VALUES ('s/w','ru','ч/б','');
INSERT INTO lang VALUES ('save_lang_file','ru','Сохранить перевод в файл','');
INSERT INTO lang VALUES ('scan_new_lang_comment','ru','(Если Вы создали ваш собственный языковой файл и помещали это в справочник установки, это скажет phpVideoPro искать это)','');
INSERT INTO lang VALUES ('scan_new_lang_files','ru','Искать файлы с новыми языками?','');
INSERT INTO lang VALUES ('screen','ru','Формат экрана','');
INSERT INTO lang VALUES ('search','ru','Поиск','');
INSERT INTO lang VALUES ('search_movie','ru','Поиск фильма','');
INSERT INTO lang VALUES ('select_add_lang','ru','Выберите дополнительный язык для установки','');
INSERT INTO lang VALUES ('select_add_lang_comment','ru','(Английский язык уже установлен и всегда будет - см. затем пункт. Для других языков, которые уже установлены, см. затем пункт, также.)','');
INSERT INTO lang VALUES ('select_primary_lang','ru','Выберите основной язык','');
INSERT INTO lang VALUES ('select_primary_lang_comment','ru','(для недостающих фраз, всегда будет отступление к английскому языку)','');
INSERT INTO lang VALUES ('sel_target_lang','ru','Выберите язык для перевода:','');
INSERT INTO lang VALUES ('session','ru','Сессия','');
INSERT INTO lang VALUES ('session_expired','ru','Время Вашей сессии истекло. Пожалуйста зарегистрируйтесь в системе еще раз.','');
INSERT INTO lang VALUES ('session_purgetime','ru','Перерыв бездействующая сессия после...','');
INSERT INTO lang VALUES ('session_purgetime_comment','ru','Как долго сессия должна остаться действительной без пользовательской деятельности?','');
INSERT INTO lang VALUES ('sess_dla','ru','Последний доступ','');
INSERT INTO lang VALUES ('sess_end','ru','Законченный','');
INSERT INTO lang VALUES ('sess_id','ru','Сессия ID','');
INSERT INTO lang VALUES ('sess_ip','ru','Удаленный IP','');
INSERT INTO lang VALUES ('sess_start','ru','Запущенный','');
INSERT INTO lang VALUES ('set_filter','ru','Задать фильтр','');
INSERT INTO lang VALUES ('site_info','ru','Информация о сайте','');
INSERT INTO lang VALUES ('site_info_comment','ru','Информация о сайте отображаемая в заголовке браузера','');
INSERT INTO lang VALUES ('skip_intro','ru','Пропустите введение новичка?','');
INSERT INTO lang VALUES ('skip_intro_comment','ru','Пропускать ли текст введения на странице начала','');
INSERT INTO lang VALUES ('source','ru','Источник','');
INSERT INTO lang VALUES ('staff','ru','Персонал','');
INSERT INTO lang VALUES ('start_page','ru','Начальная страница','');
INSERT INTO lang VALUES ('start_pvp','ru','Запустить phpVideoPro','');
INSERT INTO lang VALUES ('state_active','ru','Активизированный','');
INSERT INTO lang VALUES ('state_inactive','ru','Дезактивированный','');
INSERT INTO lang VALUES ('stats','ru','Статистика','');
INSERT INTO lang VALUES ('stat_categories','ru','Катагории (использованные/все)','');
INSERT INTO lang VALUES ('stat_counts','ru','Количество','');
INSERT INTO lang VALUES ('stat_ranks','ru','Ранжирование','');
INSERT INTO lang VALUES ('storeplace','ru','Амбар','');
INSERT INTO lang VALUES ('submit','ru','Подтвердить','');
INSERT INTO lang VALUES ('subtitle','ru','Субтитры','');
INSERT INTO lang VALUES ('sure_to_delete','ru','Вы уверены, что хотите удалить все данные за %1 ','');
INSERT INTO lang VALUES ('tapelist_update_failed','ru','Неудавшийся список ленты обновления','');
INSERT INTO lang VALUES ('taperest','ru','Управляйте остающимся временем','');
INSERT INTO lang VALUES ('taperest_absolute','ru','Сохранение времени (абсолютный)','');
INSERT INTO lang VALUES ('taperest_filtered','ru','Сохранение времени (фильтровать)','');
INSERT INTO lang VALUES ('target_trans','ru','Перевод для вашего выходного языка (%1)','');
INSERT INTO lang VALUES ('techdata','ru','Технические Данные','');
INSERT INTO lang VALUES ('template_file','ru','Шаблоны файл','');
INSERT INTO lang VALUES ('template_set','ru','Шаблон','');
INSERT INTO lang VALUES ('time_left','ru','%1 минут осталось','');
INSERT INTO lang VALUES ('title','ru','Название','');
INSERT INTO lang VALUES ('title_not_string','ru','Введенное название содержит недействительные характеры (чтобы предотвратить кодовую инъекцию, только букбы, цифры и \"-\" позволяются).','');
INSERT INTO lang VALUES ('tone','ru','Звук','');
INSERT INTO lang VALUES ('tplset_applicat','ru','Шаблон \"Applicat\"','');
INSERT INTO lang VALUES ('trans_code','ru','Код перевода','');
INSERT INTO lang VALUES ('unit','ru','Единица','');
INSERT INTO lang VALUES ('unknown','ru','неизвестно','');
INSERT INTO lang VALUES ('unlink_file_failed','ru','Подведенное удаление - проверяет разрешения или удаляет вручную.','');
INSERT INTO lang VALUES ('unset_filter','ru','Сбросить фильтр','');
INSERT INTO lang VALUES ('update','ru','Обновить','');
INSERT INTO lang VALUES ('update_failed','ru','Ошибка при обновлении записи','');
INSERT INTO lang VALUES ('update_failed_permission','ru','Обновление терпело неудачу из-за недостающих разрешений','');
INSERT INTO lang VALUES ('update_success','ru','Обновление прошло успешно','');
INSERT INTO lang VALUES ('upd_access','ru','Может изменять существующие записи','');
INSERT INTO lang VALUES ('upd_access_short','ru','изм','');
INSERT INTO lang VALUES ('upper_right_corner','ru','Верхний Правильный Угол (x/y)','');
INSERT INTO lang VALUES ('user','ru','Пользователь','');
INSERT INTO lang VALUES ('user_create_login_required','ru','Вы должны определить название логина для пользователя!','');
INSERT INTO lang VALUES ('user_deleted','ru','Успешно удален пользователь #%1, \"%2\" (%3)','');
INSERT INTO lang VALUES ('user_delete_failed','ru','Ошибка удаления пользователя #%1, \"%2\" (%3)','');
INSERT INTO lang VALUES ('user_delete_report','ru','Результат удаления пользователя','');
INSERT INTO lang VALUES ('user_grants','ru','Разрешения на собственных отчетах','');
INSERT INTO lang VALUES ('user_update_failed','ru','Ошибка изменения пользователей: %1','');
INSERT INTO lang VALUES ('view','ru','Просмотр','');
INSERT INTO lang VALUES ('view_entry','ru','Просмотреть запись %1','');
INSERT INTO lang VALUES ('warning','ru','предупреждение','');
INSERT INTO lang VALUES ('week','ru','Неделя','');
INSERT INTO lang VALUES ('welcome','ru','Добро пожаловать в phpVideoPro','');
INSERT INTO lang VALUES ('wrong_date','ru','Указанная Вами дата %1 неверна (%2). Для ввода даты используйте только цифры. В первом поле задается день, во втором месяц и в третьем год. Если Вы не знаете точную дату, введите нули, например, \"00\" \"02\" \"2002\" - \"февраль 2002\", или \"00\" \"00\" \"0000\" -  \"когда-либо\".','');
INSERT INTO lang VALUES ('xfer_unknown_filetype','ru','Этот тип резервного файла (все же) не обработан phpVideoPro.','');
INSERT INTO lang VALUES ('year','ru','Год','');
INSERT INTO lang VALUES ('yes','ru','Да','');
