# ========================================================
# Russian Language File created by phpVideoPro v0.5.4p2
# ========================================================

UPDATE languages SET charset='koi8-r' WHERE lang_id='ru';
INSERT INTO lang VALUES ('about','ru','О...','');
INSERT INTO lang VALUES ('actions','ru','Действия','');
INSERT INTO lang VALUES ('actor','ru','Актер','');
INSERT INTO lang VALUES ('actors','ru','Актеры','');
INSERT INTO lang VALUES ('actors_list','ru','Список актеров','');
INSERT INTO lang VALUES ('actor_persons','ru','Актеры','');
INSERT INTO lang VALUES ('add_access','ru','Может добавлять новые записи','');
INSERT INTO lang VALUES ('add_access_short','ru','доб','');
INSERT INTO lang VALUES ('add_entry','ru','Добавить запись','');
INSERT INTO lang VALUES ('add_user','ru','Добавить пользователя','');
INSERT INTO lang VALUES ('admin','ru','Админ','');
INSERT INTO lang VALUES ('admin_access','ru','Имеет доступ к меню администратора','');
INSERT INTO lang VALUES ('admin_access_short','ru','адм','');
INSERT INTO lang VALUES ('admin_cats','ru','Категории администратора','');
INSERT INTO lang VALUES ('admin_disktypes','ru','Редактировать тип диска','');
INSERT INTO lang VALUES ('admin_filter','ru','Установки фильтра по умолчанию','');
INSERT INTO lang VALUES ('admin_movietech','ru','Редактировать данные фильма','');
INSERT INTO lang VALUES ('admin_orphans','ru','Removal of orphaned entries','');
INSERT INTO lang VALUES ('admin_printers','ru','Редактировать принтеры','');
INSERT INTO lang VALUES ('admin_pstemplates','ru','Редактировать шаблоны PSLabel ','');
INSERT INTO lang VALUES ('admin_sessions','ru','Управление сессиями','');
INSERT INTO lang VALUES ('admin_translations','ru','Перевод интерфейса','');
INSERT INTO lang VALUES ('admin_useredit','ru','Редактировать пользовательскую запись','');
INSERT INTO lang VALUES ('admin_users','ru','Пользователи','');
INSERT INTO lang VALUES ('back','ru','Назад','');
INSERT INTO lang VALUES ('backup_db','ru','Резервная копия БД','');
INSERT INTO lang VALUES ('backup_db_complete','ru','Редактировать ВСЮ БД(включая технические данные и и предпочтения)','');
INSERT INTO lang VALUES ('backup_db_moviedel','ru','Откат данных исключительно относящихся к фильму 
 и предложение стереть старые данные перед вставкой новых(сохранённых)данных','');
INSERT INTO lang VALUES ('backup_db_movies','ru','Откат данных исключительно относящихся к фильму
 (фильм,актёры и т.д.)','');
INSERT INTO lang VALUES ('backup_db_runscript','ru','Хотите создать скрипт сейчас?','');
INSERT INTO lang VALUES ('cancel','ru','Отменить','');
INSERT INTO lang VALUES ('categories','ru','Категории','');
INSERT INTO lang VALUES ('category','ru','Категория','');
INSERT INTO lang VALUES ('catlist_alpha','ru','Список фильмов в алфавитном порядке,сортировка по категориям','');
INSERT INTO lang VALUES ('cat_action','ru','Боевик','');
INSERT INTO lang VALUES ('cat_adventure','ru','Приключения','');
INSERT INTO lang VALUES ('cat_agents','ru','Агентский','');
INSERT INTO lang VALUES ('cat_animal','ru','Животное','');
INSERT INTO lang VALUES ('cat_animals','ru','Животные','');
INSERT INTO lang VALUES ('cat_bible','ru','Библия','');
INSERT INTO lang VALUES ('cat_biography','ru','Биография','');
INSERT INTO lang VALUES ('cat_camera','ru','Домашнее видео','');
INSERT INTO lang VALUES ('cat_cartoon','ru','Мультфильм','');
INSERT INTO lang VALUES ('cat_catastrophe','ru','Катастрофа','');
INSERT INTO lang VALUES ('cat_children','ru','Для детей','');
INSERT INTO lang VALUES ('cat_comedy','ru','Комедия','');
INSERT INTO lang VALUES ('cat_concert','ru','Концерт','');
INSERT INTO lang VALUES ('cat_crime','ru','Криминал','');
INSERT INTO lang VALUES ('cat_documentary','ru','Документация','');
INSERT INTO lang VALUES ('cat_drama','ru','Драма','');
INSERT INTO lang VALUES ('cat_fairytale','ru','Сказки','');
INSERT INTO lang VALUES ('cat_fantasy','ru','Фэнтэзи','');
INSERT INTO lang VALUES ('cat_handle_empty','ru','Пусто','');
INSERT INTO lang VALUES ('cat_history','ru','История','');
INSERT INTO lang VALUES ('cat_horror','ru','Ужасы','');
INSERT INTO lang VALUES ('cat_judaica','ru','Иудаика','');
INSERT INTO lang VALUES ('cat_love','ru','Любовные истории','');
INSERT INTO lang VALUES ('cat_melodrama','ru','Мелодрама','');
INSERT INTO lang VALUES ('cat_misc','ru','Разное','');
INSERT INTO lang VALUES ('cat_monumental','ru','Классика','');
INSERT INTO lang VALUES ('cat_music','ru','Музыка','');
INSERT INTO lang VALUES ('cat_musical','ru','Музыкальный','');
INSERT INTO lang VALUES ('cat_musicmovie','ru','Музыкальные фильмы','');
INSERT INTO lang VALUES ('cat_nature','ru','Природа','');
INSERT INTO lang VALUES ('cat_opera','ru','Опера','');
INSERT INTO lang VALUES ('cat_operetta','ru','Оперетта','');
INSERT INTO lang VALUES ('cat_party','ru','Вечеринка','');
INSERT INTO lang VALUES ('cat_problem','ru','Проблема','');
INSERT INTO lang VALUES ('cat_report','ru','Репортаж','');
INSERT INTO lang VALUES ('cat_satire','ru','Сатира','');
INSERT INTO lang VALUES ('cat_scary','ru','Ужасы','');
INSERT INTO lang VALUES ('cat_sf','ru','Научная фантастика','');
INSERT INTO lang VALUES ('cat_show','ru','Шоу','');
INSERT INTO lang VALUES ('cat_spy','ru','Шпионские фильмы','');
INSERT INTO lang VALUES ('cat_stage','ru','Сцена','');
INSERT INTO lang VALUES ('cat_thriller','ru','Триллер','');
INSERT INTO lang VALUES ('cat_trans_update_failed','ru','Updating failed for the translations of the following categories: %1','');
INSERT INTO lang VALUES ('cat_travesty','ru','Пародия','');
INSERT INTO lang VALUES ('cat_update_failed','ru','Происходит апдейт файлов в следующих категориях: %1','');
INSERT INTO lang VALUES ('cat_vacation','ru','Отпуск','');
INSERT INTO lang VALUES ('cat_videoclip','ru','Видео клип','');
INSERT INTO lang VALUES ('cat_war','ru','Военные фильмы','');
INSERT INTO lang VALUES ('cat_western','ru','Вестерн','');
INSERT INTO lang VALUES ('cat_westerncomedy','ru','Комедия-вестерн','');
INSERT INTO lang VALUES ('cat_xmas','ru','Рождественский','');
INSERT INTO lang VALUES ('change_disktype','ru','Изменить тип диска','');
INSERT INTO lang VALUES ('change_media_length','ru','Изменить размер носителя','');
INSERT INTO lang VALUES ('change_media_length_for','ru','Пожалуйста введите объем для %1','');
INSERT INTO lang VALUES ('change_nr','ru','Изменить Номер/Тип носителя %1','');
INSERT INTO lang VALUES ('change_rc','ru','Изменить код региона','');
INSERT INTO lang VALUES ('change_rc_for','ru','Изменить код региона на %1','');
INSERT INTO lang VALUES ('check_completed','ru','Проверка завершена','');
INSERT INTO lang VALUES ('check_media_delete','ru','Проверка,не пуст ли носитель','');
INSERT INTO lang VALUES ('close','ru','Закрыть','');
INSERT INTO lang VALUES ('colors','ru','Цвета','');
INSERT INTO lang VALUES ('comments','ru','Комментарии','');
INSERT INTO lang VALUES ('commercials','ru','Реклама','');
INSERT INTO lang VALUES ('composer','ru','Композиторы','');
INSERT INTO lang VALUES ('compose_person','ru','композитор','');
INSERT INTO lang VALUES ('compose_persons','ru','Композиторы','');
INSERT INTO lang VALUES ('configuration','ru','Настройки','');
INSERT INTO lang VALUES ('config_media','ru','Фильмы и носители','');
INSERT INTO lang VALUES ('confirm_delete','ru','Вы действительно хотите удалить эту запись?','');
INSERT INTO lang VALUES ('confirm_userdelete','ru','Вы сейчас удаляете пользователя #%1','');
INSERT INTO lang VALUES ('confirm_userdeletion','ru','Вы действительно хотите удалить пользователя \"%1\" (%2)?','');
INSERT INTO lang VALUES ('content','ru','Содержимое','');
INSERT INTO lang VALUES ('counter_start_stop','ru','Счетчик Старт/Стоп','');
INSERT INTO lang VALUES ('countries','ru','Страны','');
INSERT INTO lang VALUES ('country','ru','Страна','');
INSERT INTO lang VALUES ('create','ru','Создать','');
INSERT INTO lang VALUES ('create_success','ru','Запись успешно создана','');
INSERT INTO lang VALUES ('credits','ru','Отдельная благодарность','');
INSERT INTO lang VALUES ('cut_off','ru','За кадром','');
INSERT INTO lang VALUES ('data_access','ru','Доступ к данным','');
INSERT INTO lang VALUES ('date_format','ru','Формат даты','');
INSERT INTO lang VALUES ('date_format_comment','ru','Формат для отобрадения даты.','');
INSERT INTO lang VALUES ('date_rec','ru','Дата принята','');
INSERT INTO lang VALUES ('day','ru','День','');
INSERT INTO lang VALUES ('db_stats','ru','Статистика','');
INSERT INTO lang VALUES ('delete','ru','Удалить','');
INSERT INTO lang VALUES ('delete_lang','ru','Удалить язык','');
INSERT INTO lang VALUES ('delete_lang_comment','ru','Удалить все фразы на выбранном языке из базы данных.Вы не удаляете языковой файл,так что вы сможете вставить фразы позднее(если вы не удалите те весь файл)','');
INSERT INTO lang VALUES ('delete_orphans','ru','Удаление  %1 пустой ссылки(ок):','');
INSERT INTO lang VALUES ('delete_remaining','ru','удаление из БД данных, относящихся к этому фильму','');
INSERT INTO lang VALUES ('deleting_entry','ru','Удаление записи %1','');
INSERT INTO lang VALUES ('del_access','ru','Может удалять записи','');
INSERT INTO lang VALUES ('del_access_short','ru','уд','');
INSERT INTO lang VALUES ('desc_admin_orphans','ru','\"Пустые ссылки\" это данные без привязки,то есть: Актёры,режиссёры и/или сценаристы на которых нет ссылки.В основном так получается при изменении неправильно написанного названия фильма после его сохранения - и никогда после удаления данных фильма.Таким образом,полезно удалять эти данные:с одной стороны это сохраняет ресурсы,а с другой предотвращает замедление работы базы данных.','');
INSERT INTO lang VALUES ('director','ru','Режиссер','');
INSERT INTO lang VALUES ('directors','ru','Режиссеры','');
INSERT INTO lang VALUES ('directors_list','ru','Список режиссеров','');
INSERT INTO lang VALUES ('director_person','ru','режиссер','');
INSERT INTO lang VALUES ('director_persons','ru','Режиссеры','');
INSERT INTO lang VALUES ('dl_pvp_latest','ru','Загрузить последнюю версию','');
INSERT INTO lang VALUES ('edit','ru','Редактировать','');
INSERT INTO lang VALUES ('edit_entry','ru','Редактировать запись %1','');
INSERT INTO lang VALUES ('enable_cookies','ru','Включить cookies?','');
INSERT INTO lang VALUES ('enter_min_free','ru','Введите minimum of free space on medium to display:','');
INSERT INTO lang VALUES ('expire_cookies','ru','Время жизни cookies','');
INSERT INTO lang VALUES ('farbe','ru','Цвет','');
INSERT INTO lang VALUES ('filter','ru','Фильтр','');
INSERT INTO lang VALUES ('filter_setup','ru','Настройки фильтра','');
INSERT INTO lang VALUES ('finnished','ru','Завершено','');
INSERT INTO lang VALUES ('first_name','ru','Имя','');
INSERT INTO lang VALUES ('format','ru','Формат','');
INSERT INTO lang VALUES ('free','ru','Свободно','');
INSERT INTO lang VALUES ('free_space_title','ru','Свободного места на носителе','');
INSERT INTO lang VALUES ('goto_entry','ru','Перейти к записи:','');
INSERT INTO lang VALUES ('help','ru','Помощь','');
INSERT INTO lang VALUES ('help_about','ru','О','');
INSERT INTO lang VALUES ('history','ru','История','');
INSERT INTO lang VALUES ('hit_back_to_correct','ru','Нажмите кнопку \"Назад\", чтобы исправить ошибку.','');
INSERT INTO lang VALUES ('hour','ru','Час','');
INSERT INTO lang VALUES ('hours','ru','Часов','');
INSERT INTO lang VALUES ('howto','ru','Как...','');
INSERT INTO lang VALUES ('howto_help','ru','Как создать файл помощи','');
INSERT INTO lang VALUES ('howto_lang','ru','Как создать файл с новым языком интерфейса','');
INSERT INTO lang VALUES ('index','ru','Индекс','');
INSERT INTO lang VALUES ('info_common','ru','Общая информация','');
INSERT INTO lang VALUES ('info_update','ru','Обновить информацию','');
INSERT INTO lang VALUES ('intro','ru','Интро','');
INSERT INTO lang VALUES ('in_list','ru','в Списке','');
INSERT INTO lang VALUES ('is_rw','ru','перезаписываемый','');
INSERT INTO lang VALUES ('label','ru','Наклейка','');
INSERT INTO lang VALUES ('labels','ru','Наклейки','');
INSERT INTO lang VALUES ('labeltype','ru','Тип наклейки','');
INSERT INTO lang VALUES ('language_settings','ru','Настройки языка','');
INSERT INTO lang VALUES ('layout_label','ru','Chose Layout','');
INSERT INTO lang VALUES ('length','ru','Продолжительность','');
INSERT INTO lang VALUES ('lines_per_page','ru','Строк на странице','');
INSERT INTO lang VALUES ('line_count','ru','Строки','');
INSERT INTO lang VALUES ('list','ru','Список','');
INSERT INTO lang VALUES ('listgen','ru','Генератор списков','');
INSERT INTO lang VALUES ('lists','ru','Списки','');
INSERT INTO lang VALUES ('login','ru','Логин','');
INSERT INTO lang VALUES ('login_failed','ru','Ошибка! Неверен пароль или указанная учетная запись не существует.<P />','');
INSERT INTO lang VALUES ('logout_user','ru','Зарегистрирован как \"%1\". <A HREF=\"%2\">Выйти</A>','');
INSERT INTO lang VALUES ('max','ru','макс.','');
INSERT INTO lang VALUES ('max_fontsize','ru','Максимальный размер шрифта','');
INSERT INTO lang VALUES ('media','ru','Носитель','');
INSERT INTO lang VALUES ('medialength','ru','Длина носителя','');
INSERT INTO lang VALUES ('medialist','ru','Список носителей','');
INSERT INTO lang VALUES ('medialist_alpha','ru','Список носителей в алфавитном порядке','');
INSERT INTO lang VALUES ('medialist_num','ru','Список носителей в числовом порядке','');
INSERT INTO lang VALUES ('medianr','ru','Номер Носителя','');
INSERT INTO lang VALUES ('mediatype','ru','Тип Носителя','');
INSERT INTO lang VALUES ('media_change','ru','Изменить Номер Носителя','');
INSERT INTO lang VALUES ('media_copy','ru','Копировать данные на Номер Носителя','');
INSERT INTO lang VALUES ('medium','ru','Носитель','');
INSERT INTO lang VALUES ('medium_not_deleted','ru','Носитель не удален','');
INSERT INTO lang VALUES ('medium_overview','ru','Обзор %1','');
INSERT INTO lang VALUES ('menues','ru','Меню','');
INSERT INTO lang VALUES ('min','ru','мин.','');
INSERT INTO lang VALUES ('minute_abbrev','ru','мин.','');
INSERT INTO lang VALUES ('month','ru','Месяц','');
INSERT INTO lang VALUES ('movies','ru','Фильмы','');
INSERT INTO lang VALUES ('movie_color_default','ru','Формат цвета фильма по умолчанию','');
INSERT INTO lang VALUES ('movie_tone_default','ru','Формат звука фильма по умолчанию','');
INSERT INTO lang VALUES ('music','ru','Композитор','');
INSERT INTO lang VALUES ('music_list','ru','Список композиторов','');
INSERT INTO lang VALUES ('name','ru','Имя','');
INSERT INTO lang VALUES ('never','ru','никогда','');
INSERT INTO lang VALUES ('new_medianr','ru','новый Номер Носителя','');
INSERT INTO lang VALUES ('no','ru','Нет','');
INSERT INTO lang VALUES ('none','ru','Ни один','');
INSERT INTO lang VALUES ('not_ok','ru','Ошибка','');
INSERT INTO lang VALUES ('not_yet_implemented','ru','Не реализовано.','');
INSERT INTO lang VALUES ('no_add_lang','ru','Дополнительные языки не доступны.','');
INSERT INTO lang VALUES ('no_entries_found','ru','Записи не найдены','');
INSERT INTO lang VALUES ('nr','ru','Номер','');
INSERT INTO lang VALUES ('ok','ru','OK','');
INSERT INTO lang VALUES ('orig_medianr','ru','исходный Номер Носителя','');
INSERT INTO lang VALUES ('other_pages','ru','Другие страницы','');
INSERT INTO lang VALUES ('password','ru','Пароль','');
INSERT INTO lang VALUES ('password_retype','ru','Еще раз пароль','');
INSERT INTO lang VALUES ('picture','ru','Формат цвета','');
INSERT INTO lang VALUES ('preferences','ru','Настройки','');
INSERT INTO lang VALUES ('print','ru','Печать','');
INSERT INTO lang VALUES ('printer','ru','Принтер','');
INSERT INTO lang VALUES ('print_label','ru','Печать наклейкиl:','');
INSERT INTO lang VALUES ('read_access','ru','Может просматривать записи','');
INSERT INTO lang VALUES ('read_access_short','ru','чит','');
INSERT INTO lang VALUES ('refresh_lang','ru','Обновить язык','');
INSERT INTO lang VALUES ('rw_media','ru','Редактируемый носитель','');
INSERT INTO lang VALUES ('s/w','ru','ч/б','');
INSERT INTO lang VALUES ('save_lang_file','ru','Сохранить перевод в файл','');
INSERT INTO lang VALUES ('scan_new_lang_files','ru','Искать файлы с новыми языками?','');
INSERT INTO lang VALUES ('screen','ru','Формат экрана','');
INSERT INTO lang VALUES ('search','ru','Поиск','');
INSERT INTO lang VALUES ('search_movie','ru','Поиск фильма','');
INSERT INTO lang VALUES ('select_add_lang','ru','Выберите дополнительный язык для установки','');
INSERT INTO lang VALUES ('select_primary_lang','ru','Выберите основной язык','');
INSERT INTO lang VALUES ('select_primary_lang_comment','ru','(for missing phrases, there will always be a fall-back to English)','');
INSERT INTO lang VALUES ('sel_target_lang','ru','Выберите язык для перевода:','');
INSERT INTO lang VALUES ('session','ru','Сессия','');
INSERT INTO lang VALUES ('session_expired','ru','Время Вашей сессии истекло. Пожалуйста зарегистрируйтесь в системе еще раз.','');
INSERT INTO lang VALUES ('set_filter','ru','Задать фильтр','');
INSERT INTO lang VALUES ('site_info','ru','Информация о сайте','');
INSERT INTO lang VALUES ('site_info_comment','ru','Информация о сайте отображаемая в заголовке браузера','');
INSERT INTO lang VALUES ('source','ru','Источник','');
INSERT INTO lang VALUES ('staff','ru','Персонал','');
INSERT INTO lang VALUES ('start_page','ru','Начальная страница','');
INSERT INTO lang VALUES ('start_pvp','ru','Запустить phpVideoPro','');
INSERT INTO lang VALUES ('stats','ru','Статистика','');
INSERT INTO lang VALUES ('stat_categories','ru','Катагории (использованные/все)','');
INSERT INTO lang VALUES ('stat_counts','ru','Counts','');
INSERT INTO lang VALUES ('stat_ranks','ru','Ranking','');
INSERT INTO lang VALUES ('submit','ru','Подтвердить','');
INSERT INTO lang VALUES ('time_left','ru','%1 минут осталось','');
INSERT INTO lang VALUES ('title','ru','Название','');
INSERT INTO lang VALUES ('tone','ru','Tone Format','');
INSERT INTO lang VALUES ('trans_code','ru','Код перевода','');
INSERT INTO lang VALUES ('unknown','ru','неизвестно','');
INSERT INTO lang VALUES ('unset_filter','ru','Сбросить фильтр','');
INSERT INTO lang VALUES ('update','ru','Обновить','');
INSERT INTO lang VALUES ('update_failed','ru','Ошибка при обновлении записи','');
INSERT INTO lang VALUES ('update_success','ru','Обновление прошло успешно','');
INSERT INTO lang VALUES ('upd_access','ru','Может изменять существующие записи','');
INSERT INTO lang VALUES ('upd_access_short','ru','изм','');
INSERT INTO lang VALUES ('user','ru','Пользователь','');
INSERT INTO lang VALUES ('user_deleted','ru','Успешно удален пользователь #%1, \"%2\" (%3)','');
INSERT INTO lang VALUES ('user_delete_failed','ru','Ошибка удаления пользователя #%1, \"%2\" (%3)','');
INSERT INTO lang VALUES ('user_delete_report','ru','Результат удаления пользователя','');
INSERT INTO lang VALUES ('user_update_failed','ru','Ошибка изменения пользователей: %1','');
INSERT INTO lang VALUES ('view','ru','Просмотр','');
INSERT INTO lang VALUES ('view_entry','ru','Просмотреть запись %1','');
INSERT INTO lang VALUES ('warning','ru','предупреждение','');
INSERT INTO lang VALUES ('week','ru','Неделя','');
INSERT INTO lang VALUES ('welcome','ru','Добро пожаловать в phpVideoPro','');
INSERT INTO lang VALUES ('wrong_date','ru','Указанная Вами дата %1 неверна (%2). Для ввода даты используйте только цифры. В первом поле задается день, во втором месяц и в третьем год. Если Вы не знаете точную дату, введите нули, например, \"00\" \"02\" \"2002\" - \"февраль 2002\", или \"00\" \"00\" \"0000\" -  \"когда-либо\".','');
INSERT INTO lang VALUES ('year','ru','Год','');
INSERT INTO lang VALUES ('yes','ru','Да','');
