# ========================================================
# French Language File created by phpVideoPro v0.5.8
# ========================================================

UPDATE languages SET charset='iso-8859-1' WHERE lang_id='fr';
INSERT INTO lang VALUES ('about','fr','A propos','');
INSERT INTO lang VALUES ('actor','fr','Acteur','');
INSERT INTO lang VALUES ('actors','fr','Acteurs','');
INSERT INTO lang VALUES ('actors_list','fr','Liste des Acteurs','');
INSERT INTO lang VALUES ('actor_persons','fr','Acteurs','');
INSERT INTO lang VALUES ('add_access','fr','Peut ajouter une nouvelle entrée','');
INSERT INTO lang VALUES ('add_access_short','fr','Ajouter','');
INSERT INTO lang VALUES ('add_entry','fr','Ajouter une entrée','');
INSERT INTO lang VALUES ('add_user','fr','Ajouter un utilisateur','');
INSERT INTO lang VALUES ('admin','fr','Admin','');
INSERT INTO lang VALUES ('admin_access','fr','Peut accéder aux menus administateurs','');
INSERT INTO lang VALUES ('admin_cats','fr','Gérer les catégories','');
INSERT INTO lang VALUES ('admin_disktypes','fr','Editer les types de disque','');
INSERT INTO lang VALUES ('admin_filter','fr','Paramétrages du filtre par défaut','');
INSERT INTO lang VALUES ('admin_movietech','fr','Editer les données techniques du film','');
INSERT INTO lang VALUES ('admin_orphans','fr','Enlevement des entrées orphelines','');
INSERT INTO lang VALUES ('admin_printers','fr','Editer les imprimantes','');
INSERT INTO lang VALUES ('admin_pstemplates','fr','Editer les gabarits des étiquettes PS','');
INSERT INTO lang VALUES ('admin_sessions','fr','Gérer les sessions','');
INSERT INTO lang VALUES ('admin_translations','fr','Editer les traductions','');
INSERT INTO lang VALUES ('admin_useredit','fr','Editer le compte utilisateur','');
INSERT INTO lang VALUES ('admin_users','fr','Gérer les comptes utilisateurs','');
INSERT INTO lang VALUES ('back','fr','Retour','');
INSERT INTO lang VALUES ('backup_compress','fr','Permettre la compression?','');
INSERT INTO lang VALUES ('backup_db','fr','Sauvegarde de la Base','');
INSERT INTO lang VALUES ('backup_db_complete','fr','Sauvegarder la base de données complète (incl. les les données techniques et les préférences)','');
INSERT INTO lang VALUES ('backup_db_moviedel','fr','Sauvegarder les données appropriées de film seulement et insérer un rapport d\'effacement pour les vieilles données avant les rapports d\'insertion pour de nouvelles données (sauvegardées)','');
INSERT INTO lang VALUES ('backup_db_movies','fr','Sauvegarder les données importantes du film seulement (film, acteurs, etc.) ','');
INSERT INTO lang VALUES ('backup_db_movie_internal','fr','Sauvegarder tous les films en utilisant le format interne de phpVideoPro','');
INSERT INTO lang VALUES ('backup_db_runscript','fr','Voulez-vous créer le script maintenant?','');
INSERT INTO lang VALUES ('backup_file_corrupt','fr','Le fichier de sauvegarde sélectionné est corrompu - ne peut être restauré','');
INSERT INTO lang VALUES ('button_backup','fr','Sauvegarder','');
INSERT INTO lang VALUES ('button_restore','fr','Restaurer','');
INSERT INTO lang VALUES ('cancel','fr','Annuler','');
INSERT INTO lang VALUES ('categories','fr','Catégories','');
INSERT INTO lang VALUES ('category','fr','Catégorie','');
INSERT INTO lang VALUES ('catlist_alpha','fr','Liste des médias par ordre alphabétique, trié par catégorie','');
INSERT INTO lang VALUES ('cat_action','fr','Action','');
INSERT INTO lang VALUES ('cat_adventure','fr','Aventure','');
INSERT INTO lang VALUES ('cat_animal','fr','Animal','');
INSERT INTO lang VALUES ('cat_animals','fr','Animaux','');
INSERT INTO lang VALUES ('cat_bible','fr','Biblique','');
INSERT INTO lang VALUES ('cat_biography','fr','Biographie','');
INSERT INTO lang VALUES ('cat_cartoon','fr','Dessin animé','');
INSERT INTO lang VALUES ('cat_catastrophe','fr','Catastrophe','');
INSERT INTO lang VALUES ('cat_children','fr','Enfants','');
INSERT INTO lang VALUES ('cat_comedy','fr','Comédie','');
INSERT INTO lang VALUES ('cat_concert','fr','Concert','');
INSERT INTO lang VALUES ('cat_crime','fr','Policier','');
INSERT INTO lang VALUES ('cat_documentary','fr','Documentaire','');
INSERT INTO lang VALUES ('cat_drama','fr','Drame','');
INSERT INTO lang VALUES ('cat_fairytale','fr','Contes de fée','');
INSERT INTO lang VALUES ('cat_fantasy','fr','Fantaisie','');
INSERT INTO lang VALUES ('cat_handle_empty','fr','La poignée pour une catégorie ne doit pas être vide.  Veuillez retourner et fixez ceci pour la catégorie #%1.','');
INSERT INTO lang VALUES ('cat_history','fr','Historique','');
INSERT INTO lang VALUES ('cat_horror','fr','Horreur','');
INSERT INTO lang VALUES ('cat_internal_name','fr','Poignée','');
INSERT INTO lang VALUES ('cat_love','fr','Histoires d\'amour','');
INSERT INTO lang VALUES ('cat_melodrama','fr','Mélodrame','');
INSERT INTO lang VALUES ('cat_misc','fr','Divers','');
INSERT INTO lang VALUES ('cat_music','fr','Musique','');
INSERT INTO lang VALUES ('cat_musicmovie','fr','Films musicaux','');
INSERT INTO lang VALUES ('cat_opera','fr','Opéra','');
INSERT INTO lang VALUES ('cat_operetta','fr','Opérette','');
INSERT INTO lang VALUES ('cat_party','fr','Fête','');
INSERT INTO lang VALUES ('cat_problem','fr','Problème','');
INSERT INTO lang VALUES ('cat_report','fr','Reportage','');
INSERT INTO lang VALUES ('cat_scary','fr','Film d\'horreur','');
INSERT INTO lang VALUES ('cat_sf','fr','Science Fiction','');
INSERT INTO lang VALUES ('cat_show','fr','Montrer','');
INSERT INTO lang VALUES ('cat_spy','fr','Films d\'espionage','');
INSERT INTO lang VALUES ('cat_stage','fr','Théatre','');
INSERT INTO lang VALUES ('cat_trans_update_failed','fr','La mise à jour a échoué lors de la traduction des catégories suivantes','');
INSERT INTO lang VALUES ('cat_travesty','fr','Parodie','');
INSERT INTO lang VALUES ('cat_update_failed','fr','Mise à jour raté pour la catégorie suivante: %1','');
INSERT INTO lang VALUES ('cat_vacation','fr','Vacances','');
INSERT INTO lang VALUES ('cat_videoclip','fr','Vidéo-clip','');
INSERT INTO lang VALUES ('cat_war','fr','Film de guerre','');
INSERT INTO lang VALUES ('cat_westerncomedy','fr','Western spaghetti','');
INSERT INTO lang VALUES ('cat_xmas','fr','Noël','');
INSERT INTO lang VALUES ('change_disktype','fr','Changer le type de disque pour %1','');
INSERT INTO lang VALUES ('change_media_length','fr','Changer la longeur du média','');
INSERT INTO lang VALUES ('change_media_length_for','fr','Entrer la capacité pour %1, svp.','');
INSERT INTO lang VALUES ('change_nr','fr','Changer le no/type de média pour %1','');
INSERT INTO lang VALUES ('change_rc','fr','Changer le code régional','');
INSERT INTO lang VALUES ('change_rc_for','fr','Changer le code régional pour %1','');
INSERT INTO lang VALUES ('check_completed','fr','Test achevé','');
INSERT INTO lang VALUES ('check_media_delete','fr','Tester si le média est vide','');
INSERT INTO lang VALUES ('clean_restore','fr','Nettoyer (enlever) les vieilles données avant la restauration','');
INSERT INTO lang VALUES ('close','fr','Fermer','');
INSERT INTO lang VALUES ('colors','fr','Couleurs','');
INSERT INTO lang VALUES ('comments','fr','Commentaires','');
INSERT INTO lang VALUES ('commercials','fr','Publicité','');
INSERT INTO lang VALUES ('composer','fr','Composition','');
INSERT INTO lang VALUES ('compose_person','fr','Compositeur','');
INSERT INTO lang VALUES ('compose_persons','fr','Compositeurs','');
INSERT INTO lang VALUES ('config_media','fr','Films et média','');
INSERT INTO lang VALUES ('confirm_delete','fr','Voulez-vous vraiment supprimer cet enregistrement?','');
INSERT INTO lang VALUES ('confirm_prilang','fr','Voulez-vous vraiment changer le langage principal pour TOUS les (nouveaux) utilisateurs?','');
INSERT INTO lang VALUES ('confirm_userdelete','fr','Vous êtes sur le point de supprimer l\'utilisateur %1','');
INSERT INTO lang VALUES ('confirm_userdeletion','fr','Voulez-vous vraiment supprimer l\'utilisateur \"%1\" (%2)?','');
INSERT INTO lang VALUES ('content','fr','Index','');
INSERT INTO lang VALUES ('counter_start_stop','fr','Compteur au début et à la fin','');
INSERT INTO lang VALUES ('countries','fr','Pays','');
INSERT INTO lang VALUES ('country','fr','pays','');
INSERT INTO lang VALUES ('create','fr','Créer','');
INSERT INTO lang VALUES ('create_success','fr','Entrée créée avec succès','');
INSERT INTO lang VALUES ('credits','fr','Crédits','');
INSERT INTO lang VALUES ('cut_off','fr','coupé','');
INSERT INTO lang VALUES ('data_access','fr','Accès aux données','');
INSERT INTO lang VALUES ('date_format','fr','Format de la date','');
INSERT INTO lang VALUES ('date_format_comment','fr','Quel format utilisé pour afficher la date.','');
INSERT INTO lang VALUES ('date_rec','fr','Date d\'acquisition','');
INSERT INTO lang VALUES ('day','fr','Jour','');
INSERT INTO lang VALUES ('db_stats','fr','Statistiques','');
INSERT INTO lang VALUES ('delete','fr','Supprimer','');
INSERT INTO lang VALUES ('delete_lang','fr','Supprimer la langue','');
INSERT INTO lang VALUES ('delete_lang_comment','fr','Supprimer de la BD toutes les expressions d\'une langue spécifiée. Cela ne supprimera le fichier de traduction, ainsi vous pourrez réinsérer les expressions plus tard (si vous n\'avez pas détruit le fichier vous-même).','');
INSERT INTO lang VALUES ('delete_orphans','fr','Suppression de %1 orphelin(s):','');
INSERT INTO lang VALUES ('delete_remaining','fr','Tous les dates de ce film en va remplacé','');
INSERT INTO lang VALUES ('deleting_entry','fr','Remplacer de date %1','');
INSERT INTO lang VALUES ('del_access','fr','Peut supprimer des entrées','');
INSERT INTO lang VALUES ('desc_admin_orphans','fr','\"Les entrées orphelines\" sont des données sans attributions, par exemple: Les acteurs, réalisateurs et/ou compositeurs qui ne sont plus référencés dans aucun film. C\'est principalement les résultats du changement d\'un nom mal orthographié après l\'avoir enregistré, mais jamais les resulats d\'entrées de film détruites. 
  C\'est une bonne idée de supprimer ces entrées: d\'un côté, cela sauve des ressources, et de l\'autre, cela aide à prévenir un ralentissement des actions de la base de données.','');
INSERT INTO lang VALUES ('desc_backup_db','fr','C\'est toujours une bonne idée d\'avoir une sauvegarde sous la main. Alors qu\'il est préférable d\'utiliser les outils propres avec votre base de données (<code>mysql_dump</code>, <code>pgsql_dump</code> etc.) pour cela, vous pouvez avoir une base de données hébergée sur une machine où vous n\'avez pas d\'accès shell. Dans ce case, utilisez \"Sauvegarde complète\" qui sauve votre base de données entière dans un script SQL <BR>Si vous voulez juste sauver vos données de film, par exemple pour les dupliquer  dans une autre base de données, vous pouvez utiliser le format interne de phpVideoPro lui-même: comme cela, vous pouvez même migrer entre différents types de base de données, p.ex. MySQL et PostgresSQL. La reconstitution de la sauvegarde complète d\'une version précédente de phpVideoPro vers une nouvelle a comme conséquence le besoin de mettre à jour la base de données après (comme si vous mettiez juste à jour phpVideoPro), la sauvegarde interne de PVP devrait être compatible entre les 
  versions (le futur le montrera;)<BR>Vous pouvez vouloir compreser votre sauvegarde: si votre
  installation de PHP est compilée avec el support de gzip, cocher simplement la case compression
  et cela sauvera jusqu\'à 90% de la taille du fichier.<BR>
  ','');
INSERT INTO lang VALUES ('director','fr','Réalisateur','');
INSERT INTO lang VALUES ('directors','fr','Réalisateurs','');
INSERT INTO lang VALUES ('directors_list','fr','Liste des Réalisateurs','');
INSERT INTO lang VALUES ('director_person','fr','réalisateur','');
INSERT INTO lang VALUES ('director_persons','fr','Réalisateurs','');
INSERT INTO lang VALUES ('disktype_add_failed','fr','Désolé, je ne peux pas ajouter le nouveau type de disque','');
INSERT INTO lang VALUES ('disktype_change','fr','Changer le type de disque','');
INSERT INTO lang VALUES ('disktype_contains_media','fr','Le type de disque ne peut pas être détruit en ce moment car les médias suivants s\'y réfèrent encore:','');
INSERT INTO lang VALUES ('disktype_name_empty','fr','Le nom pour le type de disque ne doit pas être vide. Veuillez, svp, aller en arrière et corriger le type de disque #%1','');
INSERT INTO lang VALUES ('disktype_update_failed','fr','Désolé, je ne peux pas mettre à jour le type de disque suivant #s: %1','');
INSERT INTO lang VALUES ('disk_size','fr','Taille du disque','');
INSERT INTO lang VALUES ('disk_type','fr','Type de disque','');
INSERT INTO lang VALUES ('display','fr','Afficher','');
INSERT INTO lang VALUES ('display_limit','fr','Limite d\'affichage','');
INSERT INTO lang VALUES ('display_limit_comment','fr','(combien de lignes à afficher par page pour des listes)','');
INSERT INTO lang VALUES ('dl_pvp_latest','fr','Télécharger la dernière version','');
INSERT INTO lang VALUES ('dupes','fr','Entrées dupliquées','');
INSERT INTO lang VALUES ('dupe_id_entered','fr','Il existe déja une entrée dans la base de donnée pour le MédiaID entré. Veuillez cliquez sur le bouton \"Retour\" de votre navigateur pour corriger l\'entrée. Conseil:  Il y a une boîte de sélection à côté de la boîte d\'entrée où vous avez indiqué le numéro de média.  Cette boîte de sélection vous indique le plus grand id média existant.  Normalement c\'est un bon choix pour un nouveau médium d\'incrémenter par un le premier nombre (à 4 chiffres)de nouveaux médias pour augmenter le premier nombre (à quatre chiffres), ou pour un nouveau film sur le même média, d\'incrémenter par un le deuxième nombre (de deux-chiffre).','');
INSERT INTO lang VALUES ('dupe_titles_found','fr','%1 titres trouvés avec doublons possibles:','');
INSERT INTO lang VALUES ('edit','fr','Éditer','');
INSERT INTO lang VALUES ('edit_entry','fr','Edition de l\'entrée %1','');
INSERT INTO lang VALUES ('enable_cookies','fr','Autoriser les cookies?','');
INSERT INTO lang VALUES ('enable_cookies_comment','fr','Est-ce que les préférences (par exemple les paramétrages du filtre) doivent être gérés avec des cookies?','');
INSERT INTO lang VALUES ('ended_sessions','fr','Sessions terminées','');
INSERT INTO lang VALUES ('enter_min_free','fr','La mince de place libre en minute:','');
INSERT INTO lang VALUES ('enter_new_medianr','fr','Entrer le numéro de média pour ce nouveau %1','');
INSERT INTO lang VALUES ('expire_cookies','fr','Durée de vie des cookies','');
INSERT INTO lang VALUES ('expire_cookies_comment','fr','Combien de temps est-ce qu\'un cookie doir survivre dans le navigateur de l\'utilisateur','');
INSERT INTO lang VALUES ('farbe','fr','Couleur','');
INSERT INTO lang VALUES ('filter','fr','Filtre','');
INSERT INTO lang VALUES ('filter_setup','fr','Réglage du filtre','');
INSERT INTO lang VALUES ('finnished','fr','Complet','');
INSERT INTO lang VALUES ('first_name','fr','Prénom','');
INSERT INTO lang VALUES ('format','fr','Format','');
INSERT INTO lang VALUES ('free','fr','Libre','');
INSERT INTO lang VALUES ('free_space_on_media','fr','Les prochains média ont au moins %1 minutes de libre:','');
INSERT INTO lang VALUES ('free_space_title','fr','Place choissable sur les mediums','');
INSERT INTO lang VALUES ('general','fr','Général','');
INSERT INTO lang VALUES ('goto_entry','fr','Annonce le film:','');
INSERT INTO lang VALUES ('graphic_file','fr','Ficher d\'image','');
INSERT INTO lang VALUES ('help','fr','Aide','');
INSERT INTO lang VALUES ('help_about','fr','Aide pour le thème','');
INSERT INTO lang VALUES ('highest_db_entries','fr','les plus hautes entrées dans la BD','');
INSERT INTO lang VALUES ('history','fr','Histoire','');
INSERT INTO lang VALUES ('hit_back_to_correct','fr','Pressez le bouton \"Retour\" pour corriger l\'erreur.','');
INSERT INTO lang VALUES ('hour','fr','Heure','');
INSERT INTO lang VALUES ('hours','fr','Heures','');
INSERT INTO lang VALUES ('howto','fr','HowTo\'s','');
INSERT INTO lang VALUES ('howto_help','fr','Comment créer un fichier d\'aide?','');
INSERT INTO lang VALUES ('howto_label','fr','Comment créer/configurer des gabarits d\'étiquettes?','');
INSERT INTO lang VALUES ('howto_lang','fr','Comment créer un nouveau fichier de langue?','');
INSERT INTO lang VALUES ('howto_templates','fr','Comment créer un nouveau gabarit?','');
INSERT INTO lang VALUES ('imp_errors','fr','Importation de %2 enregistrements achevée avec %1 erreurs.','');
INSERT INTO lang VALUES ('imp_success','fr','Importation de %1 enregistrements achevée avec succès','');
INSERT INTO lang VALUES ('incomplete_date','fr','Si vous ne connaissez pas la date exacte, mais par exemple, que vous l\'avez enregistrer en 2000, substistuez les données manquantes par des zéros, dans notre exemple, la date ressemblera à \"00\" \"00\" \"2000\"','');
INSERT INTO lang VALUES ('info_common','fr','Information courante','');
INSERT INTO lang VALUES ('info_common_info','fr','<DIV ALIGN=\"center\">C\'est la version %1 de phpVideoPro, fonctionnant sur %2.</div>','');
INSERT INTO lang VALUES ('info_noupdate','fr','<DIV ALIGN=\"center\">La version installée de phpVideoPro (%1) est récente - il n\'y a pas de  version plus nouvelle disponible en télécharger. Pour télécharger le tarball de la version installée, veuillez suivre <A HREF=\"http://www.qumran.org/homes/izzy/software/get_update.php?program=pvp\" TARGET=\"_blank\">ce lien</a>.</div>','');
INSERT INTO lang VALUES ('info_update','fr','Mettre à jour l\'information','');
INSERT INTO lang VALUES ('intro','fr','Introduction','');
INSERT INTO lang VALUES ('invalid_backup_dir','fr','Le dossier de sauvegarde configuré n\'existe pas.','');
INSERT INTO lang VALUES ('invalid_fsk','fr','La valeur entrée pour PG (\"%1\") est invalide.<br>PG veut dire Guide Parental, p.ex. l\'âge minimum  pour voir un film. Les personnes plus jeunes ne devraient pas y avoir accès.','');
INSERT INTO lang VALUES ('invalid_media_nr','fr','Le MédiaID, que vous avez donné, est soit incomplet soit invalide. Vous devez spécifier un <b>numéro</b> dans <b>les deux</b> champs ud MédiaID pour le numero de media, s-il-vous-plait','');
INSERT INTO lang VALUES ('in_list','fr','en liste','');
INSERT INTO lang VALUES ('is_rw','fr','réinscriptible','');
INSERT INTO lang VALUES ('label','fr','Etiquette','');
INSERT INTO lang VALUES ('labels','fr','Etiquettes','');
INSERT INTO lang VALUES ('labeltype','fr','Type d\'étiquette','');
INSERT INTO lang VALUES ('language_settings','fr','Configuration de la langue','');
INSERT INTO lang VALUES ('last_entry','fr','Dernière entrée','');
INSERT INTO lang VALUES ('last_medianr','fr','Le plus grand numéro pour ce média est à présent:','');
INSERT INTO lang VALUES ('layout_label','fr','Agencement choisi','');
INSERT INTO lang VALUES ('left_offset','fr','Offset gauche','');
INSERT INTO lang VALUES ('length','fr','Longueur','');
INSERT INTO lang VALUES ('lines_per_page','fr','Lignes par page','');
INSERT INTO lang VALUES ('lines_per_page_comment','fr','C\'est pour que les fonctions d\'impression puissent déterminer le nombre de lignes de texte qui peuvent tenir sur un page de papier','');
INSERT INTO lang VALUES ('line_count','fr','Lignes','');
INSERT INTO lang VALUES ('list','fr','Liste','');
INSERT INTO lang VALUES ('listgen','fr','Générateur de liste','');
INSERT INTO lang VALUES ('lists','fr','Listes','');
INSERT INTO lang VALUES ('login_failed','fr','Votre Login a échoué. Soit vous l\'avez mal orthografié ou le compte demandé n\'existe pas <P />','');
INSERT INTO lang VALUES ('login_required','fr','Vos droits ne sont pas suffisants pour l\'action demandé. Vous pouvez vous loguer avec un compte approprié maintenant.<P />','');
INSERT INTO lang VALUES ('logout_user','fr','Logué comme \"%1\".<A HREF=\"%2\">Déconnection</a>','');
INSERT INTO lang VALUES ('lower_left_corner','fr','Coin en bas à gauche (x/y)','');
INSERT INTO lang VALUES ('max_fontsize','fr','Taille de police max.','');
INSERT INTO lang VALUES ('media','fr','Médias','');
INSERT INTO lang VALUES ('medialength','fr','Longueur du média','');
INSERT INTO lang VALUES ('medialist','fr','Liste des médias','');
INSERT INTO lang VALUES ('medialist_alpha','fr','Liste des médias par ordre alphabétique','');
INSERT INTO lang VALUES ('medialist_num','fr','Liste des médias par ordre numérique','');
INSERT INTO lang VALUES ('medianr','fr','MédiaNo','');
INSERT INTO lang VALUES ('mediatype','fr','Type de média','');
INSERT INTO lang VALUES ('media_change','fr','Changer le MédiaNo','');
INSERT INTO lang VALUES ('media_copy','fr','Copier la donnée vers le MédiaNo','');
INSERT INTO lang VALUES ('medium','fr','Média','');
INSERT INTO lang VALUES ('medium_deleted','fr','Plus de films dans ce média - média enlevé','');
INSERT INTO lang VALUES ('medium_not_deleted','fr','Média non-enlevé','');
INSERT INTO lang VALUES ('medium_overview','fr','Vue d\'ensemble pour %1','');
INSERT INTO lang VALUES ('month','fr','Mois','');
INSERT INTO lang VALUES ('movies','fr','Films','');
INSERT INTO lang VALUES ('movies_left_in_cat','fr','La catégorie %1 contient encrore %2 film(s) et ne peut être supprimée pour cela. Désolé.','');
INSERT INTO lang VALUES ('movies_left_reference','fr','Cette entrée ne peut pas être détruite: Il y a %1 film(s) dans la BD y référent.','');
INSERT INTO lang VALUES ('movie_color_default','fr','Format couleur par défaut d\'un film','');
INSERT INTO lang VALUES ('movie_color_default_comment','fr','Ce sera utilisé comme format couleur par défaut pour  les nouvelles entrées.','');
INSERT INTO lang VALUES ('movie_onlabel_default','fr','Valeur par défaut pour l\'information étiquette','');
INSERT INTO lang VALUES ('movie_onlabel_default_comment','fr','Valeur par défaut pour de nouvelles entrées: Est-ce que l\'information pour ce film doit être inclue lorsque le(s) étiquette(s) pour ce médium est(sont) générée(s)?','');
INSERT INTO lang VALUES ('movie_tone_default','fr','Format sonore par défaut d\'un film','');
INSERT INTO lang VALUES ('movie_tone_default_comment','fr','Ce sera utilisé pour prérégler le format sonore d\'une nouvelle entrée.','');
INSERT INTO lang VALUES ('music','fr','Compositeur','');
INSERT INTO lang VALUES ('music_list','fr','Liste des compositeurs','');
INSERT INTO lang VALUES ('name','fr','Nom','');
INSERT INTO lang VALUES ('never','fr','jamais','');
INSERT INTO lang VALUES ('new_disktype','fr','Nouveau type de disque','');
INSERT INTO lang VALUES ('new_medianr','fr','nouveau MédiaNo','');
INSERT INTO lang VALUES ('new_movie_on','fr','Nouveau %1','');
INSERT INTO lang VALUES ('no','fr','Non','');
INSERT INTO lang VALUES ('nobody_named','fr','Il n\'y a aucun autre film par un %1 appelé %2 %3 dans cette BD, donc j\'enlève cette entrée de la table de %1.','');
INSERT INTO lang VALUES ('none','fr','Aucun','');
INSERT INTO lang VALUES ('not_ok','fr','Echec','');
INSERT INTO lang VALUES ('not_yet_implemented','fr','Désolé - pas encore impémenté.','');
INSERT INTO lang VALUES ('no_add_lang','fr','Il n\'existe pas d\'autre langue disponible.','');
INSERT INTO lang VALUES ('no_backup_avail','fr','Pas de fichier de restauration disponible','');
INSERT INTO lang VALUES ('no_entries_found','fr','Pas d\'entrée trouvée.','');
INSERT INTO lang VALUES ('no_entry_in_tapelist','fr','Echec - pas d\'entrée trouvée dans la liste de cassette.','');
INSERT INTO lang VALUES ('no_orphans_found','fr','Félicitation! Vous semblez ne pas avoir de squelette dans le placart (plus jamais?)','');
INSERT INTO lang VALUES ('no_restore_file','fr','Désolé, le fichier sélectionné n\'existe plus','');
INSERT INTO lang VALUES ('no_space_of','fr','Non recherchement pour la reste de temps en liste avec min. %1 minutes de place libre en DB','');
INSERT INTO lang VALUES ('nr','fr','No','');
INSERT INTO lang VALUES ('of_aquiration','fr','d\'enregistrement','');
INSERT INTO lang VALUES ('old_sessions','fr','Sessions plus vieilles que <INPUT NAME=\"%1\" VALUE=\"\" CLASS=\"yesnobutton\"> jours','');
INSERT INTO lang VALUES ('orig_disktype','fr','Type de disque original','');
INSERT INTO lang VALUES ('orig_medianr','fr','MédiaNo original','');
INSERT INTO lang VALUES ('orig_trans','fr','Texte original (%1)','');
INSERT INTO lang VALUES ('orphans_found','fr','%1 orphelin(s) trouvé(s):','');
INSERT INTO lang VALUES ('other_pages','fr','Autre pages','');
INSERT INTO lang VALUES ('page_bg','fr','Fond de la site','');
INSERT INTO lang VALUES ('password','fr','Mot de passe','');
INSERT INTO lang VALUES ('password_retype','fr','Retaper le mot de passe','');
INSERT INTO lang VALUES ('picture','fr','Format de couleur','');
INSERT INTO lang VALUES ('preferences','fr','Préférences','');
INSERT INTO lang VALUES ('print','fr','Imprimer','');
INSERT INTO lang VALUES ('printer','fr','Imprimante','');
INSERT INTO lang VALUES ('printer_add_failed','fr','Une erreur s\'est produite en ajoutant cette imprimante','');
INSERT INTO lang VALUES ('printer_add_success','fr','Imprimante ajoutée avec succès','');
INSERT INTO lang VALUES ('printer_comment','fr','Pour imprimer des \"forms\" ( comme utilisées par les étiquettes PS), nous devons avoir les offsets exacts  de votre imprimante.','');
INSERT INTO lang VALUES ('printer_name','fr','Nom','');
INSERT INTO lang VALUES ('printer_upd_failed','fr','La mise à jour de l\'imprimante suivant a échoué: %1','');
INSERT INTO lang VALUES ('print_label','fr','Imprimer une étiquette:','');
INSERT INTO lang VALUES ('pslabel','fr','Etiquette PS','');
INSERT INTO lang VALUES ('pstpl_name','fr','Nom du cabarit','');
INSERT INTO lang VALUES ('pstpl_type','fr','Type de cabarit','');
INSERT INTO lang VALUES ('read_access','fr','Peut feuilleter les entrées','');
INSERT INTO lang VALUES ('read_access_short','fr','lec','');
INSERT INTO lang VALUES ('recalc_free','fr','Recalculez la place libre sur ce média','');
INSERT INTO lang VALUES ('refresh_lang','fr','Rafraichir le langage','');
INSERT INTO lang VALUES ('refresh_lang_comment','fr','Réinsérer des expressions d\'un fichier de traduction dans la BD','');
INSERT INTO lang VALUES ('region_code','fr','Code régional','');
INSERT INTO lang VALUES ('remove_empty_media','fr','Enlever les médias vides','');
INSERT INTO lang VALUES ('remove_empty_media_comment','fr','Est-ce que les médias doivent être enlevés de la maintenance d\'espace vide lorsque le dernier film en est enlevé?','');
INSERT INTO lang VALUES ('reset','fr','Ré-initialiser','');
INSERT INTO lang VALUES ('restore_db_movie_internal','fr','Restaurer les film du fichier de sauvegarde PVP','');
INSERT INTO lang VALUES ('rw_media','fr','Médias réenregistrables','');
INSERT INTO lang VALUES ('rw_media_comment','fr','Médias à maintenir de l\'espace vide 
 (jusqu\'à ce que vous enregistriez dessus)','');
INSERT INTO lang VALUES ('s/w','fr','n/b','');
INSERT INTO lang VALUES ('save_lang_file','fr','Sauver la traduction dans le fichier','');
INSERT INTO lang VALUES ('scan_new_lang_comment','fr','(Si vous créez votre propre fichier de traduction et que vous le mettiez dans le dossier de paramétrage, cela dira à phpVidoPro de le rechercher)','');
INSERT INTO lang VALUES ('scan_new_lang_files','fr','Chercher pour des nouvelles records de langue?','');
INSERT INTO lang VALUES ('screen','fr','Format de vue','');
INSERT INTO lang VALUES ('search','fr','Rechercher','');
INSERT INTO lang VALUES ('search_movie','fr','Rechercher un film','');
INSERT INTO lang VALUES ('select_add_lang','fr','Sélectionner un langage additionel à installer','');
INSERT INTO lang VALUES ('select_add_lang_comment','fr','(L\'anglais est déjà installé et le sera toujours - regarder le prochain élément. Pour d\'autres langages que vous avez déjà installés, regarder aussi aussi le prochain élément)','');
INSERT INTO lang VALUES ('select_primary_lang','fr','Choix de langue primaire','');
INSERT INTO lang VALUES ('select_primary_lang_comment','fr','(pour toutes expressions manquantes, il y aura toujours le recours à l\'anglais)','');
INSERT INTO lang VALUES ('sel_target_lang','fr','Sélectionner la langue (vers laquelle traduire )','');
INSERT INTO lang VALUES ('session_expired','fr','Votre session a expirée - veuillez vous reloguer','');
INSERT INTO lang VALUES ('session_purgetime','fr','Après combien de temps est-ce qu\'une session inactive est expirée?','');
INSERT INTO lang VALUES ('session_purgetime_comment','fr','Combien de temps est-ce que une session reste valable sans activité de l\'utilisateur?','');
INSERT INTO lang VALUES ('sess_dla','fr','Dernier accès','');
INSERT INTO lang VALUES ('sess_end','fr','Terminée','');
INSERT INTO lang VALUES ('sess_ip','fr','IP distante','');
INSERT INTO lang VALUES ('sess_start','fr','Démarrée','');
INSERT INTO lang VALUES ('set_filter','fr','Placer de filtre','');
INSERT INTO lang VALUES ('site_info_comment','fr','Quelle information du site est à afficher dans le titre du navigateur?','');
INSERT INTO lang VALUES ('start_page','fr','Page de démarrage','');
INSERT INTO lang VALUES ('start_pvp','fr','Démarrer phpVideoPro','');
INSERT INTO lang VALUES ('stats','fr','Statistiques','');
INSERT INTO lang VALUES ('stat_categories','fr','Catégories (utilisées/toutes)','');
INSERT INTO lang VALUES ('stat_counts','fr','Totaux','');
INSERT INTO lang VALUES ('stat_ranks','fr','Classement','');
INSERT INTO lang VALUES ('submit','fr','Soumettre','');
INSERT INTO lang VALUES ('sure_to_delete','fr','Remplacée tous les dates pour %1?','');
INSERT INTO lang VALUES ('table_bg','fr','Fond de tableau','');
INSERT INTO lang VALUES ('tapelist_update_failed','fr','Echec dans la mise à jour de la liste des bandes','');
INSERT INTO lang VALUES ('taperest_absolute','fr','Reste de bande (absolu)','');
INSERT INTO lang VALUES ('taperest_filtered','fr','Reste de bande (filtré)','');
INSERT INTO lang VALUES ('target_trans','fr','Traduction vers votre langage cible (%1)','');
INSERT INTO lang VALUES ('techdata','fr','Donnée technique','');
INSERT INTO lang VALUES ('template_file','fr','Fichier de gabarit','');
INSERT INTO lang VALUES ('template_set','fr','Réglage du gabarit','');
INSERT INTO lang VALUES ('th_bg','fr','Fond de tete du tablau','');
INSERT INTO lang VALUES ('time_left','fr','%1 minutes restantes','');
INSERT INTO lang VALUES ('title','fr','Titre','');
INSERT INTO lang VALUES ('tone','fr','Format sonore','');
INSERT INTO lang VALUES ('top_offset','fr','Offset du haut','');
INSERT INTO lang VALUES ('trans_code','fr','Code de traduction','');
INSERT INTO lang VALUES ('unit','fr','Unité','');
INSERT INTO lang VALUES ('unknown','fr','inconnu','');
INSERT INTO lang VALUES ('unset_filter','fr','Remplacer de filtre','');
INSERT INTO lang VALUES ('update','fr','Actualiser','');
INSERT INTO lang VALUES ('update_failed','fr','Impossibilité d\'actualisation des dates','');
INSERT INTO lang VALUES ('update_success','fr','Entré mise à jour avec succès','');
INSERT INTO lang VALUES ('upd_access','fr','Peut mettre à jour les entrées existantes','');
INSERT INTO lang VALUES ('upd_access_short','fr','màj','');
INSERT INTO lang VALUES ('upper_right_corner','fr','Coin en haut à droite (x/y)','');
INSERT INTO lang VALUES ('user','fr','Utilisateur','');
INSERT INTO lang VALUES ('user_deleted','fr','Utilisateur détruit avec succès: #%1 ,\"%2\" (%3) ','');
INSERT INTO lang VALUES ('user_delete_failed','fr','Echec de la destruction de l\'utilisateur #%1 ,\"%2\" (%3) ','');
INSERT INTO lang VALUES ('user_delete_report','fr','Résultats du processus de destruction de l\'utilisateur','');
INSERT INTO lang VALUES ('user_update_failed','fr','Echec de la mise à jour des utilisateurs suivants: %1','');
INSERT INTO lang VALUES ('view','fr','Voir','');
INSERT INTO lang VALUES ('view_entry','fr','Voir l\'entrée %1','');
INSERT INTO lang VALUES ('warning','fr','Attention','');
INSERT INTO lang VALUES ('week','fr','Semaine','');
INSERT INTO lang VALUES ('welcome','fr','Bienvenue à phpVideoPro','');
INSERT INTO lang VALUES ('wrong_date','fr','La date donnée %1 (%2) est invalide. Placez la date de jour au premier, la date de mois au deuxieme et la date d\'année en fin. En cas d\'inconnue de la date completement remplace avec du numero \"0\".','');
INSERT INTO lang VALUES ('year','fr','Année','');
INSERT INTO lang VALUES ('yes','fr','Oui','');
