# ========================================================
# Spanish Translation phrases for phpVideoPro
# ========================================================

UPDATE languages SET charset='iso-8859-1' WHERE lang_id='es';
INSERT INTO lang (message_id,lang,content) VALUES ('not_yet_implemented','es','Sorry - not yet implemented.');
INSERT INTO lang VALUES('medium','es','Soporte');
INSERT INTO lang VALUES('nr','es','Número');
INSERT INTO lang VALUES('title','es','Título');
INSERT INTO lang VALUES('length','es','Duración');
INSERT INTO lang VALUES('year','es','Año');
INSERT INTO lang VALUES('date_rec','es','Fecha de registro');
INSERT INTO lang VALUES('category','es','Categoría');
INSERT INTO lang VALUES('medialist','es','Soportes');
INSERT INTO lang VALUES('enter_min_free','es','Introducir el mínimo de espacio libre en el soporte a mostrar:');
INSERT INTO lang VALUES('display','es','Pantalla');
INSERT INTO lang VALUES('free_space_on_media','es','Los siguientes soportes tienen al menos %1 minutos de espacio disopnible:');
INSERT INTO lang VALUES('free','es','Gratis');
INSERT INTO lang VALUES('content','es','Contenido');
INSERT INTO lang VALUES('filter_setup','es','Configuración del filtro');
INSERT INTO lang VALUES('mediatype','es','Tipo de soporte');
INSERT INTO lang VALUES('screen','es','Formato de la pantalla');
INSERT INTO lang VALUES('picture','es','Formato del color');
INSERT INTO lang VALUES('tone','es','Formato del tono');
INSERT INTO lang VALUES('longplay','es','Larga duración');
INSERT INTO lang VALUES('fsk','es','PG');
INSERT INTO lang VALUES('actor','es','Actor');
INSERT INTO lang VALUES('actors','es','Actores');
INSERT INTO lang VALUES('director','es','Director');
INSERT INTO lang VALUES('directors','es','Directores');
INSERT INTO lang VALUES('composer','es','Compositor');
INSERT INTO lang VALUES('music','es','Compositores');
INSERT INTO lang VALUES('min','es','min');
INSERT INTO lang VALUES('max','es','max');
INSERT INTO lang VALUES('s/w','es','b/n');
INSERT INTO lang VALUES('farbe','es','Color');
INSERT INTO lang VALUES('3d','es','3D');
INSERT INTO lang VALUES('edit_entry','es','Editar entrada %1');
INSERT INTO lang VALUES('view_entry','es','Ver entrada %1');
INSERT INTO lang VALUES('add_entry','es','Añadir entrada');
INSERT INTO lang VALUES('unknown','es','desconocido');
INSERT INTO lang VALUES('country','es','País');
INSERT INTO lang VALUES('medianr','es','NumSoporte');
INSERT INTO lang VALUES('highest_db_entries','es','primeras entradas en la BD');
INSERT INTO lang VALUES('no','es','No');
INSERT INTO lang VALUES('yes','es','Sí');
INSERT INTO lang VALUES('medialength','es','Duración del soporte');
INSERT INTO lang VALUES('minute_abbrev','es','min');
INSERT INTO lang VALUES('source','es','Fuente');
INSERT INTO lang VALUES('staff','es','Equipo');
INSERT INTO lang VALUES('name','es','Nombre');
INSERT INTO lang VALUES('first_name','es','Nombre');
INSERT INTO lang VALUES('in_list','es','en la lista');
INSERT INTO lang VALUES('comments','es','Comentarios');
INSERT INTO lang VALUES('cancel','es','Cancelar');
INSERT INTO lang VALUES('create','es','Crear');
INSERT INTO lang VALUES('update','es','Actualizar');
INSERT INTO lang VALUES('edit','es','Editar');
INSERT INTO lang VALUES('delete','es','Eliminar');
INSERT INTO lang VALUES('invalid_media_nr','es','El número del soporte especificado esta incompleto o es inválido. Debe ser un <b>número</b> dentro de los campos <b>both</b> NumSoporte.');
INSERT INTO lang VALUES('warning','es','aviso');
INSERT INTO lang VALUES('of_aquiration','es','de adquisición');
INSERT INTO lang VALUES('wrong_date','es','La fecha %1 especificada (%2) es incorrecta. El formato de las fechas es: primero el día, segundo el mes y el año al final sólo pudiendo usar dígitos. Si desconoces algún dato rellena el campo con ceros: ej. "00" "02" "2002" significa "algún día de  Febrero del 2002", or "00" "00" "0000" significa "alguna vez".');
INSERT INTO lang VALUES('incomplete_date','es','Si no conoces la fecha exacta y por ejemplo sólo el año de compra, substituye por ceros los datos desconocidos. - ejemplo: "00" "00" "2000".');
INSERT INTO lang VALUES('dupe_id_entered','es','No hay ninguna entrada en la BD para la ID del soporte introducida. Pulse "Atras" en el navegador y ponga un dato correcto. Consejo: Hay un menú desplegable al seleccionar el número del soporte. Te informara de la película con mayor id. Normalmente es una buena elección para un nuevo soporte incrementar en uno el primer número(4 dígitos), o para una nueva película en el mismoe soporte, incrementar en uno el segundo (2 dígitos).');
INSERT INTO lang VALUES('create_success','es','Entrada creada correctamente');
INSERT INTO lang VALUES('update_failed','es','Error al actualizar la entrada');
INSERT INTO lang VALUES('update_success','es','Entrada actualizada correctamente');
INSERT INTO lang VALUES('about','es','Acerca de');
INSERT INTO lang VALUES('history','es','Historia');
INSERT INTO lang VALUES('view','es','Ver');
INSERT INTO lang VALUES('deleting_entry','es','Borrando entrada %1');
INSERT INTO lang VALUES('free_space_title','es','Espacio libre en el soporte');
INSERT INTO lang VALUES('filter','es','Filtro');
INSERT INTO lang VALUES('set_filter','es','Activar Filtro');
INSERT INTO lang VALUES('unset_filter','es','Desactivar filtro');
INSERT INTO lang VALUES('taperest_absolute','es','Cintas (todas)');
INSERT INTO lang VALUES('taperest_filtered','es','Cintas (filtradas)');
INSERT INTO lang VALUES('help','es','Ayuda');
INSERT INTO lang VALUES('general','es','General');
INSERT INTO lang VALUES('sure_to_delete','es','¿Estas seguro de querer borrar todos los datos de %1');
INSERT INTO lang VALUES('nobody_named','es','No hay una película que se llame %1 %2 %3 en esta BD, se eliminara esta entrada de la tabla %1.');
INSERT INTO lang VALUES('compose_person','es','compositor');
INSERT INTO lang VALUES('director_person','es','director');
INSERT INTO lang VALUES('check_completed','es','Comprobación completa');
INSERT INTO lang VALUES('delete_remaining','es','Eliminando los datos existentes de la película en la BD');
INSERT INTO lang VALUES('ok','es','OK');
INSERT INTO lang VALUES('not_ok','es','Error');
INSERT INTO lang VALUES('recalc_free','es','Recalculando el espacio libre disponible en el soporte');
INSERT INTO lang VALUES('tapelist_update_failed','es','Error al actualizar lista de cintas');
INSERT INTO lang VALUES('no_entry_in_tapelist','es','Error - no se encontraron entradas en la lista de cintas');
INSERT INTO lang VALUES('finnished','es','Completado');
INSERT INTO lang VALUES('time_left','es','Quedan %1 minutos');
INSERT INTO lang VALUES('configuration','es','Configuración');
INSERT INTO lang VALUES('index','es','Indice');
INSERT INTO lang VALUES('intro','es','Intro');
INSERT INTO lang VALUES('menues','es','Menus');
INSERT INTO lang VALUES('back','es','Atras');
INSERT INTO lang VALUES('close','es','Cerrar');
INSERT INTO lang VALUES('help_about','es','Acerca de la ayuda');
INSERT INTO lang VALUES('actors_list','es','Lista de actores');
INSERT INTO lang VALUES('directors_list','es','Lista de directores');
INSERT INTO lang VALUES('music_list','es','Lista de compositores');
INSERT INTO lang VALUES('no_entries_found','es','No se encontraron entradas');
INSERT INTO lang VALUES('no_space_of','es','No hay un soporte con un mínimo de %1 espacio libre en la BD.');
INSERT INTO lang VALUES('howto','es','Como...');
INSERT INTO lang VALUES('howto_lang','es','Como crear un nuevo fichero de idioma');
INSERT INTO lang VALUES('howto_help','es','Como crear un fichero de ayuda');
INSERT INTO lang VALUES('howto_templates','es','Como crear una nueva plantilla');
INSERT INTO lang VALUES('language_settings','es','Configuración del idioma');
INSERT INTO lang VALUES('scan_new_lang_files','es','¿Buscar nuevos ficheros de idiomas?');
INSERT INTO lang VALUES('scan_new_lang_comment','es','(Si creas tus propios ficheros de idioma y lo pones dentro del directorio setup, phpVideoPro los podra usar)');
INSERT INTO lang VALUES('select_add_lang','es','Seleccionar un idioma adicional a instalar');
INSERT INTO lang VALUES('select_add_lang_comment','es','(Ingles ya instalado - ver siguiente. Para otros idiomas ya instalados, ver siguiente también.)');
INSERT INTO lang VALUES('no_add_lang','es','No hay idiomas adicionales disponibles.');
INSERT INTO lang VALUES('refresh_lang','es','Actualizar lista de idiomas');
INSERT INTO lang VALUES('refresh_lang_comment','es','(reescriba las frases del fichero de idioma en la BD)');
INSERT INTO lang VALUES('none','es','Ninguno');
INSERT INTO lang VALUES('select_primary_lang','es','Seleccionar idioma principal');
INSERT INTO lang VALUES('select_primary_lang_comment','es','(para las frases desconocidas, siempre las podras dejar en ingles');
INSERT INTO lang VALUES('colors','es','Colores');
INSERT INTO lang VALUES('feedback_ok','es','Respuesta "OK"');
INSERT INTO lang VALUES('feedback_err','es','Respuesta "Error"');
INSERT INTO lang VALUES('template_set','es','Usar una plantilla');
INSERT INTO lang VALUES('start_pvp','es','Iniciar phpVideoPro');
INSERT INTO lang VALUES('hit_back_to_correct','es','Pulsar "Atras" para corregir el error.');
INSERT INTO lang VALUES('goto_entry','es','Ir directamente a la entrada:');
INSERT INTO lang VALUES('start_page','es','Página inicial');
INSERT INTO lang VALUES('invalid_fsk','es','El valor introducido en PG ("%1") es inválido. PG significa calificación por edades, es decir, la edad mínima que se necesita para tener acceso a esta película.');
INSERT INTO lang VALUES('counter_start_stop','es','Cargar/Parar el contador');
INSERT INTO lang VALUES('other_pages','es','Otras páginas');
INSERT INTO lang VALUES('commercials','es','Comerciales');
INSERT INTO lang VALUES('cut_off','es','desconectar');
INSERT INTO lang VALUES('display_limit','es','Limite de pantalla');
INSERT INTO lang VALUES('display_limit_comment','es','(número de lineas a mostrar por página para las listas');
INSERT INTO lang VALUES('print_label','es','Imprimir etiqueta:');
INSERT INTO lang VALUES('howto_label','es','Como crear/configurar una plantilla de etiquetas');
INSERT INTO lang VALUES('label','es','Etiqueta');
INSERT INTO lang VALUES('print','es','Imprimir');
INSERT INTO lang VALUES('medialist_num','es','Lista de soportes en orden numérico');
INSERT INTO lang VALUES('medialist_alpha','es','Lista de soportes en orden alfabético');
INSERT INTO lang VALUES('lines_per_page','es','Lineas por página');
INSERT INTO lang VALUES('lines_per_page_comment','es','Determina cuantas lineas de texto caben en una hoja de papel (funciones de impresión).');
INSERT INTO lang VALUES('date_format','es','Formato de fecha');
INSERT INTO lang VALUES('date_format_comment','es','Formato para mostrar la fecha.');
INSERT INTO lang VALUES('listgen','es','Generador de listados');
INSERT INTO lang VALUES('list','es','Lista');
INSERT INTO lang VALUES('format','es','Formato');
INSERT INTO lang VALUES('line_count','es','Lineas');
INSERT INTO lang VALUES('catlist_alpha','es','Lista de soportes en orden alfabético, ordenada por categoría');
INSERT INTO lang VALUES('lists','es','Listas');
INSERT INTO lang VALUES('labels','es','Etiquetas');
INSERT INTO lang VALUES('cat_adventure','es','Aventura');
INSERT INTO lang VALUES('cat_action','es','Acción');
INSERT INTO lang VALUES('cat_agents','es','Agentes');
INSERT INTO lang VALUES('cat_bible','es','Bíblicas');
INSERT INTO lang VALUES('cat_biography','es','Biográficas');
INSERT INTO lang VALUES('cat_stage','es','Estados');
INSERT INTO lang VALUES('cat_documentary','es','Documentales');
INSERT INTO lang VALUES('cat_drama','es','Drama');
INSERT INTO lang VALUES('cat_fantasy','es','Fantasía');
INSERT INTO lang VALUES('cat_party','es','Festiva');
INSERT INTO lang VALUES('cat_scary','es','Miedo');
INSERT INTO lang VALUES('cat_history','es','Histórica');
INSERT INTO lang VALUES('cat_horror','es','Horror');
INSERT INTO lang VALUES('cat_judaica','es','Judaica');
INSERT INTO lang VALUES('cat_camera','es','Camera');
INSERT INTO lang VALUES('cat_catastrophe','es','Catastrofes');
INSERT INTO lang VALUES('cat_children','es','Infantiles');
INSERT INTO lang VALUES('cat_comedy','es','Comedia');
INSERT INTO lang VALUES('cat_concert','es','Conciertos');
INSERT INTO lang VALUES('cat_war','es','Películas de guerra');
INSERT INTO lang VALUES('cat_crime','es','Crimén');
INSERT INTO lang VALUES('cat_love','es','Películas de amor');
INSERT INTO lang VALUES('cat_fairytale','es','Cuentos de hadas');
INSERT INTO lang VALUES('cat_melodrama','es','Melodrama');
INSERT INTO lang VALUES('cat_monumental','es','Monumental');
INSERT INTO lang VALUES('cat_musical','es','Musical');
INSERT INTO lang VALUES('cat_music','es','Música');
INSERT INTO lang VALUES('cat_videoclip','es','Videoclip');
INSERT INTO lang VALUES('cat_musicmovie','es','Musicales');
INSERT INTO lang VALUES('cat_nature','es','Naturaleza');
INSERT INTO lang VALUES('cat_opera','es','Opera');
INSERT INTO lang VALUES('cat_operetta','es','Opereta');
INSERT INTO lang VALUES('cat_problem','es','Problemas');
INSERT INTO lang VALUES('cat_report','es','Reportajes');
INSERT INTO lang VALUES('cat_satire','es','Satíricas');
INSERT INTO lang VALUES('cat_misc','es','Otras');
INSERT INTO lang VALUES('cat_sf','es','Ciencia ficción');
INSERT INTO lang VALUES('cat_show','es','Espectáculos');
INSERT INTO lang VALUES('cat_spy','es','Películas de espias');
INSERT INTO lang VALUES('cat_thriller','es','Intriga');
INSERT INTO lang VALUES('cat_animal','es','Animal');
INSERT INTO lang VALUES('cat_animals','es','Animales');
INSERT INTO lang VALUES('cat_travesty','es','Travestismo');
INSERT INTO lang VALUES('cat_vacation','es','Vacaciones');
INSERT INTO lang VALUES('cat_xmas','es','Navideñas');
INSERT INTO lang VALUES('cat_western','es','Oeste');
INSERT INTO lang VALUES('cat_westerncomedy','es','Comedia del Oeste');
INSERT INTO lang VALUES('cat_cartoon','es','Dibujos');
INSERT INTO lang VALUES('db_stats','es','Estadísticas');
INSERT INTO lang VALUES('stat_counts','es','Contadores');
INSERT INTO lang VALUES('stat_ranks','es','Clasificación');
INSERT INTO lang VALUES('movies','es','Películas');
INSERT INTO lang VALUES('media','es','Soporte');
INSERT INTO lang VALUES('compose_persons','es','Compositores');
INSERT INTO lang VALUES('director_persons','es','Directores');
INSERT INTO lang VALUES('actor_persons','es','Actores');
INSERT INTO lang VALUES('categories','es','Categorías');
INSERT INTO lang VALUES('countries','es','Paises');
INSERT INTO lang VALUES('stat_categories','es','Categorías (usadas/todas)');
INSERT INTO lang VALUES('stats','es','Estadísticas');
INSERT INTO lang VALUES('dl_pvp_latest','es','Ultima versión D/L');
INSERT INTO lang VALUES('info_update','es','Actualizar información');
INSERT INTO lang VALUES('info_noupdate','es','<DIV ALIGN="center">La versión instalada de phpVideoPro (%1) es reciente - no hay nuevas versiones disponibles para la descarga. Para descargar el paquete de la versión instalada:  <A HREF=http://www.qumran.org/homes/izzy/software/get_update.php?program=pvp" TARGET="_blank">descargar aquí</A>.</DIV>');
INSERT INTO lang VALUES('info_common','es','Información común');
INSERT INTO lang VALUES('info_common_info','es','<DIV ALIGN="center">Esta es la versión %1 de phpVideoPro, bajo %2.</DIV>');
INSERT INTO lang VALUES('change_nr','es','Cambiar el NumSoporteNr/TipoSoporte para %1');
INSERT INTO lang VALUES('orig_medianr','es','NumSoporte original');
INSERT INTO lang VALUES('new_medianr','es','Nuevo Numsoporte');
INSERT INTO lang VALUES('media_copy','es','Copiar datos a NumSoporte');
INSERT INTO lang VALUES('media_change','es','Cambiar NumSoporte');
INSERT INTO lang VALUES('check_media_delete','es','Comprobando si el soporte esta vacío');
INSERT INTO lang VALUES('medium_deleted','es','No hay peliculas en este soporte - soporte borrado');
INSERT INTO lang VALUES('medium_not_deleted','es','Soporte no eliminado');
INSERT INTO lang VALUES('change_media_length','es','Cambiar la duración del soporte');
INSERT INTO lang VALUES('change_media_length_for','es','Introduzca la capacidad para %1');
INSERT INTO lang VALUES('admin_cats','es','Administrar categorías');
INSERT INTO lang VALUES('cat_internal_name','es','Interno');
INSERT INTO lang VALUES('cat_update_failed','es','Actualización fallida para las siguientes categorías: %1');
INSERT INTO lang VALUES('cat_trans_update_failed','es','Error al actualizar las traducciones en la siguiente categoría: %1');
INSERT INTO lang VALUES('credits','es','Créditos');
INSERT INTO lang VALUES('movies_left_in_cat','es','La categoría %1 debera contener %2 película(s) y no podran ser borradas.');
INSERT INTO lang VALUES('admin_orphans','es','Eliminar entradas huérfanas');
INSERT INTO lang VALUES('desc_admin_orphans','es','"Entradas huérfanas" son datos sin asignación, ejemplo: Actores, directores y/o compositores que están en la BD y no estan relacionados con ninguna película. Son el resultado de cambiar un nombre mal puesto despues de guardarlo - pero nunca de borrar entradas de películass. Una buena idea es eliminar esas entradas huérfanas: primero para liberar recursos,  y segundo ayuda a prevenir una bajada del rendimiento de la BD.');
INSERT INTO lang VALUES('orphans_found','es','Encontrada(s) %1 entrada(s) huérfana(s):');
INSERT INTO lang VALUES('no_orphans_found','es','¡Enhorabuena! No tienes entradas huérfanas.');
INSERT INTO lang VALUES('delete_orphans','es','Eliminando %1 huérfana(s):');
INSERT INTO lang VALUES('backup_db','es','Copia de seguridad de la base de datos');
INSERT INTO lang VALUES('desc_backup_db','es','Siempre es bueno hacer una copia de seguridad. Así, todos tus datos de la BD son exportados, y usar el comando SQL file. Puedes usar este comando para rellenar una base de datos vacía (ej: para la duplicación). Asegurate de no actualizar una BD con una copia más antigua de phpVideoPro - ¡puede crear muchos problemas!<BR><BR><DIV ALIGN="center"><B>¿Deseas crear la copia ahora?</B></DIV>');
INSERT INTO lang VALUES('admin','es','Administrador');
INSERT INTO lang VALUES('dupes','es','Entradas duplicadas');
INSERT INTO lang VALUES('dupe_titles_found','es','Encontrado(s) %1 título(s) con posibles duplicados:');
INSERT INTO lang VALUES('rw_media','es','Soporte editable');
INSERT INTO lang VALUES('rw_media_comment','es','El soporte mantendra fijo su espacio libre (desde que se graba).');
INSERT INTO lang VALUES('remove_empty_media','es','Eliminar soporte vacío');
INSERT INTO lang VALUES('remove_empty_media_comment','es','¿Eliminar el soporte para un mejor mantenimiento del espacio libre, cuando la última película sea borrada del mismo?');
INSERT INTO lang VALUES('movie_tone_default','es','Formato por defecto del sonido de la película');
INSERT INTO lang VALUES('movie_tone_default_comment','es','Será usado por defecto como el formato de sonido de una nueva entrada.');
INSERT INTO lang VALUES('movie_color_default','es','Formato por defecto del color de la película');
INSERT INTO lang VALUES('movie_color_default_comment','es','Será usado por defecto como el formato de sonido de una nueva entrada.');
INSERT INTO lang VALUES('site_info','es','Información del sitio');
INSERT INTO lang VALUES('site_info_comment','es','¿Qué información del sitio se mostrara en la barra del título del navegador?');
INSERT INTO lang VALUES('movie_onlabel_default','es','Información para la etiqueta por defecto');
INSERT INTO lang VALUES('movie_onlabel_default_comment','es','Por defecto para las nuevas entradas: ¿la información para esta película será incluida cuando la(s) etiqueta(s) del soporte sean generadas?');
INSERT INTO lang VALUES('config_media','es','Videos y Multimedia');
INSERT INTO lang VALUES('cookies','es','Cookies');
INSERT INTO lang VALUES('enable_cookies','es','¿Activar cookies?');
INSERT INTO lang VALUES('enable_cookies_comment','es','¿Guardar las preferencias del usuario (ej. filtros) en cookies?');
INSERT INTO lang VALUES('expire_cookies','es','Vida de las Cookies');
INSERT INTO lang VALUES('expire_cookies_comment','es','¿Cuanto tiempo durara una cookie en el navegador del usuario?');
INSERT INTO lang VALUES('session','es','Sesión');
INSERT INTO lang VALUES('day','es','Día');
INSERT INTO lang VALUES('week','es','Semana');
INSERT INTO lang VALUES('month','es','Mes');
INSERT INTO lang VALUES('preferences','es','Preferencias');
INSERT INTO lang VALUES('admin_filter','es','Configuración de los filtros por defecto');
INSERT INTO lang VALUES('admin_users','es','Configurar cuentas de usuarios');
INSERT INTO lang VALUES('user','es','Usuario');
INSERT INTO lang VALUES('login','es','Inicio de sesión');
INSERT INTO lang VALUES('data_access','es','Acceso a los datos');
INSERT INTO lang VALUES('read_access','es','Buscar entradas');
INSERT INTO lang VALUES('read_access_short','es','buscar');
INSERT INTO lang VALUES('add_access','es','Añadir nuevas entradas');
INSERT INTO lang VALUES('add_access_short','es','añadir');
INSERT INTO lang VALUES('upd_access','es','Actualizar entradas ya existentes');
INSERT INTO lang VALUES('upd_access_short','es','act');
INSERT INTO lang VALUES('del_access','es','Borrar entradas');
INSERT INTO lang VALUES('del_access_short','es','borrar');
INSERT INTO lang VALUES('admin_access','es','Acceder al menú de admininistrador');
INSERT INTO lang VALUES('admin_access_short','es','adm');
INSERT INTO lang VALUES('add_user','es','Añadir usuario');
INSERT INTO lang VALUES('actions','es','Acciones');
INSERT INTO lang VALUES('user_update_failed','es','Actualización fallida para los siguientes usuarios: %1');
INSERT INTO lang VALUES('password','es','Contraseña');
INSERT INTO lang VALUES('password_retype','es','Escribir de nuevo la contraseña');
INSERT INTO lang VALUES('admin_useredit','es','Editar la cuenta de usuario');
INSERT INTO lang VALUES('confirm_userdelete','es','Vas a eliminar al usuario #%1');
INSERT INTO lang VALUES('confirm_userdeletion','es','¿Realmente quieres eliminar al usuario? "%1" (%2)?');
INSERT INTO lang VALUES('user_delete_report','es','Resultados del proceso de borrado del usuario');
INSERT INTO lang VALUES('user_deleted','es','Borrado correcto del usuario #%1, "%2" (%3)');
INSERT INTO lang VALUES('user_delete_failed','es','Borrado del usuario #%1, "%2" (%3) fallido');
INSERT INTO lang VALUES('submit','es','Enviar');
INSERT INTO lang VALUES('welcome','es','Bienvenido a phpVideoPro');
INSERT INTO lang VALUES('login_failed','es','Fallo al iniciar sesión. Quizas escribiste mal tu contraseña o el usuario.<P />');
INSERT INTO lang VALUES('login_required','es','Tus privilegios no son suficientes para esta acción. Debes iniciar la sesión con una cuenta apropiada.<P />');
INSERT INTO lang VALUES('logout_user','es','Sesión iniciada como "%1". <A HREF="%2">Cerrar sesión</A>');
INSERT INTO lang VALUES('never','es','nunca');
INSERT INTO lang VALUES('hour','es','Hora');
INSERT INTO lang VALUES('hours','es','Horas');
INSERT INTO lang VALUES('session_purgetime','es','¿Despues de cuanto tiempo sin uso se considera una sesión inactiva?');
INSERT INTO lang VALUES('session_purgetime_comment','es','¿Cuanto tiempo puede estar un usuario sin actividad antes de cerrar la sesión?');
INSERT INTO lang VALUES('max_fontsize','es','Tamaño máximo de la fuente');
INSERT INTO lang VALUES('labeltype','es','Tipo de etiqueta');
INSERT INTO lang VALUES('layout_label','es','Escoger grosor');
INSERT INTO lang VALUES('printer','es','Impresora');
INSERT INTO lang VALUES('printer_comment','es','Si quieres imprimir los formularios (usados para etiquetas PS), necesitas los márgenes exactos para tu impresora.');
INSERT INTO lang VALUES('session_expired','es','Tu sesión ha expirado - iniciala de nuevo.');
