# ========================================================
# Bulgarian Translation phrases for phpVideoPro
# by Tsvetanka Stoyanova tsvetankas@excite.com
# iso-8859-5
# ========================================================

UPDATE pvp_languages SET charset='UTF-8' WHERE lang_id='bg';
INSERT INTO pvp_lang (message_id,lang,content) VALUES ('not_yet_implemented','bg','Съжалявам - още не е имплементиран.','');
INSERT INTO pvp_lang VALUES('medium','bg','Носител','');
INSERT INTO pvp_lang VALUES('nr','bg','Номер','');
INSERT INTO pvp_lang VALUES('title','bg','Заглавие','');
INSERT INTO pvp_lang VALUES('length','bg','Продължителност','');
INSERT INTO pvp_lang VALUES('year','bg','Година','');
INSERT INTO pvp_lang VALUES('date_rec','bg','Дата на придобиване','');
INSERT INTO pvp_lang VALUES('category','bg','Категория','');
INSERT INTO pvp_lang VALUES('medialist','bg','Списък на носителите','');
INSERT INTO pvp_lang VALUES('enter_min_free','bg','Въведете минимума свободно място на носителя, което да се визуализира:','');
INSERT INTO pvp_lang VALUES('display','bg','Визуализирай','');
INSERT INTO pvp_lang VALUES('free_space_on_media','bg','Следните носители имат поне %1 минута свободно място:','');
INSERT INTO pvp_lang VALUES('free','bg','Свободно','');
INSERT INTO pvp_lang VALUES('content','bg','Съдържание','');
INSERT INTO pvp_lang VALUES('filter_setup','bg','Настройка на филтри','');
INSERT INTO pvp_lang VALUES('mediatype','bg','Тип носител','');
INSERT INTO pvp_lang VALUES('screen','bg','Екранен формат','');
INSERT INTO pvp_lang VALUES('picture','bg','Цветови формат','');
INSERT INTO pvp_lang VALUES('tone','bg','Звуков формат','');
INSERT INTO pvp_lang VALUES('longplay','bg','Продължителност / LongPlay','');
INSERT INTO pvp_lang VALUES('fsk','bg','PG','');
INSERT INTO pvp_lang VALUES('actor','bg','Артист','');
INSERT INTO pvp_lang VALUES('actors','bg','Артисти','');
INSERT INTO pvp_lang VALUES('director','bg','Режисьор','');
INSERT INTO pvp_lang VALUES('directors','bg','Режисьори','');
INSERT INTO pvp_lang VALUES('composer','bg','Композитор','');
INSERT INTO pvp_lang VALUES('music','bg','Композитор','');
INSERT INTO pvp_lang VALUES('min','bg','min','');
INSERT INTO pvp_lang VALUES('max','bg','max','');
INSERT INTO pvp_lang VALUES('s/w','bg','Черно-бял','');
INSERT INTO pvp_lang VALUES('farbe','bg','Цветен','');
INSERT INTO pvp_lang VALUES('3d','bg','3D','');
INSERT INTO pvp_lang VALUES('edit_entry','bg','Редактирай запис %1','');
INSERT INTO pvp_lang VALUES('view_entry','bg','Визуализирай запис %1','');
INSERT INTO pvp_lang VALUES('add_entry','bg','Добави запис','');
INSERT INTO pvp_lang VALUES('unknown','bg','неизвестен','');
INSERT INTO pvp_lang VALUES('country','bg','Страна','');
INSERT INTO pvp_lang VALUES('medianr','bg','Номер носител','');
INSERT INTO pvp_lang VALUES('highest_db_entries','bg','най-голям номер в базата данни','');
INSERT INTO pvp_lang VALUES('no','bg','Не','');
INSERT INTO pvp_lang VALUES('yes','bg','Да','');
INSERT INTO pvp_lang VALUES('medialength','bg','Продължителност на носителя','');
INSERT INTO pvp_lang VALUES('minute_abbrev','bg','min','');
INSERT INTO pvp_lang VALUES('source','bg','Източник','');
INSERT INTO pvp_lang VALUES('staff','bg','Екип','');
INSERT INTO pvp_lang VALUES('name','bg','Име','');
INSERT INTO pvp_lang VALUES('first_name','bg','Собствено име','');
INSERT INTO pvp_lang VALUES('in_list','bg','в списъка','');
INSERT INTO pvp_lang VALUES('comments','bg','Коментари','');
INSERT INTO pvp_lang VALUES('cancel','bg','Отказ','');
INSERT INTO pvp_lang VALUES('create','bg','Създай','');
INSERT INTO pvp_lang VALUES('update','bg','Актуализирай','');
INSERT INTO pvp_lang VALUES('edit','bg','Редактирай','');
INSERT INTO pvp_lang VALUES('delete','bg','Изтрий','');
INSERT INTO pvp_lang VALUES('invalid_media_nr','bg','Номерът носител, който въведохте, е непълен, или невалиден. Трябва да укажете <b>номер</b> в <b>двете</b> полета за номер на носител (MediaNr).','');
INSERT INTO pvp_lang VALUES('warning','bg','предупреждение','');
INSERT INTO pvp_lang VALUES('of_aquiration','bg','на придобиване','');
INSERT INTO pvp_lang VALUES('wrong_date','bg','Датата, %1 която въведохте, (%2) е невалидна. При въвеждане на дата тук, моля въведете деня в първото, месеца във второто и годината в третото поле, като използвате само цифри. Ако не сте сигурни за точната, въведете нули във въпросните полета, например: "00" "02" "2002" означава "евентуално през февруари 2000", или пък "00" "00" "0000" означава "някога".).','');
INSERT INTO pvp_lang VALUES('incomplete_date','bg','Ако не знаете точната дата, но например, знаете само, че този диск е от 2000г., заместете неизвестните данни с нули. В нашия пример датата трябва да изглежда така: "00" "00" "2000".','');
INSERT INTO pvp_lang VALUES('dupe_id_entered','bg','В базата данни вече има запис с това ID. Моля натиснете бутона "Back" в браузъра и поправете въведеното. Съвет: До полето за въвеждане, в което зададохте номера на носителя, има поле Select-Box. Полето Select-Box указва най-голямата стойност ID на носител. Обикновено е добре, ако новият носител е с едно по-голям (първите четири цифри) или пък новият филм на същия носител е с едно по-голям при второто (двуцифрено) число.','');
INSERT INTO pvp_lang VALUES('create_success','bg','Записът е създаден успешно','');
INSERT INTO pvp_lang VALUES('update_failed','bg','Записът не беше актуализиран','');
INSERT INTO pvp_lang VALUES('update_success','bg','Записът е актуализиран успешно','');
INSERT INTO pvp_lang VALUES('about','bg','За / About','');
INSERT INTO pvp_lang VALUES('history','bg','История / History','');
INSERT INTO pvp_lang VALUES('view','bg','Визуалирай','');
INSERT INTO pvp_lang VALUES('deleting_entry','bg','Изтриване на запис %1','');
INSERT INTO pvp_lang VALUES('free_space_title','bg','Свободно място на носителя','');
INSERT INTO pvp_lang VALUES('filter','bg','Филтър','');
INSERT INTO pvp_lang VALUES('set_filter','bg','Задай филтъра','');
INSERT INTO pvp_lang VALUES('unset_filter','bg','Изчисти филтъра','');
INSERT INTO pvp_lang VALUES('taperest_absolute','bg','TapeRest (absolute)','');
INSERT INTO pvp_lang VALUES('taperest_filtered','bg','TapeRest (filtered)','');
INSERT INTO pvp_lang VALUES('help','bg','Помощ','');
INSERT INTO pvp_lang VALUES('general','bg','Общи','');
INSERT INTO pvp_lang VALUES('sure_to_delete','bg','Сигурен(а) ли сте, че искате да изтриете всичките данни за %1','');
INSERT INTO pvp_lang VALUES('nobody_named','bg','There\'s no other movie by a %1 named %2 %3 in this db, so I remove this entry from the %1\'s table.','');
INSERT INTO pvp_lang VALUES('compose_person','bg','композитор','');
INSERT INTO pvp_lang VALUES('director_person','bg','режисьор','');
INSERT INTO pvp_lang VALUES('check_completed','bg','Проверката е завършена','');
INSERT INTO pvp_lang VALUES('delete_remaining','bg','сега изтриваме от базата данни останалите данни за този филм','');
INSERT INTO pvp_lang VALUES('ok','bg','OK','');
INSERT INTO pvp_lang VALUES('not_ok','bg','Неуспешно','');
INSERT INTO pvp_lang VALUES('recalc_free','bg','Преизчисляване на оставащото празно място върху носителя','');
INSERT INTO pvp_lang VALUES('tapelist_update_failed','bg','Списъкът на носителите не беше актуализиран успешно','');
INSERT INTO pvp_lang VALUES('no_entry_in_tapelist','bg','Failed - в списъка с носителите няма записи','');
INSERT INTO pvp_lang VALUES('finnished','bg','Завършено','');
INSERT INTO pvp_lang VALUES('time_left','bg','%1 минута е останала','');
INSERT INTO pvp_lang VALUES('configuration','bg','Конфигуриране','');
INSERT INTO pvp_lang VALUES('index','bg','Индекс','');
INSERT INTO pvp_lang VALUES('intro','bg','Въведение','');
INSERT INTO pvp_lang VALUES('menues','bg','Менюта','');
INSERT INTO pvp_lang VALUES('back','bg','Назад / Back','');
INSERT INTO pvp_lang VALUES('close','bg','Затвори','');
INSERT INTO pvp_lang VALUES('help_about','bg','Помощ за','');
INSERT INTO pvp_lang VALUES('actors_list','bg','Списък на артистите','');
INSERT INTO pvp_lang VALUES('directors_list','bg','Списък на режисьорите','');
INSERT INTO pvp_lang VALUES('music_list','bg','Списък на композиторите','');
INSERT INTO pvp_lang VALUES('no_entries_found','bg','Не са намерени записи','');
INSERT INTO pvp_lang VALUES('no_space_of','bg','В базата данни не беше намерен носител, на който да има минимум %1 минути свободно място.','');
INSERT INTO pvp_lang VALUES('howto','bg','Как да ... /How to...','');
INSERT INTO pvp_lang VALUES('howto_lang','bg','Как да създадем файл за нов език','');
INSERT INTO pvp_lang VALUES('howto_help','bg','Как да създадем помощен файл','');
INSERT INTO pvp_lang VALUES('howto_templates','bg','Как да създадем нов набор от темплейти','');
INSERT INTO pvp_lang VALUES('language_settings','bg','Настройки за езика','');
INSERT INTO pvp_lang VALUES('scan_new_lang_files','bg','Да сканирам ли за нови езикови файлове?','');
INSERT INTO pvp_lang VALUES('scan_new_lang_comment','bg','(Ако създадохте файл за собствения си език и го поставихте в директорията setup, phpVideoPro ще го потърси)','');
INSERT INTO pvp_lang VALUES('select_add_lang','bg','Изберете допълнителен език, който да се инсталира','');
INSERT INTO pvp_lang VALUES('select_add_lang_comment','bg','(Английският вече е инсталиран и винаги ще бъде - вижте по-долу. За други езици, които също вече са инсталирани, също вижте по-долу.)','');
INSERT INTO pvp_lang VALUES('no_add_lang','bg','Няма достъпни допълнителни езици.','');
INSERT INTO pvp_lang VALUES('refresh_lang','bg','Презареди езика','');
INSERT INTO pvp_lang VALUES('refresh_lang_comment','bg','(вмъкни повторно в базата данни фразите от езиковия файл)','');
INSERT INTO pvp_lang VALUES('none','bg','Нито един','');
INSERT INTO pvp_lang VALUES('select_primary_lang','bg','Изберете основен език','');
INSERT INTO pvp_lang VALUES('select_primary_lang_comment','bg','(за липсващи фрази винаги ще се извиква английският файл)','');
INSERT INTO pvp_lang VALUES('colors','bg','Цветове','');
INSERT INTO pvp_lang VALUES('page_bg','bg','Фон на страницата','');
INSERT INTO pvp_lang VALUES('table_bg','bg','Фон на таблицата','');
INSERT INTO pvp_lang VALUES('th_bg','bg','Фон на колонтитулите на таблицата','');
INSERT INTO pvp_lang VALUES('template_set','bg','Задаване на темплейт','');
INSERT INTO pvp_lang VALUES('start_pvp','bg','Стартирай phpVideoPro','');
INSERT INTO pvp_lang VALUES('hit_back_to_correct','bg','Натиснете бутона "Back", за да поправите грешката.','');
INSERT INTO pvp_lang VALUES('goto_entry','bg','Директно отидете на запис:','');
INSERT INTO pvp_lang VALUES('start_page','bg','Начална страница','');
INSERT INTO pvp_lang VALUES('invalid_fsk','bg','Стойността, въведена за PG ("%1"), е невалидна. PG означава Parental Guide (Родителски контрол), т.е минималната възраст, под която на никому не трябва да давате достъп до този филм.','');
INSERT INTO pvp_lang VALUES('counter_start_stop','bg','Брояч Пускане/Спиране','');
INSERT INTO pvp_lang VALUES('other_pages','bg','Други страници','');
INSERT INTO pvp_lang VALUES('commercials','bg','Реклами','');
INSERT INTO pvp_lang VALUES('cut_off','bg','отрязан','');
INSERT INTO pvp_lang VALUES('display_limit','bg','Лимит за визуализиране','');
INSERT INTO pvp_lang VALUES('display_limit_comment','bg','(по колко реда на страница да се показват при списъците)','');
INSERT INTO pvp_lang VALUES('print_label','bg','Отпечатай Етикет:','');
INSERT INTO pvp_lang VALUES('howto_label','bg','Как да се създадат/конфигурират темплейти за етикети','');
INSERT INTO pvp_lang VALUES('label','bg','Етикет','');
INSERT INTO pvp_lang VALUES('print','bg','Отпечатай','');
