# ========================================================
# Portuguese Language File created by phpVideoPro v0.8.0p19
# ========================================================

UPDATE languages SET charset='UTF-8' WHERE lang_id='pt';
INSERT INTO lang VALUES ('about','pt','Acerca','');
INSERT INTO lang VALUES ('actions','pt','Acções','');
INSERT INTO lang VALUES ('actor','pt','Actor','');
INSERT INTO lang VALUES ('actors','pt','Actores','');
INSERT INTO lang VALUES ('actors_list','pt','Lista de Actores','');
INSERT INTO lang VALUES ('actor_persons','pt','Actores','');
INSERT INTO lang VALUES ('add_access','pt','Pode adicionar novas entradas','');
INSERT INTO lang VALUES ('add_access_short','pt','adicionar','');
INSERT INTO lang VALUES ('add_entry','pt','Adicionar entrada','');
INSERT INTO lang VALUES ('add_user','pt','Adicionar utilizador','');
INSERT INTO lang VALUES ('admin','pt','Administrador','');
INSERT INTO lang VALUES ('admin_access','pt','Pode aceder aos menus de administrador','');
INSERT INTO lang VALUES ('admin_avlang','pt','Editar disponibilidade de linguagens para áudio e legendas','');
INSERT INTO lang VALUES ('admin_cats','pt','Categorias Administrativas','');
INSERT INTO lang VALUES ('admin_disktypes','pt','Editar Tipo de Discos','');
INSERT INTO lang VALUES ('admin_filter','pt','Definições de Filtros padrão','');
INSERT INTO lang VALUES ('admin_movietech','pt','Editar dados Técnicos do Filme','');
INSERT INTO lang VALUES ('admin_orphans','pt','Remover entradas soltas','');
INSERT INTO lang VALUES ('admin_orphan_fs','pt','Remover ficheiros soltos','');
INSERT INTO lang VALUES ('admin_printers','pt','Configurar impressoras','');
INSERT INTO lang VALUES ('admin_pstemplates','pt','Editar modelos PSLabel','');
INSERT INTO lang VALUES ('admin_required','pt','Esta acção necessita previlégios de administrador!','');
INSERT INTO lang VALUES ('admin_sessions','pt','Gerir Sessões','');
INSERT INTO lang VALUES ('admin_translations','pt','Editar Traduções','');
INSERT INTO lang VALUES ('admin_useredit','pt','Editar contas de utilizador','');
INSERT INTO lang VALUES ('admin_users','pt','Gerir contas de utilizador','');
INSERT INTO lang VALUES ('audio_ts','pt','Áudio','');
INSERT INTO lang VALUES ('back','pt','Retroceder','');
INSERT INTO lang VALUES ('backup_compress','pt','Activar compressão?','');
INSERT INTO lang VALUES ('backup_db','pt','Salvaguardar Base de Dados','');
INSERT INTO lang VALUES ('backup_db_cats','pt','Salvaguardar categorias','');
INSERT INTO lang VALUES ('backup_db_complete','pt','Salvaguardar Base de Dados completa(incl. preferências tecnicas e de dados)','');
INSERT INTO lang VALUES ('backup_db_movie_internal','pt','Salvaguardar todos os filmes usando o formato interno do phpVideoPro','');
INSERT INTO lang VALUES ('backup_db_sysconf','pt','Salvaguardar configurações de sistema e preferências padrão','');
INSERT INTO lang VALUES ('backup_file_corrupt','pt','O Ficheiro de Salvaguarda seleccionado está corrupto - não é possível restaurar a partir deste!','');
INSERT INTO lang VALUES ('backup_file_unreadable','pt','Não é possível lever o ficheiro de salvaguarda - tenha a certeza que as permissões do ficheiro estão definindas correctamente!','');
INSERT INTO lang VALUES ('bubble_help_enable','pt','Activar BubbleHelp?','');
INSERT INTO lang VALUES ('bubble_help_enable_comment','pt','Se activado, a ajuda de conteúdo-susceptível é mostrada para alguns itens se mover o rato por cima deles(e.g. no botão da janela do conjunto de Padrões de Aplicações).','');
INSERT INTO lang VALUES ('button_backup','pt','Cópia de Segurança','');
INSERT INTO lang VALUES ('button_restore','pt','Restaurar','');
INSERT INTO lang VALUES ('cache_enable','pt','Activar cache no navegador/proxy?','');
INSERT INTO lang VALUES ('cache_enable_comment','pt','Como phpVideoPro é uma aplicação dinâmica, gerar páginas baseadas em informação da base de dados em cada pedido, pode querer desactivar colocar em cache as páginas geradas. Por vezes, isto é muito útil para utilizadores de MSIE...','');
INSERT INTO lang VALUES ('cancel','pt','Cancelar','');
INSERT INTO lang VALUES ('categories','pt','Categorias','');
INSERT INTO lang VALUES ('category','pt','Categoria','');
INSERT INTO lang VALUES ('catlist_alpha','pt','Lista de media em ordem alfabética, ordenada por categoria','');
INSERT INTO lang VALUES ('cat_action','pt','Acção','');
INSERT INTO lang VALUES ('cat_adventure','pt','Aventura','');
INSERT INTO lang VALUES ('cat_agents','pt','Agente','');
INSERT INTO lang VALUES ('cat_animals','pt','Animais','');
INSERT INTO lang VALUES ('cat_bible','pt','Biblía','');
INSERT INTO lang VALUES ('cat_biography','pt','Biografia','');
INSERT INTO lang VALUES ('cat_camera','pt','Câmera','');
INSERT INTO lang VALUES ('cat_cartoon','pt','Desenhos-Animados','');
INSERT INTO lang VALUES ('cat_catastrophe','pt','Catástrofe','');
INSERT INTO lang VALUES ('cat_children','pt','Crianças','');
INSERT INTO lang VALUES ('cat_comedy','pt','Comédia','');
INSERT INTO lang VALUES ('cat_concert','pt','Concerto','');
INSERT INTO lang VALUES ('cat_documentary','pt','Documentário','');
INSERT INTO lang VALUES ('cat_fairytale','pt','Contos-de-Fadas','');
INSERT INTO lang VALUES ('cat_fantasy','pt','Fantasia','');
INSERT INTO lang VALUES ('cat_handle_empty','pt','O campo de categoria não deve estar vazio. Por favor volte atrás e corrija isto para categoria #%1.','');
INSERT INTO lang VALUES ('cat_history','pt','História','');
INSERT INTO lang VALUES ('cat_internal_name','pt','Tratar','');
INSERT INTO lang VALUES ('cat_love','pt','Histórias de Amor','');
INSERT INTO lang VALUES ('cat_misc','pt','Vários','');
INSERT INTO lang VALUES ('cat_music','pt','Musica','');
INSERT INTO lang VALUES ('cat_musicmovie','pt','Filmes de Música','');
INSERT INTO lang VALUES ('cat_nature','pt','Natureza','');
INSERT INTO lang VALUES ('cat_opera','pt','Ópera','');
INSERT INTO lang VALUES ('cat_operetta','pt','Opereta','');
INSERT INTO lang VALUES ('cat_party','pt','Festa','');
INSERT INTO lang VALUES ('cat_problem','pt','Problema','');
INSERT INTO lang VALUES ('cat_report','pt','Reportagem','');
INSERT INTO lang VALUES ('cat_satire','pt','Sátira','');
INSERT INTO lang VALUES ('cat_scary','pt','Filmes de Terror','');
INSERT INTO lang VALUES ('cat_sf','pt','Ficção Científica','');
INSERT INTO lang VALUES ('cat_show','pt','Espectáculo','');
INSERT INTO lang VALUES ('cat_spy','pt','Filmes de Espionagem','');
INSERT INTO lang VALUES ('cat_stage','pt','Palco','');
INSERT INTO lang VALUES ('cat_trans_update_failed','pt','Actualização falhou para a tradução das seguintes categorias: %1','');
INSERT INTO lang VALUES ('cat_travesty','pt','Travesti','');
INSERT INTO lang VALUES ('cat_update_failed','pt','Actualização falhou para as seguintes categorias: %1','');
INSERT INTO lang VALUES ('cat_vacation','pt','Férias','');
INSERT INTO lang VALUES ('cat_videoclip','pt','Clip de Música','');
INSERT INTO lang VALUES ('cat_war','pt','Filmes de Guerra','');
INSERT INTO lang VALUES ('cat_western','pt','Velho Oeste','');
INSERT INTO lang VALUES ('cat_westerncomedy','pt','Comédia-Velho Oeste','');
INSERT INTO lang VALUES ('cat_xmas','pt','Natal','');
INSERT INTO lang VALUES ('change_disktype','pt','Trocar Disco para %1','');
INSERT INTO lang VALUES ('change_media_length','pt','Alterar Tamanho de Media','');
INSERT INTO lang VALUES ('change_media_length_for','pt','Por Favor insira a capacidade para %1','');
INSERT INTO lang VALUES ('change_nr','pt','Alterar Número de Media/Tipo de Media para %1','');
INSERT INTO lang VALUES ('change_rc','pt','Alterar Código de Região','');
INSERT INTO lang VALUES ('change_rc_for','pt','Alterar Código de Região para %1','');
INSERT INTO lang VALUES ('check_completed','pt','Verificação completa','');
INSERT INTO lang VALUES ('check_media_delete','pt','Verificando se a média está vazia','');
INSERT INTO lang VALUES ('clean_restore','pt','Limpar (remover) dados antigos antes de restaurar','');
INSERT INTO lang VALUES ('close','pt','Fechar','');
INSERT INTO lang VALUES ('comments','pt','Comentários','');
INSERT INTO lang VALUES ('comment_not_string','pt','O comentário inserido contem caracteres inválidos (para prevenir injecção de código, apenas letras, digitos e \"-\" são permitidos).','');
INSERT INTO lang VALUES ('commercials','pt','Comerciais','');
INSERT INTO lang VALUES ('composer','pt','Compositor','');
INSERT INTO lang VALUES ('compose_person','pt','compositor','');
INSERT INTO lang VALUES ('compose_persons','pt','Compositores','');
INSERT INTO lang VALUES ('configuration','pt','Configuração','');
INSERT INTO lang VALUES ('config_media','pt','Filmes e Media','');
INSERT INTO lang VALUES ('confirm_delete','pt','Deseja mesmo apagar esta gravação?','');
INSERT INTO lang VALUES ('confirm_prilang','pt','Pretende mesmo alterar a linguagem primária padrão  para TODOS os (novos) utilizadores?','');
INSERT INTO lang VALUES ('confirm_userdelete','pt','Está prestes a apagar o utilizador #%1','');
INSERT INTO lang VALUES ('confirm_userdeletion','pt','Está prestes a apagar o utilizador \"%1\" (%2). O que deverá ser feito com a media do utilizador?','');
INSERT INTO lang VALUES ('content','pt','Conteúdo','');
INSERT INTO lang VALUES ('counter_start_stop','pt','Contador Iniciar/Parar','');
INSERT INTO lang VALUES ('countries','pt','Países','');
INSERT INTO lang VALUES ('country','pt','País','');
INSERT INTO lang VALUES ('create','pt','Criar','');
INSERT INTO lang VALUES ('create_success','pt','Entrada criada com sucesso','');
INSERT INTO lang VALUES ('credits','pt','Créditos','');
INSERT INTO lang VALUES ('cut_off','pt','Cortados','');
INSERT INTO lang VALUES ('data_access','pt','Acesso de Dados','');
INSERT INTO lang VALUES ('date_format','pt','Formatar Dados','');
INSERT INTO lang VALUES ('date_format_comment','pt','Qual o formato a usar para mostrar a data','');
INSERT INTO lang VALUES ('date_is_nan','pt','Data, mês e ano têm que ser numéricos!n(i.e. apenas digitos são permitidos)','');
INSERT INTO lang VALUES ('date_rec','pt','Data adquirida','');
INSERT INTO lang VALUES ('day','pt','Dia','');
INSERT INTO lang VALUES ('db_stats','pt','Estatísticas','');
INSERT INTO lang VALUES ('delete','pt','Apagar','');
INSERT INTO lang VALUES ('delete_lang','pt','Apagar linguagem','');
INSERT INTO lang VALUES ('delete_lang_comment','pt','Apagar todas as frases da linguagem especifícada da base de dados. Isto não vai apagar o ficheiro da linguagem, para poder reinserir as frases posteiormente (se não apagar o ficheiro você mesmo)','');
INSERT INTO lang VALUES ('delete_orphans','pt','Apagando %1 orfão(s):','');
INSERT INTO lang VALUES ('delete_remaining','pt','apagando agora dados restantes para este filme da base de dados','');
INSERT INTO lang VALUES ('deleting_entry','pt','Apagando a entrada %1','');
INSERT INTO lang VALUES ('del_access','pt','Pode apagar entradas','');
