# ========================================================
# Dutch Language File created by phpVideoPro v0.4.6p5
# Original by Tom Albers
# ========================================================

UPDATE languages SET charset='UTF-8' WHERE lang_id='nl';
INSERT INTO lang VALUES ('about','nl','Over...','');
INSERT INTO lang VALUES ('actor','nl','Acteur','');
INSERT INTO lang VALUES ('actors','nl','Acteurs','');
INSERT INTO lang VALUES ('actors_list','nl','Lijst van acteurs','');
INSERT INTO lang VALUES ('add_entry','nl','Toevoegen','');
INSERT INTO lang VALUES ('back','nl','Terug','');
INSERT INTO lang VALUES ('cancel','nl','Annuleer','');
INSERT INTO lang VALUES ('category','nl','Categorie','');
INSERT INTO lang VALUES ('check_completed','nl','Controle gereed','');
INSERT INTO lang VALUES ('close','nl','Sluit','');
INSERT INTO lang VALUES ('colors','nl','Kleuren','');
INSERT INTO lang VALUES ('comments','nl','Opmerkingen','');
INSERT INTO lang VALUES ('commercials','nl','Reclame','');
INSERT INTO lang VALUES ('composer','nl','Komponist','');
INSERT INTO lang VALUES ('compose_person','nl','komponist','');
INSERT INTO lang VALUES ('configuration','nl','Configuratie','');
INSERT INTO lang VALUES ('content','nl','Inhoud','');
INSERT INTO lang VALUES ('counter_start_stop','nl','Teller Start/Stop','');
INSERT INTO lang VALUES ('country','nl','Land','');
INSERT INTO lang VALUES ('create','nl','Creeër','');
INSERT INTO lang VALUES ('create_success','nl','Opgeslagen!','');
INSERT INTO lang VALUES ('cut_off','nl','Afgelopen op','');
INSERT INTO lang VALUES ('date_rec','nl','Datum opname/koop','');
INSERT INTO lang VALUES ('delete','nl','Verwijderen','');
INSERT INTO lang VALUES ('delete_remaining','nl','Verwijderen van de overgebleven gegevens van de film uit de database','');
INSERT INTO lang VALUES ('deleting_entry','nl','Verwijder %1','');
INSERT INTO lang VALUES ('director','nl','Regisseur','');
INSERT INTO lang VALUES ('directors','nl','Regisseurs','');
INSERT INTO lang VALUES ('directors_list','nl','Lijst van regisseurs','');
INSERT INTO lang VALUES ('director_person','nl','regisseur','');
INSERT INTO lang VALUES ('display','nl','Toon','');
INSERT INTO lang VALUES ('dupe_id_entered','nl','Er is al een film opgeslagen onder dit mediumnummer. Ga terug en pas dit aan.','');
INSERT INTO lang VALUES ('edit','nl','Wijzigen','');
INSERT INTO lang VALUES ('edit_entry','nl','wijzig %1','');
INSERT INTO lang VALUES ('enter_min_free','nl','Hoeveel ruimte moet er minimaal vrij zijn:','');
INSERT INTO lang VALUES ('farbe','nl','Kleur','');
INSERT INTO lang VALUES ('filter_setup','nl','Filter configuratie','');
INSERT INTO lang VALUES ('finnished','nl','Klaar','');
INSERT INTO lang VALUES ('first_name','nl','Voornaam','');
INSERT INTO lang VALUES ('free','nl','Vrij','');
INSERT INTO lang VALUES ('free_space_on_media','nl','De volgende mediums hebben minimaal %1 vrije ruimte:','');
INSERT INTO lang VALUES ('free_space_title','nl','Vrije ruimte op medium','');
INSERT INTO lang VALUES ('fsk','nl','ML','');
INSERT INTO lang VALUES ('general','nl','Algemeen','');
INSERT INTO lang VALUES ('goto_entry','nl','Ga direct naar:','');
INSERT INTO lang VALUES ('help_about','nl','Help Over','');
INSERT INTO lang VALUES ('highest_db_entries','nl','Hoogste nummers in de database','');
INSERT INTO lang VALUES ('history','nl','Geschiedenis...','');
INSERT INTO lang VALUES ('hit_back_to_correct','nl','Druk op de \"Terug\" button om de fout te herstellen.','');
INSERT INTO lang VALUES ('howto','nl','Hoe...','');
INSERT INTO lang VALUES ('howto_help','nl','How maak ik een nieuw help bestand','');
INSERT INTO lang VALUES ('howto_lang','nl','Hoe maak ik een nieuw taal bestand','');
INSERT INTO lang VALUES ('howto_templates','nl','Hoe maak ik een nieuwe template','');
INSERT INTO lang VALUES ('incomplete_date','nl','Indien je niet de exacte datum weet, maar bijvoorbeeld alleen dat u het hebt opgenomen inhet jaar 2000, pas dan alleen het jaar gedeelte in de datum aan.','');
INSERT INTO lang VALUES ('invalid_fsk','nl','De waarde van %1 is ongelig. %1 betekent Minimum Leeftijd.','');
INSERT INTO lang VALUES ('invalid_media_nr','nl','Het ingevoerde medianummer is opgeldig of incompleet. U moet een <b>nummer</b> in <b>beide</b> velden invullen.','');
INSERT INTO lang VALUES ('in_list','nl','In de lijst','');
INSERT INTO lang VALUES ('language_settings','nl','Taal instellingen','');
INSERT INTO lang VALUES ('length','nl','Lengte','');
INSERT INTO lang VALUES ('medialength','nl','Medialengte','');
INSERT INTO lang VALUES ('medialist','nl','Medialijst','');
INSERT INTO lang VALUES ('menues','nl','Menu','');
INSERT INTO lang VALUES ('music','nl','Muziek','');
INSERT INTO lang VALUES ('music_list','nl','Lijst van componisten','');
INSERT INTO lang VALUES ('name','nl','Naam','');
INSERT INTO lang VALUES ('no','nl','Nee','');
INSERT INTO lang VALUES ('none','nl','Geen','');
INSERT INTO lang VALUES ('not_ok','nl','Mislukt','');
INSERT INTO lang VALUES ('not_yet_implemented','nl','Sorry - nog niet geimplementeerd.','');
INSERT INTO lang VALUES ('no_add_lang','nl','Geen additoneel taalbestand gevonden.','');
INSERT INTO lang VALUES ('no_entries_found','nl','Niets gevonden','');
INSERT INTO lang VALUES ('no_entry_in_tapelist','nl','Helaas, geen film gevonden.','');
INSERT INTO lang VALUES ('no_space_of','nl','Er is geen medium gevonden met %1 minuten vrije ruimte','');
INSERT INTO lang VALUES ('of_aquiration','nl','aankoop/opname','');
INSERT INTO lang VALUES ('page_bg','nl','Pagina achtergrond','');
INSERT INTO lang VALUES ('picture','nl','Kleurformaat','');
INSERT INTO lang VALUES ('recalc_free','nl','Vrije ruimte aan het berekenen voor dit medium.','');
INSERT INTO lang VALUES ('refresh_lang','nl','Overschrijf taalbestand','');
INSERT INTO lang VALUES ('refresh_lang_comment','nl','(Indien er een wijziging heeft plaats gevonden in het taalbestand (wellicht doordat u een taalfout heeft gevonden), dan kunt u hier het taalbestand opnieuw laten inlezen)','');
INSERT INTO lang VALUES ('s/w','nl','z/w','');
INSERT INTO lang VALUES ('scan_new_lang_comment','nl','(Indien u een nieuw taalbestand hebt gemaakt in die in de setup directory heeft geplaatst, dan kunt u hiermee phpVideoPro er naar laten zoeken)','');
INSERT INTO lang VALUES ('scan_new_lang_files','nl','Zoeken naar nieuwe taalbestanden?','');
INSERT INTO lang VALUES ('screen','nl','Beeldformaat','');
INSERT INTO lang VALUES ('select_add_lang','nl','Selecteer additioneel taalbestand','');
INSERT INTO lang VALUES ('select_add_lang_comment','nl','(Als na het scannen er additionele taalbestanden gevonden zijn, kunt u die hier selecteren. Deze zullen dan worden geinstelleerd.)','');
INSERT INTO lang VALUES ('select_primary_lang','nl','Selecteer taal','');
INSERT INTO lang VALUES ('select_primary_lang_comment','nl','(Voor niet vertaalde delen, zal er worden teruggevallen op het engels.)','');
INSERT INTO lang VALUES ('set_filter','nl','Filter instellen','');
INSERT INTO lang VALUES ('source','nl','Bron','');
INSERT INTO lang VALUES ('staff','nl','Staf','');
INSERT INTO lang VALUES ('start_page','nl','Start pagina','');
INSERT INTO lang VALUES ('sure_to_delete','nl','Weet u zeker dat u alles wilt verwijderen van %1','');
INSERT INTO lang VALUES ('table_bg','nl','Tabel achtergrond','');
INSERT INTO lang VALUES ('tapelist_update_failed','nl','Het is niet gelukt om het bijtewerken','');
INSERT INTO lang VALUES ('taperest_absolute','nl','Vrije ruimte (totaal)','');
INSERT INTO lang VALUES ('taperest_filtered','nl','Vrije ruimte (met filter)','');
INSERT INTO lang VALUES ('template_set','nl','Template','');
INSERT INTO lang VALUES ('th_bg','nl','Tabelkoppen achtergrond','');
INSERT INTO lang VALUES ('time_left','nl','%1 minuten beschikbaar','');
INSERT INTO lang VALUES ('title','nl','Titel','');
INSERT INTO lang VALUES ('tone','nl','Geluidformat','');
INSERT INTO lang VALUES ('unknown','nl','Onbekend','');
INSERT INTO lang VALUES ('unset_filter','nl','Filter opnieuw instellen','');
INSERT INTO lang VALUES ('update','nl','Aanpassen','');
INSERT INTO lang VALUES ('update_failed','nl','Niet gelukt!','');
INSERT INTO lang VALUES ('update_success','nl','Wijzigingen opgeslagen!','');
INSERT INTO lang VALUES ('view','nl','Beeld','');
INSERT INTO lang VALUES ('view_entry','nl','bekijk %1','');
INSERT INTO lang VALUES ('warning','nl','waarschuwing','');
INSERT INTO lang VALUES ('wrong_date','nl','De datum %1 die je hebt opgegeven (%2) is ongeldig. De datum moet volgens het volgende systeem worden ingevoerd: \"JJJJ-MM-DD\"','');
INSERT INTO lang VALUES ('year','nl','Jaar','');
INSERT INTO lang VALUES ('yes','nl','Ja','');
