# ========================================================
# Dutch Language File created by phpVideoPro v0.7.6
# ========================================================

UPDATE pvp_languages SET charset='UTF-8' WHERE lang_id='nl';
INSERT INTO pvp_lang VALUES ('about','nl','Over...',' ');
INSERT INTO pvp_lang VALUES ('actions','nl','Acties','');
INSERT INTO pvp_lang VALUES ('actor','nl','Acteur',' ');
INSERT INTO pvp_lang VALUES ('actors','nl','Acteurs',' ');
INSERT INTO pvp_lang VALUES ('actors_list','nl','Lijst van acteurs',' ');
INSERT INTO pvp_lang VALUES ('actor_persons','nl','Acteurs',' ');
INSERT INTO pvp_lang VALUES ('add_access','nl','Toevoegen nieuwe gegevens',' ');
INSERT INTO pvp_lang VALUES ('add_access_short','nl','Toevoegen',' ');
INSERT INTO pvp_lang VALUES ('add_entry','nl','Toevoegen',' ');
INSERT INTO pvp_lang VALUES ('add_user','nl','Nieuwe gebruiker',' ');
INSERT INTO pvp_lang VALUES ('admin_access','nl','Admin rechten',' ');
INSERT INTO pvp_lang VALUES ('admin_avlang','nl','Wijzig beschikbaarheid talen voor audio en ondertiteling ',' ');
INSERT INTO pvp_lang VALUES ('admin_cats','nl','Administratie categorien',' ');
INSERT INTO pvp_lang VALUES ('admin_disktypes','nl','Wijzig disktypes',' ');
INSERT INTO pvp_lang VALUES ('admin_filter','nl','Standaard filter settings',' ');
INSERT INTO pvp_lang VALUES ('admin_movietech','nl','Wijzig technische film gegevens',' ');
INSERT INTO pvp_lang VALUES ('admin_orphans','nl','Verwijder wees items',' ');
INSERT INTO pvp_lang VALUES ('admin_orphan_fs','nl','Verwijderen van \"wees\" bestanden','');
INSERT INTO pvp_lang VALUES ('admin_printers','nl','Wijzig printers',' ');
INSERT INTO pvp_lang VALUES ('admin_pstemplates','nl','Wijzig PSLabel template',' ');
INSERT INTO pvp_lang VALUES ('admin_required','nl','Voor deze actie heeft u admin rechten nodig!','');
INSERT INTO pvp_lang VALUES ('admin_sessions','nl','Beheer sessies',' ');
INSERT INTO pvp_lang VALUES ('admin_translations','nl','Wijzig vertaling',' ');
INSERT INTO pvp_lang VALUES ('admin_useredit','nl','Wijzig gebruikers account',' ');
INSERT INTO pvp_lang VALUES ('admin_users','nl','Beheer gebruikers accounts',' ');
INSERT INTO pvp_lang VALUES ('back','nl','Terug',' ');
INSERT INTO pvp_lang VALUES ('backup_compress','nl','Activeer compressie',' ');
INSERT INTO pvp_lang VALUES ('backup_db','nl','Database Back-up','');
INSERT INTO pvp_lang VALUES ('backup_db_cats','nl','Back-up categorieën','');
INSERT INTO pvp_lang VALUES ('backup_db_complete','nl','Volledige database backup. (Incl. technische data en instellingen)',' ');
INSERT INTO pvp_lang VALUES ('backup_db_movie_internal','nl','Back-up alle films d.m.v. phpVideoPro internal formaat','');
INSERT INTO pvp_lang VALUES ('backup_db_sysconf','nl','Back-up systeemconfiguratie en beginvoorkeurwaarden','');
INSERT INTO pvp_lang VALUES ('backup_file_corrupt','nl','Het geselecteerde back-upbestand is ongeldig - kan niet worden hersteld!','');
INSERT INTO pvp_lang VALUES ('backup_file_unreadable','nl','Geen leesrechten op het backup bestand (Controleer de rechten van het bestan\")',' ');
INSERT INTO pvp_lang VALUES ('bubble_help_enable','nl','Activeer BubbleHelp','');
INSERT INTO pvp_lang VALUES ('bubble_help_enable_comment','nl','Indien geactiveerd, verschijnt helpinformatie over sommige items waar met de muis over heen gegaan wordt. (bijv. bij de windows knoppen in de Applicat template\". ','');
INSERT INTO pvp_lang VALUES ('button_backup','nl','Back-up','');
INSERT INTO pvp_lang VALUES ('button_restore','nl','Herstel','');
INSERT INTO pvp_lang VALUES ('cache_enable','nl','Activeren browser/proxy caching?','');
INSERT INTO pvp_lang VALUES ('cache_enable_comment','nl','Omdat phpVideoPro een dynamisch applicatie is met gegenereerde pagina\'s uit de database bij elk browserverzoek. Daarom is het wellicht verstandig om caching uit te schakelen, vooral voor Microsoft Internet Explorer gebruikers...  ','');
INSERT INTO pvp_lang VALUES ('cancel','nl','Annuleer',' ');
INSERT INTO pvp_lang VALUES ('categories','nl','Categorieën',' ');
INSERT INTO pvp_lang VALUES ('category','nl','Categorie',' ');
INSERT INTO pvp_lang VALUES ('catlist_alpha','nl','Alfabetische medialijst gesorteerd op categorie ',' ');
INSERT INTO pvp_lang VALUES ('cat_action','nl','Aktie',' ');
INSERT INTO pvp_lang VALUES ('cat_adventure','nl','Aventuur',' ');
INSERT INTO pvp_lang VALUES ('cat_agents','nl','Politie',' ');
INSERT INTO pvp_lang VALUES ('cat_animal','nl','Dier',' ');
INSERT INTO pvp_lang VALUES ('cat_animals','nl','Dieren',' ');
INSERT INTO pvp_lang VALUES ('cat_animation','nl','Annimatie',' ');
INSERT INTO pvp_lang VALUES ('cat_bible','nl','Bijbel',' ');
INSERT INTO pvp_lang VALUES ('cat_biography','nl','Biografie',' ');
INSERT INTO pvp_lang VALUES ('cat_cartoon','nl','Tekenfilm',' ');
INSERT INTO pvp_lang VALUES ('cat_catastrophe','nl','catastrofe',' ');
INSERT INTO pvp_lang VALUES ('cat_children','nl','Kinderen',' ');
INSERT INTO pvp_lang VALUES ('cat_comedy','nl','Komedie',' ');
INSERT INTO pvp_lang VALUES ('cat_crime','nl','Misdaad',' ');
INSERT INTO pvp_lang VALUES ('cat_documentary','nl','Documantaire',' ');
INSERT INTO pvp_lang VALUES ('cat_fairytale','nl','Sprookjes',' ');
INSERT INTO pvp_lang VALUES ('cat_family','nl','Familie',' ');
INSERT INTO pvp_lang VALUES ('cat_fantasy','nl','Fantasie',' ');
INSERT INTO pvp_lang VALUES ('cat_handle_empty','nl','Categorie moet ingevuld zijn, ga terug en wijzig de invoer voor categorie #%1.',' ');
INSERT INTO pvp_lang VALUES ('cat_history','nl','Historie',' ');
INSERT INTO pvp_lang VALUES ('cat_judaica','nl','Jodendom',' ');
INSERT INTO pvp_lang VALUES ('cat_love','nl','Romantiek',' ');
INSERT INTO pvp_lang VALUES ('cat_misc','nl','Overigen',' ');
INSERT INTO pvp_lang VALUES ('cat_monumental','nl','Monumentaal',' ');
INSERT INTO pvp_lang VALUES ('cat_music','nl','Muziek',' ');
INSERT INTO pvp_lang VALUES ('cat_musicmovie','nl','Muziekfilm',' ');
INSERT INTO pvp_lang VALUES ('cat_nature','nl','Natuur',' ');
INSERT INTO pvp_lang VALUES ('cat_operetta','nl','Operette','');
INSERT INTO pvp_lang VALUES ('cat_party','nl','Feest','');
INSERT INTO pvp_lang VALUES ('cat_problem','nl','Probleem',' ');
INSERT INTO pvp_lang VALUES ('cat_scary','nl','Enge Films','');
INSERT INTO pvp_lang VALUES ('cat_spy','nl','Spionnenfilm',' ');
INSERT INTO pvp_lang VALUES ('cat_trans_update_failed','nl','Update mislukt voor de vertaling van de volgende categorieën: %1',' ');
INSERT INTO pvp_lang VALUES ('cat_travesty','nl','Travestie','');
INSERT INTO pvp_lang VALUES ('cat_update_failed','nl','Update mislukt voor de volgende categorieën: %1',' ');
INSERT INTO pvp_lang VALUES ('cat_vacation','nl','Vakantie',' ');
INSERT INTO pvp_lang VALUES ('cat_war','nl','Oorlogsfilm',' ');
INSERT INTO pvp_lang VALUES ('cat_westerncomedy','nl','Western-Komedie','');
INSERT INTO pvp_lang VALUES ('cat_xmas','nl','Kerstfilm',' ');
INSERT INTO pvp_lang VALUES ('change_disktype','nl','Verander Disc Type naar %1','');
INSERT INTO pvp_lang VALUES ('change_media_length','nl','Verander de media-lengte','');
INSERT INTO pvp_lang VALUES ('change_media_length_for','nl','Voer de capaciteit in voor %1',' ');
INSERT INTO pvp_lang VALUES ('change_nr','nl','Wijzig MediaNr/MediaType voor %1',' ');
INSERT INTO pvp_lang VALUES ('change_rc','nl','Wijzig de RegioCode',' ');
INSERT INTO pvp_lang VALUES ('change_rc_for','nl','Wijzig de RegioCode voor %1',' ');
INSERT INTO pvp_lang VALUES ('check_completed','nl','Controle compleet','');
INSERT INTO pvp_lang VALUES ('check_media_delete','nl','Controleer of het medium leeg is',' ');
INSERT INTO pvp_lang VALUES ('clean_restore','nl','Schoon of verwijder de oude data voor het starten van de restore',' ');
INSERT INTO pvp_lang VALUES ('close','nl','Sluit',' ');
INSERT INTO pvp_lang VALUES ('colors','nl','Kleuren',' ');
INSERT INTO pvp_lang VALUES ('comments','nl','Opmerkingen',' ');
INSERT INTO pvp_lang VALUES ('commercials','nl','Reclame',' ');
INSERT INTO pvp_lang VALUES ('composer','nl','Componist',' ');
INSERT INTO pvp_lang VALUES ('compose_person','nl','Componist',' ');
INSERT INTO pvp_lang VALUES ('compose_persons','nl','Componisten',' ');
INSERT INTO pvp_lang VALUES ('configuration','nl','Configuratie',' ');
INSERT INTO pvp_lang VALUES ('config_media','nl','Films en Media',' ');
INSERT INTO pvp_lang VALUES ('confirm_delete','nl','Wilt u werkelijk dit record verwijderen?',' ');
INSERT INTO pvp_lang VALUES ('confirm_prilang','nl','Wilt u werkelijk de standaard taal voor alle (nieuwe) gebruikers wijzigen? ',' ');
INSERT INTO pvp_lang VALUES ('confirm_userdelete','nl','U gaat de volgende gebruiker verwijderen #%1',' ');
INSERT INTO pvp_lang VALUES ('content','nl','Inhoud',' ');
INSERT INTO pvp_lang VALUES ('counter_start_stop','nl','Teller Start/Stop',' ');
INSERT INTO pvp_lang VALUES ('countries','nl','Landen',' ');
INSERT INTO pvp_lang VALUES ('country','nl','Land',' ');
INSERT INTO pvp_lang VALUES ('create','nl','Aanmaken',' ');
INSERT INTO pvp_lang VALUES ('create_success','nl','Item succesvol opgeslagen!',' ');
INSERT INTO pvp_lang VALUES ('credits','nl','Verdiensten','');
INSERT INTO pvp_lang VALUES ('cut_off','nl','Afgelopen op',' ');
INSERT INTO pvp_lang VALUES ('data_access','nl','Data toegang',' ');
INSERT INTO pvp_lang VALUES ('date_format','nl','Datum formaat',' ');
INSERT INTO pvp_lang VALUES ('date_format_comment','nl','Welk formaat gebruiken voor de datum.',' ');
INSERT INTO pvp_lang VALUES ('date_rec','nl','Datum opname/koop',' ');
INSERT INTO pvp_lang VALUES ('day','nl','Dag',' ');
INSERT INTO pvp_lang VALUES ('db_stats','nl','Statistieken',' ');
INSERT INTO pvp_lang VALUES ('delete','nl','Verwijderen',' ');
INSERT INTO pvp_lang VALUES ('delete_lang','nl','Verwijder taal',' ');
INSERT INTO pvp_lang VALUES ('delete_lang_comment','nl','Verwijder alle regels voor een specifieke taal in de database. Het bestand blijft bestaan zodat u zelf nog regels kunt toevoegen. (Let dat je zelf niet bestand verwijderd). ',' ');
INSERT INTO pvp_lang VALUES ('delete_orphans','nl','Verwijder %1 wees/wezen',' ');
INSERT INTO pvp_lang VALUES ('delete_remaining','nl','Verwijderen van de overgebleven gegevens van de film uit de database',' ');
INSERT INTO pvp_lang VALUES ('deleting_entry','nl','Verwijder item %1',' ');
INSERT INTO pvp_lang VALUES ('del_access','nl','Mag items verwijderen',' ');
INSERT INTO pvp_lang VALUES ('desc_admin_orphans','nl','\"Wees items\" is data zonder verwijzing. Bijv. Acteurs en componisten die geen link hebben naar een film. Dit komt meestal door verkeerd gespelde invoer die, nadat het is opgeslagen, weer gewijzigd wordt. Het verwijderen zal nooit leiden tot het verwijderen van de film. Het is het beste om deze wezen te verwijderen. Het spaart ruimte en voorkomt dat de database traag wordt. ',' ');
INSERT INTO pvp_lang VALUES ('desc_admin_orphan_fs','nl','\"Wees bestanden\" is data zonder een verwijzing. Bijv. een image zonder verwijzing naar een film. Dit komt meestal door: <UL><LI>Je hebt een image binnengekregen via een IMDB zoekopdracht maar deze informatie niet gebruikt</LI><LI>Je hebt een record gewijzigd een de image verwijzing aangepast of verwijderd</LI><LI>Je hebt een record verwijderd en dit programma was niet zo slim om ook de image te verwijderen</LI></UL>Echter: als je denkt dat je deze images niet meer wilt koppelen aan een film dan kan phpVideoPro bijgaande lijst verwijderen.','');
INSERT INTO pvp_lang VALUES ('desc_backup_db','nl','Het is verstandig om altijd een backup van de database te hebben. Het heeft de voorkeur om uw eigen tools hiervoor te gebruiken.
 (<code>mysql_dump</code>, code>pgsql_dump</code> etc.)
 In dit geval kan het zijn dat uw database staat op een server waar u geen shell toegang heeft. Kies daarom nu voor een \"Complete Backup\". Het slaat uw gehele database op als een SQL script<BR>Wilt u alleen de filmdata om die bijv. te gebruiken in een andere database, kies dan  alleen voor de films in het interne phpVideoPro formaat. U kunt op deze manier zelfs migreren tussen MySQL en PostgreSQL. Het terugzetten van een volledige backup van een oudere versie van phpVideoPro naar een recentere versie zal leiden tot het updaten (achteraf) van de database. De interne phpVideoPro backup is compatibel tussen de versies. (Toekomsige versies is nog niet zeker)<BR>U kunt de backup comprimeren als uw installatie van PHP is gecompileerd met gzip ondersteuning. Activeer de compressie box om tot 90% te besparen op de bestands grootte.<BR>    
 ',' ');
INSERT INTO pvp_lang VALUES ('director','nl','Regisseur',' ');
INSERT INTO pvp_lang VALUES ('directors','nl','Regisseurs',' ');
INSERT INTO pvp_lang VALUES ('directors_list','nl','Overzicht van regisseurs',' ');
INSERT INTO pvp_lang VALUES ('director_person','nl','regisseur',' ');
INSERT INTO pvp_lang VALUES ('director_persons','nl','Producer',' ');
INSERT INTO pvp_lang VALUES ('disktype_add_failed','nl','Sorry, ik kan de nieuwe disktype niet toevoegen.',' ');
INSERT INTO pvp_lang VALUES ('disktype_change','nl','Wijzig DiskType',' ');
INSERT INTO pvp_lang VALUES ('disktype_contains_media','nl','Dit disktype kan momenteel niet verwijderd worden omdat de volgende media er nog naar refereren.',' ');
INSERT INTO pvp_lang VALUES ('disktype_name_empty','nl','De naam voor een disktype mag niet leeg zijn. Ga terug en pas het aan voor disk type #%1.',' ');
INSERT INTO pvp_lang VALUES ('disktype_update_failed','nl','Sorry, ik kan het volgende disktype niet bijwerken #s: %1',' ');
INSERT INTO pvp_lang VALUES ('disk_size','nl','Disk Grootte',' ');
INSERT INTO pvp_lang VALUES ('display','nl','Toon',' ');
INSERT INTO pvp_lang VALUES ('display_limit','nl','Toon limiet',' ');
INSERT INTO pvp_lang VALUES ('display_limit_comment','nl','(hoeveel regels per pagina voor het overzicht)',' ');
INSERT INTO pvp_lang VALUES ('dl_pvp_latest','nl','Download de laatse versie',' ');
INSERT INTO pvp_lang VALUES ('dupes','nl','Dubbele items',' ');
INSERT INTO pvp_lang VALUES ('dupes_strict','nl','Strkt','');
INSERT INTO pvp_lang VALUES ('dupe_id_entered','nl','Er is al een film opgeslagen onder dit mediumnummer. Ga terug en pas dit aan. Tip: Er is een Selectie veld naast het invoerveld waar het media nummer. Dit selectie veld geeft aan het hoogste bestaande film id. Het is een juiste keuze om bij nieuwe media de eerste vier getallen met een te verhogen. Voor een nieuwe film op bestaande media verhoogt u de tweede twee getallen met een. ',' ');
INSERT INTO pvp_lang VALUES ('dupe_titles_found','nl','Gevonden %1 titel(s) die mogelijk dubbel zijn.',' ');
INSERT INTO pvp_lang VALUES ('edit','nl','Wijzig',' ');
INSERT INTO pvp_lang VALUES ('edit_entry','nl','Wijzig item %1',' ');
INSERT INTO pvp_lang VALUES ('enable_cookies','nl','Activeren cookies?',' ');
INSERT INTO pvp_lang VALUES ('enable_cookies_comment','nl','Moeten de gebruikersinstellingen (bijv. filters) geregeld worden via cookies?',' ');
INSERT INTO pvp_lang VALUES ('ended_sessions','nl','Beëindigde sessies',' ');
INSERT INTO pvp_lang VALUES ('enter_min_free','nl','Hoeveel ruimte moet er minimaal vrij zijn:',' ');
INSERT INTO pvp_lang VALUES ('enter_new_medianr','nl','Voer het MediaNr in voor deze nieuwe %1',' ');
INSERT INTO pvp_lang VALUES ('expire_cookies','nl','Levensduur coockies',' ');
INSERT INTO pvp_lang VALUES ('expire_cookies_comment','nl','Hoe lang mag een cookie actief blijven in de browser van de gebruiker ',' ');
INSERT INTO pvp_lang VALUES ('farbe','nl','Kleur',' ');
INSERT INTO pvp_lang VALUES ('filter_setup','nl','Filter configuratie',' ');
INSERT INTO pvp_lang VALUES ('finnished','nl','Gereed',' ');
INSERT INTO pvp_lang VALUES ('first_name','nl','Voornaam',' ');
INSERT INTO pvp_lang VALUES ('format','nl','Formaat',' ');
INSERT INTO pvp_lang VALUES ('free','nl','Vrij',' ');
INSERT INTO pvp_lang VALUES ('free_space_on_media','nl','De volgende mediums hebben minimaal %1 vrije ruimte:',' ');
INSERT INTO pvp_lang VALUES ('free_space_title','nl','Vrije ruimte op medium',' ');
INSERT INTO pvp_lang VALUES ('fsk','nl','OudersControle OC (Min-Max leeftijd)',' ');
INSERT INTO pvp_lang VALUES ('fsk_is_nan','nl','De geselecteerde,nbut waarde voor PG (Parent Guide) is niet numeriek. phpVideoPro verwacht een numerieke waarde. nClick het informatie icoon naast de PG voor meer informatie.','');
INSERT INTO pvp_lang VALUES ('general','nl','Algemeen',' ');
INSERT INTO pvp_lang VALUES ('goto_entry','nl','Ga direct naar:',' ');
INSERT INTO pvp_lang VALUES ('graphic_file','nl','Imagebestand',' ');
INSERT INTO pvp_lang VALUES ('help_about','nl','Help over',' ');
INSERT INTO pvp_lang VALUES ('help_for_block','nl','Help voor dit blok','');
INSERT INTO pvp_lang VALUES ('hide_cat','nl','Verberg category','');
INSERT INTO pvp_lang VALUES ('highest_db_entries','nl','Hoogste items in database',' ');
INSERT INTO pvp_lang VALUES ('history','nl','Geschiedenis',' ');
INSERT INTO pvp_lang VALUES ('hit_back_to_correct','nl','Druk op de \"Terug\" knop om de fout te herstellen.',' ');
INSERT INTO pvp_lang VALUES ('hour','nl','Uur',' ');
INSERT INTO pvp_lang VALUES ('hours','nl','Uren',' ');
INSERT INTO pvp_lang VALUES ('howto','nl','Hoe...',' ');
INSERT INTO pvp_lang VALUES ('howto_help','nl','How maak ik een nieuw help bestand',' ');
INSERT INTO pvp_lang VALUES ('howto_label','nl','Hoe maak of configureer ik label templates',' ');
INSERT INTO pvp_lang VALUES ('howto_lang','nl','Hoe maak ik een nieuw taal bestand',' ');
INSERT INTO pvp_lang VALUES ('howto_templates','nl','Hoe maak ik een nieuwe template',' ');
INSERT INTO pvp_lang VALUES ('imdbsearch','nl','Haal de film inforamtie op bij de IMDB site','');
INSERT INTO pvp_lang VALUES ('imdb_cache_dir','nl','Directory waar de IMDB cache opgeslagen moet worden.','');
INSERT INTO pvp_lang VALUES ('imdb_cache_dir_comment','nl','Deze directory moet lees-/schrijfbaar zijn voor de webserver en alleen hier voor gebruikt worden. Het pad (path) kan relatief zijn t.o.v. de phpVideoPro basis pad (path) installatie (gaanbevolen). Hebruik hiervoor <b><i>nooit</i></b> je temp directory van je systeem.','');
INSERT INTO pvp_lang VALUES ('imdb_cache_enable','nl','Activeren IMDB data caching?','');
INSERT INTO pvp_lang VALUES ('imdb_cache_enable_comment','nl','Het opvragen van de informatie bij IMDB kan enige tijd kosten omdat meerdere pagina\'s opgehaald moeten worden. Caching heeft alleen nut als je meerdere malen dezelfde informatie moet ophalen, dit doe je normaalgesproken niet dus heb je de caching ook niet nodig. Activeer je het toch zorg er dan voor dat de cache directory beschreven kan worden door de webserver!','');
INSERT INTO pvp_lang VALUES ('imdb_cache_expire','nl','Verwijder IMDB cache','');
INSERT INTO pvp_lang VALUES ('imdb_cache_expire_comment','nl','Als de IMDB caching geactiveerd is dan zal de omvang van je cache directory groeien. Gebruik deze optie om aan te geven waanneer de cache data mag komen te vervallen (maximale bewaartijd).','');
INSERT INTO pvp_lang VALUES ('imdb_cache_use','nl','Cache data gebruiken bij nieuwe opvragingen?','');
INSERT INTO pvp_lang VALUES ('imdb_cache_use_comment','nl','Bovengenoemde opties regelen <b><i>het opslaan</i></b> van de IMDB data in de locale cache. Deze optie regelt of phpVideoPro de cache gebruikt voor het opzoeken. Indien geactiveerd en de gewenste informatie in de cache aanwezig is dan zal phpVideoPro geen verbinding maken met de IMDB database maar de informatie uit de cache gebruiken.','');
INSERT INTO pvp_lang VALUES ('imdb_image_files','nl','IMDB image bestanden','');
INSERT INTO pvp_lang VALUES ('imdb_movie_id','nl','IMDB film ID','');
INSERT INTO pvp_lang VALUES ('imdb_search_empty_result','nl','Sorry, er is geen overeenkomstige data gevonden in de IMDB database..<BR>Je kunt het met een andere zoekterm proberen.','');
INSERT INTO pvp_lang VALUES ('imdb_title_search','nl','Zoek de film in de IMDB database','');
INSERT INTO pvp_lang VALUES ('imdb_transfer2edit','nl','Verplaats de data naar wijzigingsscherm','');
INSERT INTO pvp_lang VALUES ('imdb_tx','nl','Te verplaatsen data van de IMDB database','');
INSERT INTO pvp_lang VALUES ('imdb_txwin_autoclose','nl','Automatisch sluiten van het scherm na de data verplaatsing?','');
INSERT INTO pvp_lang VALUES ('imdb_txwin_autoclose_comment','nl','Wanneer alle benodigde informatie van IMDB verplaatst is naar het wijzigingsscherm, is het zoek scherm niet meer nodig. Desondanks kun je het houden voor referentie of andere redenen.','');
INSERT INTO pvp_lang VALUES ('imdb_tx_actor','nl','Acteurs','');
INSERT INTO pvp_lang VALUES ('imdb_tx_cat','nl','Categoriën','');
INSERT INTO pvp_lang VALUES ('imdb_tx_comment','nl','Wanneer je een film wilt toevoegen of wijzigen geeft phpVideoPro je de mogelijkheid om informatie op te halen uit de IMDB database. Hier kun je bepalen welke informatie je standaard wilt laten verplaatsen naar het wijzigingsscherm van phpVideoPro.','');
INSERT INTO pvp_lang VALUES ('imdb_tx_comments','nl','Commentaar','');
INSERT INTO pvp_lang VALUES ('imdb_tx_country','nl','Land','');
INSERT INTO pvp_lang VALUES ('imdb_tx_director','nl','Regisseur','');
INSERT INTO pvp_lang VALUES ('imdb_tx_length','nl','Duur','');
INSERT INTO pvp_lang VALUES ('imdb_tx_music','nl','Componist','');
INSERT INTO pvp_lang VALUES ('imdb_tx_title','nl','Titel','');
INSERT INTO pvp_lang VALUES ('imdb_tx_year','nl','Jaar','');
INSERT INTO pvp_lang VALUES ('imdb_url','nl','Welke IMDB site te gebruiken',' ');
INSERT INTO pvp_lang VALUES ('imdb_url2','nl','Alternatieve IMDB site','');
INSERT INTO pvp_lang VALUES ('imdb_url2_comment','nl','Ook al zijn er locale IMDB\'s (per land), de informatie op deze sites blijft in het Engels. Alleen de veld-omschrijvingen zijn in de locale taal. Om de gegevens in phpVideoPro te krijgen in het noodzakelijk dat de veld-omschrijvingen in het engels zijn. Daarom hebben we een<b><i>Engelse</i></b> IMDB site nodig. Kies een geschikte site.','');
INSERT INTO pvp_lang VALUES ('imdb_url_comment','nl','De Intenet Movie DataBase geeft informatie over veel films. Er zijn ook landen sites beschikbaar. Zo is de Nederlande site geschikt om te zoeken naar Nederlandse films. De Amerikaanse site is het beste voor Engelse films. Kies een site die het beste past bij de films in uw database.',' ');
INSERT INTO pvp_lang VALUES ('imp_errors','nl','Importeren van %2 record(s) gestopt met %1 fout(en).',' ');
INSERT INTO pvp_lang VALUES ('imp_success','nl','Importeren van %1 record(s) is succesvol gereed.',' ');
INSERT INTO pvp_lang VALUES ('incomplete_date','nl','Indien je niet de exacte datum weet, maar bijvoorbeeld alleen dat u het hebt opgenomen inhet jaar 2000, pas dan alleen het jaar gedeelte in de datum aan.',' ');
INSERT INTO pvp_lang VALUES ('info_common','nl','Algemende informatie',' ');
INSERT INTO pvp_lang VALUES ('info_common_info','nl','<DIV ALIGN=\"center\">Dit is versie %1 van phpVideoPro, draaiend op %2.</DIV> ',' ');
INSERT INTO pvp_lang VALUES ('info_noupdate','nl','<DIV ALIGN=\"center\">De geinstaleerde versie van phpVideoPro (%1) is actueel - er is geen recentere versie beschikbaar om te downloaden. Om de tarball van de geinstalleerde versie te downloaden klik op <A HREF=\"http://projects.izzysoft.de/progs/get_update.php?program=pvp\" TARGET=\"_blank\">this link</A>.</DIV>',' ');
INSERT INTO pvp_lang VALUES ('info_update','nl','Bijwerken informatie',' ');
INSERT INTO pvp_lang VALUES ('intro_usage','nl','<P>Hier is informatie voor nieuwe  gebruikers:<ul><li>Navigatie is altijd mogelijk via de menubalk die bijna boven elk scherm is</li><li>Bijna alle schermen hebben een helppagina. U kunt die openen via het help menu of, indien aanwezig, via het \"?\" icoontje.</li><li>Via onderstaand scherm kunt u direct springen naar een film, als u het media nummer weet. Gebruik anders de \"Medialijst\" van het menu item \"Overzicht\" of de \"Zoek\" functie uit het menu item \"Wijzig\".</li></ul></P>','');
INSERT INTO pvp_lang VALUES ('intro_usage_skip','nl','<P>Wilt u deze introductie tekst niet meer dan kunt u die uitschakelen via een optie in het instellingen scherm. Zie \"Wijzig\" menu.</P>','');
INSERT INTO pvp_lang VALUES ('intro_usage_title','nl','Introductie voor nieuwe gebruikers','');
INSERT INTO pvp_lang VALUES ('invalid_backup_dir','nl','De geconfigureerde backup directory bestaat niet.','');
INSERT INTO pvp_lang VALUES ('invalid_fsk','nl','De waarde van %1 is ongelig. OC betekend  \"Ouder Controlee\", ofwel de minimum leeftijd waaronder men geen toegang heeft tot deze film.',' ');
INSERT INTO pvp_lang VALUES ('invalid_media_nr','nl','Het ingevoerde MediaNr is opgeldig of incompleet. U moet een <b>nummer</b> in <b>beide</b> MediaNr velden invullen.',' ');
INSERT INTO pvp_lang VALUES ('in_list','nl','In overzicht',' ');
INSERT INTO pvp_lang VALUES ('is_rw','nl','herschrijfbaar',' ');
INSERT INTO pvp_lang VALUES ('label','nl','Etiket','');
INSERT INTO pvp_lang VALUES ('labels','nl','Etiketten',' ');
INSERT INTO pvp_lang VALUES ('labeltype','nl','Etiket Type',' ');
INSERT INTO pvp_lang VALUES ('language_settings','nl','Taal instellingen',' ');
INSERT INTO pvp_lang VALUES ('last_entry','nl','Laatste item',' ');
INSERT INTO pvp_lang VALUES ('last_medianr','nl','Het hoogste nummer voor dit media type is momenteel:',' ');
INSERT INTO pvp_lang VALUES ('layout_label','nl','Kies layout',' ');
INSERT INTO pvp_lang VALUES ('left_offset','nl','Linkermarge',' ');
INSERT INTO pvp_lang VALUES ('length','nl','Lengte',' ');
INSERT INTO pvp_lang VALUES ('lines_per_page','nl','Regels per pagina',' ');
INSERT INTO pvp_lang VALUES ('lines_per_page_comment','nl','Dit is voor de printer functionaliteit om te bepalen hoeveel regels er op he papier passen.',' ');
INSERT INTO pvp_lang VALUES ('line_count','nl','Regels',' ');
INSERT INTO pvp_lang VALUES ('list','nl','Overzicht',' ');
INSERT INTO pvp_lang VALUES ('listgen','nl','Overzichten',' ');
INSERT INTO pvp_lang VALUES ('lists','nl','Overzichten',' ');
INSERT INTO pvp_lang VALUES ('locale','nl','Lokaal',' ');
INSERT INTO pvp_lang VALUES ('local_image_files','nl','Lokale imagebestanden','');
INSERT INTO pvp_lang VALUES ('login','nl','Login naam',' ');
INSERT INTO pvp_lang VALUES ('login_failed','nl','Login mislukt. Verkeerde naam of wachtwoord gebruikt of de gebruiker bestaat niet.',' ');
INSERT INTO pvp_lang VALUES ('login_required','nl','Uw rechten zijn onvoldoende voor de gewenste actie. U kunt nu opnieuw inloggen als een andere gebruiker met de juiste rechten.<P />',' ');
INSERT INTO pvp_lang VALUES ('logout_user','nl','Ingelogd als\"%1\". <A HREF=\"%2\">afmelden</A>',' ');
INSERT INTO pvp_lang VALUES ('longplay','nl','Lange speelduur','');
INSERT INTO pvp_lang VALUES ('lower_left_corner','nl','Linkeronderhoek (x/y)',' ');
INSERT INTO pvp_lang VALUES ('max_fontsize','nl','Max Fontgrootte',' ');
INSERT INTO pvp_lang VALUES ('medialength','nl','MediaLengte',' ');
INSERT INTO pvp_lang VALUES ('medialist','nl','Medialijst',' ');
INSERT INTO pvp_lang VALUES ('medialist_alpha','nl','Media overzicht in alfabetische volgorde',' ');
INSERT INTO pvp_lang VALUES ('medialist_num','nl','Media overzicht op nummer volgorde',' ');
INSERT INTO pvp_lang VALUES ('media_change','nl','Wijzig MediaNr',' ');
INSERT INTO pvp_lang VALUES ('media_copy','nl','Kopieer data naar MediaNr',' ');
INSERT INTO pvp_lang VALUES ('medium_deleted','nl','Geen films meer op dit medium - medium verwijderd',' ');
INSERT INTO pvp_lang VALUES ('medium_not_deleted','nl','Medium niet verwijderd',' ');
INSERT INTO pvp_lang VALUES ('medium_overview','nl','Overzicht voor %1',' ');
INSERT INTO pvp_lang VALUES ('menues','nl','Menus',' ');
INSERT INTO pvp_lang VALUES ('month','nl','Maand',' ');
INSERT INTO pvp_lang VALUES ('movies','nl','Films',' ');
INSERT INTO pvp_lang VALUES ('movies_left_in_cat','nl','Categorie %1 bevat nog steeds %2 film(s). Verwijderen kan niet, sorry. ',' ');
INSERT INTO pvp_lang VALUES ('movies_left_reference','nl','Deze regel kan niet verwijderd worden. Er is/zijn nog steeds %1 film(s) in de database die er naar verwijzen.',' ');
INSERT INTO pvp_lang VALUES ('movie_color_default','nl','Standaard kleurformaat voor een film',' ');
INSERT INTO pvp_lang VALUES ('movie_color_default_comment','nl','Dit is de standaard kleurinstelling voor een nieuwe entry',' ');
INSERT INTO pvp_lang VALUES ('movie_lang_default','nl','Standaard audio taal voor nieuwe films','');
INSERT INTO pvp_lang VALUES ('movie_lang_default_comment','nl','Dit zal gebruikt worden als standaard audio taal als er een nieuw record wordt toegevoegd ','');
INSERT INTO pvp_lang VALUES ('movie_onlabel_default','nl','Standaard label info',' ');
INSERT INTO pvp_lang VALUES ('movie_onlabel_default_comment','nl','Standaard voor nieuwe items: moet de informatie van deze film gebruikt worden wanneer labels voor dit medium gemaakt worden?',' ');
INSERT INTO pvp_lang VALUES ('movie_pict_default','nl','Standaard schermformaat voor nieuwe films','');
INSERT INTO pvp_lang VALUES ('movie_pict_default_comment','nl','Dit zal gebruikt worden als standaard schermformaat als er een nieuw record wordt toegevoegd ','');
INSERT INTO pvp_lang VALUES ('movie_tone_default','nl','Standaard geluidstype voor een film. ',' ');
INSERT INTO pvp_lang VALUES ('movie_tone_default_comment','nl','Dit zal gebruikt worden als standaard geluidstype voor een nieuw item',' ');
INSERT INTO pvp_lang VALUES ('music','nl','Componist',' ');
INSERT INTO pvp_lang VALUES ('music_list','nl','Overzicht van componisten',' ');
INSERT INTO pvp_lang VALUES ('name','nl','Naam',' ');
INSERT INTO pvp_lang VALUES ('never','nl','nooit',' ');
INSERT INTO pvp_lang VALUES ('new_disktype','nl','Nieuw disk Type',' ');
INSERT INTO pvp_lang VALUES ('new_medianr','nl','Nieuw MediaNr',' ');
INSERT INTO pvp_lang VALUES ('new_movie_on','nl','Nieuw %1',' ');
INSERT INTO pvp_lang VALUES ('no','nl','Nee',' ');
INSERT INTO pvp_lang VALUES ('nobody_named','nl','Er is geen andere film met %1 naam %2 %3 in dit bestand. Dit item zal verwijderd worden uit de %1 tabel.',' ');
INSERT INTO pvp_lang VALUES ('none','nl','Geen',' ');
INSERT INTO pvp_lang VALUES ('not_logged_in','nl','Niet aangemeld',' ');
INSERT INTO pvp_lang VALUES ('not_ok','nl','Mislukt',' ');
INSERT INTO pvp_lang VALUES ('not_yet_implemented','nl','Sorry - nog niet geimplementeerd.',' ');
INSERT INTO pvp_lang VALUES ('no_add_lang','nl','Geen aanvullend taalbestand gevonden.',' ');
INSERT INTO pvp_lang VALUES ('no_backup_avail','nl','Geen backupbestand beschikbaar om van te restoren',' ');
INSERT INTO pvp_lang VALUES ('no_entries_found','nl','Geen items gevonden',' ');
INSERT INTO pvp_lang VALUES ('no_entry_in_tapelist','nl','Helaas, geen item gevonden in tapelijst.',' ');
INSERT INTO pvp_lang VALUES ('no_orphans_found','nl','Gefeliciteerd, geen losse records meer gevonden.',' ');
INSERT INTO pvp_lang VALUES ('no_restore_file','nl','Sorry, het geselecteerde bestand bestaat niet meer!',' ');
INSERT INTO pvp_lang VALUES ('no_space_of','nl','Er is geen medium gevonden met %1 minuten vrije ruimte in de database',' ');
INSERT INTO pvp_lang VALUES ('of_aquiration','nl','aankoop/opname',' ');
INSERT INTO pvp_lang VALUES ('old_sessions','nl','Sessies ouder dan <INPUT NAME=\"%1\" VALUE=\"\" CLASS=\"yesnobutton\"> dagen',' ');
INSERT INTO pvp_lang VALUES ('orig_disktype','nl','Orgineel Disk Type',' ');
INSERT INTO pvp_lang VALUES ('orig_medianr','nl','orgineel MediaNr','');
INSERT INTO pvp_lang VALUES ('orig_trans','nl','Orginele vertaling (%1)','');
INSERT INTO pvp_lang VALUES ('orphans_found','nl','Gevonden %1 wees/wezen','');
INSERT INTO pvp_lang VALUES ('other_pages','nl','Overige pagina\'s','');
INSERT INTO pvp_lang VALUES ('page_bg','nl','Pagina achtergrond',' ');
INSERT INTO pvp_lang VALUES ('password','nl','Wachtwoord','');
INSERT INTO pvp_lang VALUES ('password_retype','nl','Voer wachtwoord opnieuwe in','');
INSERT INTO pvp_lang VALUES ('picture','nl','Kleurformaat',' ');
INSERT INTO pvp_lang VALUES ('preferences','nl','Instellingen','');
INSERT INTO pvp_lang VALUES ('printer_add_failed','nl','Er is een fout opgetreden bij het toevoegen van deze printer.','');
INSERT INTO pvp_lang VALUES ('printer_comment','nl','Als u op formulieren wilt printen (zoals bij PS Labels), dan moeten wij de juiste marges weten','');
INSERT INTO pvp_lang VALUES ('printer_name','nl','Naam','');
INSERT INTO pvp_lang VALUES ('printer_upd_failed','nl','Bijwerken mislukt voor de volgende printers: %1','');
INSERT INTO pvp_lang VALUES ('pslabel','nl','PostScript Label','');
INSERT INTO pvp_lang VALUES ('pstpl_name','nl','Template naam','');
INSERT INTO pvp_lang VALUES ('pstpl_type','nl','Template type','');
INSERT INTO pvp_lang VALUES ('pvp_homepage','nl','Project HomePagina','');
INSERT INTO pvp_lang VALUES ('read_access','nl','Mag items bekijken','');
INSERT INTO pvp_lang VALUES ('read_access_short','nl','lr','');
INSERT INTO pvp_lang VALUES ('recalc_free','nl','Vrije ruimte aan het herberekenen voor dit medium.',' ');
INSERT INTO pvp_lang VALUES ('refresh_lang','nl','Overschrijf taalbestand',' ');
INSERT INTO pvp_lang VALUES ('refresh_lang_comment','nl','(Indien er een wijziging heeft plaats gevonden in het taalbestand (wellicht doordat u een taalfout heeft gevonden), dan kunt u hier het taalbestand opnieuw laten inlezen)',' ');
INSERT INTO pvp_lang VALUES ('region_code','nl','RegioCode','');
INSERT INTO pvp_lang VALUES ('remove_cat','nl','Verwijder categorie','');
INSERT INTO pvp_lang VALUES ('remove_empty_media','nl','Verwijderen lege media','');
INSERT INTO pvp_lang VALUES ('remove_empty_media_comment','nl','Moet media verwijderd worden als de laatste film verwijderd is?','');
INSERT INTO pvp_lang VALUES ('restore_db_internal','nl','Restore van een PVP backupbestand','');
INSERT INTO pvp_lang VALUES ('restore_db_movie_internal','nl','Terugzetten van films van een PVP backupbestand','');
INSERT INTO pvp_lang VALUES ('rw_media','nl','Wijzigbare Media','');
INSERT INTO pvp_lang VALUES ('rw_media_comment','nl','Media om vrije ruimte voor te reserveren, omdat u er op opgenomen hebt','');
INSERT INTO pvp_lang VALUES ('s/w','nl','z/w',' ');
INSERT INTO pvp_lang VALUES ('save_lang_file','nl','Sla vertaling op in en bestand','');
INSERT INTO pvp_lang VALUES ('scan_new_lang_comment','nl','(Indien u een nieuw taalbestand hebt gemaakt en  die in de setup directory heeft geplaatst, dan kunt u hiermee phpVideoPro er naar laten zoeken)',' ');
INSERT INTO pvp_lang VALUES ('scan_new_lang_files','nl','Zoeken naar nieuwe taalbestanden?',' ');
INSERT INTO pvp_lang VALUES ('screen','nl','Beeldformaat',' ');
INSERT INTO pvp_lang VALUES ('search','nl','Zoek','');
INSERT INTO pvp_lang VALUES ('search_movie','nl','ZoekFilm','');
INSERT INTO pvp_lang VALUES ('select_add_lang','nl','Selecteer additioneel taalbestand',' ');
INSERT INTO pvp_lang VALUES ('select_add_lang_comment','nl','(Als er na het scannen additionele taalbestanden gevonden zijn, kunt u die hier selecteren. Deze zullen dan worden geinstelleerd.)',' ');
INSERT INTO pvp_lang VALUES ('select_primary_lang','nl','Selecteer taal',' ');
INSERT INTO pvp_lang VALUES ('select_primary_lang_comment','nl','(Voor niet vertaalde delen, zal er worden teruggevallen op het engels.)',' ');
INSERT INTO pvp_lang VALUES ('sel_target_lang','nl','Kies doeltaal om naar te vertalen:','');
INSERT INTO pvp_lang VALUES ('session','nl','Sessie','');
INSERT INTO pvp_lang VALUES ('session_expired','nl','Uw sessie is verlopen, log svp opnieuw in.','');
INSERT INTO pvp_lang VALUES ('session_purgetime','nl','Na hoeveel tijd mag een inactive sessie vervallen?','');
INSERT INTO pvp_lang VALUES ('session_purgetime_comment','nl','Hoelang mag een sessie actief blijven zonder activiteiten?','');
INSERT INTO pvp_lang VALUES ('sess_dla','nl','Laatst actief','');
INSERT INTO pvp_lang VALUES ('sess_end','nl','Beëindigd','');
INSERT INTO pvp_lang VALUES ('sess_id','nl','Sessie ID','');
INSERT INTO pvp_lang VALUES ('sess_start','nl','Gestart','');
INSERT INTO pvp_lang VALUES ('set_filter','nl','Filter instellen',' ');
INSERT INTO pvp_lang VALUES ('site_info_comment','nl','Welke site info moet op de titelbalk van de browser','');
INSERT INTO pvp_lang VALUES ('skip_intro','nl','Nieuwkomers informatie overslaan?','');
INSERT INTO pvp_lang VALUES ('skip_intro_comment','nl','Introductie tekst overslaan op de startpagina?','');
INSERT INTO pvp_lang VALUES ('source','nl','Bron',' ');
INSERT INTO pvp_lang VALUES ('staff','nl','Staf',' ');
INSERT INTO pvp_lang VALUES ('start_page','nl','Start pagina',' ');
INSERT INTO pvp_lang VALUES ('state_active','nl','actief','');
INSERT INTO pvp_lang VALUES ('state_inactive','nl','inactief','');
INSERT INTO pvp_lang VALUES ('stats','nl','Statikstieken','');
INSERT INTO pvp_lang VALUES ('stat_categories','nl','Categorieen (alles)','');
INSERT INTO pvp_lang VALUES ('stat_counts','nl','Telling','');
INSERT INTO pvp_lang VALUES ('stat_ranks','nl','Hoogte','');
INSERT INTO pvp_lang VALUES ('submit','nl','Verstuur','');
INSERT INTO pvp_lang VALUES ('subtitle','nl','Ondertiteling','');
INSERT INTO pvp_lang VALUES ('sure_to_delete','nl','Weet u zeker dat u alles wilt verwijderen van %1',' ');
INSERT INTO pvp_lang VALUES ('table_bg','nl','Tabel achtergrond',' ');
INSERT INTO pvp_lang VALUES ('tapelist_update_failed','nl','Het is niet gelukt om het bijtewerken',' ');
INSERT INTO pvp_lang VALUES ('taperest','nl','Beheren overblijvende tijd','');
INSERT INTO pvp_lang VALUES ('taperest_absolute','nl','Vrije ruimte (totaal)',' ');
INSERT INTO pvp_lang VALUES ('taperest_filtered','nl','Vrije ruimte (met filter)',' ');
INSERT INTO pvp_lang VALUES ('target_trans','nl','Vertaling voor uw taal (%1)','');
INSERT INTO pvp_lang VALUES ('techdata','nl','Technische data','');
INSERT INTO pvp_lang VALUES ('template_file','nl','Template bestand','');
INSERT INTO pvp_lang VALUES ('template_set','nl','Template',' ');
INSERT INTO pvp_lang VALUES ('th_bg','nl','Tabelkoppen achtergrond',' ');
INSERT INTO pvp_lang VALUES ('time_left','nl','%1 minuten beschikbaar',' ');
INSERT INTO pvp_lang VALUES ('title','nl','Titel',' ');
INSERT INTO pvp_lang VALUES ('tone','nl','Geluidsformaat',' ');
INSERT INTO pvp_lang VALUES ('top_offset','nl','Bovenmarge','');
INSERT INTO pvp_lang VALUES ('trans_code','nl','Te vertalen data','');
INSERT INTO pvp_lang VALUES ('unit','nl','Eenheid','');
INSERT INTO pvp_lang VALUES ('unknown','nl','Onbekend',' ');
INSERT INTO pvp_lang VALUES ('unlink_file_failed','nl','Deleten mislukt -controleer permissies of verwijder handmatig.','');
INSERT INTO pvp_lang VALUES ('unset_filter','nl','Filter opnieuw instellen',' ');
INSERT INTO pvp_lang VALUES ('update','nl','Aanpassen',' ');
INSERT INTO pvp_lang VALUES ('update_failed','nl','Bijwerken items mislukt',' ');
INSERT INTO pvp_lang VALUES ('update_success','nl','Items succesvol opgeslagen!',' ');
INSERT INTO pvp_lang VALUES ('upd_access','nl','Mag bestaande items bijwerken','');
INSERT INTO pvp_lang VALUES ('upper_right_corner','nl','Rechterbovenhoek (x/y)','');
INSERT INTO pvp_lang VALUES ('user','nl','Gebruiker','');
INSERT INTO pvp_lang VALUES ('user_create_login_required','nl','Je moet een loginnaam opgeven voor de gebruiker!','');
INSERT INTO pvp_lang VALUES ('user_deleted','nl','Succesvol verwijder gebruiker #%1, \"%2\" (%3)','');
INSERT INTO pvp_lang VALUES ('user_delete_failed','nl','Verwijderen van gebruiker #%1, \"%2\" (%3) mislukt','');
INSERT INTO pvp_lang VALUES ('user_delete_report','nl','Resultaat van het verwijderen van gebruikers','');
INSERT INTO pvp_lang VALUES ('user_update_failed','nl','Bijwerken mislukt voor de volgende gebruikers: %1','');
INSERT INTO pvp_lang VALUES ('view','nl','Beeld',' ');
INSERT INTO pvp_lang VALUES ('view_entry','nl','Bekijk item %1',' ');
INSERT INTO pvp_lang VALUES ('warning','nl','waarschuwing',' ');
INSERT INTO pvp_lang VALUES ('welcome','nl','Welkom bij phpVideoPro','');
INSERT INTO pvp_lang VALUES ('wrong_date','nl','De datum %1 die je hebt opgegeven (%2) is ongeldig. De datum moet op de volgende manier  worden ingevoerd: \"JJJJ-MM-DD\"',' ');
INSERT INTO pvp_lang VALUES ('xfer_unknown_filetype','nl','Dit backupbestandstype kan (nog) niet gebruikt worden door phpVideoPro.','');
INSERT INTO pvp_lang VALUES ('xfer_wrong_mode','nl','Programma fout, u bent in de verkeerde mode voor de gewenste actie. Vereiste mode is \"%1\", huidige mode is \"%2\". Geef dit door aan de auteur tezame met de gegevens van de uitgevoerde actie.','');
INSERT INTO pvp_lang VALUES ('year','nl','Jaar',' ');
INSERT INTO pvp_lang VALUES ('yes','nl','Ja',' ');
