UPDATE languages SET charset='iso-8859-8-i' WHERE lang_id='iw';
INSERT INTO lang (message_id,lang,content) VALUES ('not_yet_implemented','iw', '’…ƒ Œ€ „…–€ Œ”…’Œ');
INSERT INTO lang VALUES('medium','iw','€–’');
INSERT INTO lang VALUES('nr','iw','—˜…');
INSERT INTO lang VALUES('title','iw','‹…š˜');
INSERT INTO lang VALUES('length','iw','€…˜Š');
INSERT INTO lang VALUES('year','iw','™„');
INSERT INTO lang VALUES('date_rec','iw','š€˜‰Š „š—Œ');
INSERT INTO lang VALUES('category','iw','—ˆ‚…˜‰„');
INSERT INTO lang VALUES('medialist','iw','˜™‰š š—Œ‰ˆ…˜‰ …—Œˆ…š');
INSERT INTO lang VALUES('enter_min_free','iw','„‹‘ ‰‰… ™ˆ‡ ”…‰');
INSERT INTO lang VALUES('display','iw','„–‚');
INSERT INTO lang VALUES('free_space_on_media','iw','„‹‘ ™ˆ‡ ”…‰ ’Œ —Œˆš €… š—Œ‰ˆ…˜');
INSERT INTO lang VALUES('free','iw','”…‰');
INSERT INTO lang VALUES('content','iw','„˜‹');
INSERT INTO lang VALUES('filter_setup','iw','—‰’š ‘');
INSERT INTO lang VALUES('mediatype','iw','?š—Œ‰ˆ…˜ €… —Œˆš');
INSERT INTO lang VALUES('screen','iw','‘Š');
INSERT INTO lang VALUES('picture','iw','š…„');
INSERT INTO lang VALUES('tone','iw','–Œ‰Œ');
INSERT INTO lang VALUES('longplay','iw','„–‚„ €˜…‹„');
INSERT INTO lang VALUES('fsk','iw','PG');
INSERT INTO lang VALUES('actor','iw','™‡—');
INSERT INTO lang VALUES('actors','iw','™‡—‰');
INSERT INTO lang VALUES('director','iw','„Œ');
INSERT INTO lang VALUES('directors','iw','„Œ‰');
INSERT INTO lang VALUES('composer','iw','Œ‡‰');
INSERT INTO lang VALUES('music','iw','…‘‰—„');
INSERT INTO lang VALUES('min','iw','‰‰…');
INSERT INTO lang VALUES('max','iw','—‘‰…');
INSERT INTO lang VALUES('s/w','iw','Œ/™‡…˜');
INSERT INTO lang VALUES('farbe','iw','–’');
INSERT INTO lang VALUES('3D','iw','3D');
INSERT INTO lang VALUES('edit_entry','iw','’˜…Š ”—…‘');
INSERT INTO lang VALUES('view_entry','iw','˜€„ ”—…‘');
INSERT INTO lang VALUES('add_entry','iw','„…‘“ ”—…‘');
INSERT INTO lang VALUES('unknown','iw','Œ€ …ƒ’');
INSERT INTO lang VALUES('country','iw','ƒ‰„');
INSERT INTO lang VALUES('medianr','iw','š—˜ „—Œˆš €… „š—Œ‰ˆ…˜');
INSERT INTO lang VALUES('highest_db_entries','iw','”—…‘‰ €‚˜ „‹‰ ‚…„‰');
INSERT INTO lang VALUES('no','iw','Œ€');
INSERT INTO lang VALUES('yes','iw','‹');
INSERT INTO lang VALUES('medialength','iw','€…˜Š š—Œ‰ˆ…˜ €… —Œˆš');
INSERT INTO lang VALUES('minute_abbrev','iw','ƒ—…š');
INSERT INTO lang VALUES('source','iw','—…˜');
INSERT INTO lang VALUES('staff','iw','ˆ„');
INSERT INTO lang VALUES('name','iw','™');
INSERT INTO lang VALUES('first_name','iw','™ ˜€™…');
INSERT INTO lang VALUES('in_list', 'iw','˜™‰„');
INSERT INTO lang VALUES('comments','iw','„’˜…š');
INSERT INTO lang VALUES('cancel','iw','ˆŒ');
INSERT INTO lang VALUES('create','iw','‰–˜');
INSERT INTO lang VALUES('update','iw','’ƒ‹');
INSERT INTO lang VALUES('edit','iw','’˜…Š');
INSERT INTO lang VALUES('delete','iw','‡—');
INSERT INTO lang VALUES('invalid_media_nr','iw','  .€ Œ”˜ˆ ‘”˜ š‰ „™ƒ…š .„—Œˆš €… š—‰ˆ…˜ ˆŒ ' );
INSERT INTO lang VALUES('warning','iw','€†„˜„');
INSERT INTO lang VALUES('of_aquiration','iw','™Œ „™‚„');
INSERT INTO lang VALUES('wrong_date','iw','.€…˜š €‰†™„… ‰…00 00 0000 €… .2002 €…˜š ‰… €‡ƒ ”˜…€˜ 00 02 2000:ƒ…‚„.€ €š„ Œ€ ˆ…‡ ’Œ „š€˜‰Š „ƒ…‰— „‹‘ €”‘‰ ™ƒ„ „‘”…—„.…˜— Œ™™ ‘”˜…š.„™„ ™ƒ„ „™Œ‰™‰,„‡…ƒ™ ™ƒ„ „™‰,€ Œ„‹‰‘ „‰… ™ƒ„ „˜€™….„š€˜‰Š ™„‹‘š Œ€ —‰‰  ');
INSERT INTO lang VALUES('incomplete_date','iw','00 00 2000 €† ‡‰‰ Œ„‹‘ ,2000 ˜— …ƒ’ ™„™‚š ™š-Œƒ…‚„-€Œ€,—˜„ ™€š„ ‘”— ’Œ „š€˜‰Š „ƒ…‰—');
INSERT INTO lang VALUES('dupe_id_entered','iw','  .„‚„ „‘”˜„ „˜€™…„ €‡ƒ, € šš‹…… ‘˜ˆ ‡ƒ™ ’Œ €…š„ „—Œˆš,€….Œ„‚‰„ „‘”˜„ „˜€™…„ €‡ƒ,€ šš‹…… Œ—Œˆš ‡ƒ™„,„‰€ ‡‰˜„ ˆ…„.…”‰’ š‰„ „‘˜ „„‹‰ ‚…„.‰™ š‰š ‡‰˜„—˜… Œ„š‰„ ™„ „‹‘š „‘”˜ †„…‰:˜†.„‹„ €‡…˜„ …š— „‘”˜.„‘”˜ ™„…‹‘ ‹˜ —‰‰ €‚˜');
INSERT INTO lang VALUES('create_success','iw','.”—…‘ ‰–…˜ €…” ‹…');
INSERT INTO lang VALUES('update_failed','iw','.‹™Œ… ’ƒ‹… „”—…‘');
INSERT INTO lang VALUES('update_success','iw','.’ƒ‹… ’˜ „–Œ‡„');
INSERT INTO lang VALUES('about','iw','’Œ');
INSERT INTO lang VALUES('history','iw','„‘ˆ…˜‰-„');
INSERT INTO lang VALUES('view','iw','˜€„');
INSERT INTO lang VALUES('deleting_entry','iw','%1 …‡— ”—…‘');
INSERT INTO lang VALUES('free_space_title','iw',':’Œ —Œˆš €… š—Œ‰ˆ…˜ ™ˆ‡ ”…-‰');
INSERT INTO lang VALUES('filter','iw','‘');
INSERT INTO lang VALUES('set_filter','iw','—’ ‘');
INSERT INTO lang VALUES('unset_filter','iw','ˆŒ ‘');
INSERT INTO lang VALUES('taperest_absolute','iw','„‡ ‘˜ˆ (Œ€ ‘…) ');
INSERT INTO lang VALUES('taperest_filtered','iw','„‡ ‘˜ˆ(‘…)');
INSERT INTO lang VALUES('help','iw','’†˜„');
INSERT INTO lang VALUES('general','iw','‹ŒŒ‰');
INSERT INTO lang VALUES('sure_to_delete','iw','ˆ…‡ ™š˜–„ Œ‡…— ‹Œ ’˜‹‰ Œ‘”˜ %1?');
INSERT INTO lang VALUES('nobody_named','iw','€‰ ’…ƒ ‘˜ˆ ’š %1 ‹…š˜ %2 %3 €‚˜ †„. ‰-‰‡— „”—…‘ „ˆŒ„ ™Œ %1.');
INSERT INTO lang VALUES('compose_person','iw','Œ‡‰');
INSERT INTO lang VALUES('director_person','iw','„Œ');
INSERT INTO lang VALUES('check_completed','iw','ƒ‰—„ ‚˜„');
INSERT INTO lang VALUES('delete_remaining','iw','’‹™‰-… …‡— „€‚˜ ‰ƒ’ ’Œ ‘˜ˆ †„.');
INSERT INTO lang VALUES('ok','iw','‘ƒ˜');
INSERT INTO lang VALUES('not_ok','iw','‹™Œ');
INSERT INTO lang VALUES('recalc_free','iw','’…™„ ™… ‡™… ™Œ ™ˆ‡ ”…-‰ ’Œ „—Œˆš €… š—Œ‰ˆ…˜.');
INSERT INTO lang VALUES('tapelist_update_failed','iw','‹™Œ ’ƒ‹… Œ˜™‰š ‘˜ˆ‰.');
INSERT INTO lang VALUES('no_entry_in_tapelist','iw','‹™Œ. €‰ ”—…‘ ˜™‰„.');
INSERT INTO lang VALUES('finnished','iw','‚˜');
INSERT INTO lang VALUES('time_left','iw','ƒ—…š ™€˜: %1');
INSERT INTO lang VALUES('configuration','iw','‰‡™…');
INSERT INTO lang VALUES('index','iw','€‰ƒ—‘');
INSERT INTO lang VALUES('intro','iw','…€');
INSERT INTO lang VALUES('menues','iw','š”˜‰ˆ‰');
INSERT INTO lang VALUES('back','iw','€‡…˜„');
INSERT INTO lang VALUES('close','iw','‘‚…˜');
INSERT INTO lang VALUES('help_about','iw','’†˜„ …’Œ €…ƒ…š');
INSERT INTO lang VALUES('actors_list','iw','˜™‰š ™‡—‰');
INSERT INTO lang VALUES('directors_list','iw','˜™‰š „Œ‰');
INSERT INTO lang VALUES('music_list','iw','˜™‰š Œ‡‰‰');
INSERT INTO lang VALUES('no_entries_found','iw','Œ€ –€… ”—…‘‰');
INSERT INTO lang VALUES('no_space_of','iw','€‰ —Œˆš €… š—Œ‰ˆ…˜  €‚˜ ™™€˜ ’Œ‰-… „‰‰… ™Œ %1.');
INSERT INTO lang VALUES('howto','iw','...€‰Š Œ');
INSERT INTO lang VALUES('howto_lang','iw','€‰Š Œ‰–…˜ —…• ‡ƒ™ Œ™”„');
INSERT INTO lang VALUES('howto_help','iw','€‰Š Œ‰–…˜ —…• ’†˜„');
INSERT INTO lang VALUES('howto_templates','iw','€‰Š Œ‰–…˜ †…‚ ˆ”Œˆ ‡ƒ™');
INSERT INTO lang VALUES('language_settings','iw','—‰’š ™”…š');
INSERT INTO lang VALUES('scan_new_lang_files','iw','?ƒ…— Œ™”…š ‡ƒ™…š');
INSERT INTO lang VALUES('scan_new_lang_comment','iw', '†„ ‰‚‰ƒ Œ-     , € ‰–˜š —…• ™”„ ™ŒŠ …™š €…š… š‰, Œ‡”™ ™‰Œ….PhP Video Pro ');
INSERT INTO lang VALUES('select_add_lang','iw','‡˜ ™”…š …‘”…š Œ„š—‰.');
INSERT INTO lang VALUES('select_add_lang_comment','iw','(€‚Œ‰š ‹˜ „…š— …š‰ƒ š„‰ …š—-- ’‰‰ ”˜‰ˆ „€. Œ™”…š €‡˜…š ™‹˜ „-…š—…, ’‰-‰ ‚ Œ†„ ™”„ „€„.)');
INSERT INTO lang VALUES('no_add_lang','iw','Œ€ …‹…š ™”…š …‘”…š.');
INSERT INTO lang VALUES('refresh_lang','iw','™‡†˜ ™”„');
INSERT INTO lang VALUES('refresh_lang_comment','iw','(™‡†˜ ˆ…-‰-‰ —…• ™”…š.)');
INSERT INTO lang VALUES('none','iw','€“ €‡ƒ');
INSERT INTO lang VALUES('select_primary_lang','iw','‡…˜ ™”„ ˜€™…„');
INSERT INTO lang VALUES('select_primary_lang_comment','iw','(š‰ƒ ‰„‰…, ™‰Œ ˆ…-‰-‰ ‡‘˜‰, Œ…€‰ €‚Œ‰š.)');
INSERT INTO lang VALUES('colors','iw','–’‰');
INSERT INTO lang VALUES('feedback_ok','iw', '—Œš š™……š ‘ƒ˜');
INSERT INTO lang VALUES('feedback_err','iw','‹™Œ… —Œš š™……š');
INSERT INTO lang VALUES('template_set','iw','†…‚ ˆ”Œˆ');
INSERT INTO lang VALUES('start_pvp','iw','phpVideoPro „š‡Œ');
INSERT INTO lang VALUES('hit_back_to_correct','iw','„‹„ ‹”š…˜ €‡…˜„ Œš— „ˆ’…š.');
INSERT INTO lang VALUES('goto_entry','iw','ŒŠ ‰™˜ Œ”—…‘');
INSERT INTO lang VALUES('start_page','iw','’…ƒ „š‡Œ„');
INSERT INTO lang VALUES('invalid_fsk','iw', '  ‰™„-… š‡š „‚‰Œ Œ€ ‹‘. .parental guide ˆŒ. ‘…  †„-PG„’˜Š Œ- ');
INSERT INTO lang VALUES('counter_start_stop','iw','„ „š‡Œ/’–…˜');
INSERT INTO lang VALUES('other_pages','iw','’…ƒ‰ €‡˜‰');
INSERT INTO lang VALUES('commercials','iw','š’…Œ…š');
INSERT INTO lang VALUES('cut_off','iw','‘…“');
INSERT INTO lang VALUES('display_limit','iw','‚…Œ „–‚„');
INSERT INTO lang VALUES('display_limit_comment','iw','(‹„ ™…˜…š Œ„–‚, Œ”‰ ’…ƒ, Œ„˜™‰„?)');
INSERT INTO lang VALUES('print_label','iw','š……‰š „ƒ”‘„');
INSERT INTO lang VALUES('howto_label','iw',' €‰Š Œ‰–…˜ …Œ‡™ š…-…-‰…š ˆ”Œˆ‰. ');
INSERT INTO lang VALUES('label','iw','š……‰š');
INSERT INTO lang VALUES('print','iw','„ƒ”‘');
INSERT INTO lang VALUES('medialist_num','iw','˜™‰š š—Œ‰ˆ…˜‰-—Œˆ…š ‘ƒ˜ ‘”˜…š‰.');
INSERT INTO lang VALUES('medialist_alpha','iw','˜™‰š —Œˆ…š-š—Œ‰ˆ…˜‰ ‘ƒ˜ €Œ”ˆ‰.');
INSERT INTO lang VALUES('lines_per_page','iw','™…˜…š ’…ƒ');
INSERT INTO lang VALUES('lines_per_page_comment','iw','†„ ™‰Œ ”’…Œš „„ƒ”‘„ Œ„‡Œ‰ˆ ‹„ ™…˜…š š€‰…š Œ’…ƒ.');
INSERT INTO lang VALUES('date_format','iw','˜™‰š š€˜‰Š');
INSERT INTO lang VALUES('date_format_comment','iw','?€‰Š Œ˜™… „š€˜‰Š');
INSERT INTO lang VALUES('listgen','iw','‰–˜ ˜™‰„');
INSERT INTO lang VALUES('list','iw','˜™‰„');
INSERT INTO lang VALUES('format','iw','„‚ƒ˜„');
INSERT INTO lang VALUES('line_count','iw','™…˜…š');
INSERT INTO lang VALUES('catlist_alpha','iw','˜™‰š —Œˆš š—Œ‰ˆ…˜ ’˜…Š Œ”‰ —ˆ‚…˜‰-„.');
INSERT INTO lang VALUES('lists','iw','˜™‰…š');
INSERT INTO lang VALUES('labels','iw','š……‰…š');
INSERT INTO lang VALUES('cat_adventure','iw','„˜”š—„');
INSERT INTO lang VALUES('cat_action','iw','”’…Œ„');
INSERT INTO lang VALUES('cat_agents','iw','‘…‹');
INSERT INTO lang VALUES('cat_bible','iw','—˜€');
INSERT INTO lang VALUES('cat_biography','iw','‰…‚˜”‰-„');
INSERT INTO lang VALUES('cat_stage','iw','„');
INSERT INTO lang VALUES('cat_documentary','iw','š‰’…ƒ');
INSERT INTO lang VALUES('cat_drama','iw','ƒ˜„');
INSERT INTO lang VALUES('cat_fantasy','iw','”ˆ‘‰„');
INSERT INTO lang VALUES('cat_party','iw','™š„');
INSERT INTO lang VALUES('cat_scary','iw','‘˜ˆ‰ ”‡ƒ');
INSERT INTO lang VALUES('cat_history','iw','„‘ˆ…˜‰-„');
INSERT INTO lang VALUES('cat_horror','iw','„…˜˜');
INSERT INTO lang VALUES('cat_judaica','iw','‰…ƒ€‰—„');
INSERT INTO lang VALUES('cat_camera','iw','–Œ„');
INSERT INTO lang VALUES('cat_catastrophe','iw','‡…˜');
INSERT INTO lang VALUES('cat_children','iw','‰Œƒ‰');
INSERT INTO lang VALUES('cat_comedy','iw','—…ƒ‰-„');
INSERT INTO lang VALUES('cat_concert','iw','—…–˜ˆ');
INSERT INTO lang VALUES('cat_war','iw','‘˜ˆ‰ Œ‡„');
INSERT INTO lang VALUES('cat_crime','iw','”™’');
INSERT INTO lang VALUES('cat_love','iw','‘”…˜‰ €„„');
INSERT INTO lang VALUES('cat_fairytale','iw','€‚ƒ…š');
INSERT INTO lang VALUES('cat_melodrama','iw','”‚’„');
INSERT INTO lang VALUES('cat_monumental','iw','™Œ –„');
INSERT INTO lang VALUES('cat_musical','iw','…‘‰—Œ‰');
INSERT INTO lang VALUES('cat_music','iw','…‘‰—„');
INSERT INTO lang VALUES('cat_videoclip','iw','‚†‰†š …-…-‰ƒ€…');
INSERT INTO lang VALUES('cat_musicmovie','iw','‘˜ˆ‰ …‘‰—„');
INSERT INTO lang VALUES('cat_nature','iw','ˆ’');
INSERT INTO lang VALUES('cat_opera','iw','€…”˜„');
INSERT INTO lang VALUES('cat_operetta','iw','€…”˜ˆ„');
INSERT INTO lang VALUES('cat_problem','iw','„-’‰');
INSERT INTO lang VALUES('cat_report','iw','ƒ…-…‡');
INSERT INTO lang VALUES('cat_satire','iw','„šŒ„');
INSERT INTO lang VALUES('cat_misc','iw','™…‰');
INSERT INTO lang VALUES('cat_sf','iw','ƒ’ ƒ‰…‰');
INSERT INTO lang VALUES('cat_show','iw','š–…‚„');
INSERT INTO lang VALUES('cat_spy','iw','‘˜ˆ‰ ˜‰‚…Œ');
INSERT INTO lang VALUES('cat_thriller','iw','…š‡');
INSERT INTO lang VALUES('cat_animal','iw','‡‰-„');
INSERT INTO lang VALUES('cat_animals','iw', '‡‰-…š');
INSERT INTO lang VALUES('cat_travesty','iw','‡—…-‰');
INSERT INTO lang VALUES('cat_vacation','iw','‡…”™„'); 
INSERT INTO lang VALUES('cat_xmas','iw','‡‚ „…Œƒ');
INSERT INTO lang VALUES('cat_western','iw','’˜‰');
INSERT INTO lang VALUES('cat_westerncomedy','iw','—…ƒ‰-„ ’˜‰');
INSERT INTO lang VALUES('cat_cartoon','iw',' –‰-…˜');
INSERT INTO lang VALUES('db_stats','iw','‘ˆ‰‘ˆ‰—„');
INSERT INTO lang VALUES('stat_counts','iw','‘”‰˜…š');
INSERT INTO lang VALUES('stat_ranks','iw','ƒ‰˜…‚');
INSERT INTO lang VALUES('movies','iw','‘˜ˆ‰');
INSERT INTO lang VALUES('media','iw','š—™…˜š');
INSERT INTO lang VALUES('compose_persons','iw','Œ‡‰‰');
INSERT INTO lang VALUES('director_persons','iw','„Œ‰');
INSERT INTO lang VALUES('actor_persons','iw','™‡—‰');
INSERT INTO lang VALUES('categories','iw','—ˆ‚…˜‰-…-š');
INSERT INTO lang VALUES('countries','iw','ƒ‰…š');
INSERT INTO lang VALUES('categories_stat','iw','—ˆ‚…˜‰…š („‹Œ/™…™)');
INSERT INTO lang VALUES('stats','iw','‘ˆ‰‘ˆ‰—„');
INSERT INTO lang VALUES('dl_pvp_latest','iw','D/L „ƒ…˜„ €‡˜…„');
INSERT INTO lang VALUES('info_update','iw','‰ƒ’ ’ƒ‹…');
INSERT INTO lang VALUES('info_noupdate','iw','<DIV ALIGN="center">The installed version of phpVideoPro (%1) is recent - there\'s no newer version available for download. To download the tarball of the installed version, please follow <A HREF=http://www.qumran.org/homes/izzy/software/get_update.php?program=pvp" TARGET="_blank">this link</A>.</DIV>');
INSERT INTO lang VALUES('info_common','iw','‰ƒ’ ˜‚‰Œ');
INSERT INTO lang VALUES('info_common_info','iw','<DIV ALIGN="center">This is version %1 of phpVideoPro, running on %2.</DIV>');
INSERT INTO lang VALUES('change_nr','iw','Change MediaNr/MediaType for %1');
INSERT INTO lang VALUES('orig_medianr','iw','original MediaNr');
INSERT INTO lang VALUES('new_medianr','iw','new MediaNr');
INSERT INTO lang VALUES('media_copy','iw','Copy data to MediaNr');
INSERT INTO lang VALUES('media_change','iw','Change MediaNr');
INSERT INTO lang VALUES('check_media_delete','iw','…ƒ— € —Œˆš-š—Œ‰ˆ…˜ ”…-‰');
INSERT INTO lang VALUES('medium_deleted','iw','€‰ ’…ƒ ‘˜ˆ‰ ’Œ —Œˆš €… š—Œ‰ˆ…˜.„-…‘˜ —Œˆš €… š—Œ‰ˆ…˜.');
INSERT INTO lang VALUES('medium_not_deleted','iw','—Œˆš €… š—Œ‰ˆ…˜ Œ€ „-…‘˜');
INSERT INTO lang VALUES('change_media_length','iw', '™„ €…˜Š š—Œ‰ˆ…˜ €… —Œˆš ');
INSERT INTO lang VALUES('change_media_length_for','iw', '™„ €…˜Š š—Œ‰ˆ…˜ €… —Œˆš');
INSERT INTO lang VALUES('admin_cats','iw','„Œ —ˆ‚…˜‰-…š');
INSERT INTO lang VALUES('cat_internal_name','iw','‰ƒ…');
INSERT INTO lang VALUES('cat_update_failed','iw','’ƒ‹… ‹™Œ Œ„—ˆ‚…˜‰-…š „€…š: %1');
INSERT INTO lang VALUES('cat_trans_update_failed','iw','’ƒ‹… ™Œ š˜‚… ‹™Œ Œ„—ˆ‚…˜‰-…š „€…š: %1');
INSERT INTO lang VALUES('credits','iw','„‹˜…š');
INSERT INTO lang VALUES('movies_left_in_cat','iw','—ˆ‚…˜‰-„ %1 ’ƒ‰-‰ „…˜‹ ™‰ ‘˜ˆ‰ …€‰ €”™˜ Œ‡…—.');
INSERT INTO lang VALUES('admin_orphans','iw','„‘˜š ”—…‘‰ ‰š…‰');
INSERT INTO lang VALUES('desc_admin_orphans','iw','"Orphaned entries" are data without assignment, i.e. here: Actors, directors and/or composers to whom is nowhere refered to from any movie. These are mostly results of changing a misspelled name after having it saved - but never results of deleted movie entries. Hence it\'s a good idea to remove those entries: on one hand it saves resources, and on the other it helps to prevent a slow-down of database actions.');
INSERT INTO lang VALUES('orphans_found','iw','–€(‰) %1 ‰š…‰');
INSERT INTO lang VALUES('no_orphans_found','iw','†Œ ˆ…. €‰ ŒŠ ’…ƒ ™Œƒ‰ €˜…. (‰™ ’…ƒ?)');
INSERT INTO lang VALUES('delete_orphans','iw','…‡— %1 ‰š…(‰):');
INSERT INTO lang VALUES('backup_db','iw','€‚˜ Œ…€‰');
INSERT INTO lang VALUES('desc_backup_db','iw','It\'s always a good idea to have a backup at hand. Via this form, all your data you saved into the database are extracted, and a SQL command file is created. You can use this file at any time to fill an empty database with (good e.g. for duplication). Just make sure to not use a backup from a never version with an older version of phpVideoPro - this can lead to trouble!<BR><BR><DIV ALIGN="center"><B>Would you like to create the script now?</B></DIV>');
INSERT INTO lang VALUES('admin','iw','‰-„-…Œ');
INSERT INTO lang VALUES('dupes','iw','”—…‘‰ ™…‹”Œ‰');
INSERT INTO lang VALUES('dupe_titles_found','iw','–€(…) %1 ”—…‘‰ € ‹…š˜‰ ™…‹”Œ‰.');
INSERT INTO lang VALUES('rw_media','iw','—Œˆ…š-š—Œ‰ˆ…˜‰ ‰š‰ Œ’˜…Š:');
INSERT INTO lang VALUES('rw_media_comment','iw','—Œˆ…š-š—Œ‰ˆ…˜‰ (™šš‹…… Œ—Œ…ˆ ’Œ‰-„) Œ„™€‰˜ ’Œ‰-„ ™ˆ‡ ”…-‰:');
INSERT INTO lang VALUES('remove_empty_media','iw','„‘˜ —Œˆ…š-š—Œ‰ˆ…˜‰ ˜‰—‰');
INSERT INTO lang VALUES('remove_empty_media_comment','iw','„€ Œ‡…— „˜™‰„, €‡˜‰ ™™ƒ … „‘˜ˆ „€‡˜…, „š—Œ‰ˆ…˜-—Œˆš „˜‰—? ');
INSERT INTO lang VALUES('movie_tone_default','iw','„‚ƒ˜š —…Œ €…ˆ…ˆ‰š Œ‘˜ˆ:');
INSERT INTO lang VALUES('movie_tone_default_comment','iw','†„ ‰™…™ Œ„‚ƒ˜š —…Œ €…ˆ…ˆ‰š  (—…’ ˜€™) Œ”—…‘ ‡ƒ™.');
INSERT INTO lang VALUES('movie_color_default','iw','„‚ƒ˜š –’ €…ˆ…ˆ‰š Œ‘˜ˆ:');
INSERT INTO lang VALUES('movie_color_default_comment','iw','†„ ‰™…™ Œ„‚ƒ˜š –’ €…ˆ…ˆ‰š (—…’ ˜€™) Œ”—…‘ ‡ƒ™. ');
INSERT INTO lang VALUES('site_info','iw','‰ƒ’ ’Œ ’…ƒ');
INSERT INTO lang VALUES('site_info_comment','iw','€‰†„ ‰ƒ’  ’Œ „’…ƒ Œ„–‚ ‘…˜‚ ‹…š˜ ™Œ „˜……‘˜? ');
INSERT INTO lang VALUES('movie_onlabel_default','iw','„‚ƒ˜„ €…ˆ…ˆ‰š Œš…-…-‰-…š');
INSERT INTO lang VALUES('movie_onlabel_default_comment','iw','„‚ƒ˜„ €…ˆ…ˆ‰š Œ”—…‘‰ ‡ƒ™‰: „€ Œ‹ŒŒ, š‰ ™‰-…-…–˜ š-…-‰-…š Œš—Œ‰ˆ…˜‰-—Œˆ…š, ‚ „‰ƒ’ ’Œ ‘˜ˆ †„. ');
INSERT INTO lang VALUES('config_media','iw','‰‡™… ‘˜ˆ‰ …š—Œ‰ˆ…˜‰-—Œˆ…š');
INSERT INTO lang VALUES('cookies','iw','’…‚‰-…š');
INSERT INTO lang VALUES('enable_cookies','iw','‰‹Œ ’…‚‰-…š?');
INSERT INTO lang VALUES('enable_cookies_comment','iw','„€ Œ„Œ ’ƒ‰”…-‰-…š „™™ (Œ™Œ —‰’š ‘) ƒ˜Š „’…‚‰-…š?');
INSERT INTO lang VALUES('expire_cookies','iw',' š—…”š ‡‰-‰ Œ’…‚‰-…š');
INSERT INTO lang VALUES('expire_cookies_comment','iw','How long should a cookie survive in the user\'s browser?');
INSERT INTO lang VALUES('session','iw','Session');
INSERT INTO lang VALUES('day','iw','Day');
INSERT INTO lang VALUES('week','iw','Week');
INSERT INTO lang VALUES('month','iw','Month');
INSERT INTO lang VALUES('preferences','iw','Preferences');
INSERT INTO lang VALUES('admin_filter','iw','Default filter settings');
INSERT INTO lang VALUES('admin_users','iw','Manage user accounts');
INSERT INTO lang VALUES('user','iw','User');
INSERT INTO lang VALUES('login','iw','Login');
INSERT INTO lang VALUES('data_access','iw','Data Access');
INSERT INTO lang VALUES('read_access','iw','May browse entries');
INSERT INTO lang VALUES('read_access_short','iw','rd');
INSERT INTO lang VALUES('add_access','iw','May add new entries');
INSERT INTO lang VALUES('add_access_short','iw','add');
INSERT INTO lang VALUES('upd_access','iw','May update existing entries');
INSERT INTO lang VALUES('upd_access_short','iw','upd');
INSERT INTO lang VALUES('del_access','iw','May delete entries');
INSERT INTO lang VALUES('del_access_short','iw','del');
INSERT INTO lang VALUES('admin_access','iw','May access administrator menues');
INSERT INTO lang VALUES('admin_access_short','iw','adm');
INSERT INTO lang VALUES('add_user','iw','Add User');
INSERT INTO lang VALUES('actions','iw','Actions');
INSERT INTO lang VALUES('user_update_failed','iw','Updating failed for the following users: %1');
INSERT INTO lang VALUES('password','iw','Password');
INSERT INTO lang VALUES('password_retype','iw','Retype Password');
INSERT INTO lang VALUES('admin_useredit','iw','Edit user account');
INSERT INTO lang VALUES('confirm_userdelete','iw','You are about to delete user #%1');
INSERT INTO lang VALUES('confirm_userdeletion','iw','Do you really want to delete user "%1" (%2)?');
INSERT INTO lang VALUES('user_delete_report','iw','Results of user deletion process');
INSERT INTO lang VALUES('user_deleted','iw','Successfully deleted user #%1, "%2" (%3)');
INSERT INTO lang VALUES('user_delete_failed','iw','Deletion of user #%1, "%2" (%3) failed');
INSERT INTO lang VALUES('submit','iw','Submit');
INSERT INTO lang VALUES('welcome','iw','Welcome to phpVideoPro');
INSERT INTO lang VALUES('login_failed','iw','Your LogIn failed. Either you misspelled your password, or the requested account does not exist.<P />');
INSERT INTO lang VALUES('login_required','iw','Your privileges are not sufficient for the requested action. You may login with an appropriate account now.<P />');
INSERT INTO lang VALUES('logout_user','iw','Logged in as "%1". <A HREF="%2">Log out</A>');
INSERT INTO lang VALUES('never','iw','never');
INSERT INTO lang VALUES('hour','iw','Hour');
INSERT INTO lang VALUES('hours','iw','Hours');
INSERT INTO lang VALUES('session_purgetime','iw','After what time time-out an inactive session?');
INSERT INTO lang VALUES('session_purgetime_comment','iw','How long shall a session stay valid without user activity?');
INSERT INTO lang VALUES('max_fontsize','iw','Max Fontsize');
INSERT INTO lang VALUES('labeltype','iw','Label Type');
INSERT INTO lang VALUES('layout_label','iw','Chose Layout');
INSERT INTO lang VALUES('printer','iw','Printer');
INSERT INTO lang VALUES('printer_comment','iw','If you want to print on forms (as used for the PS Labels), we need the exact offsets of your printer.');
INSERT INTO lang VALUES('session_expired','iw','Your session has expired - please log in again.');


