# ========================================================
# Polish Translation phrases for phpVideoPro
# by Leszek Boroch borek@ajax.umcslublin.pl
# iso-8859-2
# ========================================================

INSERT INTO lang (message_id,lang,content) VALUES ('not_yet_implemented','pl','Niestety, jeszcze nie zaimplementowane.');
INSERT INTO lang VALUES('medium','pl','Medium');
INSERT INTO lang VALUES('nr','pl','Nr');
INSERT INTO lang VALUES('title','pl','Tytu³');
INSERT INTO lang VALUES('length','pl','D³ugo¶æ');
INSERT INTO lang VALUES('year','pl','Rok');
INSERT INTO lang VALUES('date_rec','pl','Date Aquired');
INSERT INTO lang VALUES('category','pl','Kategoria');
INSERT INTO lang VALUES('medialist','pl','Lista no¶ników');
INSERT INTO lang VALUES('enter_min_free','pl','Podaj minimaln± ilo¶æ miejsca na no¶niku do pokazania:');
INSERT INTO lang VALUES('display','pl','Display');
INSERT INTO lang VALUES('free_space_on_media','pl','Ten no¶nik ma conajmniej %1 minutê(y) wolnej przestrzeni:');
INSERT INTO lang VALUES('free','pl','Wolny');
INSERT INTO lang VALUES('content','pl','Zawarto¶æ');
INSERT INTO lang VALUES('filter_setup','pl','Ustawienia Filtru');
INSERT INTO lang VALUES('mediatype','pl','Typ No¶nika');
INSERT INTO lang VALUES('screen','pl','Format Obrazu');
INSERT INTO lang VALUES('picture','pl','Format Koloru');
INSERT INTO lang VALUES('tone','pl','Format D¼wiêku');
INSERT INTO lang VALUES('longplay','pl','LongPlay');
INSERT INTO lang VALUES('fsk','pl','PG');
INSERT INTO lang VALUES('actor','pl','Aktor');
INSERT INTO lang VALUES('actors','pl','Aktorzy');
INSERT INTO lang VALUES('director','pl','Re¿yser');
INSERT INTO lang VALUES('directors','pl','Re¿yserzy');
INSERT INTO lang VALUES('composer','pl','Kompozytor');
INSERT INTO lang VALUES('music','pl','Muzyka');
INSERT INTO lang VALUES('min','pl','min');
INSERT INTO lang VALUES('max','pl','max');
INSERT INTO lang VALUES('s/w','pl','b/w');
INSERT INTO lang VALUES('farbe','pl','Kolor');
INSERT INTO lang VALUES('3d','pl','3D');
INSERT INTO lang VALUES('edit_entry','pl','Edycja wpisu %1');
INSERT INTO lang VALUES('view_entry','pl','Podgl±d wpisu %1');
INSERT INTO lang VALUES('add_entry','pl','Dodanie wpisu');
INSERT INTO lang VALUES('unknown','pl','nieznany');
INSERT INTO lang VALUES('country','pl','Kraj');
INSERT INTO lang VALUES('medianr','pl','Nr no¶nika');
INSERT INTO lang VALUES('highest_db_entries','pl','highest entries in db');
INSERT INTO lang VALUES('no','pl','Nie');
INSERT INTO lang VALUES('yes','pl','Tak');
INSERT INTO lang VALUES('medialength','pl','D³ugo¶æ no¶nika');
INSERT INTO lang VALUES('minute_abbrev','pl','min');
INSERT INTO lang VALUES('source','pl','¬ród³o');
INSERT INTO lang VALUES('staff','pl','Staff');
INSERT INTO lang VALUES('name','pl','Nazwa');
INSERT INTO lang VALUES('first_name','pl','Imiê');
INSERT INTO lang VALUES('in_list','pl','na li¶cie');
INSERT INTO lang VALUES('comments','pl','Komentarz');
INSERT INTO lang VALUES('cancel','pl','Anuluj');
INSERT INTO lang VALUES('create','pl','Utwórz');
INSERT INTO lang VALUES('update','pl','Zastosuj');
INSERT INTO lang VALUES('edit','pl','Edytuj');
INSERT INTO lang VALUES('delete','pl','Kasuj');
INSERT INTO lang VALUES('invalid_media_nr','pl','Podany Nr no¶nika jest nieprawid³owy lub niekompletny. Nale¿y podaæ <b>numer</b> w <b>obu</b> polach NrNo¶nika.');
INSERT INTO lang VALUES('warning','pl','Ostrze¿enie');
INSERT INTO lang VALUES('of_aquiration','pl','of aquiration');
INSERT INTO lang VALUES('wrong_date','pl','Wprowadzona data %1 jest (%2) nieprawid³owa. Datê nale¿y wprowadziæ w formacie "YYYY-MM-DD", gdzie "RRRR" to rok (cztery cyfry), "MM" to miesi±c, a "DD" to dzieñ (po dwie cyfry). Pole mo¿e byæ puste (lub ustawione na "0000-00-00").');
INSERT INTO lang VALUES('incomplete_date','pl','If you do not know the exact date, but - for example - only that you aquired it in the year 2000, substitute zeros for the unknown data - in our example the date should look like "2000-00-00".');
INSERT INTO lang VALUES('dupe_id_entered','pl','There is already an entry in the database for the entered media ID. Please hit the "Back" button of your browser and correct your input. Hint: There is a Select-Box next to the input box you specified the media number in. This select box tells you the highest existing movie id. Normally it is a good choice for a new media to increase the first (four-digit) number by one, or for a new movie on the same media, increase the second (two-digit) number by one.');
INSERT INTO lang VALUES('create_success','pl','Wpis utworzony');
INSERT INTO lang VALUES('update_failed','pl','Nieudane uaktualnianie wpisu');
INSERT INTO lang VALUES('update_success','pl','Wpis uaktualniony');
INSERT INTO lang VALUES('about','pl','O programie');
INSERT INTO lang VALUES('history','pl','Historia');
INSERT INTO lang VALUES('view','pl','Widok');
INSERT INTO lang VALUES('deleting_entry','pl','Usuwanie wpisu %1');
INSERT INTO lang VALUES('free_space_title','pl','Wolna przestrzeñ na no¶niku');
INSERT INTO lang VALUES('filter','pl','Filtr');
INSERT INTO lang VALUES('set_filter','pl','W³±cz filtr');
INSERT INTO lang VALUES('unset_filter','pl','Wy³±cz filtr');
INSERT INTO lang VALUES('taperest_absolute','pl','TapeRest (absolute)');
INSERT INTO lang VALUES('taperest_filtered','pl','TapeRest (filtered)');
INSERT INTO lang VALUES('help','pl','Pomoc');
INSERT INTO lang VALUES('general','pl','Ogólne');
INSERT INTO lang VALUES('sure_to_delete','pl','Are you sure you want to delete all data for %1');
INSERT INTO lang VALUES('nobody_named','pl','There\'s no other movie by a %1 named %2 %3 in this db, so I remove this entry from the %1\'s table.');
INSERT INTO lang VALUES('compose_person','pl','kompozytor');
INSERT INTO lang VALUES('director_person','pl','re¿yser');
INSERT INTO lang VALUES('check_completed','pl','Kontrola zakoñczona');
INSERT INTO lang VALUES('delete_remaining','pl','now deleting remaining data for this movie from db');
INSERT INTO lang VALUES('ok','pl','OK');
INSERT INTO lang VALUES('not_ok','pl','Failed');
INSERT INTO lang VALUES('recalc_free','pl','Re-calculating remaining free space on this medium');
INSERT INTO lang VALUES('tapelist_update_failed','pl','Failed updating tape list');
INSERT INTO lang VALUES('no_entry_in_tapelist','pl','Failed - no entry found in tape list');
INSERT INTO lang VALUES('finnished','pl','Zakoñczone');
INSERT INTO lang VALUES('time_left','pl','Pozosta³o(a) %1 minut(a)');
INSERT INTO lang VALUES('configuration','pl','Konfiguracja');
INSERT INTO lang VALUES('index','pl','Index');
INSERT INTO lang VALUES('intro','pl','Intro');
INSERT INTO lang VALUES('menues','pl','Menu');
INSERT INTO lang VALUES('back','pl','Wstecz');
INSERT INTO lang VALUES('close','pl','Zamknij');
INSERT INTO lang VALUES('help_about','pl','Help about');
INSERT INTO lang VALUES('actors_list','pl','Lista aktorów');
INSERT INTO lang VALUES('directors_list','pl','Lista re¿yserów');
INSERT INTO lang VALUES('music_list','pl','Lista kompozytorów');
INSERT INTO lang VALUES('no_entries_found','pl','Nic nie znaleziono');
INSERT INTO lang VALUES('no_space_of','pl','There was no medium with a minimum of %1 min of free space found in the database.');
INSERT INTO lang VALUES('howto','pl','Jak to zrobiæ...');
INSERT INTO lang VALUES('howto_lang','pl','Jak stworzyæ plik z nowym jêzykiem');
INSERT INTO lang VALUES('howto_help','pl','Jak stworzyæ nowy plik pomocy');
INSERT INTO lang VALUES('howto_templates','pl','How to create a new template set');
INSERT INTO lang VALUES('language_settings','pl','Language Settings');
INSERT INTO lang VALUES('scan_new_lang_files','pl','Scan for new language files?');
INSERT INTO lang VALUES('scan_new_lang_comment','pl','(If you created your own language file and put it into the setup directory, this will tell phpVideoPro to look for it)');
INSERT INTO lang VALUES('select_add_lang','pl','Select additional language to install');
INSERT INTO lang VALUES('select_add_lang_comment','pl','(English is already installed and always will be - see next item. For other languages that are already installed, see next item, too.)');
INSERT INTO lang VALUES('no_add_lang','pl','Brak dodatkowych jêzyków.');
INSERT INTO lang VALUES('refresh_lang','pl','Od¶wierz jêzyk');
INSERT INTO lang VALUES('refresh_lang_comment','pl','(re-insert phrases from language file into db)');
INSERT INTO lang VALUES('none','pl','None');
INSERT INTO lang VALUES('select_primary_lang','pl','Wybór jêzyka podstawowego');
INSERT INTO lang VALUES('select_primary_lang_comment','pl','(for missing phrases, there will always be a fall-back to English)');
INSERT INTO lang VALUES('use_charset','pl','U¿ywana tablica znaków');
INSERT INTO lang VALUES('use_charset_comment','pl','(istotne dla kodowania znaków)');
INSERT INTO lang VALUES('colors','pl','Kolory');
INSERT INTO lang VALUES('page_bg','pl','T³o strony');
INSERT INTO lang VALUES('table_bg','pl','T³o tabeli');
INSERT INTO lang VALUES('th_bg','pl','T³o nag³ówków tabeli');
INSERT INTO lang VALUES('feedback_ok','pl','Odpowied¼ "OK"');
INSERT INTO lang VALUES('feedback_err','pl','Odpowied¼ "Failure"');
INSERT INTO lang VALUES('template_set','pl','Template Set');
INSERT INTO lang VALUES('start_pvp','pl','Start phpVideoPro');
INSERT INTO lang VALUES('hit_back_to_correct','pl','Wci¶nij "Wstecz" w celu poprawy b³êdu.');

