# ========================================================
# Italian Language File created by phpVideoPro v0.4.6p5
# Original file created 20010920 by Alessandro Danti
# ========================================================

UPDATE languages SET charset='iso-8859-1' WHERE lang_id='it';
INSERT INTO lang VALUES ('about','it','Informazioni');
INSERT INTO lang VALUES ('actor','it','Attore');
INSERT INTO lang VALUES ('actors','it','Attori');
INSERT INTO lang VALUES ('actors_list','it','Lista degli Attori');
INSERT INTO lang VALUES ('add_entry','it','Aggiungi voce');
INSERT INTO lang VALUES ('back','it','Indietro');
INSERT INTO lang VALUES ('cancel','it','Annulla');
INSERT INTO lang VALUES ('category','it','Categoria');
INSERT INTO lang VALUES ('cat_children','it','Bambini');
INSERT INTO lang VALUES ('check_completed','it','Controllo completato');
INSERT INTO lang VALUES ('close','it','Chiudi');
INSERT INTO lang VALUES ('colors','it','Colori');
INSERT INTO lang VALUES ('comments','it','Commenti');
INSERT INTO lang VALUES ('composer','it','Compositore');
INSERT INTO lang VALUES ('compose_person','it','compositore');
INSERT INTO lang VALUES ('configuration','it','Configurazione');
INSERT INTO lang VALUES ('content','it','Contenuto');
INSERT INTO lang VALUES ('country','it','Nazione');
INSERT INTO lang VALUES ('create','it','Crea');
INSERT INTO lang VALUES ('create_success','it','Voce creata con successo.');
INSERT INTO lang VALUES ('date_rec','it','Data Registrazione');
INSERT INTO lang VALUES ('delete','it','Elimina');
INSERT INTO lang VALUES ('delete_remaining','it','Eliminazione dei dati rimanenti per questo filmato dal database');
INSERT INTO lang VALUES ('deleting_entry','it','Eliminazione voce %1');
INSERT INTO lang VALUES ('director','it','Regista');
INSERT INTO lang VALUES ('directors','it','Registi');
INSERT INTO lang VALUES ('directors_list','it','Lista dei Registi');
INSERT INTO lang VALUES ('director_person','it','regista');
INSERT INTO lang VALUES ('dupe_id_entered','it','Esiste già una voce nel database per l\'identificatore di media selezionato. Premere il pulsante \"Back\" del browser e correggere l\'inserimento. Aiuto: c\'è un box di selezione vicino al box di inserimento dove si specifica il numero di media. Questo box di selezione indica il numero di filmato più recentemente inserito nel database. Normalmente è una ottima scelta per un nuovo inserimento di aumentare il primo numero (a quattro cifre)di uno, o per un nuovo filmato sullo stesso media, di aumentare il secondo numero (di due cifre) di uno.');
INSERT INTO lang VALUES ('edit','it','Modifica');
INSERT INTO lang VALUES ('edit_entry','it','Modifica voce %1');
INSERT INTO lang VALUES ('enter_min_free','it','Enter minimum of free space on medium to display:');
INSERT INTO lang VALUES ('farbe','it','Colore');
INSERT INTO lang VALUES ('filter','it','Filtro');
INSERT INTO lang VALUES ('filter_setup','it','Configurazione Filtri');
INSERT INTO lang VALUES ('finnished','it','Finito');
INSERT INTO lang VALUES ('first_name','it','Nome');
INSERT INTO lang VALUES ('free','it','Vergine');
INSERT INTO lang VALUES ('free_space_on_media','it','Following media have at least %1 minutes of free space available:');
INSERT INTO lang VALUES ('free_space_title','it','Spazio libero sul media');
INSERT INTO lang VALUES ('fsk','it','Vietato ai minori (età)');
INSERT INTO lang VALUES ('general','it','Generale');
INSERT INTO lang VALUES ('help','it','Aiuto');
INSERT INTO lang VALUES ('help_about','it','Aiuto - info');
INSERT INTO lang VALUES ('highest_db_entries','it','Valori più alti nel database');
INSERT INTO lang VALUES ('history','it','Storia');
INSERT INTO lang VALUES ('howto','it','Come fare a...');
INSERT INTO lang VALUES ('howto_help','it','Come creare un file di aiuto');
INSERT INTO lang VALUES ('howto_lang','it','Come creare un nuovo file di linguaggio');
INSERT INTO lang VALUES ('howto_templates','it','Come creare un nuovo set di template');
INSERT INTO lang VALUES ('incomplete_date','it','Se non si conosce la data esatta, ma - per esempio - solo che è stato registrato nell\'anno 2000, sostituire gli zeri solo per i dati conosciuti - nel nostro esempio la data sarebbe \"2000-00-00\".');
INSERT INTO lang VALUES ('index','it','Indice');
INSERT INTO lang VALUES ('intro','it','Introduzione');
INSERT INTO lang VALUES ('invalid_media_nr','it','Il numero di media specificato è incompleto o invalido. Devi specificare un <b>numero/<b> in <b>tutti</b>i campi N. Media');
INSERT INTO lang VALUES ('in_list','it','in Lista');
INSERT INTO lang VALUES ('language_settings','it','Impostazioni linguaggio');
INSERT INTO lang VALUES ('length','it','Durata');
INSERT INTO lang VALUES ('medialength','it','Durata Media');
INSERT INTO lang VALUES ('medialist','it','Lista Formati');
INSERT INTO lang VALUES ('medianr','it','N. Media');
INSERT INTO lang VALUES ('mediatype','it','Formato');
INSERT INTO lang VALUES ('medium','it','Formato');
INSERT INTO lang VALUES ('menues','it','Menu');
INSERT INTO lang VALUES ('music','it','Compositore');
INSERT INTO lang VALUES ('music_list','it','Lista dei compositori');
INSERT INTO lang VALUES ('name','it','Nome');
INSERT INTO lang VALUES ('nobody_named','it','Non c\'è nessun altro filmato con un %1 chiamato %2 %3 in questo database , quindi verrà eliminata questa voce dalla tabella %1.');
INSERT INTO lang VALUES ('none','it','Nessuno');
INSERT INTO lang VALUES ('not_ok','it','Fallito');
INSERT INTO lang VALUES ('not_yet_implemented','it','Spiacente - non ancora disponibile.');
INSERT INTO lang VALUES ('no_add_lang','it','Nessun altro linguaggio disponibile.');
INSERT INTO lang VALUES ('no_entries_found','it','nessuna voce trovata');
INSERT INTO lang VALUES ('no_entry_in_tapelist','it','Fallito - Nessuna voce trovata nella lista dei nastri');
INSERT INTO lang VALUES ('no_space_of','it','Non c\'è alcun media con un minimo di %1 min di spazio libero nel database.');
INSERT INTO lang VALUES ('nr','it','N.');
INSERT INTO lang VALUES ('of_aquiration','it','di registrazione');
INSERT INTO lang VALUES ('page_bg','it','Sfondo della pagina');
INSERT INTO lang VALUES ('picture','it','Formato Colore');
INSERT INTO lang VALUES ('recalc_free','it','Calcolo dello spazio libero rimanente su questo media');
INSERT INTO lang VALUES ('refresh_lang','it','Aggiorna linguaggio');
INSERT INTO lang VALUES ('refresh_lang_comment','it','(reinserisce le frasi dal file di linguaggio nel database)');
INSERT INTO lang VALUES ('s/w','it','b/n');
INSERT INTO lang VALUES ('scan_new_lang_comment','it','(Se sono stati creati dei nuovi files di linguaggio e inseriti nella directory setup, qui è dove phpVideoPro andrà a cercarli)');
INSERT INTO lang VALUES ('scan_new_lang_files','it','Controllare per nuovi files di linguaggio?');
INSERT INTO lang VALUES ('screen','it','Formato Schermo');
INSERT INTO lang VALUES ('select_add_lang','it','Selezionare linguaggi aggiuntivi');
INSERT INTO lang VALUES ('select_add_lang_comment','it','(L\'inglese è già installato e sempre lo sarà. Per altri luinguaggi che sono già installati, guardare dopo.)');
INSERT INTO lang VALUES ('select_primary_lang','it','Scegliere il linguaggio principale');
INSERT INTO lang VALUES ('select_primary_lang_comment','it','(Per le frasi mancanti farà sempre testo il file di lingua inglese)');
INSERT INTO lang VALUES ('set_filter','it','Imposta Filtro');
INSERT INTO lang VALUES ('source','it','Sorgente');
INSERT INTO lang VALUES ('start_pvp','it','Attiva phpVideoPro');
INSERT INTO lang VALUES ('sure_to_delete','it','Sicuri di voler cancellare tutti i dati per %1');
INSERT INTO lang VALUES ('table_bg','it','Sfondo della tabella');
INSERT INTO lang VALUES ('tapelist_update_failed','it','Impossibile aggiornare la lista dei nastri');
INSERT INTO lang VALUES ('taperest_absolute','it','Nastro rimanente (assoluto)');
INSERT INTO lang VALUES ('taperest_filtered','it','Nastro rimanente (filtrato)');
INSERT INTO lang VALUES ('template_set','it','Set di Template');
INSERT INTO lang VALUES ('th_bg','it','Sfondo delle intestazioni della tabella');
INSERT INTO lang VALUES ('time_left','it','%1 minuti rimasti');
INSERT INTO lang VALUES ('title','it','Titolo');
INSERT INTO lang VALUES ('tone','it','Formato Audio');
INSERT INTO lang VALUES ('unknown','it','sconosciuto');
INSERT INTO lang VALUES ('unset_filter','it','Annulla Filtro');
INSERT INTO lang VALUES ('update','it','Aggiorna');
INSERT INTO lang VALUES ('update_failed','it','Impossibile aggiornare la voce.');
INSERT INTO lang VALUES ('update_success','it','Voce aggiornata con successo.');
INSERT INTO lang VALUES ('use_charset','it','CharSet da usare');
INSERT INTO lang VALUES ('use_charset_comment','it','(questo è importante per la codifica del carattere)');
INSERT INTO lang VALUES ('view','it','Mostra');
INSERT INTO lang VALUES ('view_entry','it','Mostra voce %1');
INSERT INTO lang VALUES ('warning','it','attenzione');
INSERT INTO lang VALUES ('wrong_date','it','La data %1 specificata (%2) non è valida. Inserendo qui una data, rispettare la sintassi \"YYYY-MM-DD\"NULL, dove \"YYYY\" è l\'anno (quattro numeri), \"MM\" il mese e \"DD\" per il giorno (tutti a due cifre). Se non si desidera la data, lasciare il campo vuoto (o immettere \"0000-00-00\").');
INSERT INTO lang VALUES ('year','it','Anno');
INSERT INTO lang VALUES ('yes','it','Si');
