# ========================================================
# Portuguese Language File created by phpVideoPro v0.8.0p19
# Translation by Filipe Marques <sopadapedra AT gmail DOT com>
# ========================================================

UPDATE pvp_languages SET charset='UTF-8' WHERE lang_id='pt';
INSERT INTO pvp_lang VALUES ('about','pt','Acerca','');
INSERT INTO pvp_lang VALUES ('actions','pt','Acções','');
INSERT INTO pvp_lang VALUES ('actor','pt','Actor','');
INSERT INTO pvp_lang VALUES ('actors','pt','Actores','');
INSERT INTO pvp_lang VALUES ('actors_list','pt','Lista de Actores','');
INSERT INTO pvp_lang VALUES ('actor_persons','pt','Actores','');
INSERT INTO pvp_lang VALUES ('add_access','pt','Pode adicionar novas entradas','');
INSERT INTO pvp_lang VALUES ('add_access_short','pt','adicionar','');
INSERT INTO pvp_lang VALUES ('add_entry','pt','Adicionar entrada','');
INSERT INTO pvp_lang VALUES ('add_user','pt','Adicionar utilizador','');
INSERT INTO pvp_lang VALUES ('admin','pt','Administrador','');
INSERT INTO pvp_lang VALUES ('admin_access','pt','Pode aceder aos menus de administrador','');
INSERT INTO pvp_lang VALUES ('admin_avlang','pt','Editar disponibilidade de linguagens para áudio e legendas','');
INSERT INTO pvp_lang VALUES ('admin_cats','pt','Categorias Administrativas','');
INSERT INTO pvp_lang VALUES ('admin_disktypes','pt','Editar Tipo de Discos','');
INSERT INTO pvp_lang VALUES ('admin_filter','pt','Definições de Filtros padrão','');
INSERT INTO pvp_lang VALUES ('admin_movietech','pt','Editar dados Técnicos do Filme','');
INSERT INTO pvp_lang VALUES ('admin_orphans','pt','Remover entradas soltas','');
INSERT INTO pvp_lang VALUES ('admin_orphan_fs','pt','Remover ficheiros soltos','');
INSERT INTO pvp_lang VALUES ('admin_printers','pt','Configurar impressoras','');
INSERT INTO pvp_lang VALUES ('admin_pstemplates','pt','Editar modelos PSLabel','');
INSERT INTO pvp_lang VALUES ('admin_required','pt','Esta acção necessita previlégios de administrador!','');
INSERT INTO pvp_lang VALUES ('admin_sessions','pt','Gerir Sessões','');
INSERT INTO pvp_lang VALUES ('admin_translations','pt','Editar Traduções','');
INSERT INTO pvp_lang VALUES ('admin_useredit','pt','Editar contas de utilizador','');
INSERT INTO pvp_lang VALUES ('admin_users','pt','Gerir contas de utilizador','');
INSERT INTO pvp_lang VALUES ('audio_ts','pt','Áudio','');
INSERT INTO pvp_lang VALUES ('back','pt','Retroceder','');
INSERT INTO pvp_lang VALUES ('backup_compress','pt','Activar compressão?','');
INSERT INTO pvp_lang VALUES ('backup_db','pt','Salvaguardar Base de Dados','');
INSERT INTO pvp_lang VALUES ('backup_db_cats','pt','Salvaguardar categorias','');
INSERT INTO pvp_lang VALUES ('backup_db_complete','pt','Salvaguardar Base de Dados completa(incl. preferências tecnicas e de dados)','');
INSERT INTO pvp_lang VALUES ('backup_db_movie_internal','pt','Salvaguardar todos os filmes usando o formato interno do phpVideoPro','');
INSERT INTO pvp_lang VALUES ('backup_db_sysconf','pt','Salvaguardar configurações de sistema e preferências padrão','');
INSERT INTO pvp_lang VALUES ('backup_file_corrupt','pt','O Ficheiro de Salvaguarda seleccionado está corrupto - não é possível restaurar a partir deste!','');
INSERT INTO pvp_lang VALUES ('backup_file_unreadable','pt','Não é possível lever o ficheiro de salvaguarda - tenha a certeza que as permissões do ficheiro estão definindas correctamente!','');
INSERT INTO pvp_lang VALUES ('bubble_help_enable','pt','Activar BubbleHelp?','');
INSERT INTO pvp_lang VALUES ('bubble_help_enable_comment','pt','Se activado, a ajuda de conteúdo-susceptível é mostrada para alguns itens se mover o rato por cima deles(e.g. no botão da janela do conjunto de Padrões de Aplicações).','');
INSERT INTO pvp_lang VALUES ('button_backup','pt','Cópia de Segurança','');
INSERT INTO pvp_lang VALUES ('button_restore','pt','Restaurar','');
INSERT INTO pvp_lang VALUES ('cache_enable','pt','Activar cache no navegador/proxy?','');
INSERT INTO pvp_lang VALUES ('cache_enable_comment','pt','Como phpVideoPro é uma aplicação dinâmica, gerar páginas baseadas em informação da base de dados em cada pedido, pode querer desactivar colocar em cache as páginas geradas. Por vezes, isto é muito útil para utilizadores de MSIE...','');
INSERT INTO pvp_lang VALUES ('cancel','pt','Cancelar','');
INSERT INTO pvp_lang VALUES ('categories','pt','Categorias','');
INSERT INTO pvp_lang VALUES ('category','pt','Categoria','');
INSERT INTO pvp_lang VALUES ('catlist_alpha','pt','Lista de media em ordem alfabética, ordenada por categoria','');
INSERT INTO pvp_lang VALUES ('cat_action','pt','Acção','');
INSERT INTO pvp_lang VALUES ('cat_adventure','pt','Aventura','');
INSERT INTO pvp_lang VALUES ('cat_agents','pt','Agente','');
INSERT INTO pvp_lang VALUES ('cat_animals','pt','Animais','');
INSERT INTO pvp_lang VALUES ('cat_bible','pt','Biblía','');
INSERT INTO pvp_lang VALUES ('cat_biography','pt','Biografia','');
INSERT INTO pvp_lang VALUES ('cat_camera','pt','Câmera','');
INSERT INTO pvp_lang VALUES ('cat_cartoon','pt','Desenhos-Animados','');
INSERT INTO pvp_lang VALUES ('cat_catastrophe','pt','Catástrofe','');
INSERT INTO pvp_lang VALUES ('cat_children','pt','Crianças','');
INSERT INTO pvp_lang VALUES ('cat_comedy','pt','Comédia','');
INSERT INTO pvp_lang VALUES ('cat_concert','pt','Concerto','');
INSERT INTO pvp_lang VALUES ('cat_documentary','pt','Documentário','');
INSERT INTO pvp_lang VALUES ('cat_fairytale','pt','Contos-de-Fadas','');
INSERT INTO pvp_lang VALUES ('cat_fantasy','pt','Fantasia','');
INSERT INTO pvp_lang VALUES ('cat_handle_empty','pt','O campo de categoria não deve estar vazio. Por favor volte atrás e corrija isto para categoria #%1.','');
INSERT INTO pvp_lang VALUES ('cat_history','pt','História','');
INSERT INTO pvp_lang VALUES ('cat_internal_name','pt','Tratar','');
INSERT INTO pvp_lang VALUES ('cat_love','pt','Histórias de Amor','');
INSERT INTO pvp_lang VALUES ('cat_misc','pt','Vários','');
INSERT INTO pvp_lang VALUES ('cat_music','pt','Musica','');
INSERT INTO pvp_lang VALUES ('cat_musicmovie','pt','Filmes de Música','');
INSERT INTO pvp_lang VALUES ('cat_nature','pt','Natureza','');
INSERT INTO pvp_lang VALUES ('cat_opera','pt','Ópera','');
INSERT INTO pvp_lang VALUES ('cat_operetta','pt','Opereta','');
INSERT INTO pvp_lang VALUES ('cat_party','pt','Festa','');
INSERT INTO pvp_lang VALUES ('cat_problem','pt','Problema','');
INSERT INTO pvp_lang VALUES ('cat_report','pt','Reportagem','');
INSERT INTO pvp_lang VALUES ('cat_satire','pt','Sátira','');
INSERT INTO pvp_lang VALUES ('cat_scary','pt','Filmes de Terror','');
INSERT INTO pvp_lang VALUES ('cat_sf','pt','Ficção Científica','');
INSERT INTO pvp_lang VALUES ('cat_show','pt','Espectáculo','');
INSERT INTO pvp_lang VALUES ('cat_spy','pt','Filmes de Espionagem','');
INSERT INTO pvp_lang VALUES ('cat_stage','pt','Palco','');
INSERT INTO pvp_lang VALUES ('cat_trans_update_failed','pt','Actualização falhou para a tradução das seguintes categorias: %1','');
INSERT INTO pvp_lang VALUES ('cat_travesty','pt','Travesti','');
INSERT INTO pvp_lang VALUES ('cat_update_failed','pt','Actualização falhou para as seguintes categorias: %1','');
INSERT INTO pvp_lang VALUES ('cat_vacation','pt','Férias','');
INSERT INTO pvp_lang VALUES ('cat_videoclip','pt','Clip de Música','');
INSERT INTO pvp_lang VALUES ('cat_war','pt','Filmes de Guerra','');
INSERT INTO pvp_lang VALUES ('cat_western','pt','Velho Oeste','');
INSERT INTO pvp_lang VALUES ('cat_westerncomedy','pt','Comédia-Velho Oeste','');
INSERT INTO pvp_lang VALUES ('cat_xmas','pt','Natal','');
INSERT INTO pvp_lang VALUES ('change_disktype','pt','Trocar Disco para %1','');
INSERT INTO pvp_lang VALUES ('change_media_length','pt','Alterar Tamanho de Media','');
INSERT INTO pvp_lang VALUES ('change_media_length_for','pt','Por Favor insira a capacidade para %1','');
INSERT INTO pvp_lang VALUES ('change_nr','pt','Alterar Número de Media/Tipo de Media para %1','');
INSERT INTO pvp_lang VALUES ('change_rc','pt','Alterar Código de Região','');
INSERT INTO pvp_lang VALUES ('change_rc_for','pt','Alterar Código de Região para %1','');
INSERT INTO pvp_lang VALUES ('check_completed','pt','Verificação completa','');
INSERT INTO pvp_lang VALUES ('check_media_delete','pt','Verificando se a média está vazia','');
INSERT INTO pvp_lang VALUES ('clean_restore','pt','Limpar (remover) dados antigos antes de restaurar','');
INSERT INTO pvp_lang VALUES ('close','pt','Fechar','');
INSERT INTO pvp_lang VALUES ('comments','pt','Comentários','');
INSERT INTO pvp_lang VALUES ('comment_not_string','pt','O comentário inserido contem caracteres inválidos (para prevenir injecção de código, apenas letras, digitos e \"-\" são permitidos).','');
INSERT INTO pvp_lang VALUES ('commercials','pt','Comerciais','');
INSERT INTO pvp_lang VALUES ('composer','pt','Compositor','');
INSERT INTO pvp_lang VALUES ('compose_person','pt','compositor','');
INSERT INTO pvp_lang VALUES ('compose_persons','pt','Compositores','');
INSERT INTO pvp_lang VALUES ('configuration','pt','Configuração','');
INSERT INTO pvp_lang VALUES ('config_media','pt','Filmes e Media','');
INSERT INTO pvp_lang VALUES ('confirm_delete','pt','Deseja mesmo apagar esta gravação?','');
INSERT INTO pvp_lang VALUES ('confirm_prilang','pt','Pretende mesmo alterar a linguagem primária padrão  para TODOS os (novos) utilizadores?','');
INSERT INTO pvp_lang VALUES ('confirm_userdelete','pt','Está prestes a apagar o utilizador #%1','');
INSERT INTO pvp_lang VALUES ('confirm_userdeletion','pt','Está prestes a apagar o utilizador \"%1\" (%2). O que deverá ser feito com a media do utilizador?','');
INSERT INTO pvp_lang VALUES ('content','pt','Conteúdo','');
INSERT INTO pvp_lang VALUES ('counter_start_stop','pt','Contador Iniciar/Parar','');
INSERT INTO pvp_lang VALUES ('countries','pt','Países','');
INSERT INTO pvp_lang VALUES ('country','pt','País','');
INSERT INTO pvp_lang VALUES ('create','pt','Criar','');
INSERT INTO pvp_lang VALUES ('create_success','pt','Entrada criada com sucesso','');
INSERT INTO pvp_lang VALUES ('credits','pt','Créditos','');
INSERT INTO pvp_lang VALUES ('cut_off','pt','Cortados','');
INSERT INTO pvp_lang VALUES ('data_access','pt','Acesso de Dados','');
INSERT INTO pvp_lang VALUES ('date_format','pt','Formatar Dados','');
INSERT INTO pvp_lang VALUES ('date_format_comment','pt','Qual o formato a usar para mostrar a data','');
INSERT INTO pvp_lang VALUES ('date_is_nan','pt','Data, mês e ano têm que ser numéricos!n(i.e. apenas digitos são permitidos)','');
INSERT INTO pvp_lang VALUES ('date_rec','pt','Data adquirida','');
INSERT INTO pvp_lang VALUES ('day','pt','Dia','');
INSERT INTO pvp_lang VALUES ('db_stats','pt','Estatísticas','');
INSERT INTO pvp_lang VALUES ('delete','pt','Apagar','');
INSERT INTO pvp_lang VALUES ('delete_lang','pt','Apagar linguagem','');
INSERT INTO pvp_lang VALUES ('delete_lang_comment','pt','Apagar todas as frases da linguagem especifícada da base de dados. Isto não vai apagar o ficheiro da linguagem, para poder reinserir as frases posteiormente (se não apagar o ficheiro você mesmo)','');
INSERT INTO pvp_lang VALUES ('delete_orphans','pt','Apagando %1 orfão(s):','');
INSERT INTO pvp_lang VALUES ('delete_remaining','pt','apagando agora dados restantes para este filme da base de dados','');
INSERT INTO pvp_lang VALUES ('deleting_entry','pt','Apagando a entrada %1','');
INSERT INTO pvp_lang VALUES ('del_access','pt','Pode apagar entradas','');
INSERT INTO pvp_lang VALUES ('desc_admin_orphans','pt','\"Entradas Orfão\" são dados não atribuidas, i.e. aqui: Actores, directores, e/ou compositores a quem não existe referência em qualquer filme. Estes são maioritariamente resultado de alterações de nomes mal escritos após gravação - mas nunca resultam de apagar entradas de filmes. Daqui é uma boa ideia remover aquelas entradas: por um lado poupa recursos, e por outro ajuda a prevenir um atraso nas acções da base de dados.','');
INSERT INTO pvp_lang VALUES ('desc_admin_orphan_fs','pt','\"Fiheiros Orfãos\" são dados não atribuidos, i.e. aqui:images às quais não há referência em qualquer filme. A razão mais provável para isto: <UL><LI>Você adquiriu imagens com uma pesquisa IMDB mas decidiu não as usar</LI><LI>Você editou uma gravação e modificou/removeu a imagem da descrição</LI><LI>Você apagou uma gravação, e esta aplicação estúpida não se importou com a imagem</LI></UL>No entanto: Se pensar não atribuir estas imagens a nenhum ficheiro de gravação, pode permitir ao phpVideoPro apagar os ficheiros listados aqui.','');
INSERT INTO pvp_lang VALUES ('desc_backup_db','pt','É sempre uma boa ideia ter uma cópia de segurança à mão. Enquanto é preferível usar as ferramentas da base de dados <code>mysql_dump</code>,<code>pgsql_dump</code>etc.) para uma cópia de segurança completa, tem que ter a base de dados hospedada numa máquina a que não tem acesso a consola - neste caso, use a \"Cópia de Segurança Completa\" aqui, que vai salvar a sua base de dados completa num script SQL.<BR>Se apenas pretender gravar os dados do seu filme, e.g. para duplicar noutra base de dados, deve fazer uma cópia de segurança de todos os seus filmes usando o formato interno do phpVideoPro: deste modo pode até migrar entre bases de dados de diferentes tipos, e.g. MySQL e PostgreSQL. Enquanto restaura a cópia de segurança completa de uma versão anterior do phpVideoPro para uma nova os resultados a necessitar de actualização da base de dados após (como se fizesse apenas uma actualização ao phpVideoPro), a cópia de segurança interna PVP devem ser compativeis entre versões(futuramente irá mostrar ;)<BR>Pode prentender comprimir a sua cópia de segurança: se a sua instalação do PHP está compilada com o suporte de gzip, apenas verifique a caixa de compressão e poupe até 90% do tamanho do ficheiro.><BR>','');
INSERT INTO pvp_lang VALUES ('directors','pt','Directores','');
INSERT INTO pvp_lang VALUES ('directors_list','pt','Lista de Directores','');
INSERT INTO pvp_lang VALUES ('director_persons','pt','Directores','');
INSERT INTO pvp_lang VALUES ('disktype_add_failed','pt','Lamento, Não consegui adicionar o novo tipo de disco','');
INSERT INTO pvp_lang VALUES ('disktype_change','pt','Alterar Tipo de Disco','');
INSERT INTO pvp_lang VALUES ('disktype_contains_media','pt','Este tipo de disco não pode ser apagado no momento, uma vez que a seguinte media se está a referir a ele:','');
INSERT INTO pvp_lang VALUES ('disktype_name_empty','pt','O nome para o tipo de disco não deve estar vazio. Por favor volte atrás e corrija isto para o tipo de disco #%1.','');
INSERT INTO pvp_lang VALUES ('disktype_update_failed','pt','Lamento, Não consegui actualizar o seguinte tipo de disco #s: %1.','');
INSERT INTO pvp_lang VALUES ('disk_size','pt','Tamanho de Disco','');
INSERT INTO pvp_lang VALUES ('disk_type','pt','Tipo de Disco','');
INSERT INTO pvp_lang VALUES ('display','pt','Mostrar','');
INSERT INTO pvp_lang VALUES ('display_limit','pt','Mostra Limite','');
INSERT INTO pvp_lang VALUES ('display_limit_comment','pt','(quantas linhas mostrar por página de listas)','');
INSERT INTO pvp_lang VALUES ('dl_pvp_latest','pt','D/L última versão','');
INSERT INTO pvp_lang VALUES ('dupes','pt','Duplicar entradas','');
INSERT INTO pvp_lang VALUES ('dupes_own','pt','Próprias','');
INSERT INTO pvp_lang VALUES ('dupes_own_strict','pt','Próprias+Estritas)','');
INSERT INTO pvp_lang VALUES ('dupes_strict','pt','Estritas','');
INSERT INTO pvp_lang VALUES ('dupe_id_entered','pt','Já existe uma entrada na base de dados para a ID da media indicada. Por favor carregue no botão \"retroceder\" no seu navegador e corrija este valor de entrada. Dica: Existe uma Caixa-Selecção ao lado da caixa de entrada em que especifíca o número da media. Esta caixa de selecção diz-lhe qual a ID mais alta de um filme existente. Normalmente é uma boa escolha para uma nova media incrementar o primeiro (quatro-digitos) número em um, ou para um novo filme na mesma media, incrementar o segundo (dois-digitos) número em um.','');
INSERT INTO pvp_lang VALUES ('dupe_titles_found','pt','Encontrados %1 titúlos com possíveis duplicados:','');
INSERT INTO pvp_lang VALUES ('edit','pt','Editar','');
INSERT INTO pvp_lang VALUES ('edit_entry','pt','Editar entrada %1','');
INSERT INTO pvp_lang VALUES ('enable_cookies','pt','Activar cookies?','');
INSERT INTO pvp_lang VALUES ('enable_cookies_comment','pt','Deviam as preferências de utilizador(e.g. definições de filtros) ser geridas através de cookies?','');
INSERT INTO pvp_lang VALUES ('ended_sessions','pt','Sessões Terminadas','');
INSERT INTO pvp_lang VALUES ('enter_min_free','pt','Inserir minímo de espaço livro na media a mostrar:','');
INSERT INTO pvp_lang VALUES ('enter_new_medianr','pt','Por favor insira o MediaNr para este novo %1','');
INSERT INTO pvp_lang VALUES ('error_occured','pt','Erro de phpVideoPro','');
INSERT INTO pvp_lang VALUES ('expire_cookies','pt','Tempo de vida dos cookies','');
INSERT INTO pvp_lang VALUES ('expire_cookies_comment','pt','Quanto tempo deve um cookie soberviver no navegador do utilizador?','');
INSERT INTO pvp_lang VALUES ('farbe','pt','Cor','');
INSERT INTO pvp_lang VALUES ('filter','pt','Filtro','');
INSERT INTO pvp_lang VALUES ('filter_setup','pt','Configurar Filtro','');
INSERT INTO pvp_lang VALUES ('finnished','pt','Terminado','');
INSERT INTO pvp_lang VALUES ('first_name','pt','Primeiro Nome','');
INSERT INTO pvp_lang VALUES ('fontsize_is_nan','pt','Tamanho de Fonte deve ser dado em valores numéricosn(i.e. apenas digitos são permitidos aqui).','');
INSERT INTO pvp_lang VALUES ('format','pt','Formatar','');
INSERT INTO pvp_lang VALUES ('free','pt','Libertar','');
INSERT INTO pvp_lang VALUES ('free_space_on_media','pt','A seguinte media tem pelo menos %1 minutos de espaço livre disponível:','');
INSERT INTO pvp_lang VALUES ('free_space_title','pt','Espaço livre na media','');
INSERT INTO pvp_lang VALUES ('fsk_is_nan','pt','O valor seleccionado para PG não é numérico,nmas phpVideoPro exije um valor numérico.nClique no ícone de informação ao lado do PG para mais detalhes.','');
INSERT INTO pvp_lang VALUES ('general','pt','Geral','');
INSERT INTO pvp_lang VALUES ('goto_entry','pt','Ir directamente para a entrada:','');
INSERT INTO pvp_lang VALUES ('grant_filter_desc','pt','Mostrar gravações desde','');
INSERT INTO pvp_lang VALUES ('graphic_file','pt','Ficheiro de Imagem','');
INSERT INTO pvp_lang VALUES ('help','pt','Ajuda','');
INSERT INTO pvp_lang VALUES ('help_about','pt','Ajuda acerca','');
INSERT INTO pvp_lang VALUES ('help_for_block','pt','Ajuda para este bloco','');
INSERT INTO pvp_lang VALUES ('hide_cat','pt','Esconder categoria','');
INSERT INTO pvp_lang VALUES ('highest_db_entries','pt','entrada mais alta na bd','');
INSERT INTO pvp_lang VALUES ('history','pt','História','');
INSERT INTO pvp_lang VALUES ('hit_back_to_correct','pt','Carregue no botão \"Retroceder\" para corrijir o erro.','');
INSERT INTO pvp_lang VALUES ('hour','pt','Hora','');
INSERT INTO pvp_lang VALUES ('hours','pt','Horas','');
INSERT INTO pvp_lang VALUES ('howto','pt','Como...','');
INSERT INTO pvp_lang VALUES ('howto_help','pt','Como criar um ficheiro de ajuda','');
INSERT INTO pvp_lang VALUES ('howto_label','pt','Como criar/configurar etiquetas modelo','');
INSERT INTO pvp_lang VALUES ('howto_lang','pt','Como criar um novo ficheiro de linguagem','');
INSERT INTO pvp_lang VALUES ('howto_templates','pt','Como criar um novo conjunto de modelos','');
INSERT INTO pvp_lang VALUES ('id_is_nan','pt','ID deve ser numérican(i.e. apenas digítos são permitidos)','');
INSERT INTO pvp_lang VALUES ('imdbsearch','pt','Recuperar detalhes de filmes do IMDB','');
INSERT INTO pvp_lang VALUES ('imdb_cache_dir','pt','Directório para guardar a cache do IMDB','');
INSERT INTO pvp_lang VALUES ('imdb_cache_dir_comment','pt','Este directório deve ser e/l para o Servidor da Rede e usado especifícamente para este propósito. O caminho pode estar ligado ao caminho base para a instalação do phpVideoPro(recomendado). <b><i>Não</i></b> usar os directórios temporários do sistema para isto.','');
INSERT INTO pvp_lang VALUES ('imdb_cache_enable','pt','Activar caching dos dados do IMDB?','');
INSERT INTO pvp_lang VALUES ('imdb_cache_enable_comment','pt','Procurar detalhes do filme no IMDB pode ser intensivo em termos temporais, uma vez que o phpVideoPro necessita de adquidir várias páginas. No entanto, caching só faz sentido se tenciona procurar os dados do mesmo filme mais do que uma vez - por isso normalmente você não necessita disso. Se trocar esta opção para activa, tenha a certeza que define um directório cache que tenha permissões de escrita para o servidor da rede.','');
INSERT INTO pvp_lang VALUES ('imdb_cache_expire','pt','Remover cache do IMDB','');
INSERT INTO pvp_lang VALUES ('imdb_cache_expire_comment','pt','Se a função caching do IMDB estiver activada, o tamanho do directório de cache vai aumentar. Use esta opção para espicíficar quando os ficheiros devem \"expirar\", i.e. a idade máxima que é permitido estes atingirem.','');
INSERT INTO pvp_lang VALUES ('imdb_cache_use','pt','Usar dados em cache para novos pedidos?','');
INSERT INTO pvp_lang VALUES ('imdb_cache_use_comment','pt','Enquanto a indicação acima controla o <b><i>armazenamento</i></b> dos dados do IMDB na cache local, esta opção controla se o phpVideoPro usa esta cache para procuras. Se activado, e existem dados na cache, o phpVideoPro não vai contactar o IMDB para detalhes no filme especifícado mas sim usa os dados da cache.','');
INSERT INTO pvp_lang VALUES ('imdb_image_files','pt','Ficheiros de imagem do IMDB','');
INSERT INTO pvp_lang VALUES ('imdb_movie_id','pt','ID do filme do IMDB','');
INSERT INTO pvp_lang VALUES ('imdb_search_empty_result','pt','Lamento, mas não encontrámos nenhuma entrada correspondente no IMDB.<BR>Pode querer tentar novamente com termos de procura diferentes.','');
INSERT INTO pvp_lang VALUES ('imdb_title_search','pt','Procurar filme no IMDB','');
INSERT INTO pvp_lang VALUES ('imdb_transfer2edit','pt','Transferir dados para editar ecrã','');
INSERT INTO pvp_lang VALUES ('imdb_tx','pt','Dados a transferir do IMDB','');
INSERT INTO pvp_lang VALUES ('imdb_txwin_autoclose','pt','Fechar Automaticamente janela de procurar na transferência de dados?','');
INSERT INTO pvp_lang VALUES ('imdb_txwin_autoclose_comment','pt','Quando tiver todos os valores necessários do IMDB e tranferidos estes para o ecrã de edição, a janela de procurar não é mais necessária. Não obstante, pode querer guardar para referência por outras razões.','');
INSERT INTO pvp_lang VALUES ('imdb_tx_actor','pt','Actores','');
INSERT INTO pvp_lang VALUES ('imdb_tx_cat','pt','Categorias','');
INSERT INTO pvp_lang VALUES ('imdb_tx_comment','pt','Quando adicionado/editando uma entrada de um filme, phpVideoPro oferece a possibilidade de adquirir alguma informação do IMDB. Aqui pode especifícar qual a informação que pretende por definição transferir para a base de dados do phpVideoPro.','');
INSERT INTO pvp_lang VALUES ('imdb_tx_comments','pt','Comentário','');
INSERT INTO pvp_lang VALUES ('imdb_tx_country','pt','País','');
INSERT INTO pvp_lang VALUES ('imdb_tx_director','pt','Director','');
INSERT INTO pvp_lang VALUES ('imdb_tx_length','pt','Comprimento','');
INSERT INTO pvp_lang VALUES ('imdb_tx_music','pt','Compositor','');
INSERT INTO pvp_lang VALUES ('imdb_tx_title','pt','Título','');
INSERT INTO pvp_lang VALUES ('imdb_tx_year','pt','Ano','');
INSERT INTO pvp_lang VALUES ('imdb_url','pt','Sítio do IMDB a usar','');
INSERT INTO pvp_lang VALUES ('imdb_url2','pt','Sítio Alternativo do IMDB','');
INSERT INTO pvp_lang VALUES ('imdb_url2_comment','pt','Apesar de termos localizado instâncias do IMDB, o que elas estão localizadas para saber são os identificadores que a classe IMDB usa para analise - por isso esta(s) localização(ões) apenas quebram a classe. Por outro lado, a informação do filme que necessitamos permanece em Inglês mesmo em sítios não Ingleses. Isto significa, para análise dos detalhes que precisamos do sítio <b><i>Ingês</i></b> do IMDB - por favor escolha um adequado.','');
INSERT INTO pvp_lang VALUES ('imdb_url_comment','pt','A Base de Dados de Filmes na Internet fornece informação de muitos filmes. Há sítios localizados disponíveis: o sítio Alemão e.g. permite pesquisas por filmes de nome Alemão, enquanto que o sítio dos EUA é pesquisável por nomes Ingleses. Seleccione um sítio que corresponda melhor com os títulos dos filmes na sua base de dados.','');
INSERT INTO pvp_lang VALUES ('imp_errors','pt','Importação de %2 gravações terminou com %1 erros.','');
INSERT INTO pvp_lang VALUES ('imp_success','pt','Importação de %1 gravações completada com sucesso.','');
INSERT INTO pvp_lang VALUES ('incomplete_date','pt','Se não sabe a data exacta, mas - por exemplo - apenas que adiquiriu no ano 2000 substítua zeros pela data desconhecida - no nosso exemplo a data devia ficar assim \"00\" \"00\" \"2000\".','');
INSERT INTO pvp_lang VALUES ('index','pt','Índice','');
INSERT INTO pvp_lang VALUES ('info_common','pt','Informação comum','');
INSERT INTO pvp_lang VALUES ('info_common_info','pt','<DIV ALIGN=\"center\">Esta é a versão %1 do phpVideoPro, correndo em %2.</DIV>','');
INSERT INTO pvp_lang VALUES ('info_noupdate','pt','<DIV ALIGN=\"center\">A versão instalada do phpVideoPro (%1) é recente - não há nenhuma nova versão disponível para baixar. Para baixar o ficheiro tar da versão instalada por favor siga <A HREF=\"http://projects.izzysoft.de/progs/get_update.php?program=pvp\" TARGET=\"_blank\">esta hiperligação</A>.</DIV>','');
INSERT INTO pvp_lang VALUES ('info_update','pt','Actualizar Informação','');
INSERT INTO pvp_lang VALUES ('input_errors_occured','pt','O phpVideoPro encontrou %1 problema(s) enquanto processava o valor de entrada:','');
INSERT INTO pvp_lang VALUES ('intro','pt','Introdução','');
INSERT INTO pvp_lang VALUES ('intro_usage','pt','<P>Aqui estão algumas informações para os novos utilizadores:</P><ul><li>Navegação é sempre possível usando o barra de menu disponível no topo em quase todas as páginas</li><li>A Maioria das páginas são suportadas por um ecrã de ajuda. Pode invocar este através de menu de ajuda ou (quando disponível) do botão \"?\"</li><li>O campo em baixo permite-lhe saltar directamente para um filme - se sabe o número da media. De outro modo, é preferível usar a ListaMedia (disponível a partir do menu \"Ver\") ou através do campo procura (menu \"Editar\").</li></ul>','');
INSERT INTO pvp_lang VALUES ('intro_usage_skip','pt','<P>Se não precisa deste texto introdutório mais, pode desliga-lo com a opção correspondente no ecrã das preferências (ver o menu \"Editar\").</P>','');
INSERT INTO pvp_lang VALUES ('intro_usage_title','pt','Introdução para novos utilizadores','');
INSERT INTO pvp_lang VALUES ('invalid_backup_dir','pt','O directório de Segurança configurado não existe.','');
INSERT INTO pvp_lang VALUES ('invalid_fsk','pt','O valor inserido para PG (\"%1\") é inválido. PG significa Controlo Parental, i.e. o mínimo de idade abaixo do qual ninguém deve ter acesso a este filme.','');
INSERT INTO pvp_lang VALUES ('invalid_media_nr','pt','O NumMedia especifícado ou está incompleto ou é inválido. Deve especifícar um <b>número</b> em <b>ambos</b> os campos NumMedia.','');
INSERT INTO pvp_lang VALUES ('in_list','pt','em Lista','');
INSERT INTO pvp_lang VALUES ('is_rw','pt','reescrevível','');
INSERT INTO pvp_lang VALUES ('label','pt','Etiqueta','');
INSERT INTO pvp_lang VALUES ('labels','pt','Etiquetas','');
INSERT INTO pvp_lang VALUES ('labeltype','pt','Tipo de Etiqueta','');
INSERT INTO pvp_lang VALUES ('language_settings','pt','Definições de Linguagem','');
INSERT INTO pvp_lang VALUES ('lang_aa','pt','Afegão','');
INSERT INTO pvp_lang VALUES ('lang_af','pt','Africano','');
INSERT INTO pvp_lang VALUES ('lang_ar','pt','Árabe','');
INSERT INTO pvp_lang VALUES ('lang_be','pt','Bielorruso','');
INSERT INTO pvp_lang VALUES ('lang_bg','pt','Búlgaro','');
INSERT INTO pvp_lang VALUES ('lang_bo','pt','Tibetano','');
INSERT INTO pvp_lang VALUES ('lang_br','pt','Bretão','');
INSERT INTO pvp_lang VALUES ('lang_bs','pt','Bósnio','');
INSERT INTO pvp_lang VALUES ('lang_ca','pt','Catalão','');
INSERT INTO pvp_lang VALUES ('lang_ce','pt','Checheno','');
INSERT INTO pvp_lang VALUES ('lang_co','pt','Córsico','');
INSERT INTO pvp_lang VALUES ('lang_cs','pt','Checo','');
INSERT INTO pvp_lang VALUES ('lang_cy','pt','Galego','');
INSERT INTO pvp_lang VALUES ('lang_da','pt','Dinamarquês','');
INSERT INTO pvp_lang VALUES ('lang_de','pt','Alemão','');
INSERT INTO pvp_lang VALUES ('lang_el','pt','Grego','');
INSERT INTO pvp_lang VALUES ('lang_en','pt','Inglês','');
INSERT INTO pvp_lang VALUES ('lang_es','pt','Espanhol','');
INSERT INTO pvp_lang VALUES ('lang_et','pt','Estónio','');
INSERT INTO pvp_lang VALUES ('lang_eu','pt','Basco','');
INSERT INTO pvp_lang VALUES ('lang_fa','pt','Persa','');
INSERT INTO pvp_lang VALUES ('lang_fi','pt','Finlandês','');
INSERT INTO pvp_lang VALUES ('lang_fr','pt','Francês','');
INSERT INTO pvp_lang VALUES ('lang_ga','pt','Irlandês','');
INSERT INTO pvp_lang VALUES ('lang_gd','pt','Gaelico','');
INSERT INTO pvp_lang VALUES ('lang_hr','pt','Croata','');
INSERT INTO pvp_lang VALUES ('lang_hu','pt','Húngaro','');
INSERT INTO pvp_lang VALUES ('lang_hy','pt','Armeniano','');
INSERT INTO pvp_lang VALUES ('lang_in','pt','Indonesio','');
INSERT INTO pvp_lang VALUES ('lang_is','pt','Islândes','');
INSERT INTO pvp_lang VALUES ('lang_it','pt','Italiano','');
INSERT INTO pvp_lang VALUES ('lang_iw','pt','Hebreu','');
INSERT INTO pvp_lang VALUES ('lang_ja','pt','Japonês','');
INSERT INTO pvp_lang VALUES ('lang_ka','pt','Georgiano','');
INSERT INTO pvp_lang VALUES ('lang_km','pt','Cambodjiano','');
INSERT INTO pvp_lang VALUES ('lang_ko','pt','Coreano','');
INSERT INTO pvp_lang VALUES ('lang_ku','pt','Curdo','');
INSERT INTO pvp_lang VALUES ('lang_la','pt','Latino','');
INSERT INTO pvp_lang VALUES ('lang_lb','pt','Luxemburgês','');
INSERT INTO pvp_lang VALUES ('lang_lt','pt','Lituâno','');
INSERT INTO pvp_lang VALUES ('lang_mk','pt','Macedonio','');
INSERT INTO pvp_lang VALUES ('lang_mo','pt','Moldavo','');
INSERT INTO pvp_lang VALUES ('lang_ne','pt','Nepalês','');
INSERT INTO pvp_lang VALUES ('lang_nl','pt','Holandês','');
INSERT INTO pvp_lang VALUES ('lang_no','pt','Norueguês','');
INSERT INTO pvp_lang VALUES ('lang_pl','pt','Polaco','');
INSERT INTO pvp_lang VALUES ('lang_pt','pt','Português','');
INSERT INTO pvp_lang VALUES ('lang_ro','pt','Romeno','');
INSERT INTO pvp_lang VALUES ('lang_ru','pt','Russo','');
INSERT INTO pvp_lang VALUES ('lang_sh','pt','Servo-Croata','');
INSERT INTO pvp_lang VALUES ('lang_sk','pt','Eslovaco','');
INSERT INTO pvp_lang VALUES ('lang_sl','pt','Esloveno','');
INSERT INTO pvp_lang VALUES ('lang_sq','pt','Albanês','');
INSERT INTO pvp_lang VALUES ('lang_sr','pt','Sérvio','');
INSERT INTO pvp_lang VALUES ('lang_su','pt','Sudanês','');
INSERT INTO pvp_lang VALUES ('lang_sv','pt','Sueco','');
INSERT INTO pvp_lang VALUES ('lang_tr','pt','Turco','');
INSERT INTO pvp_lang VALUES ('lang_uk','pt','Ucraniano','');
INSERT INTO pvp_lang VALUES ('lang_vi','pt','Vietnamita','');
INSERT INTO pvp_lang VALUES ('lang_zh','pt','Chinês','');
INSERT INTO pvp_lang VALUES ('last_entry','pt','Última entrada','');
INSERT INTO pvp_lang VALUES ('last_medianr','pt','o número mais alto para este tipo de media é presentemente:','');
INSERT INTO pvp_lang VALUES ('layout_label','pt','Escolher Disposição','');
INSERT INTO pvp_lang VALUES ('left_offset','pt','Margem Esquerda','');
INSERT INTO pvp_lang VALUES ('length','pt','Tamanho','');
INSERT INTO pvp_lang VALUES ('lentto','pt','Emprestar a','');
INSERT INTO pvp_lang VALUES ('len_is_nan','pt','O valor seleccionado para Tamanho não é numérico,nmas o phpVideoPro necessita de um valor numérico.','');
INSERT INTO pvp_lang VALUES ('lines_per_page','pt','Linhas por página','');
INSERT INTO pvp_lang VALUES ('lines_per_page_comment','pt','Isto é para as funções da impressora determinarem quantas linhas de texto cabem numa página de papel.','');
INSERT INTO pvp_lang VALUES ('line_count','pt','Linhas','');
INSERT INTO pvp_lang VALUES ('list','pt','Lista','');
INSERT INTO pvp_lang VALUES ('listgen','pt','Gerador de Lista','');
INSERT INTO pvp_lang VALUES ('lists','pt','Listas','');
INSERT INTO pvp_lang VALUES ('locale','pt','Local','');
INSERT INTO pvp_lang VALUES ('local_image_files','pt','Ficheiros de imagem locais','');
INSERT INTO pvp_lang VALUES ('login','pt','Nome de Ínicio de Sessão','');
INSERT INTO pvp_lang VALUES ('loginpwd_whitespace','pt','Nome de Ínicio de Sessão e/ou Palavra-Passe contêm espaços(em branco). Isto não é válido.','');
INSERT INTO pvp_lang VALUES ('login_failed','pt','A sua entrada na sessão falhou. Ou escreveu mal a palavra-passe, ou a conta requisitada não existe.','');
INSERT INTO pvp_lang VALUES ('login_required','pt','Os seus previlégios não são suficientes para a acção pretendidad. Pode iniciar sessão com uma conta apropriada agora.<P />','');
INSERT INTO pvp_lang VALUES ('logout_user','pt','Sessão Iniciada como \"%1\". <A HREF=\"%2\">Terminar Sessão</A>','');
INSERT INTO pvp_lang VALUES ('longplay','pt','LongaMetragem','');
INSERT INTO pvp_lang VALUES ('lower_left_corner','pt','Canto Inferior Esquerdo (x/y)','');
INSERT INTO pvp_lang VALUES ('max_fontsize','pt','TamanhoFonte Máximo','');
INSERT INTO pvp_lang VALUES ('medialength','pt','TamanhoMedia','');
INSERT INTO pvp_lang VALUES ('medialist','pt','ListaMedia','');
INSERT INTO pvp_lang VALUES ('medialist_alpha','pt','ListaMedia em ordem alfabética','');
INSERT INTO pvp_lang VALUES ('medialist_num','pt','ListaMedia em ordem numérica','');
INSERT INTO pvp_lang VALUES ('medianr','pt','NumMedia','');
INSERT INTO pvp_lang VALUES ('medianr_is_nan','pt','O NumMedia deve ser numéricon(i.e. letras e caracteres especiais não são permitidos).','');
INSERT INTO pvp_lang VALUES ('mediatype','pt','TipoMedia','');
INSERT INTO pvp_lang VALUES ('media_change','pt','Alterar NumMedia','');
INSERT INTO pvp_lang VALUES ('media_copy','pt','Copiar dados para NumMedia','');
INSERT INTO pvp_lang VALUES ('media_info','pt','Informação da Media','');
INSERT INTO pvp_lang VALUES ('medium','pt','Meio','');
INSERT INTO pvp_lang VALUES ('medium_deleted','pt','Sem mais filmes neste media - media removido.','');
INSERT INTO pvp_lang VALUES ('medium_not_deleted','pt','Media não foi removido.','');
INSERT INTO pvp_lang VALUES ('medium_no_access','pt','Lamento: Este media não existe, ou está vazio, ou não tem permissão para aceder ao seu conteúdo.','');
INSERT INTO pvp_lang VALUES ('medium_overview','pt','Vista geral para %1','');
INSERT INTO pvp_lang VALUES ('menues','pt','Menús','');
INSERT INTO pvp_lang VALUES ('month','pt','Mês','');
INSERT INTO pvp_lang VALUES ('movies','pt','Filmes','');
INSERT INTO pvp_lang VALUES ('movies_left_in_cat','pt','Categoria %1 ainda contém %2 filme(s) e por isso não pode ser apagado. Lamento.','');
INSERT INTO pvp_lang VALUES ('movies_left_reference','pt','Esta entrada não pode ser apagada: Esta(ão) %1 filme(s) na BD referenciado-a.','');
INSERT INTO pvp_lang VALUES ('movie_color_default','pt','Formato de cor do filme por defeito','');
INSERT INTO pvp_lang VALUES ('movie_color_default_comment','pt','Isto vai ser usado como uma pre-definição do formato de cor para a nova entrada.','');
INSERT INTO pvp_lang VALUES ('movie_lang_default','pt','Linguagem do audio padrão para os novos filmes','');
INSERT INTO pvp_lang VALUES ('movie_lang_default_comment','pt','Isto vai ser usado como padrão para linguagem de audio quando adicionar uma nova entrada.','');
INSERT INTO pvp_lang VALUES ('movie_onlabel_default','pt','Padrão para informação de etiquetas ','');
INSERT INTO pvp_lang VALUES ('movie_onlabel_default_comment','pt','Padrão para novas entradas: devia a informação para este filme ser incluída quando etiqueta(s) para esta media for(em) criada(as)?','');
INSERT INTO pvp_lang VALUES ('movie_pict_default','pt','Formato de ecrã padrão para novos filmes','');
INSERT INTO pvp_lang VALUES ('movie_pict_default_comment','pt','Isto vai ser usado como padrão de formato de ecrã quando adicionar uma nova entrada.','');
INSERT INTO pvp_lang VALUES ('movie_tone_default','pt','Formato de som padrão de um filme','');
INSERT INTO pvp_lang VALUES ('movie_tone_default_comment','pt','Isto vai ser usado como formato de som pré-definido de uma nova entrada.','');
INSERT INTO pvp_lang VALUES ('music','pt','Compositor','');
INSERT INTO pvp_lang VALUES ('music_list','pt','Lista de Compositores','');
INSERT INTO pvp_lang VALUES ('name','pt','Nome','');
INSERT INTO pvp_lang VALUES ('name_not_string','pt','Um dos nomes inseridos contém caracteres inválidos (para prevenir injecção de código, apenas letras, dígitos e \"-\" são permitidos).','');
INSERT INTO pvp_lang VALUES ('never','pt','nunca','');
INSERT INTO pvp_lang VALUES ('new_disktype','pt','Novo Tipo de Disco','');
INSERT INTO pvp_lang VALUES ('new_medianr','pt','novo NumMedia','');
INSERT INTO pvp_lang VALUES ('new_movie_on','pt','Novo %1','');
INSERT INTO pvp_lang VALUES ('no','pt','Não','');
INSERT INTO pvp_lang VALUES ('nobody_named','pt','Não há qualquer outro filme com %1 nome %2%3 nesta bd, por isso removi esta entrada da tabela %1\'s.','');
INSERT INTO pvp_lang VALUES ('none','pt','Nenhum','');
INSERT INTO pvp_lang VALUES ('not_logged_in','pt','sem sessão iniciada','');
INSERT INTO pvp_lang VALUES ('not_ok','pt','Falhou','');
INSERT INTO pvp_lang VALUES ('not_yet_implemented','pt','Lamento - ainda não implementado.','');
INSERT INTO pvp_lang VALUES ('no_add_lang','pt','Nenhuma linguagem adicional disponível.','');
INSERT INTO pvp_lang VALUES ('no_backup_avail','pt','Sem ficheiro de segurança para restaurar o sistema.','');
INSERT INTO pvp_lang VALUES ('no_delete_permission','pt','Esta media não é sua, e o proprietário não lhe deu permissão para apagar esta gravação - Lamento.','');
INSERT INTO pvp_lang VALUES ('no_entries_found','pt','Não encontradas entradas','');
INSERT INTO pvp_lang VALUES ('no_entry_in_tapelist','pt','Falhou - sem entradas na lista da fita','');
INSERT INTO pvp_lang VALUES ('no_orphans_found','pt','Parabéns! Parace não ter esqueletos no seu armário (algo mais?).','');
INSERT INTO pvp_lang VALUES ('no_restore_file','pt','Lamento: o ficheiro seleccionado já não existe mais!','');
INSERT INTO pvp_lang VALUES ('no_space_of','pt','Não havia qualquer media com um mínimo de %1 min de espaço livre na base de dados.','');
INSERT INTO pvp_lang VALUES ('nr','pt','Num','');
INSERT INTO pvp_lang VALUES ('of_aquiration','pt','de aquisição','');
INSERT INTO pvp_lang VALUES ('old_sessions','pt','Sessão mais velha que <INPUT NAME=\"%1\" VALUE=\"\" CLASS=\"yesnoinput\"> dias','');
INSERT INTO pvp_lang VALUES ('orig_disktype','pt','Tipo de Disco Original','');
INSERT INTO pvp_lang VALUES ('orig_medianr','pt','NumMedia original','');
INSERT INTO pvp_lang VALUES ('orig_trans','pt','Tradução Original (%1)','');
INSERT INTO pvp_lang VALUES ('orphans_found','pt','Encontrou %1 orfão(s):','');
INSERT INTO pvp_lang VALUES ('other_pages','pt','Outras páginas','');
INSERT INTO pvp_lang VALUES ('owner','pt','Dono','');
INSERT INTO pvp_lang VALUES ('own_to_user','pt','Transferir para','');
INSERT INTO pvp_lang VALUES ('password','pt','Palavra Passe','');
INSERT INTO pvp_lang VALUES ('password_retype','pt','Reescrever Palavra Passe','');
INSERT INTO pvp_lang VALUES ('picture','pt','Formato de Côr','');
INSERT INTO pvp_lang VALUES ('preferences','pt','Preferências','');
INSERT INTO pvp_lang VALUES ('print','pt','Imprimir','');
INSERT INTO pvp_lang VALUES ('printer','pt','Impressora','');
INSERT INTO pvp_lang VALUES ('printer_add_failed','pt','Ocorreu um erro a adicionar a impressora.','');
INSERT INTO pvp_lang VALUES ('printer_add_success','pt','Impressora adicionada com sucesso.','');
INSERT INTO pvp_lang VALUES ('printer_comment','pt','Se pretende imprimir em formas (como usado para a Etiqueta PS), precisamos das margens exactas da sua impressora.','');
INSERT INTO pvp_lang VALUES ('printer_name','pt','Nome','');
INSERT INTO pvp_lang VALUES ('printer_upd_failed','pt','Falhou actualização para as seguintes impressoras: %1','');
INSERT INTO pvp_lang VALUES ('print_label','pt','Etiqueta de Impressora:','');
INSERT INTO pvp_lang VALUES ('pslabel','pt','Etiqueta PS','');
INSERT INTO pvp_lang VALUES ('pstpl_name','pt','Nome do Modelo','');
INSERT INTO pvp_lang VALUES ('pstpl_type','pt','Tipo do Modelo','');
INSERT INTO pvp_lang VALUES ('pvp_homepage','pt','Página do Projecto','');
INSERT INTO pvp_lang VALUES ('read_access','pt','Pode procurar entradas','');
INSERT INTO pvp_lang VALUES ('recalc_free','pt','Re-calculando espaço livre restante nesta media','');
INSERT INTO pvp_lang VALUES ('refresh_lang','pt','Refrescar linguagem','');
INSERT INTO pvp_lang VALUES ('refresh_lang_comment','pt','Re-inserir frases da linguagem na BD','');
INSERT INTO pvp_lang VALUES ('region_code','pt','CódigoRegião','');
INSERT INTO pvp_lang VALUES ('remove_cat','pt','Remover categoria','');
INSERT INTO pvp_lang VALUES ('remove_empty_media','pt','Remover media vazia','');
INSERT INTO pvp_lang VALUES ('remove_empty_media_comment','pt','Devia a media ser removida do espaço-livre-manutenção, quando o último filme é apagado dele?','');
INSERT INTO pvp_lang VALUES ('restore_db_internal','pt','Restaurar de um ficheiro de cópia de segurança PVP','');
INSERT INTO pvp_lang VALUES ('rw_media','pt','Media Editável','');
INSERT INTO pvp_lang VALUES ('rw_media_comment','pt','Media a manter espaço livre para (desde que grave nele).','');
INSERT INTO pvp_lang VALUES ('s/w','pt','p/b','');
INSERT INTO pvp_lang VALUES ('save_lang_file','pt','Salvar tradução alvo para ficheiro','');
INSERT INTO pvp_lang VALUES ('scan_new_lang_comment','pt','(Se criar o seu próprio ficheiro de linguagem e o colocar no directório de configuração, isto vai dizer ao phpVideoPro para procural por ele)','');
INSERT INTO pvp_lang VALUES ('scan_new_lang_files','pt','Procurar por novos ficheiros de linguagem?','');
INSERT INTO pvp_lang VALUES ('screen','pt','Formato do Ecrã','');
INSERT INTO pvp_lang VALUES ('search','pt','Procurar','');
INSERT INTO pvp_lang VALUES ('search_movie','pt','ProcurarFilme','');
INSERT INTO pvp_lang VALUES ('select_add_lang','pt','Seleccionar linguagem adicional a instalar','');
INSERT INTO pvp_lang VALUES ('select_add_lang_comment','pt','(Inglês já está instalado e vai sempre estar - ver próximo item. Para outras linguagens que já se encontram instaladas, veja o próximo item, também.)','');
INSERT INTO pvp_lang VALUES ('select_primary_lang','pt','Seleccionar linguagem principal','');
INSERT INTO pvp_lang VALUES ('select_primary_lang_comment','pt','(para frases em falta, haverá sempre um retorno ao Inglês)','');
INSERT INTO pvp_lang VALUES ('sel_target_lang','pt','Seleccione linguagem alvo (traduzir para):','');
INSERT INTO pvp_lang VALUES ('session','pt','Sessão','');
INSERT INTO pvp_lang VALUES ('session_expired','pt','A sua sessão expirou - por favor volte a iniciar sessão.','');
INSERT INTO pvp_lang VALUES ('session_purgetime','pt','Após quanto tempo uma sessão inactiva expira?','');
INSERT INTO pvp_lang VALUES ('session_purgetime_comment','pt','Quanto tempo deve uma sessão ser válida sem actividade do utilizador?','');
INSERT INTO pvp_lang VALUES ('sess_dla','pt','Última vez acedida','');
INSERT INTO pvp_lang VALUES ('sess_end','pt','Terminada','');
INSERT INTO pvp_lang VALUES ('sess_id','pt','ID de Sessão','');
INSERT INTO pvp_lang VALUES ('sess_ip','pt','IP Remoto','');
INSERT INTO pvp_lang VALUES ('sess_start','pt','Iniciada','');
INSERT INTO pvp_lang VALUES ('set_filter','pt','Definir Filtro','');
INSERT INTO pvp_lang VALUES ('site_info','pt','Informação do Sítio','');
INSERT INTO pvp_lang VALUES ('site_info_comment','pt','Qual a informação do sítio a mostrar na barra de título do navegador','');
INSERT INTO pvp_lang VALUES ('skip_intro','pt','Saltar a introdução de novato?','');
INSERT INTO pvp_lang VALUES ('skip_intro_comment','pt','Se saltar o texto de introdução para a página inicial','');
INSERT INTO pvp_lang VALUES ('source','pt','Fonte','');
INSERT INTO pvp_lang VALUES ('staff','pt','Equipa','');
INSERT INTO pvp_lang VALUES ('start_page','pt','Página inicial','');
INSERT INTO pvp_lang VALUES ('start_pvp','pt','Iniciar phpVideoPro','');
INSERT INTO pvp_lang VALUES ('state_active','pt','activo','');
INSERT INTO pvp_lang VALUES ('state_inactive','pt','inactivo','');
INSERT INTO pvp_lang VALUES ('stats','pt','Estatísticas','');
INSERT INTO pvp_lang VALUES ('stat_categories','pt','Categorias (usadas/todas)','');
INSERT INTO pvp_lang VALUES ('stat_counts','pt','Contagens','');
INSERT INTO pvp_lang VALUES ('storeplace','pt','Guardado em','');
INSERT INTO pvp_lang VALUES ('submit','pt','Submeter','');
INSERT INTO pvp_lang VALUES ('subtitle','pt','Legendas','');
INSERT INTO pvp_lang VALUES ('sure_to_delete','pt','Tem a certeza que pretende apagar todos os dados para %1','');
INSERT INTO pvp_lang VALUES ('tapelist_update_failed','pt','Falhou a actualizar a lista da fita','');
INSERT INTO pvp_lang VALUES ('taperest','pt','Geir tempo restante','');
INSERT INTO pvp_lang VALUES ('taperest_absolute','pt','Descanso da Fita (absoluto)','');
INSERT INTO pvp_lang VALUES ('taperest_filtered','pt','Descanso da Fita (filtrado)','');
INSERT INTO pvp_lang VALUES ('target_trans','pt','Tradução para a sua linguagem alvo (%1)','');
INSERT INTO pvp_lang VALUES ('techdata','pt','Dados Técnicos','');
INSERT INTO pvp_lang VALUES ('template_file','pt','Ficheiro Modelo','');
INSERT INTO pvp_lang VALUES ('template_set','pt','Conjunto Modelo','');
INSERT INTO pvp_lang VALUES ('time_left','pt','%1 minutos restantes','');
INSERT INTO pvp_lang VALUES ('title','pt','Título','');
INSERT INTO pvp_lang VALUES ('title_not_string','pt','O título inserido contem caracteres inválidos(para prevenir injecção de código, apenas letras, dígitos e \"-\" são permitidos).','');
INSERT INTO pvp_lang VALUES ('tone','pt','Formato de Som','');
INSERT INTO pvp_lang VALUES ('top_offset','pt','Fronteira Superior','');
INSERT INTO pvp_lang VALUES ('tplset_applicat','pt','Applicat Conjunto de Modelos','');
INSERT INTO pvp_lang VALUES ('trans_code','pt','Código de Tradução','');
INSERT INTO pvp_lang VALUES ('unit','pt','Unidade','');
INSERT INTO pvp_lang VALUES ('unknown','pt','desconhecido','');
INSERT INTO pvp_lang VALUES ('unlink_file_failed','pt','Falhou a apagar - verifique permissões ou apague manualmente','');
INSERT INTO pvp_lang VALUES ('unset_filter','pt','Filtro Não Definido','');
INSERT INTO pvp_lang VALUES ('update','pt','Actualizar','');
INSERT INTO pvp_lang VALUES ('update_failed','pt','Falhou a actualizar entrada','');
INSERT INTO pvp_lang VALUES ('update_failed_permission','pt','Falhou a actualizar entrada devido a falta de parâmetros','');
INSERT INTO pvp_lang VALUES ('update_success','pt','Entrada actualizada com sucesso','');
INSERT INTO pvp_lang VALUES ('upd_access','pt','Pode actualizar entradas existentes','');
INSERT INTO pvp_lang VALUES ('upd_access_short','pt','act','');
INSERT INTO pvp_lang VALUES ('upper_right_corner','pt','Canto Superior Direito (x/y)','');
INSERT INTO pvp_lang VALUES ('user','pt','Utilizador','');
INSERT INTO pvp_lang VALUES ('user_create_login_required','pt','Deve especifícar um nome de início de sessão para este utilizador!','');
INSERT INTO pvp_lang VALUES ('user_deleted','pt','Removido com sucesso utilizador #%1, \"%2\" (%3)','');
INSERT INTO pvp_lang VALUES ('user_delete_failed','pt','Remoção do utilizador #%1, \"%2\" (%3) falhou','');
INSERT INTO pvp_lang VALUES ('user_delete_report','pt','Resultados do processo de remoção','');
INSERT INTO pvp_lang VALUES ('user_grants','pt','Permissões nas suas gravações','');
INSERT INTO pvp_lang VALUES ('user_update_failed','pt','Falhou a actualizar os seguintes utilizadores: %1','');
INSERT INTO pvp_lang VALUES ('view','pt','Ver','');
INSERT INTO pvp_lang VALUES ('view_entry','pt','Ver entrada %1','');
INSERT INTO pvp_lang VALUES ('warning','pt','aviso','');
INSERT INTO pvp_lang VALUES ('week','pt','Semana','');
INSERT INTO pvp_lang VALUES ('welcome','pt','Bem Vindo ao phpVideoPro','');
INSERT INTO pvp_lang VALUES ('wrong_date','pt','Os dados %1 que especifícou (%2) são inválidos. Quando insere a data aqui, por favor insira o dia no primeiro, o mês no segundo e o ano no terceiro campo e apenas use digítos. Se não tem a certeza da data exacta, insira zeros nos campos em questão: e.g. \"00\" \"02\" \"2002\" quer dizer \"eventualmente em Fevereiro de 2002\", or \"00\" \"00\" \"0000\" quer dizer \"alguma data\".','');
INSERT INTO pvp_lang VALUES ('xfer_unknown_filetype','pt','Este ficheiro de segurança não está (ainda) tratado pelo phpVideoPro','');
INSERT INTO pvp_lang VALUES ('xfer_wrong_mode','pt','Erro do Programa: Você está no modo errado para a operação pedida. Necessita do modo \"%1\", e modo actual é \"%2\". Por favor reporte este erro ao autor com detalhes da acção efectuada.','');
INSERT INTO pvp_lang VALUES ('year','pt','Ano','');
INSERT INTO pvp_lang VALUES ('yes','pt','Sim','');
