# ========================================================
# Danish Language File created by phpVideoPro v0.8.1
# Translations by Kresten Kjeldgaard
# ========================================================

UPDATE languages SET charset='UTF-8' WHERE lang_id='da';
INSERT INTO lang VALUES ('about','da','Om','');
INSERT INTO lang VALUES ('actions','da','Handlinger','');
INSERT INTO lang VALUES ('actor','da','Skuespiller','');
INSERT INTO lang VALUES ('actor_persons','da','Skuespillere','');
INSERT INTO lang VALUES ('actors','da','Skuespillerne','');
INSERT INTO lang VALUES ('actors_list','da','Liste af skuespillere','');
INSERT INTO lang VALUES ('add_access','da','Må tilføje nye ','');
INSERT INTO lang VALUES ('add_access_short','da','tilføj','');
INSERT INTO lang VALUES ('add_entry','da','Tilføj film','');
INSERT INTO lang VALUES ('add_user','da','Tilføj bruger','');
INSERT INTO lang VALUES ('admin_access','da','Har adgang til administrator menuen','');
INSERT INTO lang VALUES ('admin_access_short','da','adm','');
INSERT INTO lang VALUES ('admin_avlang','da','ret tilgængelig sprog for lyd og undertekster','');
INSERT INTO lang VALUES ('admin_cats','da','Administrer katagorier','');
INSERT INTO lang VALUES ('admin_disktypes','da','Ret disk typer','');
INSERT INTO lang VALUES ('admin_filter','da','Standard filter indstillinger','');
INSERT INTO lang VALUES ('admin_movietech','da','Ret teknisk film data','');
INSERT INTO lang VALUES ('admin_orphan_fs','da','Fjern ikke længere brugte filer','');
INSERT INTO lang VALUES ('admin_orphans','da','Fjern ikke længere brugte entries','');
INSERT INTO lang VALUES ('admin_printers','da','Ret printere','');
INSERT INTO lang VALUES ('admin_pstemplates','da','ret PSLabel templates','');
INSERT INTO lang VALUES ('admin_required','da','Denne handling kræver administrator adgang','');
INSERT INTO lang VALUES ('admin_sessions','da','administrer sessioner','');
INSERT INTO lang VALUES ('admin_translations','da','Ret oversættelser','');
INSERT INTO lang VALUES ('admin_useredit','da','ret bruger konto','');
INSERT INTO lang VALUES ('admin_users','da','administrer bruger konti','');
INSERT INTO lang VALUES ('audio_ts','da','Lydspor','');
INSERT INTO lang VALUES ('back','da','Tilbage','');
INSERT INTO lang VALUES ('backup_compress','da','Komprimer?','');
INSERT INTO lang VALUES ('backup_db','da','Database backup','');
INSERT INTO lang VALUES ('backup_db_cats','da','Backup katagorier','');
INSERT INTO lang VALUES ('backup_db_complete','da','Backup komplet database (inklusiv teknisk data og opsætnint)','');
INSERT INTO lang VALUES ('backup_db_movie_internal','da','Backup alle film i phpVideoPros interne format','');
INSERT INTO lang VALUES ('backup_db_sysconf','da','Backup system configuration og default opsætning','');
INSERT INTO lang VALUES ('backup_file_corrupt','da','Den valgte backup fil er korrupt - kan ikke gendanne fra dette!','');
INSERT INTO lang VALUES ('backup_file_unreadable','da','Backup filen kan ikke læses - kontroller fil rettigheder','');
INSERT INTO lang VALUES ('bubble_help_enable','da','Aktiver popup hjælp','');
INSERT INTO lang VALUES ('bubble_help_enable_comment','da','Hvis dette er slået kan du få hjælp ved at holde musen over nogen enkelte punkter','');
INSERT INTO lang VALUES ('button_backup','da','Backup','');
INSERT INTO lang VALUES ('button_restore','da','Gendan','');
INSERT INTO lang VALUES ('cache_enable','da','Slå browser/proxy cache til','');
INSERT INTO lang VALUES ('cache_enable_comment','da','Da phpVideoPro er et dynamisk progrem der genererer siderne for hver request vil du muligvis slå browserens caching fra. Dette kan hjælpe MSIE brugere.','');
INSERT INTO lang VALUES ('cancel','da','Afbryd','');
INSERT INTO lang VALUES ('cat_adventure','da','Eventyr','');
INSERT INTO lang VALUES ('cat_animal','da','Dyr','');
INSERT INTO lang VALUES ('cat_animals','da','Dyr','');
INSERT INTO lang VALUES ('cat_bible','da','Bibel','');
INSERT INTO lang VALUES ('cat_biography','da','Bibliografi','');
INSERT INTO lang VALUES ('cat_camera','da','Kamera','');
INSERT INTO lang VALUES ('cat_cartoon','da','Tegnefilm','');
INSERT INTO lang VALUES ('cat_catastrophe','da','Katastrofe','');
INSERT INTO lang VALUES ('cat_children','da','Børn','');
INSERT INTO lang VALUES ('cat_comedy','da','Komedie','');
INSERT INTO lang VALUES ('cat_concert','da','Koncert','');
INSERT INTO lang VALUES ('cat_crime','da','Forbrydelse','');
INSERT INTO lang VALUES ('cat_documentary','da','Dokumentar','');
INSERT INTO lang VALUES ('cat_drama','da','Dramatik','');
INSERT INTO lang VALUES ('categories','da','Katagorier','');
INSERT INTO lang VALUES ('category','da','Katagori','');
INSERT INTO lang VALUES ('cat_fairytale','da','Eventyr','');
INSERT INTO lang VALUES ('cat_fantasy','da','Fantasi','');
INSERT INTO lang VALUES ('cat_handle_empty','da','Katagorien må ikke være tom, gå venligst tilbage og ret dette for katagoti #%1.','');
INSERT INTO lang VALUES ('cat_history','da','Historie','');
INSERT INTO lang VALUES ('catlist_alpha','da','Liste i alfabetisk orden sorteret efter katagori','');
INSERT INTO lang VALUES ('cat_love','da','Kærlighedhistorier','');
INSERT INTO lang VALUES ('cat_misc','da','Forskelligt','');
INSERT INTO lang VALUES ('cat_music','da','Musik','');
INSERT INTO lang VALUES ('cat_musical','da','Musikal','');
INSERT INTO lang VALUES ('cat_musicmovie','da','Musik film','');
INSERT INTO lang VALUES ('cat_nature','da','Natur','');
INSERT INTO lang VALUES ('cat_party','da','Fest','');
INSERT INTO lang VALUES ('cat_report','da','Reportage','');
INSERT INTO lang VALUES ('cat_scary','da','Skrækfilm','');
INSERT INTO lang VALUES ('cat_spy','da','Spion film','');
INSERT INTO lang VALUES ('cat_stage','da','Scene','');
INSERT INTO lang VALUES ('cat_trans_update_failed','da','Opdatering fejlede for oversættelserne af følgende katagorier: %1','');
INSERT INTO lang VALUES ('cat_travesty','da','Parodi','');
INSERT INTO lang VALUES ('cat_update_failed','da','Opdatering fejlede for følgende katagorier: %1','');
INSERT INTO lang VALUES ('cat_vacation','da','Ferie','');
INSERT INTO lang VALUES ('cat_videoclip','da','Videoklip','');
INSERT INTO lang VALUES ('cat_war','da','Krigsfilm','');
INSERT INTO lang VALUES ('cat_westerncomedy','da','Western komedie','');
INSERT INTO lang VALUES ('cat_xmas','da','Jul','');
INSERT INTO lang VALUES ('change_disktype','da','Skift disk type for %1','');
INSERT INTO lang VALUES ('change_media_length','da','Ændre Medium længde','');
INSERT INTO lang VALUES ('change_media_length_for','da','Indtast kapacitenn for %1','');
INSERT INTO lang VALUES ('change_nr','da','Skift MedieNr/Medie type for %1','');
INSERT INTO lang VALUES ('change_rc','da','SKift regionskode','');
INSERT INTO lang VALUES ('change_rc_for','da','Skift regionskode for %1','');
INSERT INTO lang VALUES ('check_completed','da','Kontrol færdig','');
INSERT INTO lang VALUES ('check_media_delete','da','Kontrollerer om medie er tomt','');
INSERT INTO lang VALUES ('clean_restore','da','oprydning (fjern) gamle data inden gendannelse','');
INSERT INTO lang VALUES ('close','da','Luk','');
INSERT INTO lang VALUES ('comment_not_string','da','Den indtastede kommentar indeholder ulovlige tegn, kun bogstager, tal og \"-\" er tilladte.','');
INSERT INTO lang VALUES ('comments','da','Kommentarer','');
INSERT INTO lang VALUES ('commercials','da','Reklamer','');
INSERT INTO lang VALUES ('compose_person','da','Komponist','');
INSERT INTO lang VALUES ('compose_persons','da','Komponister','');
INSERT INTO lang VALUES ('composer','da','Komponist','');
INSERT INTO lang VALUES ('config_media','da','Film og midia','');
INSERT INTO lang VALUES ('configuration','da','Konfiguration','');
INSERT INTO lang VALUES ('confirm_delete','da','Er du sikker på at du vil slette denne ting?','');
INSERT INTO lang VALUES ('confirm_prilang','da','Er du sikker på at du vil ændre standard sproget for alle nye brugere?','');
INSERT INTO lang VALUES ('confirm_userdelete','da','Du er ved at slette bruger #%1','');
INSERT INTO lang VALUES ('confirm_userdeletion','da','Er du sikker på at du vil slette bruger \"%1\" (%2)?','');
INSERT INTO lang VALUES ('content','da','Indhold','');
INSERT INTO lang VALUES ('counter_start_stop','da','Tæller Start/Stop','');
INSERT INTO lang VALUES ('countries','da','Lande','');
INSERT INTO lang VALUES ('country','da','Land','');
INSERT INTO lang VALUES ('create','da','Opret','');
INSERT INTO lang VALUES ('create_success','da','Ting oprettet med succes','');
INSERT INTO lang VALUES ('cut_off','da','Klippet ud','');
INSERT INTO lang VALUES ('data_access','da','Data Adgang','');
INSERT INTO lang VALUES ('date_format','da','Dato format','');
INSERT INTO lang VALUES ('date_format_comment','da','Hvilket format skal dato vises i ','');
INSERT INTO lang VALUES ('date_is_nan','da','Dato, måned og år skal være numerisk (kun tal)','');
INSERT INTO lang VALUES ('date_rec','da','Anskaffelses dato','');
INSERT INTO lang VALUES ('day','da','Dag','');
INSERT INTO lang VALUES ('db_stats','da','Statistik','');
INSERT INTO lang VALUES ('del_access','da','Må slette ting','');
INSERT INTO lang VALUES ('del_access_short','da','slt','');
INSERT INTO lang VALUES ('delete','da','Slet','');
INSERT INTO lang VALUES ('delete_lang','da','Alet sprog','');
INSERT INTO lang VALUES ('delete_lang_comment','da','Slet alle fraser til det valgte sprog fra databasen. Dette vil ikke slette sprogfilen, så du kan indsætte fraserne igen medmindre du selv sletter filen.','');
INSERT INTO lang VALUES ('delete_orphans','da','Sletter %1 forældreløse:','');
INSERT INTO lang VALUES ('delete_remaining','da','Sletter nu tilbageværende data for denne film fra databasen','');
INSERT INTO lang VALUES ('deleting_entry','da','Sletter %1','');
INSERT INTO lang VALUES ('desc_admin_orphan_fs','da','\"Forældreløse filer\" er data uden referencer, her: billeder der ikke længere er nogen referance til fra nogen film. Sandsynligvis af en af følgende årsager <ul><li> Du har hentet billeder fra IMDB men valgt ikke at bruge dem </li><li>Du har rettet en film og slettet billedet fra beskrivelsen</li><li>Du har slettet en film og billedet blev ikke fjernet</li><ul>Hvis du ikke tror du vil tilknytte disse filer til en anden film kan du få phpVideoPro til at slette de listede filer her.','');
INSERT INTO lang VALUES ('desc_admin_orphans','da','\"Forældreløst indhold\" er data uden referencer, her: Skuespillere, instruktører og komponister der ikke længere er refereret fra nogen film. Disse er normalt resultatet af at ændre et navn der er stavet forkert efter at have gemt det - men aldrig resultatet af slettede film. Derfor er det en god ide at fjerne dette indhold: det sparer resourcer og gør databasen hurtigere.','');
INSERT INTO lang VALUES ('desc_backup_db','da','Det er altid en god ide at have en backup ved hånden. Selvom det er bedst at bruge databasens egne tools (<code>mysql_dump</code>, <code>pgsql_dump</code> etc.) for en komplet backup, kan du blive nødt til at have din database hosted på en maskine hvor du ikke har adgang til disse værktøjer. I det tilfælde kan du bruge \"Komplet Backup\" her, som gemmer din database i et SQL script. <br> Hvis du bare vil gemme dine film data for at kopiere dem til en anden database bør du lave backup af alle dine film i phpVideoPro\'s interne database format. Dette gør at du kan gendanne dataene på en anden database server (fra mysql til f.eks postgresQL). Selvom gendannelse af en komplet backup fra en tidligere version af phpVideoPro resulterer i et krav om at opdatere databasen bagefter. Ligesom ved en update af phpVideoPro burde den interne backup være kompatibel imellem de enkelte versioner.<BR> Du vil måske komprimere din backup hvis din PHP version har gzip support kan du bare klikke i kompressions checkboxen og spare op til 90% af filstørrelsen.<br>','');
INSERT INTO lang VALUES ('director','da','Instruktør','');
INSERT INTO lang VALUES ('director_person','da','instruktør','');
INSERT INTO lang VALUES ('director_persons','da','Instruktører','');
INSERT INTO lang VALUES ('directors','da','Instruktør','');
INSERT INTO lang VALUES ('directors_list','da','Instruktør liste','');
INSERT INTO lang VALUES ('disk_size','da','Disk størelse','');
INSERT INTO lang VALUES ('disk_type','da','Disk type','');
INSERT INTO lang VALUES ('disktype_add_failed','da','Kunne ikke tilføje den nye disk type','');
INSERT INTO lang VALUES ('disktype_change','da','Skift disk type','');
INSERT INTO lang VALUES ('disktype_contains_media','da','Denne disk type kan ikke blive slettet lige nu, da følgende medier stadig refererer til det:','');
INSERT INTO lang VALUES ('disktype_name_empty','da','En disks navn må ikke være tomt. Gå venligst tilbage og ret dette for disk type #%1.','');
INSERT INTO lang VALUES ('disktype_update_failed','da','Kunne ikke opdatere følgende disk type #s: %1','');
INSERT INTO lang VALUES ('display','da','Vis','');
INSERT INTO lang VALUES ('display_limit','da','Begræns visning','');
INSERT INTO lang VALUES ('display_limit_comment','da','(Hvor mange linier skal der vises pr. side for lister)','');
INSERT INTO lang VALUES ('dl_pvp_latest','da','Hent seneste version','');
INSERT INTO lang VALUES ('dupe_id_entered','da','Der er allerede en ting i databasen med det indtastede medie ID. Tryk venligst på \"Tilbage\" knappen i din browser og ret inputtet. Hint: Der er en markerings boks ved siden af boksen du specificerede medie nummeret i. Denne boks fortæller dig det højeste eksisterende film ID. Normalt er det et godt falg for nye medier at inkrementere det første (4 cifrede)  nummer med en, eller for en ny film på samme medie inkrementere det andet (2 cifrede) nummer med en.','');
INSERT INTO lang VALUES ('dupes','da','Duplikerede film','');
INSERT INTO lang VALUES ('dupes_own','da','Duplikerede film (egne)','');
INSERT INTO lang VALUES ('dupes_own_strict','da','Duplikerede film (egne + skærpet)','');
INSERT INTO lang VALUES ('dupes_strict','da','Duplikerede film (skærpet)','');
INSERT INTO lang VALUES ('dupe_titles_found','da','Fundet %1 titler med mulige duplikater','');
INSERT INTO lang VALUES ('edit','da','Ret','');
INSERT INTO lang VALUES ('edit_entry','da','Ret film: %1','');
INSERT INTO lang VALUES ('enable_cookies','da','Slå cookies til?','');
INSERT INTO lang VALUES ('enable_cookies_comment','da','Skal user preferences (filter indstillinger) være styret vha. cookies?','');
INSERT INTO lang VALUES ('ended_sessions','da','Afsluttede sessioner','');
INSERT INTO lang VALUES ('enter_min_free','da','Indtast mindste fri plads der skal vises på medier:','');
INSERT INTO lang VALUES ('enter_new_medianr','da','Indtast venligst medieNu for denne nye %1','');
INSERT INTO lang VALUES ('error_occured','da','phpVideoPro fejl','');
INSERT INTO lang VALUES ('expire_cookies','da','Cookies levetid','');
INSERT INTO lang VALUES ('expire_cookies_comment','da','Hvor længe skal en cookie overleve i brugerens browser?','');
INSERT INTO lang VALUES ('farbe','da','Farve','');
INSERT INTO lang VALUES ('filter_setup','da','Filter opsætning','');
INSERT INTO lang VALUES ('finnished','da','Færdiggjort','');
INSERT INTO lang VALUES ('first_name','da','Fornavn','');
INSERT INTO lang VALUES ('fontsize_is_nan','da','Skriftstørrelse skal angives numerisk (kun tal).','');
INSERT INTO lang VALUES ('free','da','Fri','');
INSERT INTO lang VALUES ('free_space_on_media','da','Følgende medier har mindst %1 minutter fri plads:','');
INSERT INTO lang VALUES ('free_space_title','da','Fri plads på mediet','');
INSERT INTO lang VALUES ('fsk_is_nan','da','Den valgte værdi for PG er ikke numerisk, phpVideoPro kræver en numerisk værdi. Tryk på info ikonet ved siden af PG for flere detaljer.','');
INSERT INTO lang VALUES ('general','da','Generelt','');
INSERT INTO lang VALUES ('goto_entry','da','Gå direkte til film:','');
INSERT INTO lang VALUES ('grant_filter_desc','da','Vis indhold fra','');
INSERT INTO lang VALUES ('graphic_file','da','Billed fil','');
INSERT INTO lang VALUES ('help','da','Hjælp','');
INSERT INTO lang VALUES ('help_about','da','Hjælp om','');
INSERT INTO lang VALUES ('help_for_block','da','Hjælp for denne blok','');
INSERT INTO lang VALUES ('hide_cat','da','Gem katagori','');
INSERT INTO lang VALUES ('highest_db_entries','da','Højeste nummer i databasen','');
INSERT INTO lang VALUES ('history','da','Historie','');
INSERT INTO lang VALUES ('hit_back_to_correct','da','tryk på \"Tilbage\" knappen for at rette fejlen','');
INSERT INTO lang VALUES ('hour','da','Time','');
INSERT INTO lang VALUES ('hours','da','Timer','');
INSERT INTO lang VALUES ('howto','da','Hvordan...','');
INSERT INTO lang VALUES ('howto_help','da','Hvordan opretter man en hjælp fil','');
INSERT INTO lang VALUES ('howto_label','da','Hvordan opretter/konfigurerer man label skabeloner','');
INSERT INTO lang VALUES ('howto_lang','da','Hvordan opretter man en ny sprog fil','');
INSERT INTO lang VALUES ('howto_templates','da','Hvordan opretter man et nyt skabelon sæt','');
INSERT INTO lang VALUES ('id_is_nan','da','ID skal være numerisk (kun tal)','');
INSERT INTO lang VALUES ('imdb_cache_dir','da','Directorie til at gemme IMDB cache i','');
INSERT INTO lang VALUES ('imdb_cache_dir_comment','da','Dette direktorie skal være læs og skrivbart for webserveren og brugt specifikt til dette formål. Stier må være relative fra phpVideoPro installations stien (anbefalet). Brug IKKE dit systems midlertidige direktorie til dette.','');
INSERT INTO lang VALUES ('imdb_cache_enable','da','Slå caching af IMDB data til','');
INSERT INTO lang VALUES ('imdb_cache_enable_comment','da','Opslag af film detaljer på IMDB kan tage lang tid da phpVideoPro skal hente flere sider. Caching giver kun mening hvis du ofte laver opslag af de samme filmdata, så normalt skulle du ikke have brug for det. Husk at specificere et direktorie ovenfor hvis du slår dette til.','');
INSERT INTO lang VALUES ('imdb_cache_expire','da','Slet IMDB cache','');
INSERT INTO lang VALUES ('imdb_cache_expire_comment','da','Hvis IMDB caching er slået til vil størrelsen af cach direktoriet wokse. Denne option kan bruges til at fortælle hvor gamle filerne i direktoriet må blive.','');
INSERT INTO lang VALUES ('imdb_cache_use','da','Brug cachede data til nye requests','');
INSERT INTO lang VALUES ('imdb_cache_use_comment','da','Imens de ovenstående valg styrer opsætningen af IMDB cachen, styrer dette valg om phpVideoPro bruge denne cache til søgninger. Hvis det er slået til og data cachen eksisterer vil phpVideoPro ikke kontakte IMDB for detaljer om filmen, men bruge de cachede data i stedet.','');
INSERT INTO lang VALUES ('imdb_image_files','da','IMDB billed filer','');
INSERT INTO lang VALUES ('imdb_movie_id','da','IMDB film ID','');
INSERT INTO lang VALUES ('imdbsearch','da','Hent film detaljer fra IMDB','');
INSERT INTO lang VALUES ('imdb_search_empty_result','da','Der kunne ikke findes nogen film i IMDB der matchede søgningen. <br> Du vil måske prøve igen med andre søge termer.','');
INSERT INTO lang VALUES ('imdb_title_search','da','Søg efter film på IMDB','');
INSERT INTO lang VALUES ('imdb_transfer2edit','da','Overfør data til ret skærmen','');
INSERT INTO lang VALUES ('imdb_tx','da','Data der skal overføres fra IMDB','');
INSERT INTO lang VALUES ('imdb_tx_actor','da','Skuespillere','');
INSERT INTO lang VALUES ('imdb_tx_cat','da','Katagorier','');
INSERT INTO lang VALUES ('imdb_tx_comment','da','Når du tilføjer eller retter en film tilbyder phpVideoPro dig muligheden for at hente noget information fra IMDB. Her kan du specificere hvilken information der som standard skal overføres.','');
INSERT INTO lang VALUES ('imdb_tx_comments','da','Kommentar','');
INSERT INTO lang VALUES ('imdb_tx_country','da','Land','');
INSERT INTO lang VALUES ('imdb_tx_director','da','Instruktør','');
INSERT INTO lang VALUES ('imdb_tx_length','da','Længde','');
INSERT INTO lang VALUES ('imdb_tx_music','da','Komponist','');
INSERT INTO lang VALUES ('imdb_tx_title','da','Titel','');
INSERT INTO lang VALUES ('imdb_txwin_autoclose','da','Luk automatisk søgevindue efter data overførsel?','');
INSERT INTO lang VALUES ('imdb_txwin_autoclose_comment','da','Når du har hentet alle værdier fra IMDB du vil bruge og overført dem til ret skærmen er søgevinduet ikke længere påkrævet. Derfor kan det tænkes du gerne vil holde det åbent af andre årsager.','');
INSERT INTO lang VALUES ('imdb_tx_year','da','År','');
INSERT INTO lang VALUES ('imdb_url','da','Hvilken IMDB side skal bruges','');
INSERT INTO lang VALUES ('imdb_url2','da','Alternativ IMDB side','');
INSERT INTO lang VALUES ('imdb_url2_comment','da','Selvom der findes IMDB sider på andre sprog end engelsk så er film detaljerne altid på engelsk og dette skal bruges for at kunne importere dataene. Dette betyder at vi også skal bruge en engelsk side. Vælg venligst en.','');
INSERT INTO lang VALUES ('imdb_url_comment','da','Internet film databasen (IMDB) indeholder information om mange film, der er sider tilgængelige på andre sprog (f.eks tysk) vælg en side der best passer til titlerne af dine film.','');
INSERT INTO lang VALUES ('imp_errors','da','Import af %2 film udført med %1 fejl.','');
INSERT INTO lang VALUES ('imp_success','da','Import af %1 film udført.','');
INSERT INTO lang VALUES ('incomplete_date','da','Hvis du ikke kender den nøjagtige dato men f.eks kun året du anskaffede en filk kan du skrive 00 for de ukendte data.','');
INSERT INTO lang VALUES ('info_common','da','Generel information','');
INSERT INTO lang VALUES ('info_common_info','da','<div align=center\">Dette er version %1 af phpVideoPro, kørende på %2.</div>','');
INSERT INTO lang VALUES ('info_noupdate','da','<div align=\"center\">Den installerede version af  phpVideoPro (%1) er den nyeste. Du kan hente en tarball med den installerede version her:<a href=\"http://www.qumran.org/homes/izzy/software/get_update.php?program=pvp\" target=\"_blank\">this link</a>.</div>','');
INSERT INTO lang VALUES ('info_update','da','Opdaterings information','');
INSERT INTO lang VALUES ('in_list','da','i liste','');
INSERT INTO lang VALUES ('input_errors_occured','da','phpVideoPro mødte %1 fejl under behandling af dit input:','');
INSERT INTO lang VALUES ('intro','da','Introduktion','');
INSERT INTO lang VALUES ('intro_usage','da','<p>Her er noget information til nye brugere:</p><ul><li>Navigation er altid muligt ved hjælp af menu bjælken i toppen af næsten alle sider</li><li>De fleste sider har en hjælpe tekst. Denne kan enten findes i menuen hjælp eller (hvor tilgængeligt) \"?\" knappen</li><li>Hvis du kender medienummeret kan du bruge denne til at springe direkte til en film, ellers må du hellere bruge Medielisten (i \"Vis\" menuen) eller søgnings siden i \"Ret\" menuen.</li></ul>','');
INSERT INTO lang VALUES ('intro_usage_skip','da','<p>Hvis du ikke længere har brug for denne introduktions text kan du slå den fra i preferense vinduet (se \"Ret\" menuen).</p>','');
INSERT INTO lang VALUES ('intro_usage_title','da','Introduktion for nye brugere','');
INSERT INTO lang VALUES ('invalid_backup_dir','da','Det konfigurede backup directorie findes ikke.','');
INSERT INTO lang VALUES ('invalid_fsk','da','Værdien du har indtastet for PG (\"%1\") er ulovlig PG er minimums alderen for at se denne film.','');
INSERT INTO lang VALUES ('invalid_media_nr','da','Det MedieNr du har specificeret er enten inkomplet eller ulovligt, du skal skrive tal i begge MedieNr felter.','');
INSERT INTO lang VALUES ('is_rw','da','Genskrivbar','');
INSERT INTO lang VALUES ('last_entry','da','Sidste film','');
INSERT INTO lang VALUES ('last_medianr','da','Det nuværende højeste nummer for denne medietype er:','');
INSERT INTO lang VALUES ('layout_label','da','Vælg layoug','');
INSERT INTO lang VALUES ('left_offset','da','Venstre margin','');
INSERT INTO lang VALUES ('length','da','Længde','');
INSERT INTO lang VALUES ('len_is_nan','da','Den valgte længde værdi er ikke numerisk, phpVideoPro kræver en numerisk værdi.','');
INSERT INTO lang VALUES ('lentto','da','Udlånt til','');
INSERT INTO lang VALUES ('line_count','da','Linier','');
INSERT INTO lang VALUES ('lines_per_page','da','Linier pr. side','');
INSERT INTO lang VALUES ('lines_per_page_comment','da','Dette er til udprintnings funktionerne for at bestemme hvor mange linier text der kan være pr. ark.','');
INSERT INTO lang VALUES ('list','da','Liste','');
INSERT INTO lang VALUES ('listgen','da','Liste generator','');
INSERT INTO lang VALUES ('lists','da','Lister','');
INSERT INTO lang VALUES ('local_image_files','da','Lokale billed filer','');
INSERT INTO lang VALUES ('login','da','Brugernavn','');
INSERT INTO lang VALUES ('login_failed','da','Dit login forsøg fejlede. Enten er dit password forkert eller kontoen findes ikke.','');
INSERT INTO lang VALUES ('loginpwd_whitespace','da','Login og/eller password indeholder ikke printbare karakterer. Dette er ikke tilladt.','');
INSERT INTO lang VALUES ('login_required','da','Du har ikke rettigheder til at foretage den valgte handling, du kan logge ind med en anden konto nu.<p/>','');
INSERT INTO lang VALUES ('logout_user','da','Logget ind som \"%1\" <a href=\"%2\">Logout</a>','');
INSERT INTO lang VALUES ('lower_left_corner','da','Nederste venstre hjørne (x/y)','');
INSERT INTO lang VALUES ('max','da','Maximum','');
INSERT INTO lang VALUES ('max_fontsize','da','Maks tekststørrelse','');
INSERT INTO lang VALUES ('media','da','Medier','');
INSERT INTO lang VALUES ('media_change','da','Skift MedieNr','');
INSERT INTO lang VALUES ('media_copy','da','Kopier data til MedieNr','');
INSERT INTO lang VALUES ('media_info','da','Medie information','');
INSERT INTO lang VALUES ('medialength','da','Medie længde','');
INSERT INTO lang VALUES ('medialist','da','Medie liste','');
INSERT INTO lang VALUES ('medialist_alpha','da','Medie liste i alfabetisk orden','');
INSERT INTO lang VALUES ('medialist_num','da','Medie liste i numerisk orden','');
INSERT INTO lang VALUES ('medianr','da','MedieNr','');
INSERT INTO lang VALUES ('medianr_is_nan','da','MedieNr skal være numerisk (kun tal).','');
INSERT INTO lang VALUES ('mediatype','da','Medie type','');
INSERT INTO lang VALUES ('medium','da','Medie','');
INSERT INTO lang VALUES ('medium_deleted','da','Der er ikke flere film på dette medie - medie fjernet','');
INSERT INTO lang VALUES ('medium_no_access','da','Mediet eksisterer enten ikke, er tomt eller du har ikke adgang til dette indhold.','');
INSERT INTO lang VALUES ('medium_not_deleted','da','Medie ikke fjernet','');
INSERT INTO lang VALUES ('medium_overview','da','Oversigt for %1','');
INSERT INTO lang VALUES ('menues','da','Menuer','');
INSERT INTO lang VALUES ('month','da','Måned','');
INSERT INTO lang VALUES ('movie_color_default','da','Standard farve format for en film','');
INSERT INTO lang VALUES ('movie_color_default_comment','da','Dette vil være standard farve format for nye film.','');
INSERT INTO lang VALUES ('movie_lang_default','da','Standard sprog for lyd i nye film','');
INSERT INTO lang VALUES ('movie_lang_default_comment','da','Dette vil være standard lyd sprog for nye film','');
INSERT INTO lang VALUES ('movie_onlabel_default','da','Standard label for information','');
INSERT INTO lang VALUES ('movie_onlabel_default_comment','da','Standard for nye film: skal informationen om denne film være inkluderet når der udskrives labels for dette medie?','');
INSERT INTO lang VALUES ('movie_pict_default','da','Standard skærmformat for nye film','');
INSERT INTO lang VALUES ('movie_pict_default_comment','da','Dette vil blive brugt som default skærmbillede format for nye film.','');
INSERT INTO lang VALUES ('movies','da','Film','');
INSERT INTO lang VALUES ('movies_left_in_cat','da','Katagori %1 indeholder stadig %2 film og kan derfor ikke slettes.','');
INSERT INTO lang VALUES ('movies_left_reference','da','Denne film kan ikke blive slettet: der er %1 film i databasen der refererer det.','');
INSERT INTO lang VALUES ('movie_tone_default','da','Standard lyd format for nye film','');
INSERT INTO lang VALUES ('movie_tone_default_comment','da','Dette vil være standard lyd format for nye film','');
INSERT INTO lang VALUES ('music','da','Komponist','');
INSERT INTO lang VALUES ('music_list','da','Liste af Komponister','');
INSERT INTO lang VALUES ('name','da','Navn','');
INSERT INTO lang VALUES ('name_not_string','da','Et at de indtastede navne indeholder ulovlige tegn, kun bogstaver, tal og \"-\" er tilladt.','');
INSERT INTO lang VALUES ('never','da','aldrig','');
INSERT INTO lang VALUES ('new_disktype','da','Ny disk type','');
INSERT INTO lang VALUES ('new_medianr','da','nyt MedieNr','');
INSERT INTO lang VALUES ('new_movie_on','da','Ny %1','');
INSERT INTO lang VALUES ('no','da','Nej','');
INSERT INTO lang VALUES ('no_add_lang','da','Ingen yderligere sprog er tilgængelige','');
INSERT INTO lang VALUES ('no_backup_avail','da','Ingen backupfiler at gendanne fra.','');
INSERT INTO lang VALUES ('nobody_named','da','Der er ikke nogen film af %1 navngivet %2 %3 i denne database. Så denne indtastning bliver fjernet fra %1\'s tabel.','');
INSERT INTO lang VALUES ('no_delete_permission','da','Dette medie er ikke dit, og ejeren har ikke givet dig lov til at slette hans film.','');
INSERT INTO lang VALUES ('no_entries_found','da','Ingen film fundet','');
INSERT INTO lang VALUES ('no_entry_in_tapelist','da','Fejlet - ingen film fundet i bånd listen','');
INSERT INTO lang VALUES ('none','da','Ingen','');
INSERT INTO lang VALUES ('no_orphans_found','da','Ikke flere forældreløse.','');
INSERT INTO lang VALUES ('no_restore_file','da','Den valgte fil findes ikke længere','');
INSERT INTO lang VALUES ('no_space_of','da','Der var ikke noget medie med minimum %1 minutters fri plads i databasen.','');
INSERT INTO lang VALUES ('not_logged_in','da','Ikke logget ind','');
INSERT INTO lang VALUES ('not_ok','da','Fejlet','');
INSERT INTO lang VALUES ('not_yet_implemented','da','Ikke implementeret endnu.','');
INSERT INTO lang VALUES ('of_aquiration','da','anskaffelse','');
INSERT INTO lang VALUES ('old_sessions','da','Sessioner ændre ind <input name=\"%1\" value=\"\" class=\"yesnoinput\"> dage','');
INSERT INTO lang VALUES ('orig_medianr','da','original medieNr','');
INSERT INTO lang VALUES ('orig_trans','da','Original oversættelse (%1)','');
INSERT INTO lang VALUES ('orphans_found','da','%1 forældreløse fundet','');
INSERT INTO lang VALUES ('other_pages','da','Andre sider','');
INSERT INTO lang VALUES ('owner','da','Ejer','');
INSERT INTO lang VALUES ('own_to_user','da','Overfør til','');
INSERT INTO lang VALUES ('password','da','Kodeord','');
INSERT INTO lang VALUES ('password_retype','da','Gentag kodeord','');
INSERT INTO lang VALUES ('picture','da','Farve format','');
INSERT INTO lang VALUES ('preferences','da','Præferencer','');
INSERT INTO lang VALUES ('print','da','Udskriv','');
INSERT INTO lang VALUES ('printer_add_failed','da','Der skete en fejl under tilføjelsen af denne printer.','');
INSERT INTO lang VALUES ('printer_add_success','da','Printer tilføjet.','');
INSERT INTO lang VALUES ('printer_comment','da','Hvis du vil udskrive på tabeller (PS labels) skal du bruge de nøjagtige marginer for din printer.','');
INSERT INTO lang VALUES ('printer_name','da','Navn','');
INSERT INTO lang VALUES ('printer_upd_failed','da','Opdatering fejlede for følgende printere: %1','');
INSERT INTO lang VALUES ('print_label','da','Udskriv label','');
INSERT INTO lang VALUES ('pstpl_name','da','Skabelon navn','');
INSERT INTO lang VALUES ('pstpl_type','da','Skabelon type','');
INSERT INTO lang VALUES ('pvp_homepage','da','Projekt hjemmeside','');
INSERT INTO lang VALUES ('read_access','da','Læse adgang','');
INSERT INTO lang VALUES ('read_access_short','da','læs','');
INSERT INTO lang VALUES ('recalc_free','da','Genberegner fri plas på dette medie','');
INSERT INTO lang VALUES ('refresh_lang','da','Opfrisk sprog','');
INSERT INTO lang VALUES ('refresh_lang_comment','da','Genindsæt fraser fra sprogfil ind i database','');
INSERT INTO lang VALUES ('region_code','da','Regions kode','');
INSERT INTO lang VALUES ('remove_cat','da','Fjern katagori','');
INSERT INTO lang VALUES ('remove_empty_media','da','Fjern tomt medie','');
INSERT INTO lang VALUES ('remove_empty_media_comment','da','Skal medie fjernes fra fri plads overvågning når den sidste film er slettet fra dem?','');
INSERT INTO lang VALUES ('restore_db_internal','da','Gendan en PVP backup fil','');
INSERT INTO lang VALUES ('rw_media','da','Ret bart medie','');
INSERT INTO lang VALUES ('rw_media_comment','da','medie der skal overvåges fri plads for (da du kan skrive til dem).','');
INSERT INTO lang VALUES ('save_lang_file','da','Gem oversættelser i en fil','');
INSERT INTO lang VALUES ('scan_new_lang_comment','da','(Hvis du har oprettet din egen sprog fil og lagt den ind i setup direktoriet, vil dette fortælle phpVideoPro at den skal lede efter den)','');
INSERT INTO lang VALUES ('scan_new_lang_files','da','Skan for nye sprog filer','');
INSERT INTO lang VALUES ('screen','da','Skærm format','');
INSERT INTO lang VALUES ('search','da','Søg','');
INSERT INTO lang VALUES ('search_movie','da','Film søgning','');
INSERT INTO lang VALUES ('select_add_lang','da','Vælg yderligere sprog for installation','');
INSERT INTO lang VALUES ('select_add_lang_comment','da','(Engelsk er allerede installeret og vil altid være det)','');
INSERT INTO lang VALUES ('select_primary_lang','da','Vælg primært sprog','');
INSERT INTO lang VALUES ('select_primary_lang_comment','da','(fraser der ikke er i det valgte sprog vil være på engelsk)','');
INSERT INTO lang VALUES ('sel_target_lang','da','Vælg sprog at over sætte til:','');
INSERT INTO lang VALUES ('sess_dla','da','Sidst tilgået','');
INSERT INTO lang VALUES ('sess_end','da','Lukket','');
INSERT INTO lang VALUES ('session_expired','da','Din session er udløbet - log venligst ind igen','');
INSERT INTO lang VALUES ('session_purgetime','da','Hvor længe skal der gå før en inaktiv session udløber?','');
INSERT INTO lang VALUES ('session_purgetime_comment','da','Hvor længe skal en skal en inaktiv session være lovlig?','');
INSERT INTO lang VALUES ('sess_ip','da','Gæsts IP','');
INSERT INTO lang VALUES ('sess_start','da','Startet','');
INSERT INTO lang VALUES ('set_filter','da','Sæt filter','');
INSERT INTO lang VALUES ('site_info','da','Side information','');
INSERT INTO lang VALUES ('site_info_comment','da','Hvad side information skal der vises i browserens titel bjælke','');
INSERT INTO lang VALUES ('skip_intro','da','Spring over ny bruger intro','');
INSERT INTO lang VALUES ('skip_intro_comment','da','Skal intro teksten på start siden springes over','');
INSERT INTO lang VALUES ('source','da','Kilde','');
INSERT INTO lang VALUES ('start_page','da','Startside','');
INSERT INTO lang VALUES ('start_pvp','da','Start phpVideoPro','');
INSERT INTO lang VALUES ('stat_categories','da','Katagorier (brugte/alle)','');
INSERT INTO lang VALUES ('stat_counts','da','Tæller','');
INSERT INTO lang VALUES ('state_active','da','aktive','');
INSERT INTO lang VALUES ('state_inactive','da','inaktive','');
INSERT INTO lang VALUES ('stats','da','Statistik','');
INSERT INTO lang VALUES ('storeplace','da','Opbevaret i','');
INSERT INTO lang VALUES ('submit','da','Gem','');
INSERT INTO lang VALUES ('subtitle','da','Undertekst','');
INSERT INTO lang VALUES ('sure_to_delete','da','Er du sikker på at du vil slette alt data for %1','');
INSERT INTO lang VALUES ('s/w','da','s/w','');
INSERT INTO lang VALUES ('tapelist_update_failed','da','Fejlede opdatering at bånd liste','');
INSERT INTO lang VALUES ('taperest','da','Styr tibageværende tid','');
INSERT INTO lang VALUES ('taperest_absolute','da','Tilbageværende tid (alle medier)','');
INSERT INTO lang VALUES ('taperest_filtered','da','Tilbageværende tid (filtreret)','');
INSERT INTO lang VALUES ('target_trans','da','Oversættelse for det valgte sprog (%1)','');
INSERT INTO lang VALUES ('techdata','da','Teknisk data','');
INSERT INTO lang VALUES ('template_file','da','Skabelon fil','');
INSERT INTO lang VALUES ('template_set','da','Skabelon sæt','');
INSERT INTO lang VALUES ('time_left','da','%1 minutter tilbage','');
INSERT INTO lang VALUES ('title','da','Titel','');
INSERT INTO lang VALUES ('title_not_string','da','Den indtastede titel indeholder ulovlige tegn, kun bogstaver, tal og \"-\" er tilladt.','');
INSERT INTO lang VALUES ('tone','da','Lyd format','');
INSERT INTO lang VALUES ('top_offset','da','Top margin','');
INSERT INTO lang VALUES ('tplset_applicat','da','Applicat skabelon sæt','');
INSERT INTO lang VALUES ('trans_code','da','Oversættelses kode','');
INSERT INTO lang VALUES ('unit','da','Enhed','');
INSERT INTO lang VALUES ('unknown','da','Ukendt','');
INSERT INTO lang VALUES ('unlink_file_failed','da','Sletning mislykkedes - kontroller rettighederne eller slet manuelt.','');
INSERT INTO lang VALUES ('unset_filter','da','Fjern filter','');
INSERT INTO lang VALUES ('upd_access','da','Må opdatere eksisterende film','');
INSERT INTO lang VALUES ('upd_access_short','da','opd','');
INSERT INTO lang VALUES ('update','da','Opdater','');
INSERT INTO lang VALUES ('update_failed','da','Opdatering fejlede','');
INSERT INTO lang VALUES ('update_failed_permission','da','Opdatering fejlede på grund af manglende rettigheder','');
INSERT INTO lang VALUES ('update_success','da','Film opdateret','');
INSERT INTO lang VALUES ('upper_right_corner','da','Øverste højre hjørne (x/y)','');
INSERT INTO lang VALUES ('user','da','Bruger','');
INSERT INTO lang VALUES ('user_create_login_required','da','Du skal specificere et brugernavn for brugeren','');
INSERT INTO lang VALUES ('user_deleted','da','bruger #%1, \"%2\" (%3) er slettet','');
INSERT INTO lang VALUES ('user_delete_failed','da','Sletning af bruger #%1, \"%2\" (%3) fejlet','');
INSERT INTO lang VALUES ('user_delete_report','da','Resultat af bruger sletning','');
INSERT INTO lang VALUES ('user_update_failed','da','Opdatering fejlede for følgende brugere: %1','');
INSERT INTO lang VALUES ('view','da','Vis','');
INSERT INTO lang VALUES ('view_entry','da','Vis film %1','');
INSERT INTO lang VALUES ('warning','da','advarsel','');
INSERT INTO lang VALUES ('week','da','Uge','');
INSERT INTO lang VALUES ('welcome','da','Velkommen','');
INSERT INTO lang VALUES ('wrong_date','da','Den dato %1 du specificerede (%2) er ulovlig. Når du taster en dago så gør det venligst som DDMMÅÅÅÅ og brug kun tal.','');
INSERT INTO lang VALUES ('xfer_unknown_filetype','da','Denne backup filtype er endnu ikke håndteret af phpVideoPro','');
INSERT INTO lang VALUES ('xfer_wrong_mode','da','Programfejl du er i den forkerte tilstand for den forespurgte operation, tilstand skal være \"%1\" og du er i tilstand \"%2\". Rapporter venligst denne fejl til programmets ophavsmand.','');
INSERT INTO lang VALUES ('year','da','År','');
INSERT INTO lang VALUES ('yes','da','Ja','');
