# ========================================================
# French Language File created by phpVideoPro v0.7.1
# ========================================================

UPDATE pvp_languages SET charset='UTF-8' WHERE lang_id='fr';
INSERT INTO pvp_lang VALUES ('3d','fr','3D','');
INSERT INTO pvp_lang VALUES ('about','fr','A propos','');
INSERT INTO pvp_lang VALUES ('actions','fr','Actions','');
INSERT INTO pvp_lang VALUES ('actor','fr','Acteur','');
INSERT INTO pvp_lang VALUES ('actors','fr','Acteurs','');
INSERT INTO pvp_lang VALUES ('actors_list','fr','Liste d\'acteurs','');
INSERT INTO pvp_lang VALUES ('actor_persons','fr','Acteurs','');
INSERT INTO pvp_lang VALUES ('add_access','fr','Peut ajouter des entrées','');
INSERT INTO pvp_lang VALUES ('add_access_short','fr','add','');
INSERT INTO pvp_lang VALUES ('add_entry','fr','Ajouter entrée','');
INSERT INTO pvp_lang VALUES ('add_user','fr','Ajouter utilisateur','');
INSERT INTO pvp_lang VALUES ('admin','fr','Administration','');
INSERT INTO pvp_lang VALUES ('admin_access','fr','Peut accéder aux menus d\'administration','');
INSERT INTO pvp_lang VALUES ('admin_access_short','fr','adm','');
INSERT INTO pvp_lang VALUES ('admin_avlang','fr','Modifier les langues disponibles pour le son et les sous-titres','');
INSERT INTO pvp_lang VALUES ('admin_cats','fr','Gérer les catégories','');
INSERT INTO pvp_lang VALUES ('admin_disktypes','fr','Gérer les types de disques','');
INSERT INTO pvp_lang VALUES ('admin_filter','fr','Paramètres du filtre par defaut','');
INSERT INTO pvp_lang VALUES ('admin_movietech','fr','Modifier les données technique de film','');
INSERT INTO pvp_lang VALUES ('admin_orphans','fr','Retrait d\'entrées orphelines','');
INSERT INTO pvp_lang VALUES ('admin_printers','fr','Gérer les imprimantes','');
INSERT INTO pvp_lang VALUES ('admin_pstemplates','fr','Gérer les modèles PSLabel','');
INSERT INTO pvp_lang VALUES ('admin_sessions','fr','Gérer les sessions','');
INSERT INTO pvp_lang VALUES ('admin_translations','fr','Editer des traductions','');
INSERT INTO pvp_lang VALUES ('admin_useredit','fr','Modifier le compte utilisateur','');
INSERT INTO pvp_lang VALUES ('admin_users','fr','Gérer les comptes utilisateur','');
INSERT INTO pvp_lang VALUES ('audio_ts','fr','Son','');
INSERT INTO pvp_lang VALUES ('back','fr','Précédent','');
INSERT INTO pvp_lang VALUES ('backup_compress','fr','Activer la compression ?','');
INSERT INTO pvp_lang VALUES ('backup_db','fr','Sauvegarde de la base de données','');
INSERT INTO pvp_lang VALUES ('backup_db_complete','fr','Sauvegarder la base de données complète (inclus les données techniques et préférences)','');
INSERT INTO pvp_lang VALUES ('backup_db_movie_internal','fr','Sauvegarder tous les films en utilisant le format interne de phpVideoPro','');
INSERT INTO pvp_lang VALUES ('backup_file_corrupt','fr','Le fichier de sauvegarde séléctionné est corrompu - impossible de restaurer!','');
INSERT INTO pvp_lang VALUES ('backup_file_unreadable','fr','Impossible de lire le fichier de sauvegarde - verifiez que les permissions de fichiers sont correctes','');
INSERT INTO pvp_lang VALUES ('button_backup','fr','Sauvegarder','');
INSERT INTO pvp_lang VALUES ('button_restore','fr','Restaurer','');
INSERT INTO pvp_lang VALUES ('cancel','fr','Annuler','');
INSERT INTO pvp_lang VALUES ('categories','fr','Catégories','');
INSERT INTO pvp_lang VALUES ('category','fr','Catégorie','');
INSERT INTO pvp_lang VALUES ('catlist_alpha','fr','Liste média par ordre alphabétique, triée par catégorie','');
INSERT INTO pvp_lang VALUES ('cat_action','fr','Action','');
INSERT INTO pvp_lang VALUES ('cat_adventure','fr','Aventure','');
INSERT INTO pvp_lang VALUES ('cat_agents','fr','Agent','');
INSERT INTO pvp_lang VALUES ('cat_animal','fr','Animal','');
INSERT INTO pvp_lang VALUES ('cat_animals','fr','Animaux','');
INSERT INTO pvp_lang VALUES ('cat_bible','fr','Bible','');
INSERT INTO pvp_lang VALUES ('cat_biography','fr','Biographie','');
INSERT INTO pvp_lang VALUES ('cat_camera','fr','Caméra','');
INSERT INTO pvp_lang VALUES ('cat_cartoon','fr','Dessin animé','');
INSERT INTO pvp_lang VALUES ('cat_catastrophe','fr','Catastrophe','');
INSERT INTO pvp_lang VALUES ('cat_children','fr','Enfants','');
INSERT INTO pvp_lang VALUES ('cat_comedy','fr','Comédie','');
INSERT INTO pvp_lang VALUES ('cat_concert','fr','Concert','');
INSERT INTO pvp_lang VALUES ('cat_crime','fr','Crime','');
INSERT INTO pvp_lang VALUES ('cat_documentary','fr','Documentaire','');
INSERT INTO pvp_lang VALUES ('cat_drama','fr','Drame','');
INSERT INTO pvp_lang VALUES ('cat_fairytale','fr','Contes de fées','');
INSERT INTO pvp_lang VALUES ('cat_fantasy','fr','Imaginaire','');
INSERT INTO pvp_lang VALUES ('cat_handle_empty','fr','Le champ pour la catégorie ne doit pas être vide. Merci de retourner et modifier pour cette catégorie #%1.','');
INSERT INTO pvp_lang VALUES ('cat_history','fr','Historique','');
INSERT INTO pvp_lang VALUES ('cat_horror','fr','Horreur','');
INSERT INTO pvp_lang VALUES ('cat_internal_name','fr','Handle','');
INSERT INTO pvp_lang VALUES ('cat_judaica','fr','Judaïque','');
INSERT INTO pvp_lang VALUES ('cat_love','fr','Romantique','');
INSERT INTO pvp_lang VALUES ('cat_melodrama','fr','Mélodrame','');
INSERT INTO pvp_lang VALUES ('cat_misc','fr','Divers','');
INSERT INTO pvp_lang VALUES ('cat_monumental','fr','Monument','');
INSERT INTO pvp_lang VALUES ('cat_music','fr','Musique','');
INSERT INTO pvp_lang VALUES ('cat_musical','fr','Comédie musicale','');
INSERT INTO pvp_lang VALUES ('cat_musicmovie','fr','Films musicaux','');
INSERT INTO pvp_lang VALUES ('cat_nature','fr','Nature','');
INSERT INTO pvp_lang VALUES ('cat_opera','fr','Opéra','');
INSERT INTO pvp_lang VALUES ('cat_operetta','fr','Opérette','');
INSERT INTO pvp_lang VALUES ('cat_party','fr','Fête','');
INSERT INTO pvp_lang VALUES ('cat_problem','fr','Problème','');
INSERT INTO pvp_lang VALUES ('cat_report','fr','Reportage','');
INSERT INTO pvp_lang VALUES ('cat_satire','fr','Satirique','');
INSERT INTO pvp_lang VALUES ('cat_scary','fr','Peur','');
INSERT INTO pvp_lang VALUES ('cat_sf','fr','Science Fiction','');
INSERT INTO pvp_lang VALUES ('cat_show','fr','Spectacle','');
INSERT INTO pvp_lang VALUES ('cat_spy','fr','Film d\'espionnage','');
INSERT INTO pvp_lang VALUES ('cat_stage','fr','Scene','');
INSERT INTO pvp_lang VALUES ('cat_thriller','fr','Thriller','');
INSERT INTO pvp_lang VALUES ('cat_trans_update_failed','fr','La mise à  jour a échoué pour la traductions des catégories suivantes : %1','');
INSERT INTO pvp_lang VALUES ('cat_travesty','fr','Déguisement','');
INSERT INTO pvp_lang VALUES ('cat_update_failed','fr','La mise à  échoué pour les catégories suivantes : %1','');
INSERT INTO pvp_lang VALUES ('cat_vacation','fr','Vacances','');
INSERT INTO pvp_lang VALUES ('cat_videoclip','fr','Clip','');
INSERT INTO pvp_lang VALUES ('cat_war','fr','Films de guerre','');
INSERT INTO pvp_lang VALUES ('cat_western','fr','Western','');
INSERT INTO pvp_lang VALUES ('cat_westerncomedy','fr','Comédie-Western','');
INSERT INTO pvp_lang VALUES ('cat_xmas','fr','Noel','');
INSERT INTO pvp_lang VALUES ('change_disktype','fr','Changer le type de disque pour %1','');
INSERT INTO pvp_lang VALUES ('change_media_length','fr','Changer la taille des média','');
INSERT INTO pvp_lang VALUES ('change_media_length_for','fr','Entrer la capacité pour %1','');
INSERT INTO pvp_lang VALUES ('change_nr','fr','Changer le numéro/type des média pour %1','');
INSERT INTO pvp_lang VALUES ('change_rc','fr','Changer le code région','');
INSERT INTO pvp_lang VALUES ('change_rc_for','fr','Changer le code région pour %1','');
INSERT INTO pvp_lang VALUES ('check_completed','fr','Vérification terminée','');
INSERT INTO pvp_lang VALUES ('check_media_delete','fr','Vérifier si le medium est vide','');
INSERT INTO pvp_lang VALUES ('clean_restore','fr','Nettoyer les anciennes données avant de restaurer','');
INSERT INTO pvp_lang VALUES ('close','fr','Fermer','');
INSERT INTO pvp_lang VALUES ('comments','fr','Commentaires','');
INSERT INTO pvp_lang VALUES ('commercials','fr','Publicité','');
INSERT INTO pvp_lang VALUES ('composer','fr','Compositeur','');
INSERT INTO pvp_lang VALUES ('compose_person','fr','compositeur','');
INSERT INTO pvp_lang VALUES ('compose_persons','fr','Compositeurs','');
INSERT INTO pvp_lang VALUES ('configuration','fr','Configuration','');
INSERT INTO pvp_lang VALUES ('config_media','fr','Films et média','');
INSERT INTO pvp_lang VALUES ('confirm_delete','fr','Voulez-vous vraiment supprimer ces enregistrements ?','');
INSERT INTO pvp_lang VALUES ('confirm_prilang','fr','Voulez-vous vraiment changer la langue par défaut pour TOUS les (nouveaux) utilisateurs ?','');
INSERT INTO pvp_lang VALUES ('confirm_userdelete','fr','Vous allez supprimer l\'utilisateur #%1','');
INSERT INTO pvp_lang VALUES ('content','fr','Contenu','');
INSERT INTO pvp_lang VALUES ('cookies','fr','Cookies','');
INSERT INTO pvp_lang VALUES ('counter_start_stop','fr','Compteur Début/Fin','');
INSERT INTO pvp_lang VALUES ('countries','fr','Pays','');
INSERT INTO pvp_lang VALUES ('country','fr','Pays','');
INSERT INTO pvp_lang VALUES ('create','fr','Créer','');
INSERT INTO pvp_lang VALUES ('create_success','fr','Entrée créee avec succès','');
INSERT INTO pvp_lang VALUES ('credits','fr','Remerciements','');
INSERT INTO pvp_lang VALUES ('cut_off','fr','Sans pub','');
INSERT INTO pvp_lang VALUES ('data_access','fr','Accès données','');
INSERT INTO pvp_lang VALUES ('date_format','fr','Format de date','');
INSERT INTO pvp_lang VALUES ('date_format_comment','fr','Quel format utiliser pour l\'affichage de la date.','');
INSERT INTO pvp_lang VALUES ('date_rec','fr','Date acquise','');
INSERT INTO pvp_lang VALUES ('day','fr','Jour','');
INSERT INTO pvp_lang VALUES ('db_stats','fr','Statistiques','');
INSERT INTO pvp_lang VALUES ('delete','fr','Supprimer','');
INSERT INTO pvp_lang VALUES ('delete_lang','fr','Supprimer langue','');
INSERT INTO pvp_lang VALUES ('delete_lang_comment','fr','Supprime de la base toutes les phrase de la langue choisie. Cela ne supprimera pas le fichier langue, donc vous pourrez ré-insérer les phrases plus tard (si vous ne supprimez pas le fichier vous-même).','');
INSERT INTO pvp_lang VALUES ('delete_orphans','fr','Supprime %1 orpheline(s)','');
INSERT INTO pvp_lang VALUES ('delete_remaining','fr','Supprime maintenant les données restantes de la base de données','');
INSERT INTO pvp_lang VALUES ('deleting_entry','fr','Supprime l\'entrée %1','');
INSERT INTO pvp_lang VALUES ('del_access','fr','Peut supprimer des entrées','');
INSERT INTO pvp_lang VALUES ('del_access_short','fr','sup','');
INSERT INTO pvp_lang VALUES ('desc_admin_orphans','fr','Les \"Entrées Orphelines\" sont des données sans liens, ici, des acteurs, réalisateurs et/ou compositeurs auxquels aucun film ne se réfère. Elles sont souvent le résultat de changement d\'un nom mal épellé apres avoir enregistré - mais jamais le resultat de la suppression de l\'entrée d\'un film. C\'est donc une bonne idée de retirer ces entrées : cela permet de conserver des ressources système et de prévenir un ralentissement des actions sur la base de données.','');
INSERT INTO pvp_lang VALUES ('desc_backup_db','fr','C\'est toujours une bonne idée d\'avoir des sauvegarde prêtes. Alors qu\'il est préférable d\'utiliser les outils de votre base de données,((<code>mysql_dump</code>, <code>pgsql_dump</code> etc.) il est possible que votre base de données soit hébergée sur une machine dont vous n\'avez pas l\'accès complet - dans ce cas, utilisez la fonction \"Sauvegarde Complete\" ici, qui sauvegardera votre base de données complète dans un script SQL <BR> Si vous voulez seulement sauvegarder vos données de films, pour les copier dans une autre base par exemple, vous devrez sauvegarder tous vos films en utilisant le format interne de phpVideoPro: de cette manière, vous pouvez même faire migrer entre des types de base différents, ex: MySQL et greSQLPost.While restoring the complete backup of a previous phpVideoPro version to a newer one results in the need of updating the database afterwards (as if you just updated phpVideoPro), the internal PVP backup should be compatible between the versions (future will show ;)<BR> Il est possible de compresser vos sauvegardes: si votre installation PHP prend en charge les compressions GZIP, il vous suffit de coher la case de compression, qui réduira le fichier jusqu\'à  90% de sa taille originale. <BR>','');
INSERT INTO pvp_lang VALUES ('director','fr','Réalisateur','');
INSERT INTO pvp_lang VALUES ('directors','fr','Réalisateurs','');
INSERT INTO pvp_lang VALUES ('directors_list','fr','Liste des réalisateurs','');
INSERT INTO pvp_lang VALUES ('director_person','fr','réalisateur','');
INSERT INTO pvp_lang VALUES ('director_persons','fr','Réalisateurs','');
INSERT INTO pvp_lang VALUES ('disktype_add_failed','fr','Désolé, il était impossible d\'ajouter le nouveau type de disque.','');
INSERT INTO pvp_lang VALUES ('disktype_change','fr','Changer le type de disque','');
INSERT INTO pvp_lang VALUES ('disktype_contains_media','fr','Le type de disque ne peut-être supprimé pour le moment, parce que les media suivant s\'y reffèrent toujours:','');
INSERT INTO pvp_lang VALUES ('disktype_name_empty','fr','Le nom pour un type de disque ne doit pas être vide. merci de retourner et corriger vela pour le type de disque #%1','');
INSERT INTO pvp_lang VALUES ('disktype_update_failed','fr','Désolé, il était impossible de mettre a jour le type de disque suivant : %1','');
INSERT INTO pvp_lang VALUES ('disk_size','fr','Taille de disque','');
INSERT INTO pvp_lang VALUES ('disk_type','fr','Type de disque','');
INSERT INTO pvp_lang VALUES ('display','fr','Afficher','');
INSERT INTO pvp_lang VALUES ('display_limit','fr','Limite d\'Affichage','');
INSERT INTO pvp_lang VALUES ('display_limit_comment','fr','(Combien de lignes afficher par page pour les listes)','');
INSERT INTO pvp_lang VALUES ('dl_pvp_latest','fr','Télécharger la dernière version disponible','');
INSERT INTO pvp_lang VALUES ('dupes','fr','Doubles entrées','');
INSERT INTO pvp_lang VALUES ('dupe_id_entered','fr','Il y a déjà  une entrée dans la base de données pour l\'ID du media choisi. Cliquez sur le bouton \"Retour\" de votre navigateur pour modifiez votre saisie. Aide : Il y a un champ de sélection à  coté du cahmp dans elquel vous avez saisi le numéro du media. Ce champ de séléction vous donne le plus grand qui existe déjà . Il est conseillé d\'augmenter d\'un le premier chiffre (milliers) pour un nouveau media, ou d\'augmenter d\'un le deuxieme chiffre (dizaines) pour un nouveau film sur le même media.','');
INSERT INTO pvp_lang VALUES ('dupe_titles_found','fr','%1 titres avec possibilité de doubles trouvés.','');
INSERT INTO pvp_lang VALUES ('edit','fr','Edition','');
INSERT INTO pvp_lang VALUES ('edit_entry','fr','Modifier l\'entrée %1','');
INSERT INTO pvp_lang VALUES ('enable_cookies','fr','Autoriser les cookies ?','');
INSERT INTO pvp_lang VALUES ('enable_cookies_comment','fr','Gérer les préférences utilisateurs (ex:options de filtres) par des cookies ?','');
INSERT INTO pvp_lang VALUES ('ended_sessions','fr','Sessions Terminées','');
INSERT INTO pvp_lang VALUES ('enter_min_free','fr','Entrer le minimum d\'espace disque libre à  afficher :','');
INSERT INTO pvp_lang VALUES ('enter_new_medianr','fr','Merci de taper le Numéro du support pour ce nouveau %1','');
INSERT INTO pvp_lang VALUES ('expire_cookies','fr','Durée de vie des cookies','');
INSERT INTO pvp_lang VALUES ('expire_cookies_comment','fr','Combien de temps un cookie doit-il rester dans le navigateur de l\'utilisateur ?','');
INSERT INTO pvp_lang VALUES ('farbe','fr','Couleur','');
INSERT INTO pvp_lang VALUES ('filter','fr','Filtre','');
INSERT INTO pvp_lang VALUES ('filter_setup','fr','Option des filtres','');
INSERT INTO pvp_lang VALUES ('finnished','fr','Terminé','');
INSERT INTO pvp_lang VALUES ('first_name','fr','Prénom','');
INSERT INTO pvp_lang VALUES ('format','fr','Format','');
INSERT INTO pvp_lang VALUES ('free','fr','Libre','');
INSERT INTO pvp_lang VALUES ('free_space_on_media','fr','Les media suivants ont au moins %1 minutes d\'espace libre disponible:','');
INSERT INTO pvp_lang VALUES ('free_space_title','fr','Espace libre du media','');
INSERT INTO pvp_lang VALUES ('fsk','fr','Age Minimum','');
INSERT INTO pvp_lang VALUES ('general','fr','Général','');
INSERT INTO pvp_lang VALUES ('goto_entry','fr','Accès direct a l\'entrée:','');
INSERT INTO pvp_lang VALUES ('graphic_file','fr','Fichier Image','');
INSERT INTO pvp_lang VALUES ('help','fr','Aide','');
INSERT INTO pvp_lang VALUES ('help_about','fr','Aide sur','');
INSERT INTO pvp_lang VALUES ('highest_db_entries','fr','Dernière entrée dans la base','');
INSERT INTO pvp_lang VALUES ('history','fr','Historique','');
INSERT INTO pvp_lang VALUES ('hit_back_to_correct','fr','Cliquer sur le bouton \"Retour\" pour corriger l\'erreur.','');
INSERT INTO pvp_lang VALUES ('hour','fr','Heure','');
INSERT INTO pvp_lang VALUES ('hours','fr','Heures','');
INSERT INTO pvp_lang VALUES ('howto','fr','Tutoriel','');
INSERT INTO pvp_lang VALUES ('howto_help','fr','Comment créer un fichier d\'aide','');
INSERT INTO pvp_lang VALUES ('howto_label','fr','Comment créer/configurer les modèles d\'étiquette','');
INSERT INTO pvp_lang VALUES ('howto_lang','fr','Comment créer un nouveau fichier langue','');
INSERT INTO pvp_lang VALUES ('howto_templates','fr','Comment créer un nouveau jeu de modèles','');
INSERT INTO pvp_lang VALUES ('imdb_url','fr','Site IMDB à  utiliser','');
INSERT INTO pvp_lang VALUES ('imdb_url_comment','fr','L\'IMDB (\"Internet Movie DataBase\", ou \"Base de Données de Films Internet\") offre des informations sur beaucoup de films. Il existe plusieurs sites localisés : par exemple, le site allemand permet des recherches sur des films allemands, alors que le site americain permet les recherches sur les films anglais. Selectionnez le site qui correspond le mieux aux titres de film de votre base de données.','');
INSERT INTO pvp_lang VALUES ('imp_errors','fr','Importation de %2 enregistrements terminée avec %1 erreurs.','');
INSERT INTO pvp_lang VALUES ('imp_success','fr','Importation de %1 enregistrements completée avec succès.','');
INSERT INTO pvp_lang VALUES ('incomplete_date','fr','Si vous ne connaissez pas la date exacte mais, par exemple seulement que vous l\'avez acheté en 2000, remplacez par des zéros les informations inconnues. Dans notre exemple, on a \"00\" \"00\" \"2000\"','');
INSERT INTO pvp_lang VALUES ('index','fr','Index','');
INSERT INTO pvp_lang VALUES ('info_common','fr','Informations','');
INSERT INTO pvp_lang VALUES ('info_common_info','fr','<DIV ALIGN=\"center\">Vous utilisez la version %1 de phpVideoPro, sur %2.</DIV>','');
INSERT INTO pvp_lang VALUES ('info_noupdate','fr','<DIV ALIGN=\"center\">La version de phpVideoPro installée (%1) est la plus récente. Pour télécharger le fichier d\'installation de votre version, suivez<A HREF=\"http://projects.izzysoft.de/progs/get_update.php?program=pvp\" TARGET=\"_blank\">ce lien</A>.</DIV>','');
INSERT INTO pvp_lang VALUES ('info_update','fr','Information de mise à  jour','');
INSERT INTO pvp_lang VALUES ('intro','fr','Intro','');
INSERT INTO pvp_lang VALUES ('intro_usage','fr','<P>Voilà  quelques informations pour les nouveaux utilisateurs :<ul><li>La navigation est toujours possible en utilisant la barre de menu en ahaut de la plupart des pages.</li><li>La plupart des pages ont une rubrique d\'aide. Vous pouvez l\'appeler soit par le menu d\'aide, soit (quand il est disponnible), par le bouton \"?\" en haut de page</li><li>Le formulaire suivant vous permet de vous rendre directement à  un film, si vous en connaissez le numéro. Sinon, il vaut mieux utiliser la Liste Media (dans le menu \"Affichage\") ou le formulaire de recherche (menu \"Edition\").</li></ul></P>','');
INSERT INTO pvp_lang VALUES ('intro_usage_skip','fr','<P>Si vous ne souhaitez plus voir ce texte d\'introduction, vous pouvez le désactiver avec l\'option correspondante dans la page Préférences (menu \"Edition\").</P>','');
INSERT INTO pvp_lang VALUES ('intro_usage_title','fr','Introduction pour les nouveaux utilisateurs','');
INSERT INTO pvp_lang VALUES ('invalid_backup_dir','fr','Le répertoire de sauvegarde choisi n\'existe pas','');
INSERT INTO pvp_lang VALUES ('invalid_fsk','fr','La valeur choisie pour l\'age minimum (\"%1\") est invalide.','');
INSERT INTO pvp_lang VALUES ('invalid_media_nr','fr','Le numéro de media que vous avez entré est incomplet ou invalide. You devez entrer un <b>nombre</b> dans les <b>deux</b> champs.','');
INSERT INTO pvp_lang VALUES ('in_list','fr','Présent','');
INSERT INTO pvp_lang VALUES ('is_rw','fr','Réenregistrable','');
INSERT INTO pvp_lang VALUES ('label','fr','Etiquette','');
INSERT INTO pvp_lang VALUES ('labels','fr','Etiquettes','');
INSERT INTO pvp_lang VALUES ('labeltype','fr','Type d\'étiquettes','');
INSERT INTO pvp_lang VALUES ('language_settings','fr','Options de langue','');
INSERT INTO pvp_lang VALUES ('last_entry','fr','Dernière entrée','');
INSERT INTO pvp_lang VALUES ('last_medianr','fr','Le dernier chiffre pour ce media est en ce moment à  :','');
INSERT INTO pvp_lang VALUES ('layout_label','fr','Choisir apparence','');
INSERT INTO pvp_lang VALUES ('left_offset','fr','Bordure gauche','');
INSERT INTO pvp_lang VALUES ('length','fr','Longueur','');
INSERT INTO pvp_lang VALUES ('lines_per_page','fr','Lignes par page','');
INSERT INTO pvp_lang VALUES ('lines_per_page_comment','fr','C\'est le nombre qui determine combien de lignes de textes rentrent sur une page de papier à  l\'impression.','');
INSERT INTO pvp_lang VALUES ('line_count','fr','Lignes','');
INSERT INTO pvp_lang VALUES ('list','fr','Liste','');
INSERT INTO pvp_lang VALUES ('listgen','fr','Générateur de liste','');
INSERT INTO pvp_lang VALUES ('lists','fr','Listes','');
INSERT INTO pvp_lang VALUES ('locale','fr','Langue','');
INSERT INTO pvp_lang VALUES ('login','fr','Nom d\'utilisateur','');
INSERT INTO pvp_lang VALUES ('login_failed','fr','Votre tentative de connection a échoué. Vous avez peut-être mal tapé votre mot de passe ou le compte demandé n\'existe pas.','');
INSERT INTO pvp_lang VALUES ('login_required','fr','Vos privilèges ne sont pas suffisants pour l\'action demandée. Vous pouvez vous connecter avec un compte qui a suffisament de privilèges.<P/>','');
INSERT INTO pvp_lang VALUES ('logout_user','fr','Connecté : \"%1\". <A HREF=\"%2\">Déconnecter</A>','');
INSERT INTO pvp_lang VALUES ('longplay','fr','LongPlay (LP)','');
INSERT INTO pvp_lang VALUES ('lower_left_corner','fr','Coin bas-gauche (x/y)','');
INSERT INTO pvp_lang VALUES ('max_fontsize','fr','Taille de police maximum','');
INSERT INTO pvp_lang VALUES ('media','fr','Media','');
INSERT INTO pvp_lang VALUES ('medialength','fr','Durée media','');
INSERT INTO pvp_lang VALUES ('medialist','fr','Liste Media','');
INSERT INTO pvp_lang VALUES ('medialist_alpha','fr','Liste Media par ordre alphabétique','');
INSERT INTO pvp_lang VALUES ('medialist_num','fr','Liste Media par ordre numérique','');
INSERT INTO pvp_lang VALUES ('medianr','fr','Nombre Media','');
INSERT INTO pvp_lang VALUES ('mediatype','fr','Type Media','');
INSERT INTO pvp_lang VALUES ('media_change','fr','Changer le Nombre Media','');
INSERT INTO pvp_lang VALUES ('media_copy','fr','Copier les données vers le Nombre Media','');
INSERT INTO pvp_lang VALUES ('medium_deleted','fr','Plus de films sur ce medium - Medium supprimé','');
INSERT INTO pvp_lang VALUES ('medium_not_deleted','fr','Medium non supprimé','');
INSERT INTO pvp_lang VALUES ('medium_overview','fr','Vue globale du medium %1','');
INSERT INTO pvp_lang VALUES ('month','fr','Mois','');
INSERT INTO pvp_lang VALUES ('movies','fr','Films','');
INSERT INTO pvp_lang VALUES ('movies_left_in_cat','fr','La catégorie %1 contient toujours %2 films et ne peut donc pas être supprimée. Désolé.','');
INSERT INTO pvp_lang VALUES ('movies_left_reference','fr','Cette entrée ne peut pas être suprimée : %1 film(s) de la base s\'y réfèrent.','');
INSERT INTO pvp_lang VALUES ('movie_color_default','fr','Format de couleur par défaut pour les films','');
INSERT INTO pvp_lang VALUES ('movie_color_default_comment','fr','Utilisé comme le format de couleur pre-selectionné d\'une nouvelle entrée.','');
INSERT INTO pvp_lang VALUES ('movie_onlabel_default','fr','Option par defaut pour les infos sur les étiquettes','');
INSERT INTO pvp_lang VALUES ('movie_onlabel_default_comment','fr','Valeur par défaut pour les nouvelles entrées: Les informations sur ce film doivent-elles être incluses quand les étiquettess pour ce medium sont générées ?','');
INSERT INTO pvp_lang VALUES ('movie_tone_default','fr','Format de son par défaut pour les films','');
INSERT INTO pvp_lang VALUES ('movie_tone_default_comment','fr','Utilisé comme le format audio pre-selectionné d\'une nouvelle entrée.','');
INSERT INTO pvp_lang VALUES ('music','fr','Compositeur','');
INSERT INTO pvp_lang VALUES ('music_list','fr','Liste des compositeurs','');
INSERT INTO pvp_lang VALUES ('name','fr','Nom','');
INSERT INTO pvp_lang VALUES ('never','fr','jamais','');
INSERT INTO pvp_lang VALUES ('new_disktype','fr','Nouveau type de disque','');
INSERT INTO pvp_lang VALUES ('new_medianr','fr','Nouveau numéro media','');
INSERT INTO pvp_lang VALUES ('new_movie_on','fr','New %1','');
INSERT INTO pvp_lang VALUES ('no','fr','Non','');
INSERT INTO pvp_lang VALUES ('nobody_named','fr','Il n\'y a pas d\'autres film par un %1 qui s\'appelle %2 %3 dans cette base, je supprime donc cette entrée de la table %1.','');
INSERT INTO pvp_lang VALUES ('none','fr','Aucun(e)','');
INSERT INTO pvp_lang VALUES ('not_logged_in','fr','non identifié','');
INSERT INTO pvp_lang VALUES ('not_ok','fr','Echoué','');
INSERT INTO pvp_lang VALUES ('not_yet_implemented','fr','Désolé, fonction non existante.','');
INSERT INTO pvp_lang VALUES ('no_add_lang','fr','Aucune langue supplémentaire disponible.','');
INSERT INTO pvp_lang VALUES ('no_backup_avail','fr','Aucun fichier de sauvegarde disponible pour restaurer.','');
INSERT INTO pvp_lang VALUES ('no_entries_found','fr','Aucune entrée trouvée','');
INSERT INTO pvp_lang VALUES ('no_entry_in_tapelist','fr','Echoué, aucune entrée trouvé dans la liste des cassesttes','');
INSERT INTO pvp_lang VALUES ('no_orphans_found','fr','Bravo ! Il semble que vous n\'ayez plus de squelettes dans votre placard !','');
INSERT INTO pvp_lang VALUES ('no_restore_file','fr','Desolé: Le fichier séléctionné n\'existe plus !','');
INSERT INTO pvp_lang VALUES ('no_space_of','fr','Il n\'y avait aucun medium dans la base qui a un minimum de %1 minutes d\'espace libre','');
INSERT INTO pvp_lang VALUES ('nr','fr','n°','');
INSERT INTO pvp_lang VALUES ('of_aquiration','fr','d\'acquisition','');
INSERT INTO pvp_lang VALUES ('ok','fr','OK','');
INSERT INTO pvp_lang VALUES ('old_sessions','fr','Sessions plus vieilles que <INPUT NAME=\"%1\" VALUE=\"\" CLASS=\"yesnobutton\"> jour','');
INSERT INTO pvp_lang VALUES ('orig_disktype','fr','Type de disque d\'origine','');
INSERT INTO pvp_lang VALUES ('orig_medianr','fr','Numéro de media d\'origine','');
INSERT INTO pvp_lang VALUES ('orig_trans','fr','Traduction d\'origine','');
INSERT INTO pvp_lang VALUES ('orphans_found','fr','%1 entrées orpheline(s) trouvée(s)','');
INSERT INTO pvp_lang VALUES ('other_pages','fr','Autre spages','');
INSERT INTO pvp_lang VALUES ('password','fr','Mot de passe','');
INSERT INTO pvp_lang VALUES ('password_retype','fr','Retaper mot de passe','');
INSERT INTO pvp_lang VALUES ('picture','fr','Format de couleur','');
INSERT INTO pvp_lang VALUES ('preferences','fr','Préférences','');
INSERT INTO pvp_lang VALUES ('print','fr','Imprimer','');
INSERT INTO pvp_lang VALUES ('printer','fr','Imprimante','');
INSERT INTO pvp_lang VALUES ('printer_add_failed','fr','Une erreur est apparue en ajoutant l\'imprimante','');
INSERT INTO pvp_lang VALUES ('printer_add_success','fr','Imprimante ajoutée avec succès','');
INSERT INTO pvp_lang VALUES ('printer_comment','fr','Si vous souhaitez imprimer sur des formulaires (comme pour les etiquettes PS), il faut indiquer les bordures exactes de votre imprimante.','');
INSERT INTO pvp_lang VALUES ('printer_name','fr','Nom','');
INSERT INTO pvp_lang VALUES ('printer_upd_failed','fr','Mise à  jour échouée pour les imprimantes suivantes : %1','');
INSERT INTO pvp_lang VALUES ('print_label','fr','Imprimer l\'étiquette:','');
INSERT INTO pvp_lang VALUES ('pslabel','fr','Etiquette PS','');
INSERT INTO pvp_lang VALUES ('pstpl_name','fr','Nom du modèle','');
INSERT INTO pvp_lang VALUES ('pstpl_type','fr','Type de modèle','');
INSERT INTO pvp_lang VALUES ('read_access','fr','Peut naviguer les entrées','');
INSERT INTO pvp_lang VALUES ('recalc_free','fr','Calcul de l\'espace libre restant de ce medium','');
INSERT INTO pvp_lang VALUES ('refresh_lang','fr','Rafraà®chir la langue','');
INSERT INTO pvp_lang VALUES ('refresh_lang_comment','fr','Insérer les phrases du fichier langue dans la base de données.','');
INSERT INTO pvp_lang VALUES ('region_code','fr','Code Région','');
INSERT INTO pvp_lang VALUES ('remove_empty_media','fr','Supprimer les media vides','');
INSERT INTO pvp_lang VALUES ('remove_empty_media_comment','fr','Les media doivent-ils être retirés de la maintenance d\'espace libre quand le dernier film en est supprimé ?','');
INSERT INTO pvp_lang VALUES ('reset','fr','Effacer','');
INSERT INTO pvp_lang VALUES ('restore_db_movie_internal','fr','restaurer les films d\'un fichier de sauvegarde phpVideoPro','');
INSERT INTO pvp_lang VALUES ('rw_media','fr','Media enregistrable','');
INSERT INTO pvp_lang VALUES ('rw_media_comment','fr','Garder l\'espace libre.','');
INSERT INTO pvp_lang VALUES ('s/w','fr','n/b','');
INSERT INTO pvp_lang VALUES ('save_lang_file','fr','Sauvegarder la traduction cible dans un fichier','');
INSERT INTO pvp_lang VALUES ('scan_new_lang_comment','fr','(Si vous avez créé votre propre fichier de traduction et l\'avez mis dans le dossier d\'installation, cela dira a phpVideoPro de le rechercher)','');
INSERT INTO pvp_lang VALUES ('scan_new_lang_files','fr','Chercher les nouveaux fichier de traduction ?','');
INSERT INTO pvp_lang VALUES ('screen','fr','Taille d\'écran','');
INSERT INTO pvp_lang VALUES ('search','fr','Rechercher','');
INSERT INTO pvp_lang VALUES ('search_movie','fr','Chercher Film','');
INSERT INTO pvp_lang VALUES ('select_add_lang','fr','Choisissez une langue supplémentaire à  ajouter','');
INSERT INTO pvp_lang VALUES ('select_add_lang_comment','fr','(L\'Anglais est deja installé et le sera toujours, voir l\'élément suivant. Pour d\'autres langues installée, voir l\'élément suivant aussi.)','');
INSERT INTO pvp_lang VALUES ('select_primary_lang','fr','Choisissez une langue principale','');
INSERT INTO pvp_lang VALUES ('select_primary_lang_comment','fr','(Pour les phrases non-traduites, l\'anglais sera conservé)','');
INSERT INTO pvp_lang VALUES ('sel_target_lang','fr','Choisissez votre langue cible (vers quoi traduire):','');
INSERT INTO pvp_lang VALUES ('session_expired','fr','Votre session a expiré - Merci de vous reconnecter.','');
INSERT INTO pvp_lang VALUES ('session_purgetime','fr','Après combien de temps desactiver une session non-active ?','');
INSERT INTO pvp_lang VALUES ('session_purgetime_comment','fr','Combien de temps une sesion doit-elle rester ouverte sans aucune activité de l\'utilisateur ?','');
INSERT INTO pvp_lang VALUES ('sess_dla','fr','Accedé dernièrement','');
INSERT INTO pvp_lang VALUES ('sess_end','fr','Terminée','');
INSERT INTO pvp_lang VALUES ('sess_id','fr','ID de session','');
INSERT INTO pvp_lang VALUES ('sess_ip','fr','IP distante','');
INSERT INTO pvp_lang VALUES ('sess_start','fr','Démarrée','');
INSERT INTO pvp_lang VALUES ('set_filter','fr','Changer le filtre','');
INSERT INTO pvp_lang VALUES ('site_info','fr','Information du site','');
INSERT INTO pvp_lang VALUES ('site_info_comment','fr','Quel information du site afficher dans la barre de titre ?','');
INSERT INTO pvp_lang VALUES ('skip_intro','fr','Passer l\'intro pour débuter ?','');
INSERT INTO pvp_lang VALUES ('skip_intro_comment','fr','Si vous souhaitez passer le texte d\'introduction sur la page initiale','');
INSERT INTO pvp_lang VALUES ('staff','fr','Equipe','');
INSERT INTO pvp_lang VALUES ('start_page','fr','Page Initiale','');
INSERT INTO pvp_lang VALUES ('start_pvp','fr','Démarrer phpVideoPro','');
INSERT INTO pvp_lang VALUES ('state_active','fr','actif','');
INSERT INTO pvp_lang VALUES ('state_inactive','fr','inactif','');
INSERT INTO pvp_lang VALUES ('stats','fr','Statistiques','');
INSERT INTO pvp_lang VALUES ('stat_categories','fr','Catégories (utilisées/toutes)','');
INSERT INTO pvp_lang VALUES ('stat_counts','fr','Comptes','');
INSERT INTO pvp_lang VALUES ('stat_ranks','fr','Classement','');
INSERT INTO pvp_lang VALUES ('submit','fr','Envoyer','');
INSERT INTO pvp_lang VALUES ('subtitle','fr','Sous-titre','');
INSERT INTO pvp_lang VALUES ('sure_to_delete','fr','Etes-vous sur de vouloir supprimer toute les données de %1','');
INSERT INTO pvp_lang VALUES ('tapelist_update_failed','fr','Echec de la mise à  jour de la liste de cassettes','');
INSERT INTO pvp_lang VALUES ('taperest','fr','Editer le temps restant','');
INSERT INTO pvp_lang VALUES ('taperest_absolute','fr','Temps restant (absolu)','');
INSERT INTO pvp_lang VALUES ('taperest_filtered','fr','Temps restant (filtré)','');
INSERT INTO pvp_lang VALUES ('target_trans','fr','Traduction pour votre langue cible','');
INSERT INTO pvp_lang VALUES ('techdata','fr','Données technique','');
INSERT INTO pvp_lang VALUES ('template_file','fr','Fichier Modèle','');
INSERT INTO pvp_lang VALUES ('template_set','fr','Jeu de Modèles','');
INSERT INTO pvp_lang VALUES ('time_left','fr','%1 minutes restantes','');
INSERT INTO pvp_lang VALUES ('title','fr','Titre','');
INSERT INTO pvp_lang VALUES ('tone','fr','Format audio','');
INSERT INTO pvp_lang VALUES ('top_offset','fr','Bordure haut','');
INSERT INTO pvp_lang VALUES ('tplset_applicat','fr','Jeu de Modèles Applicat','');
INSERT INTO pvp_lang VALUES ('trans_code','fr','Code de Traduction','');
INSERT INTO pvp_lang VALUES ('unit','fr','Unité','');
INSERT INTO pvp_lang VALUES ('unknown','fr','inconnu','');
INSERT INTO pvp_lang VALUES ('unset_filter','fr','RAZ Filtre','');
INSERT INTO pvp_lang VALUES ('update','fr','Mettre à  Jour','');
INSERT INTO pvp_lang VALUES ('update_failed','fr','Impossible de mettre l\'entrée à  jour','');
INSERT INTO pvp_lang VALUES ('update_success','fr','Entrée mise à  jour avec succès','');
INSERT INTO pvp_lang VALUES ('upd_access','fr','Peut mettre des entrées existantes à  jour.','');
INSERT INTO pvp_lang VALUES ('upd_access_short','fr','mà j','');
INSERT INTO pvp_lang VALUES ('upper_right_corner','fr','Coin supérieur droit','');
INSERT INTO pvp_lang VALUES ('user','fr','Utilisateur','');
INSERT INTO pvp_lang VALUES ('user_deleted','fr','Utilisateur n°%1, \"%2\" (%3) supprimé avec succès','');
INSERT INTO pvp_lang VALUES ('user_delete_failed','fr','Echec de la suppression de l\'utilisateur n°%1, \"%2\" (%3)','');
INSERT INTO pvp_lang VALUES ('user_delete_report','fr','Resulats de la suppression d\'utilisateurs','');
INSERT INTO pvp_lang VALUES ('user_update_failed','fr','Echec de la mise a jour des utilisateurs suivants : %1','');
INSERT INTO pvp_lang VALUES ('view','fr','Affichage','');
INSERT INTO pvp_lang VALUES ('view_entry','fr','Affichage de l\'entrée %1','');
INSERT INTO pvp_lang VALUES ('warning','fr','Attention','');
INSERT INTO pvp_lang VALUES ('week','fr','Semaine','');
INSERT INTO pvp_lang VALUES ('welcome','fr','Bienvenue dans phpVideoPro','');
INSERT INTO pvp_lang VALUES ('wrong_date','fr','La date %1 que vous avez spécifié (%2) n\'est pas valide. Quand vous choisssez une date ici, entrez le jour dans le premier champ, le mois dans le deuxième et l\'année dans le troisième et n\'utilisez que des chiffres. Si vous n\'êtes pa ssà»r de la date precise, utilisez des zéros dans les champ en question. ex: \"00\" \"02\" \"2002\" signifie \"eventuellement en Février 2002\", ou \"00\" \"00\" \"0000\" signifie \"à  un moment\".','');
INSERT INTO pvp_lang VALUES ('year','fr','Année','');
INSERT INTO pvp_lang VALUES ('yes','fr','Oui','');
