# ========================================================
# Bulgarian Translation phrases for phpVideoPro
# by Tsvetanka Stoyanova tsvetankas@excite.com
# iso-8859-5
# ========================================================

INSERT INTO lang (message_id,lang,content) VALUES ('not_yet_implemented','bg','Съжалявам - още не е имплементиран.');
INSERT INTO lang VALUES('medium','bg','Носител');
INSERT INTO lang VALUES('nr','bg','Номер');
INSERT INTO lang VALUES('title','bg','Заглавие');
INSERT INTO lang VALUES('length','bg','Продължителност');
INSERT INTO lang VALUES('year','bg','Година');
INSERT INTO lang VALUES('date_rec','bg','Дата на записа');
INSERT INTO lang VALUES('category','bg','Категория');
INSERT INTO lang VALUES('medialist','bg','Списък на носителите');
INSERT INTO lang VALUES('enter_min_free','bg','Въведете минимума свободно място на носителя, което да се визуализира:');
INSERT INTO lang VALUES('display','bg','Визуализирай');
INSERT INTO lang VALUES('free_space_on_media','bg','Следните носители имат поне %1 минута свободно място:');
INSERT INTO lang VALUES('free','bg','Свободно');
INSERT INTO lang VALUES('content','bg','Съдържание');
INSERT INTO lang VALUES('filter_setup','bg','Настройка на филтър');
INSERT INTO lang VALUES('mediatype','bg','Тип носител');
INSERT INTO lang VALUES('screen','bg','Екранен формат');
INSERT INTO lang VALUES('picture','bg','Цветови формат');
INSERT INTO lang VALUES('tone','bg','Звуков формат');
INSERT INTO lang VALUES('longplay','bg','Продължителност / LongPlay');
INSERT INTO lang VALUES('fsk','bg','PG');
INSERT INTO lang VALUES('actor','bg','Артист');
INSERT INTO lang VALUES('actors','bg','Артисти');
INSERT INTO lang VALUES('director','bg','Режисьор');
INSERT INTO lang VALUES('directors','bg','Режисьори');
INSERT INTO lang VALUES('composer','bg','Композитор');
INSERT INTO lang VALUES('music','bg','Музика');
INSERT INTO lang VALUES('min','bg','Мin');
INSERT INTO lang VALUES('max','bg','Мax');
INSERT INTO lang VALUES('s/w','bg','Черно-бял');
INSERT INTO lang VALUES('farbe','bg','Цветен');
INSERT INTO lang VALUES('3d','bg','3D');
INSERT INTO lang VALUES('edit_entry','bg','Редактирай запис %1');
INSERT INTO lang VALUES('view_entry','bg','Визуализирай запис %1');
INSERT INTO lang VALUES('add_entry','bg','Добави запис');
INSERT INTO lang VALUES('unknown','bg','неизвестен');
INSERT INTO lang VALUES('country','bg','Страна');
INSERT INTO lang VALUES('medianr','bg','Номер носител');
INSERT INTO lang VALUES('highest_db_entries','bg','най-голям номер в базата данни');
INSERT INTO lang VALUES('no','bg','Не');
INSERT INTO lang VALUES('yes','bg','Да');
INSERT INTO lang VALUES('medialength','bg','Продължителност на носителя');
INSERT INTO lang VALUES('minute_abbrev','bg','min');
INSERT INTO lang VALUES('source','bg','Източник');
INSERT INTO lang VALUES('staff','bg','Екип');
INSERT INTO lang VALUES('name','bg','Име');
INSERT INTO lang VALUES('first_name','bg','Собствено име');
INSERT INTO lang VALUES('in_list','bg','в списъка');
INSERT INTO lang VALUES('comments','bg','Коментари');
INSERT INTO lang VALUES('cancel','bg','Отказ');
INSERT INTO lang VALUES('create','bg','Създай');
INSERT INTO lang VALUES('update','bg','Актуализирай');
INSERT INTO lang VALUES('edit','bg','Редактирай');
INSERT INTO lang VALUES('delete','bg','Изтрий');
INSERT INTO lang VALUES('invalid_media_nr','bg','Номерът носител, който въведохте, е непълен, или невалиден. Трябва да укажете <b>номер</b> в <b>двете</b> полета за номер на носител (MediaNr).');
INSERT INTO lang VALUES('warning','bg','предупреждение');
INSERT INTO lang VALUES('of_aquiration','bg','на придобиване');
INSERT INTO lang VALUES('wrong_date','bg','Датата, %1 която въведохте, (%2) е невалидна. При въвеждане на дата тук, моля следвайте синтаксиса "YYYY-MM-DD", където "YYYY" е година (четирицифрена), "MM" е месец и "DD" е ден (и двете са двуцифрени). Ако желаете тук да няма дата, просто оставете полето празно (или въведете "0000-00-00").');
INSERT INTO lang VALUES('incomplete_date','bg','Ако не знаете точната дата, но например, знаете само, че този диск е от 2000г, заместете неизвестните данни с нули. В нашия пример датата трябва да изглежда така: "2000-00-00".');
INSERT INTO lang VALUES('dupe_id_entered','bg','В базата данни вече има запис с това ID. Моля натиснете бутона "Back" в браузъра и поправете въведеното. Съвет: До полето за въвеждане, в което зададохте номера на носителя, има поле Select-Box. Полето Select-Box указва най-големия ID   на носител. Обикновено е добре, ако новият носител е с едно по-голям (първите четири цифри) или пък новият филм на същия носител е с едно по-голям при второто (двуцифрено) число.');
INSERT INTO lang VALUES('create_success','bg','Записът е създаден успешно');
INSERT INTO lang VALUES('update_failed','bg','Записът не беше актуализиран');
INSERT INTO lang VALUES('update_success','bg','Записът е актуализиран успешно');
INSERT INTO lang VALUES('about','bg','За / About');
INSERT INTO lang VALUES('history','bg','История / History');
INSERT INTO lang VALUES('view','bg','Визуалирай');
INSERT INTO lang VALUES('deleting_entry','bg','Изтриване на запис %1');
INSERT INTO lang VALUES('free_space_title','bg','Свободно място на носителя');
INSERT INTO lang VALUES('filter','bg','Филтър');
INSERT INTO lang VALUES('set_filter','bg','Задай филтъра');
INSERT INTO lang VALUES('unset_filter','bg','Изчисти филтъра');
INSERT INTO lang VALUES('taperest_absolute','bg','TapeRest (absolute)');
INSERT INTO lang VALUES('taperest_filtered','bg','TapeRest (filtered)');
INSERT INTO lang VALUES('help','bg','Помощ');
INSERT INTO lang VALUES('general','bg','Общи');
INSERT INTO lang VALUES('sure_to_delete','bg','Сигурен(а) ли сте, че искате да изтриете всичките данни за %1');
INSERT INTO lang VALUES('nobody_named','bg','There\'s no other movie by a %1 named %2 %3 in this db, so I remove this entry from the %1\'s table.');
INSERT INTO lang VALUES('compose_person','bg','Композитор');
INSERT INTO lang VALUES('director_person','bg','Режисьор');
INSERT INTO lang VALUES('check_completed','bg','Проверката е завършена');
INSERT INTO lang VALUES('delete_remaining','bg','Сега изтриваме от базата данни останалите данни за този филм');
INSERT INTO lang VALUES('ok','bg','OK');
INSERT INTO lang VALUES('not_ok','bg','Неуспешно');
INSERT INTO lang VALUES('recalc_free','bg','Преизчисляване на оставащото празно място върху носителя');
INSERT INTO lang VALUES('tapelist_update_failed','bg','Списъкът на носителите не беше актуализиран успешно');
INSERT INTO lang VALUES('no_entry_in_tapelist','bg','Неуспешно - в списъка с носителите няма записи');
INSERT INTO lang VALUES('finnished','bg','Завършено');
INSERT INTO lang VALUES('time_left','bg','%1 минута е останала');
INSERT INTO lang VALUES('configuration','bg','Конфигуриране');
INSERT INTO lang VALUES('index','bg','Индекс');
INSERT INTO lang VALUES('intro','bg','Въведение');
INSERT INTO lang VALUES('menues','bg','Менюта');
INSERT INTO lang VALUES('back','bg','Назад / Back');
INSERT INTO lang VALUES('close','bg','Затвори');
INSERT INTO lang VALUES('help_about','bg','Помощ за');
INSERT INTO lang VALUES('actors_list','bg','Списък на артистите');
INSERT INTO lang VALUES('directors_list','bg','Списък на режисьорите');
INSERT INTO lang VALUES('music_list','bg','Списък на композиторите');
INSERT INTO lang VALUES('no_entries_found','bg','Не са намерени записи');
INSERT INTO lang VALUES('no_space_of','bg','В базата данни не беше намерен носител, на който да има минимум %1 минути свободно място.');
INSERT INTO lang VALUES('howto','bg','Как да ... /How to...');
INSERT INTO lang VALUES('howto_lang','bg','Как да създадем файл за нов език');
INSERT INTO lang VALUES('howto_help','bg','Как да създадем помощен файл');
INSERT INTO lang VALUES('howto_templates','bg','Как да създадем нов набор от темплейти');
INSERT INTO lang VALUES('language_settings','bg','Настройки за езика');
INSERT INTO lang VALUES('scan_new_lang_files','bg','Да сканирам ли за нови езикови файлове?');
INSERT INTO lang VALUES('scan_new_lang_comment','bg','(Ако създадохте файл за собствения си език и го поставихте в директорията setup, phpVideoPro ще го потърси)');
INSERT INTO lang VALUES('select_add_lang','bg','Изберете допълнителен език, който да се инсталира');
INSERT INTO lang VALUES('select_add_lang_comment','bg','(Английският вече е инсталиран и винаги ще бъде - вижте по-долу. За други езици, които също вече са инсталирани, също вижте по-долу.)');
INSERT INTO lang VALUES('no_add_lang','bg','Няма достъпни допълнителни езици.');
INSERT INTO lang VALUES('refresh_lang','bg','Презареди езика');
INSERT INTO lang VALUES('refresh_lang_comment','bg','(Вмъкни повторно в базата данни фразите от езиковия файл)');
INSERT INTO lang VALUES('none','bg','Нито един');
INSERT INTO lang VALUES('select_primary_lang','bg','Изберете основен език');
INSERT INTO lang VALUES('select_primary_lang_comment','bg','(за липсващи фрази винаги ще се извиква английският файл)');
INSERT INTO lang VALUES('use_charset','bg','CharSet, който да се използва');
INSERT INTO lang VALUES('use_charset_comment','bg','(важно е за кодирането на символите)');
INSERT INTO lang VALUES('colors','bg','Цветове');
INSERT INTO lang VALUES('page_bg','bg','Фон на страницата');
INSERT INTO lang VALUES('table_bg','bg','Фон на таблицата');
INSERT INTO lang VALUES('th_bg','bg','Фон на колонтитулите на таблицата');
INSERT INTO lang VALUES('feedback_ok','bg','Обратна връзка "OK"');
INSERT INTO lang VALUES('feedback_err','bg','Обратна връзка "Failure"');
INSERT INTO lang VALUES('template_set','bg','Задаване на темплейт');
INSERT INTO lang VALUES('start_pvp','bg','Стартирай phpVideoPro');
INSERT INTO lang VALUES('hit_back_to_correct','bg','Натиснете бутона "Back", за да поправите грешката.');
INSERT INTO lang VALUES('goto_entry','bg','Директно отидете на запис:');
INSERT INTO lang VALUES('start_page','bg','Начална страница');
INSERT INTO lang VALUES('invalid_fsk','bg','Стойността, въведена за %1, е невалидна. %1 означава Parental Guide (Родителски контрол), т.е минималната възраст, под която на никому не трябва да давате достъп до този филм.');
