# ========================================================
# Swedish Language File created by phpVideoPro v0.4.6p6
# Original File by Tony Granberg
# ========================================================

UPDATE pvp_languages SET charset='UTF-8' WHERE lang_id='sv';
INSERT INTO pvp_lang VALUES ('about','sv','Om','');
INSERT INTO pvp_lang VALUES ('actor','sv','Skådespelare','');
INSERT INTO pvp_lang VALUES ('actors','sv','Skådespelare (i flertal)','');
INSERT INTO pvp_lang VALUES ('actors_list','sv','Lista på Skådespelare','');
INSERT INTO pvp_lang VALUES ('add_entry','sv','Lägg till notering','');
INSERT INTO pvp_lang VALUES ('back','sv','Tillbaka','');
INSERT INTO pvp_lang VALUES ('cancel','sv','Avbryt','');
INSERT INTO pvp_lang VALUES ('category','sv','Kategori','');
INSERT INTO pvp_lang VALUES ('catlist_alpha','sv','Medialista i alfabetisk ordning, sorterad efter kategori','');
INSERT INTO pvp_lang VALUES ('check_completed','sv','Koll färdig','');
INSERT INTO pvp_lang VALUES ('close','sv','Stäng','');
INSERT INTO pvp_lang VALUES ('colors','sv','Färger','');
INSERT INTO pvp_lang VALUES ('comments','sv','Kommentarer','');
INSERT INTO pvp_lang VALUES ('commercials','sv','Reklamer','');
INSERT INTO pvp_lang VALUES ('composer','sv','Kompositör','');
INSERT INTO pvp_lang VALUES ('compose_person','sv','kompositör','');
INSERT INTO pvp_lang VALUES ('configuration','sv','Konfiguration','');
INSERT INTO pvp_lang VALUES ('content','sv','Innehåll','');
INSERT INTO pvp_lang VALUES ('counter_start_stop','sv','Räknare Start/Stopp','');
INSERT INTO pvp_lang VALUES ('country','sv','Land','');
INSERT INTO pvp_lang VALUES ('create','sv','Skapa','');
INSERT INTO pvp_lang VALUES ('create_success','sv','Notering skapades utan problem','');
INSERT INTO pvp_lang VALUES ('cut_off','sv','klipp av','');
INSERT INTO pvp_lang VALUES ('date_format','sv','Datumformat','');
INSERT INTO pvp_lang VALUES ('date_format_comment','sv','Vilket format att använda för datumvisningen. Tillgängliga format är: y-m-d, d.m.y och d/m/y','');
INSERT INTO pvp_lang VALUES ('date_rec','sv','Datum då det är skaffat','');
INSERT INTO pvp_lang VALUES ('delete','sv','Ta bort','');
INSERT INTO pvp_lang VALUES ('delete_remaining','sv','tar nu bort återstående data för denna film från db','');
INSERT INTO pvp_lang VALUES ('deleting_entry','sv','Tar bort notering %1','');
INSERT INTO pvp_lang VALUES ('director','sv','Regissör','');
INSERT INTO pvp_lang VALUES ('directors','sv','Regissörer','');
INSERT INTO pvp_lang VALUES ('directors_list','sv','Lista på Regissörer','');
INSERT INTO pvp_lang VALUES ('director_person','sv','regissör','');
INSERT INTO pvp_lang VALUES ('display','sv','Visa','');
INSERT INTO pvp_lang VALUES ('display_limit','sv','Visa Gräns','');
INSERT INTO pvp_lang VALUES ('display_limit_comment','sv','(Hur många rader att visa per sida för listor)','');
INSERT INTO pvp_lang VALUES ('dupe_id_entered','sv','Det finns redan en notering i databasen för ditt angivna media ID. Var god tryck på \"Tillbaka\"-knappen i din webbläsare och korrigera det du skrev in. Tips: Det finns en Select-ruta bredvid inskrivningsrutan du angav medianumret i. Denna inskrivningsruta talar om ditt högsta existerande film-id. Normalt sett är det en bra idé för nya media att höja det första (fyr-siffriga) numret med ett, eller för en ny film på samma media, att höja det andra (två-siffriga) numret, med ett.','');
INSERT INTO pvp_lang VALUES ('edit','sv','Redigera','');
INSERT INTO pvp_lang VALUES ('edit_entry','sv','Ändra notering %1','');
INSERT INTO pvp_lang VALUES ('enter_min_free','sv','Skriv in det minimala av ledigt utrymme att visa på media:','');
INSERT INTO pvp_lang VALUES ('farbe','sv','Färg','');
INSERT INTO pvp_lang VALUES ('filter_setup','sv','Filter-inställningar','');
INSERT INTO pvp_lang VALUES ('finnished','sv','Färdig','');
INSERT INTO pvp_lang VALUES ('first_name','sv','Första namnet','');
INSERT INTO pvp_lang VALUES ('free','sv','Ledigt','');
INSERT INTO pvp_lang VALUES ('free_space_on_media','sv','Följande media har minst %1 minuter kvar av ledigt utrymme:','');
INSERT INTO pvp_lang VALUES ('free_space_title','sv','Ledigt utrymme på media','');
INSERT INTO pvp_lang VALUES ('general','sv','Allmänt','');
INSERT INTO pvp_lang VALUES ('goto_entry','sv','Gå direkt till notering:','');
INSERT INTO pvp_lang VALUES ('help','sv','Hjälp','');
INSERT INTO pvp_lang VALUES ('help_about','sv','Hjälp om','');
INSERT INTO pvp_lang VALUES ('highest_db_entries','sv','högsta noteringar i db','');
INSERT INTO pvp_lang VALUES ('history','sv','Historik','');
INSERT INTO pvp_lang VALUES ('hit_back_to_correct','sv','Tryck på \"Tillbaka\"-knappen för att fixa felet.','');
INSERT INTO pvp_lang VALUES ('howto','sv','Hur man fixar...','');
INSERT INTO pvp_lang VALUES ('howto_help','sv','Hur man skapar en hjälpfil','');
INSERT INTO pvp_lang VALUES ('howto_label','sv','Hur man skapar/konfigurerar etikett-mallar','');
INSERT INTO pvp_lang VALUES ('howto_lang','sv','Hur man skapar en ny språkfil','');
INSERT INTO pvp_lang VALUES ('howto_templates','sv','Hur man skapar ett nytt set av mallar','');
INSERT INTO pvp_lang VALUES ('incomplete_date','sv','Om du inte vet det exakta datumet, men - till exempel - att du skaffade det året 2000, byt ut nollor mot den okända datan - i vårat exempel, så ska datumet se ut ungefär som \"00\" \"00\" \"2000\".','');
INSERT INTO pvp_lang VALUES ('invalid_fsk','sv','Värdet inskrivet för %1 är felaktigt. %1 betyder Vuxenguide, t.ex. minimum-ålder som bestämmer att ingen under denna ålder ska få access till denna film.','');
INSERT INTO pvp_lang VALUES ('invalid_media_nr','sv','Medianumret du angav är antingen inte komplett eller felaktigt. Du måste ange ett <b>nummer</b> i <b>båda</b> MediaNr-fälten.','');
INSERT INTO pvp_lang VALUES ('in_list','sv','I lista','');
INSERT INTO pvp_lang VALUES ('label','sv','Etikett','');
INSERT INTO pvp_lang VALUES ('labels','sv','Etiketter','');
INSERT INTO pvp_lang VALUES ('language_settings','sv','Språk-inställningar','');
INSERT INTO pvp_lang VALUES ('length','sv','Längd','');
INSERT INTO pvp_lang VALUES ('lines_per_page','sv','Rader per sida','');
INSERT INTO pvp_lang VALUES ('lines_per_page_comment','sv','Detta är för skriv ut-funktionerna att avgöra hur många rader text som får plats på ett enda papper.','');
INSERT INTO pvp_lang VALUES ('line_count','sv','Rader','');
INSERT INTO pvp_lang VALUES ('list','sv','Lista','');
INSERT INTO pvp_lang VALUES ('listgen','sv','List-Generator','');
INSERT INTO pvp_lang VALUES ('lists','sv','Listor','');
INSERT INTO pvp_lang VALUES ('medialength','sv','Media-längd','');
INSERT INTO pvp_lang VALUES ('medialist','sv','Medialista','');
INSERT INTO pvp_lang VALUES ('medialist_alpha','sv','Medialista i alfabetisk ordning','');
INSERT INTO pvp_lang VALUES ('medialist_num','sv','Medialista i numerisk ordning','');
INSERT INTO pvp_lang VALUES ('medium','sv','Media','');
INSERT INTO pvp_lang VALUES ('menues','sv','Menyer','');
INSERT INTO pvp_lang VALUES ('music','sv','Kompositörer','');
INSERT INTO pvp_lang VALUES ('music_list','sv','Lista på Kompositörer','');
INSERT INTO pvp_lang VALUES ('name','sv','Namn','');
INSERT INTO pvp_lang VALUES ('no','sv','Nej','');
INSERT INTO pvp_lang VALUES ('nobody_named','sv','Det är ingen annan film med en/ett %1 som heter %2 %3 i denna db, så jag tar bort denna notering från %1s tabell.','');
INSERT INTO pvp_lang VALUES ('none','sv','Ingen','');
INSERT INTO pvp_lang VALUES ('not_ok','sv','Misslyckades','');
INSERT INTO pvp_lang VALUES ('no_add_lang','sv','Inga ytterligare språk tillgängliga.','');
INSERT INTO pvp_lang VALUES ('no_entries_found','sv','Inga noteringar funna','');
INSERT INTO pvp_lang VALUES ('no_entry_in_tapelist','sv','Misslyckades - ingen notering funnen i kassettlistan','');
INSERT INTO pvp_lang VALUES ('no_space_of','sv','Det fanns inget media med ett minimum av %1 min av ledigt utrymme, funnen i databasen.','');
INSERT INTO pvp_lang VALUES ('of_aquiration','sv','av införskaffning','');
INSERT INTO pvp_lang VALUES ('other_pages','sv','Andra sidor','');
INSERT INTO pvp_lang VALUES ('page_bg','sv','Bakgrund På Sidan','');
INSERT INTO pvp_lang VALUES ('picture','sv','Färgformat','');
INSERT INTO pvp_lang VALUES ('print','sv','Skriv ut','');
INSERT INTO pvp_lang VALUES ('print_label','sv','Skriv ut Etikett:','');
INSERT INTO pvp_lang VALUES ('recalc_free','sv','Kalkylerar om återstående ledigt utrymme på detta media','');
INSERT INTO pvp_lang VALUES ('refresh_lang','sv','Uppdatera språk','');
INSERT INTO pvp_lang VALUES ('refresh_lang_comment','sv','(skriv åter in fraser från språkfilen in i db)','');
INSERT INTO pvp_lang VALUES ('s/w','sv','s/v','');
INSERT INTO pvp_lang VALUES ('scan_new_lang_comment','sv','(Om du skapade din egen språkfil och lade den i setup-katalogen, så berättar detta för phpVideoPro att söka efter den)','');
INSERT INTO pvp_lang VALUES ('scan_new_lang_files','sv','Scanna efter nya språkfiler?','');
INSERT INTO pvp_lang VALUES ('screen','sv','Skärmformat','');
INSERT INTO pvp_lang VALUES ('select_add_lang','sv','Välj ytterligare språk att installera','');
INSERT INTO pvp_lang VALUES ('select_add_lang_comment','sv','(Engelska är redan installerad och kommer alltid att vara det - se nästa grej. För andra språk som redan är installerade, se nästa grej, också.)','');
INSERT INTO pvp_lang VALUES ('select_primary_lang','sv','Välj förstahandsspråk','');
INSERT INTO pvp_lang VALUES ('select_primary_lang_comment','sv','(för fraser som fattas, kommer det alltid att finnas en tillbakaövergång till Engelska på)','');
INSERT INTO pvp_lang VALUES ('set_filter','sv','Ställ in Filter','');
INSERT INTO pvp_lang VALUES ('source','sv','Källa','');
INSERT INTO pvp_lang VALUES ('staff','sv','Personal','');
INSERT INTO pvp_lang VALUES ('start_page','sv','Startsida','');
INSERT INTO pvp_lang VALUES ('start_pvp','sv','Starta phpVideoPro','');
INSERT INTO pvp_lang VALUES ('sure_to_delete','sv','Är du säker att du vill ta bort all data för %1','');
INSERT INTO pvp_lang VALUES ('table_bg','sv','Bakgrund På Tabellen','');
INSERT INTO pvp_lang VALUES ('tapelist_update_failed','sv','Misslyckades uppdatera listan på kassett','');
INSERT INTO pvp_lang VALUES ('taperest_absolute','sv','TapeRest (absolut)','');
INSERT INTO pvp_lang VALUES ('taperest_filtered','sv','TapeRest (filtrerat)','');
INSERT INTO pvp_lang VALUES ('template_set','sv','Mall-inställning','');
INSERT INTO pvp_lang VALUES ('th_bg','sv','Bakgrund på Tabell-huvuden','');
INSERT INTO pvp_lang VALUES ('time_left','sv','%1 minuter kvar','');
INSERT INTO pvp_lang VALUES ('title','sv','Titel','');
INSERT INTO pvp_lang VALUES ('tone','sv','Tonformat','');
INSERT INTO pvp_lang VALUES ('unknown','sv','okänd','');
INSERT INTO pvp_lang VALUES ('unset_filter','sv','Återställ Filter','');
INSERT INTO pvp_lang VALUES ('update','sv','Uppdatera','');
INSERT INTO pvp_lang VALUES ('update_failed','sv','Misslyckades att uppdatera notering','');
INSERT INTO pvp_lang VALUES ('update_success','sv','Notering uppdaterad utan problem','');
INSERT INTO pvp_lang VALUES ('view','sv','Visa','');
INSERT INTO pvp_lang VALUES ('view_entry','sv','Visa notering %1','');
INSERT INTO pvp_lang VALUES ('warning','sv','varning','');
INSERT INTO pvp_lang VALUES ('wrong_date','sv','Datumet %1 du angav (%2) är felaktigt. När du skriver in ett datum här, var god skriv in dagen i den första, månaden i den andra och året i det tredje datumfältet och använd enbart siffror. Om du inte är säker på det exakta datumet, skriv isf in nollor i fälten i fråga: t.ex. \"00\" \"02\" \"2002\" betyder \"troligtvis i februari 2002\"NULL, eller \"00\" \"00\" \"0000\" som betyder \"ibland\".','');
INSERT INTO pvp_lang VALUES ('year','sv','År','');
INSERT INTO pvp_lang VALUES ('yes','sv','Ja','');
