# ========================================================
# Italian Language File created by phpVideoPro v0.6.10p2
# ========================================================

UPDATE languages SET charset='UTF-8' WHERE lang_id='it';
INSERT INTO lang VALUES ('3d','it','3D','');
INSERT INTO lang VALUES ('about','it','Info','');
INSERT INTO lang VALUES ('actions','it','Azioni','');
INSERT INTO lang VALUES ('actor','it','Attore','');
INSERT INTO lang VALUES ('actors','it','Attori','');
INSERT INTO lang VALUES ('actors_list','it','Elenco degli attori','');
INSERT INTO lang VALUES ('actor_persons','it','Attori','');
INSERT INTO lang VALUES ('add_access','it','Puo\' aggiungere nuove voci','');
INSERT INTO lang VALUES ('add_access_short','it','agg','');
INSERT INTO lang VALUES ('add_entry','it','Aggiungi una voce','');
INSERT INTO lang VALUES ('add_user','it','Aggiungi un utente','');
INSERT INTO lang VALUES ('admin','it','Amministratore','');
INSERT INTO lang VALUES ('admin_access','it','Consente l\'accesso ai menu\' dell\'ammimistratore','');
INSERT INTO lang VALUES ('admin_access_short','it','adm','');
INSERT INTO lang VALUES ('admin_avlang','it','Edita le lingue disponibili per audio e sottotitoli','');
INSERT INTO lang VALUES ('admin_cats','it','Gestione categorie','');
INSERT INTO lang VALUES ('admin_disktypes','it','Edita i tipi di dischi','');
INSERT INTO lang VALUES ('admin_filter','it','Settaggio filtri di default','');
INSERT INTO lang VALUES ('admin_movietech','it','Edita i dati tecnici dei film','');
INSERT INTO lang VALUES ('admin_orphans','it','Rimozione delle voci rimaste orfane','');
INSERT INTO lang VALUES ('admin_printers','it','Elenca le stampanti','');
INSERT INTO lang VALUES ('admin_pstemplates','it','Edita le maschere PSLabel','');
INSERT INTO lang VALUES ('admin_required','it','Questa azione richiede i privilegi di ammimistratore','');
INSERT INTO lang VALUES ('admin_sessions','it','Gestione sessioni','');
INSERT INTO lang VALUES ('admin_translations','it','Edita traduzioni','');
INSERT INTO lang VALUES ('admin_useredit','it','Edita account utenti','');
INSERT INTO lang VALUES ('admin_users','it','Gestione degli account utenti','');
INSERT INTO lang VALUES ('audio_ts','it','Audio','');
INSERT INTO lang VALUES ('back','it','Indietro','');
INSERT INTO lang VALUES ('backup_compress','it','Attivo compressione?','');
INSERT INTO lang VALUES ('backup_db','it','Copia di salvataggio del database','');
INSERT INTO lang VALUES ('backup_db_cats','it','Categorie di salvataggio','');
INSERT INTO lang VALUES ('backup_db_complete','it','Salva l\'intero database (compresi i dati tecnici e le preferenze)','');
INSERT INTO lang VALUES ('backup_db_movie_internal','it','Salva tutti i film usando il formato interno di phpVideoPro','');
INSERT INTO lang VALUES ('backup_db_sysconf','it','Salva la configurazione del sistema e le preferenze di default','');
INSERT INTO lang VALUES ('backup_file_corrupt','it','Il file di salvataggio selezionato e\' alterato - non e\' possibile ripristinare i dati da questo file!','');
INSERT INTO lang VALUES ('backup_file_unreadable','it','Non riesco a leggere i dati dal file di salvataggio - assicurati che i permessi siano settati correttamente','');
INSERT INTO lang VALUES ('button_backup','it','Salvataggio','');
INSERT INTO lang VALUES ('button_restore','it','Ripristino','');
INSERT INTO lang VALUES ('cancel','it','Cancella','');
INSERT INTO lang VALUES ('categories','it','Generi','');
INSERT INTO lang VALUES ('category','it','Genere','');
INSERT INTO lang VALUES ('catlist_alpha','it','Elecno in ordine alfabetico, ordinato per genere','');
INSERT INTO lang VALUES ('cat_action','it','Azione','');
INSERT INTO lang VALUES ('cat_adventure','it','Avventura','');
INSERT INTO lang VALUES ('cat_agents','it','Spionaggio','');
INSERT INTO lang VALUES ('cat_animal','it','Animale','');
INSERT INTO lang VALUES ('cat_animals','it','Animali','');
INSERT INTO lang VALUES ('cat_bible','it','Bibbia','');
INSERT INTO lang VALUES ('cat_biography','it','Biografia','');
INSERT INTO lang VALUES ('cat_camera','it','Telecamera','');
INSERT INTO lang VALUES ('cat_cartoon','it','Cartoni','');
INSERT INTO lang VALUES ('cat_catastrophe','it','Catastrofi','');
INSERT INTO lang VALUES ('cat_children','it','Bambini','');
INSERT INTO lang VALUES ('cat_comedy','it','Commedia','');
INSERT INTO lang VALUES ('cat_concert','it','Concerto','');
INSERT INTO lang VALUES ('cat_crime','it','Giallo','');
INSERT INTO lang VALUES ('cat_documentary','it','Documentario','');
INSERT INTO lang VALUES ('cat_drama','it','Drammatico','');
INSERT INTO lang VALUES ('cat_fairytale','it','Favole','');
INSERT INTO lang VALUES ('cat_fantasy','it','Fantasy','');
INSERT INTO lang VALUES ('cat_handle_empty','it','Il titolo di una categoria non deve essere vuoto- Per cortesia torna indietro e risolvi il problema per questa categoria #%1.','');
INSERT INTO lang VALUES ('cat_history','it','Storia','');
INSERT INTO lang VALUES ('cat_horror','it','Orrore','');
INSERT INTO lang VALUES ('cat_internal_name','it','Titolo','');
INSERT INTO lang VALUES ('cat_judaica','it','Giudaismo','');
INSERT INTO lang VALUES ('cat_love','it','Storie d\'amore','');
INSERT INTO lang VALUES ('cat_melodrama','it','Melodramma','');
INSERT INTO lang VALUES ('cat_misc','it','Varie','');
INSERT INTO lang VALUES ('cat_monumental','it','Monumentale','');
INSERT INTO lang VALUES ('cat_music','it','Musica','');
INSERT INTO lang VALUES ('cat_musical','it','Musicale','');
INSERT INTO lang VALUES ('cat_musicmovie','it','Film Musicali','');
INSERT INTO lang VALUES ('cat_nature','it','Natura','');
INSERT INTO lang VALUES ('cat_opera','it','Opera','');
INSERT INTO lang VALUES ('cat_operetta','it','Operetta','');
INSERT INTO lang VALUES ('cat_party','it','Festa','');
INSERT INTO lang VALUES ('cat_problem','it','Problema','');
INSERT INTO lang VALUES ('cat_report','it','Reportage','');
INSERT INTO lang VALUES ('cat_satire','it','Satira','');
INSERT INTO lang VALUES ('cat_scary','it','Film paurosi','');
INSERT INTO lang VALUES ('cat_sf','it','Fantascienza','');
INSERT INTO lang VALUES ('cat_show','it','Spettacolo','');
INSERT INTO lang VALUES ('cat_spy','it','Spionaggio','');
INSERT INTO lang VALUES ('cat_stage','it','Teatro','');
INSERT INTO lang VALUES ('cat_thriller','it','Thriller','');
INSERT INTO lang VALUES ('cat_trans_update_failed','it','Aggiornamento non andato a buon fine per la traduzione delle seguenti categorie %1','');
INSERT INTO lang VALUES ('cat_travesty','it','Parodie','');
INSERT INTO lang VALUES ('cat_update_failed','it','Aggiormanento non andato a buon fine per le seguenti categorie: %1','');
INSERT INTO lang VALUES ('cat_vacation','it','Vacanze','');
INSERT INTO lang VALUES ('cat_videoclip','it','Videoclip','');
INSERT INTO lang VALUES ('cat_war','it','Guerra','');
INSERT INTO lang VALUES ('cat_western','it','Western','');
INSERT INTO lang VALUES ('cat_westerncomedy','it','Commedia-Western','');
INSERT INTO lang VALUES ('cat_xmas','it','Natale','');
INSERT INTO lang VALUES ('change_disktype','it','Cambia il tipo di disco per %1','');
INSERT INTO lang VALUES ('change_media_length','it','Cambia la durata del supporto','');
INSERT INTO lang VALUES ('change_media_length_for','it','Prego inserisci la durata per %1','');
INSERT INTO lang VALUES ('change_nr','it','Cambio numero/tipo per %1','');
INSERT INTO lang VALUES ('change_rc','it','Cambia il codice regione','');
INSERT INTO lang VALUES ('change_rc_for','it','Cambia il codice regione per %1','');
INSERT INTO lang VALUES ('check_completed','it','Controllo completato','');
INSERT INTO lang VALUES ('check_media_delete','it','Controllo se il campo e\' vuoto','');
INSERT INTO lang VALUES ('clean_restore','it','Pulisci (rimuovi) i dati vecchi prima del ripristino','');
INSERT INTO lang VALUES ('close','it','Chiudi','');
INSERT INTO lang VALUES ('comments','it','Commenti','');
INSERT INTO lang VALUES ('commercials','it','Pubblicit�','');
INSERT INTO lang VALUES ('composer','it','Autore della colonna sonora','');
INSERT INTO lang VALUES ('compose_person','it','Autore della colonna sonora','');
INSERT INTO lang VALUES ('compose_persons','it','Autori della colonna sonora','');
INSERT INTO lang VALUES ('configuration','it','Configurazione','');
INSERT INTO lang VALUES ('config_media','it','Film e media','');
INSERT INTO lang VALUES ('confirm_delete','it','Desideri veramente cancellare questo record?','');
INSERT INTO lang VALUES ('confirm_prilang','it','Desideri veramente cambiare la lingua originale di default per tutti i nuovi utenti?','');
INSERT INTO lang VALUES ('confirm_userdelete','it','Stai per cancellare l\'utente #%1','');
INSERT INTO lang VALUES ('content','it','Contenuti','');
INSERT INTO lang VALUES ('cookies','it','Cookies','');
INSERT INTO lang VALUES ('counter_start_stop','it','Inizio/stop contatore','');
INSERT INTO lang VALUES ('countries','it','Nazioni','');
INSERT INTO lang VALUES ('country','it','Nazione','');
INSERT INTO lang VALUES ('create','it','Crea nuova voce','');
INSERT INTO lang VALUES ('create_success','it','Nuova voce creata corretamente','');
INSERT INTO lang VALUES ('credits','it','Credits','');
INSERT INTO lang VALUES ('cut_off','it','Tagliati','');
INSERT INTO lang VALUES ('data_access','it','Accesso ai dati','');
INSERT INTO lang VALUES ('date_format','it','Formato dati','');
INSERT INTO lang VALUES ('date_format_comment','it','Quale formato usare per visualizzare i dati','');
INSERT INTO lang VALUES ('date_rec','it','Data acquisita','');
INSERT INTO lang VALUES ('day','it','Giorno','');
INSERT INTO lang VALUES ('db_stats','it','Statistiche','');
INSERT INTO lang VALUES ('delete','it','Cancella','');
INSERT INTO lang VALUES ('delete_lang','it','Cancella lingua','');
INSERT INTO lang VALUES ('delete_lang_comment','it','Cancella dal db tutte le frasi della lingua specificata. Puoi reinserire le frasi quando vuoi (se non cancelli il file)','');
INSERT INTO lang VALUES ('delete_orphans','it','Sto cancellando %1 orfano(i)','');
INSERT INTO lang VALUES ('delete_remaining','it','ora sto cancellando da db i dati rimasti di questo film','');
INSERT INTO lang VALUES ('deleting_entry','it','Sto cancellando %1','');
INSERT INTO lang VALUES ('del_access','it','Puo\' cancellare voci','');
INSERT INTO lang VALUES ('del_access_short','it','del','');
INSERT INTO lang VALUES ('desc_admin_orphans','it','le \"voci orfane\" sono dati senza collegamenti, per es: Attori, direttori e/o autori per cui non esiste alcun riferimento/collegamento a film. Queste sono generalmente conseguenza della modifica di un errore di ortografia dopo un salvataggio, ma non il risultato della cancellazione di una voce relativa al film. Quindi e\' buona norma rimuovere queste voci: da un lato salva le risorse e dall\'altro aiuta a prevenire rallentamenti nella esecuzione del database.','');
INSERT INTO lang VALUES ('desc_backup_db','it','E\' fortemente raccomandato avere sempre un salvataggio (backup) a portata di mano. Per il salvataggio completo e\' preferibile usare gli strumenti del tuo database (<code>mysql_dump</code>, <code>pgsql_dump</code> etc.). Se invece il database e\' ospitato su di una macchina di cui non hai l\'accesso alla shell allora usa la funzione del programma \"salvataggio completo\" che fa\' un salvataggio completo del database in uno script SQL.<BR>Se desideri invece salvare semplicmente i dati dei tuoi film, per esempio duplicarli in un altro database, devi salvare i dati registrati usando il formato interno di phpVideoPro: in questo modo puoi scambiare i dati con diversi tipi di database per es MySQL e PostgreSQL. Mentre per ricaricare i dati completi di una versione precedente di phpVideoPro su una nuova versione richiede l\'aggiormanento del database in una fase successiva (come un semplice aggiornamento di phpVideoPro), il salvataggio interno PVP deve essere compatibile tra le versioni (vedremo ;)<BR>se desideri comprimere il salvataggio lo poi fare se la tua installazione di PHP è compilata con il supporto gzip: semplicemente seleziona il box compressione e recupera il 90% dello spazio<BR>','');
INSERT INTO lang VALUES ('director','it','Regista','');
INSERT INTO lang VALUES ('directors','it','Registi','');
INSERT INTO lang VALUES ('directors_list','it','Lista dei registi','');
INSERT INTO lang VALUES ('director_person','it','Produttore/direttore','');
INSERT INTO lang VALUES ('director_persons','it','Produttori/direttori','');
INSERT INTO lang VALUES ('disktype_add_failed','it','Attenzione, non posso aggiungere il nuovo tipo di disco','');
INSERT INTO lang VALUES ('disktype_change','it','Cambia tipo di disco','');
INSERT INTO lang VALUES ('disktype_contains_media','it','Il tipo di disco non può essere cancellato in questo momento in quanto i seguenti componenti risultano ancora collegati/attivi','');
INSERT INTO lang VALUES ('disktype_name_empty','it','Il nome del tipo di disco non deve essere vuoto. Per cortesia torna indietro e correggi l\'errore #%1.','');
INSERT INTO lang VALUES ('disktype_update_failed','it','Spiacente, non sono in grado di aggiornare il seguente tipo di disco','');
INSERT INTO lang VALUES ('disk_size','it','Capacita\' del disco','');
INSERT INTO lang VALUES ('disk_type','it','Tipo di disco','');
INSERT INTO lang VALUES ('display','it','Mostra','');
INSERT INTO lang VALUES ('display_limit','it','Numero max risultati da mostrare','');
INSERT INTO lang VALUES ('display_limit_comment','it','(quante righe mostrare per ogni pagina per lista)','');
INSERT INTO lang VALUES ('dl_pvp_latest','it','Versione D/L  piu\' recente','');
INSERT INTO lang VALUES ('dupes','it','Voci doppie','');
INSERT INTO lang VALUES ('dupe_id_entered','it','Nel database e\' gia\'presente una voce relativa all\'ID del supporto inserito. Per cortesia premi il tasto \"Indietro\" del tuo browser e correggi i dati immessi. Suggerimento: vicino al campo di immissione in cui hai specificato il numero del supporto c\'e\' un Box di selezione. Questo box di selezione ti indica il numero massimo di film inseriti. Generalmente e\' buona norma, per un nuovo supporto incrementare il primo (4 cifre) di uno o, per un nuovo film dello stesso supporto aumentare il secondo (2 cifre) numero di uno.','');
INSERT INTO lang VALUES ('dupe_titles_found','it','Trovato %1 titolo con possibili duplicati:','');
INSERT INTO lang VALUES ('edit','it','Mostra','');
INSERT INTO lang VALUES ('edit_entry','it','Mostra la scelta %1','');
INSERT INTO lang VALUES ('enable_cookies','it','Abilito i cookies?','');
INSERT INTO lang VALUES ('enable_cookies_comment','it','Possono le preferenze dell\'utente( per es il settaggio dei filtri ) essere gestite con i cookies?','');
INSERT INTO lang VALUES ('ended_sessions','it','Sessione terminata','');
INSERT INTO lang VALUES ('enter_min_free','it','Inserisci il valore minimo di spazio libero da mostrare (del supporto)','');
INSERT INTO lang VALUES ('enter_new_medianr','it','Prego inserisci il numero supporto (MediaNr)  per questo nuovo %1','');
INSERT INTO lang VALUES ('expire_cookies','it','Durata cookies','');
INSERT INTO lang VALUES ('expire_cookies_comment','it','Per quanto tempo deve restare un cookie nel browser dell\'utente?','');
INSERT INTO lang VALUES ('farbe','it','Colore','');
INSERT INTO lang VALUES ('filter','it','Filtro','');
INSERT INTO lang VALUES ('filter_setup','it','Setup filtro','');
INSERT INTO lang VALUES ('finnished','it','Terminato','');
INSERT INTO lang VALUES ('first_name','it','Nome','');
INSERT INTO lang VALUES ('format','it','Formato','');
INSERT INTO lang VALUES ('free','it','Libero','');
INSERT INTO lang VALUES ('free_space_on_media','it','I seguenti supporti hanno almeno %1 minuti di spazio libero utilizzabile.','');
INSERT INTO lang VALUES ('free_space_title','it','Spazio libero sul supporto','');
INSERT INTO lang VALUES ('fsk','it','PG','');
INSERT INTO lang VALUES ('general','it','Generale','');
INSERT INTO lang VALUES ('goto_entry','it','Vai direttamente alla immissione','');
INSERT INTO lang VALUES ('graphic_file','it','File grafico','');
INSERT INTO lang VALUES ('help','it','Aiuto','');
INSERT INTO lang VALUES ('help_about','it','Aiuto su','');
INSERT INTO lang VALUES ('highest_db_entries','it','Massimo valore inserito nel db','');
INSERT INTO lang VALUES ('history','it','Storia','');
INSERT INTO lang VALUES ('hit_back_to_correct','it','Premi il tasto \"indietro\" per correggere l\'errore','');
INSERT INTO lang VALUES ('hour','it','Ora','');
INSERT INTO lang VALUES ('hours','it','Ore','');
INSERT INTO lang VALUES ('howto','it','Come..','');
INSERT INTO lang VALUES ('howto_help','it','Come creare un file d\'aiuto','');
INSERT INTO lang VALUES ('howto_label','it','Come creare/configurare le maschere per le etichette','');
INSERT INTO lang VALUES ('howto_lang','it','Come creare un file per una nuova lingua','');
INSERT INTO lang VALUES ('howto_templates','it','Come creare nuove maschere','');
INSERT INTO lang VALUES ('imdb_url','it','sito IMBD da usare','');
INSERT INTO lang VALUES ('imdb_url_comment','it','L\'Intenet Movies DataBase fornisce imformazioni su molti film. Ci sono siti locali disponibili: per esempio il sito tedesco permette al ricerca di film in lingia tedesca, mentre il sito US permette ricerche di titoli in inglese. Seleziona il sito piu\' appropriato ai titoli del tuo database.','');
INSERT INTO lang VALUES ('imp_errors','it','Importati %2 records terminato con %1 errori','');
INSERT INTO lang VALUES ('imp_success','it','Trasferimento di %1 records avvenuto con successo','');
INSERT INTO lang VALUES ('incomplete_date','it','Se non conosci la data esatta,ma - per esempio - solo che lo hai acquistato nel 2000, inserisci degli zero al posto delle date che non ricordi - nel nostro esempio il risultato sara\' \"00\" \"00\" \"2000\"','');
INSERT INTO lang VALUES ('index','it','Indice','');
INSERT INTO lang VALUES ('info_common','it','Informazioni comuni','');
INSERT INTO lang VALUES ('info_common_info','it','<DIV ALING=\"center\"> Questa e\' la %1 versione di phpVideoPro, in esecuzione su %2 </div>','');
INSERT INTO lang VALUES ('info_noupdate','it','<DIV ALING=\"center\">La versione installata di phpVideoPro (%1) e\' aggiornata - non ci sono nuove versioni disponibili per il download. Per scaricare il tarball della versione installata prego vai a <A HREF=\"http://www.qumran.org/homes/izzy/software/get_update.php?program=pvp\" TARGET=\"_blank\">this link</A>.</DIV>','');
INSERT INTO lang VALUES ('info_update','it','Informazioni sull\'aggiornamento','');
INSERT INTO lang VALUES ('intro','it','Intro','');
INSERT INTO lang VALUES ('intro_usage','it','<P>Qui ci sono alcune informazioni per i  nuovi utenti:<ul><li>La navigazione e\' sempre possibile usanto il menu\'presente in cima alle pagine</li><li>La maggior parte delle pagine sono dotate di una schermata di aiuto. Puoi consultarla usando il menu\' di aiuto oppure (quando disponibile) il tasto \"?\"</li><li>Il modulo sottostante ti permette di andare direttamente ad un film se conosci il numero del supporto. Altrimenti e\' preferibile usare l\'elenco dei media (MediaList) (disponibile dal menu\' \"Vedi\") o il modulo di ricerca (Menu \"Mostra\")/li></ul></P>','');
INSERT INTO lang VALUES ('intro_usage_skip','it','<P> Se non desideri piu\' consultare questo testo introduttivo in futuro puoi disattivarlo usando la relativa opzione nella pagina delle preferenze (vedi  il  menu\'\"edita\")</p>','');
INSERT INTO lang VALUES ('intro_usage_title','it','Introduzione per i nuovi utenti','');
INSERT INTO lang VALUES ('invalid_backup_dir','it','La directory di backup configurata non esiste!','');
INSERT INTO lang VALUES ('invalid_fsk','it','Il valore immesso per PG (\"%1\") non e\' valido. PG significa Parental Guide (Sorveglianza Genitori) per esempio l\'eta\' minima al disotto della quale il film non si pio\' vedere (es. film vietato min. 14 anni)','');
INSERT INTO lang VALUES ('invalid_media_nr','it','Il numero del supporto che hai specificato o e\' incompleto o non e\' valido. Devi specificare un <b>numero<b> in <b> entrambi i campi.','');
INSERT INTO lang VALUES ('in_list','it','nella Lista','');
INSERT INTO lang VALUES ('is_rw','it','Rescrivibile','');
INSERT INTO lang VALUES ('label','it','Etichetta','');
INSERT INTO lang VALUES ('labels','it','Etichette','');
INSERT INTO lang VALUES ('labeltype','it','Tipo do etichetta','');
INSERT INTO lang VALUES ('language_settings','it','Settaggio della lingua','');
INSERT INTO lang VALUES ('lang_aa','it','Afar','');
INSERT INTO lang VALUES ('lang_ab','it','Abkhazian','');
INSERT INTO lang VALUES ('lang_af','it','Africano','');
INSERT INTO lang VALUES ('lang_am','it','Amharic','');
INSERT INTO lang VALUES ('lang_ar','it','Arabo','');
INSERT INTO lang VALUES ('lang_as','it','Assamese','');
INSERT INTO lang VALUES ('lang_ay','it','Aymara','');
INSERT INTO lang VALUES ('lang_az','it','Azerbaigiano','');
INSERT INTO lang VALUES ('lang_ba','it','Bashkir','');
INSERT INTO lang VALUES ('lang_be','it','Bielorusso','');
INSERT INTO lang VALUES ('lang_bg','it','Bulgaro','');
INSERT INTO lang VALUES ('lang_bh','it','Bihari','');
INSERT INTO lang VALUES ('lang_bi','it','Bislama','');
INSERT INTO lang VALUES ('lang_bn','it','Bengali','');
INSERT INTO lang VALUES ('lang_bo','it','Tibetano','');
INSERT INTO lang VALUES ('lang_br','it','Bretone','');
INSERT INTO lang VALUES ('lang_ca','it','Catalano','');
INSERT INTO lang VALUES ('lang_co','it','Corso','');
INSERT INTO lang VALUES ('lang_cs','it','Ceco','');
INSERT INTO lang VALUES ('lang_cy','it','Scozzese','');
INSERT INTO lang VALUES ('lang_da','it','Danese
 ','');
INSERT INTO lang VALUES ('lang_de','it','Tedesco','');
INSERT INTO lang VALUES ('lang_dz','it','Bhutani','');
INSERT INTO lang VALUES ('lang_el','it','Greco','');
INSERT INTO lang VALUES ('lang_en','it','Inglese','');
INSERT INTO lang VALUES ('lang_eo','it','Esperanto','');
INSERT INTO lang VALUES ('lang_es','it','Spagnolo','');
INSERT INTO lang VALUES ('lang_et','it','Estone','');
INSERT INTO lang VALUES ('lang_eu','it','Basco','');
INSERT INTO lang VALUES ('lang_fa','it','Persiano','');
INSERT INTO lang VALUES ('lang_fi','it','Finlandese','');
INSERT INTO lang VALUES ('lang_fj','it','Fiji','');
INSERT INTO lang VALUES ('lang_fo','it','Faeroese','');
INSERT INTO lang VALUES ('lang_fr','it','Francese','');
INSERT INTO lang VALUES ('lang_fy','it','Frisian','');
INSERT INTO lang VALUES ('lang_ga','it','Irlandese','');
INSERT INTO lang VALUES ('lang_gd','it','Gaelico','');
INSERT INTO lang VALUES ('lang_gl','it','Gaelician','');
INSERT INTO lang VALUES ('lang_gn','it','Guarani','');
INSERT INTO lang VALUES ('lang_gu','it','Guajarati','');
INSERT INTO lang VALUES ('lang_ha','it','Hausa','');
INSERT INTO lang VALUES ('lang_hi','it','Hindi','');
INSERT INTO lang VALUES ('lang_hr','it','Croato','');
INSERT INTO lang VALUES ('lang_hu','it','Ungherese','');
INSERT INTO lang VALUES ('lang_hy','it','Armeno','');
INSERT INTO lang VALUES ('lang_ia','it','Interlingua','');
INSERT INTO lang VALUES ('lang_ie','it','Interlingue','');
INSERT INTO lang VALUES ('lang_ik','it','Inupiak','');
INSERT INTO lang VALUES ('lang_in','it','Indonese','');
INSERT INTO lang VALUES ('lang_is','it','Icelandic','');
INSERT INTO lang VALUES ('lang_it','it','Italiano','');
INSERT INTO lang VALUES ('lang_iw','it','Ebreo','');
INSERT INTO lang VALUES ('lang_ja','it','Giapponese','');
INSERT INTO lang VALUES ('lang_ji','it','Yiddish','');
INSERT INTO lang VALUES ('lang_jw','it','Javanese','');
INSERT INTO lang VALUES ('lang_ka','it','Georgian','');
INSERT INTO lang VALUES ('lang_kk','it','Kazalh','');
INSERT INTO lang VALUES ('lang_kl','it','Greenlandic','');
INSERT INTO lang VALUES ('lang_km','it','Cambogiano','');
INSERT INTO lang VALUES ('lang_kn','it','Kannada','');
INSERT INTO lang VALUES ('lang_ko','it','Coreano','');
INSERT INTO lang VALUES ('lang_ks','it','Kashmiri','');
INSERT INTO lang VALUES ('lang_ku','it','Curdo','');
INSERT INTO lang VALUES ('lang_ky','it','Kirghiz','');
INSERT INTO lang VALUES ('lang_la','it','Latino','');
INSERT INTO lang VALUES ('lang_ln','it','Lingala','');
INSERT INTO lang VALUES ('lang_lo','it','Laothian','');
INSERT INTO lang VALUES ('lang_lt','it','Lituano','');
INSERT INTO lang VALUES ('lang_lv','it','Latvian','');
INSERT INTO lang VALUES ('lang_mg','it','Malagasy','');
INSERT INTO lang VALUES ('lang_mi','it','Maori','');
INSERT INTO lang VALUES ('lang_mk','it','Macedone','');
INSERT INTO lang VALUES ('lang_ml','it','Malayalam','');
INSERT INTO lang VALUES ('lang_mn','it','Mongolo','');
INSERT INTO lang VALUES ('lang_mo','it','Moldavo','');
INSERT INTO lang VALUES ('lang_mr','it','Marathi','');
INSERT INTO lang VALUES ('lang_ms','it','Malay','');
INSERT INTO lang VALUES ('lang_mt','it','Maltese','');
INSERT INTO lang VALUES ('lang_my','it','Burnese','');
INSERT INTO lang VALUES ('lang_na','it','Mauru','');
INSERT INTO lang VALUES ('lang_ne','it','Nepalese','');
INSERT INTO lang VALUES ('lang_nl','it','Dutch','');
INSERT INTO lang VALUES ('lang_no','it','Norvegese','');
INSERT INTO lang VALUES ('lang_oc','it','Occitano','');
INSERT INTO lang VALUES ('lang_om','it','Oromo','');
INSERT INTO lang VALUES ('lang_or','it','Oriya','');
INSERT INTO lang VALUES ('lang_pa','it','Punjabi','');
INSERT INTO lang VALUES ('lang_pl','it','Polacco','');
INSERT INTO lang VALUES ('lang_ps','it','Pashto','');
INSERT INTO lang VALUES ('lang_pt','it','Portoghese','');
INSERT INTO lang VALUES ('lang_qu','it','Quechua','');
INSERT INTO lang VALUES ('lang_rm','it','Rhaeto-Romance','');
INSERT INTO lang VALUES ('lang_rn','it','Kirundi','');
INSERT INTO lang VALUES ('lang_ro','it','Romanian','');
INSERT INTO lang VALUES ('lang_ru','it','Russo','');
INSERT INTO lang VALUES ('lang_rw','it','Kinyarwanda','');
INSERT INTO lang VALUES ('lang_sa','it','Sanscrito','');
INSERT INTO lang VALUES ('lang_sd','it','Sindhi','');
INSERT INTO lang VALUES ('lang_sg','it','Sangro','');
INSERT INTO lang VALUES ('lang_sh','it','Serbo-croato','');
INSERT INTO lang VALUES ('lang_si','it','Singalese','');
INSERT INTO lang VALUES ('lang_sk','it','Slovacco','');
INSERT INTO lang VALUES ('lang_sl','it','Sloveno','');
INSERT INTO lang VALUES ('lang_sm','it','Samoan','');
INSERT INTO lang VALUES ('lang_sn','it','Shona','');
INSERT INTO lang VALUES ('lang_so','it','Somalo','');
INSERT INTO lang VALUES ('lang_sq','it','Albanese','');
INSERT INTO lang VALUES ('lang_sr','it','Serbo','');
INSERT INTO lang VALUES ('lang_ss','it','Siswati','');
INSERT INTO lang VALUES ('lang_st','it','Sesotho','');
INSERT INTO lang VALUES ('lang_su','it','Sudanese','');
INSERT INTO lang VALUES ('lang_sv','it','Svedese','');
INSERT INTO lang VALUES ('lang_sw','it','Swahili','');
INSERT INTO lang VALUES ('lang_ta','it','Tamil','');
INSERT INTO lang VALUES ('lang_te','it','Tegulu','');
INSERT INTO lang VALUES ('lang_tg','it','Tajik','');
INSERT INTO lang VALUES ('lang_th','it','Thai','');
INSERT INTO lang VALUES ('lang_ti','it','Tirinya','');
INSERT INTO lang VALUES ('lang_tk','it','Turkmen','');
INSERT INTO lang VALUES ('lang_tl','it','Tatalog','');
INSERT INTO lang VALUES ('lang_tn','it','Setswana','');
INSERT INTO lang VALUES ('lang_to','it','Tonga','');
INSERT INTO lang VALUES ('lang_tr','it','Turco','');
INSERT INTO lang VALUES ('lang_ts','it','Tsonga','');
INSERT INTO lang VALUES ('lang_tt','it','Tatar','');
INSERT INTO lang VALUES ('lang_tw','it','Twi','');
INSERT INTO lang VALUES ('lang_uk','it','Ucraino','');
INSERT INTO lang VALUES ('lang_ur','it','Urdu','');
INSERT INTO lang VALUES ('lang_uz','it','Uzbeco','');
INSERT INTO lang VALUES ('lang_vi','it','Vietnamita','');
INSERT INTO lang VALUES ('lang_vo','it','Volapuk','');
INSERT INTO lang VALUES ('lang_wo','it','Wolof','');
INSERT INTO lang VALUES ('lang_xh','it','Xhosa','');
INSERT INTO lang VALUES ('lang_yo','it','Yoruba','');
INSERT INTO lang VALUES ('lang_zh','it','Cinese','');
INSERT INTO lang VALUES ('lang_zu','it','Zulu','');
INSERT INTO lang VALUES ('last_entry','it','Ultina immissione','');
INSERT INTO lang VALUES ('last_medianr','it','Il numero massino inserito per questo supporto è attualmente:','');
INSERT INTO lang VALUES ('layout_label','it','Scegli l\'impaginazione','');
INSERT INTO lang VALUES ('left_offset','it','Margine sinistro','');
INSERT INTO lang VALUES ('length','it','Durata','');
INSERT INTO lang VALUES ('lines_per_page','it','Linee (righe) per pagina','');
INSERT INTO lang VALUES ('lines_per_page_comment','it','Riguarda la funzione di stampa che determina il numero di righe di testo presenti in una pagina.','');
INSERT INTO lang VALUES ('line_count','it','Righe','');
INSERT INTO lang VALUES ('list','it','Elenco','');
INSERT INTO lang VALUES ('listgen','it','Genera elenco','');
INSERT INTO lang VALUES ('lists','it','Elenchi','');
INSERT INTO lang VALUES ('locale','it','Locale','');
INSERT INTO lang VALUES ('login','it','Login','');
INSERT INTO lang VALUES ('login_failed','it','Login non andato a buon fine: o hai sbagliato la password o l\'account richiesto non esiste.','');
INSERT INTO lang VALUES ('login_required','it','Non hai sufficienti privilegi per compiere l\'azione richiesta. Ora puoi connetterti con il giusto account <p/>','');
INSERT INTO lang VALUES ('logout_user','it','Sei collegato come \"%1\" <A HREF=\"%2\">Esci</A>','');
INSERT INTO lang VALUES ('longplay','it','LongPlay(lunga durata)','');
INSERT INTO lang VALUES ('lower_left_corner','it','Angolo in basso a sinistra (x/y)','');
INSERT INTO lang VALUES ('max','it','Max','');
INSERT INTO lang VALUES ('max_fontsize','it','Dimensione massima font','');
INSERT INTO lang VALUES ('media','it','Supporti','');
INSERT INTO lang VALUES ('medialength','it','Durata del supporto','');
INSERT INTO lang VALUES ('medialist','it','Elenco generale','');
INSERT INTO lang VALUES ('medialist_alpha','it','Elenco generale in ordine alfabetico','');
INSERT INTO lang VALUES ('medialist_num','it','Elenco generale in ordine numerico','');
INSERT INTO lang VALUES ('medianr','it','NumeroSupporto','');
INSERT INTO lang VALUES ('mediatype','it','Tipo supporto','');
INSERT INTO lang VALUES ('media_change','it','Cambia numero supporto','');
INSERT INTO lang VALUES ('media_copy','it','Copia dati sul supporto numero','');
INSERT INTO lang VALUES ('medium','it','Supporto','');
INSERT INTO lang VALUES ('medium_deleted','it','Nessun film in questo supporto - supporto rimosso','');
INSERT INTO lang VALUES ('medium_not_deleted','it','Supporto non rimosso','');
INSERT INTO lang VALUES ('medium_overview','it','Elenco generale per %1','');
INSERT INTO lang VALUES ('menues','it','Menu','');
INSERT INTO lang VALUES ('min','it','minimo','');
INSERT INTO lang VALUES ('minute_abbrev','it','minuti','');
INSERT INTO lang VALUES ('month','it','Mese','');
INSERT INTO lang VALUES ('movies','it','Film','');
INSERT INTO lang VALUES ('movies_left_in_cat','it','La categoria %1 contiene ancora %2 film(s) e quindi non puo\' essere rimossa.','');
INSERT INTO lang VALUES ('movies_left_reference','it','Questa voce non puo\' esere cancellata: ci sono %1 film(s) che fanno riferimento ad essa.','');
INSERT INTO lang VALUES ('movie_color_default','it','Colore di default per un film','');
INSERT INTO lang VALUES ('movie_color_default_comment','it','Questo sara\'  usato cone colore pre-settato per una nuova voce','');
INSERT INTO lang VALUES ('movie_onlabel_default','it','Default per l\'etichetta del film','');
INSERT INTO lang VALUES ('movie_onlabel_default_comment','it','Default per nuove voci inserite: le informazioni su questo film possono essere inserite quando vengono generate l\'etichetta(e) per questo supporto?','');
INSERT INTO lang VALUES ('movie_tone_default','it','Suono di default per un film','');
INSERT INTO lang VALUES ('movie_tone_default_comment','it','Questo sara\'  usato cone suono pre-settato per una nuova voce','');
INSERT INTO lang VALUES ('music','it','Compositore (colonna sonora)','');
INSERT INTO lang VALUES ('music_list','it','Elenco compositori','');
INSERT INTO lang VALUES ('name','it','nome','');
INSERT INTO lang VALUES ('never','it','mai','');
INSERT INTO lang VALUES ('new_disktype','it','Nuovo tipo di Disco','');
INSERT INTO lang VALUES ('new_medianr','it','Nuovo numeroSupporto','');
INSERT INTO lang VALUES ('new_movie_on','it','Nuovo %1','');
INSERT INTO lang VALUES ('no','it','no','');
INSERT INTO lang VALUES ('nobody_named','it','Ci sono altri film  con questo %1 nome %2% %3 in questo db, quindi cancello questa voce dalla tabella %1','');
INSERT INTO lang VALUES ('none','it','Nessuno','');
INSERT INTO lang VALUES ('not_logged_in','it','non connesso','');
INSERT INTO lang VALUES ('not_ok','it','Fallito','');
INSERT INTO lang VALUES ('not_yet_implemented','it','Scusa.. non ancora implementato.','');
INSERT INTO lang VALUES ('no_add_lang','it','Non sono disponibili ulteriori lingue','');
INSERT INTO lang VALUES ('no_backup_avail','it','Non ci sono Backup disponibili da cui ricaricare i dati','');
INSERT INTO lang VALUES ('no_entries_found','it','Voce(i) non trovata(e)','');
INSERT INTO lang VALUES ('no_entry_in_tapelist','it','Errore - non trovate voci nell\'elenco nastri','');
INSERT INTO lang VALUES ('no_orphans_found','it','Complimenti! Smbra proprio che tu non abbia scheletri nell\'armadio!','');
INSERT INTO lang VALUES ('no_restore_file','it','Scusa: il file selezionato non esiste piu\' ','');
INSERT INTO lang VALUES ('no_space_of','it','Nel database non ho trovato supporti con un minimo di %1 minuti di spazio libero.','');
INSERT INTO lang VALUES ('nr','it','Num','');
INSERT INTO lang VALUES ('of_aquiration','it','di acquisizione','');
INSERT INTO lang VALUES ('ok','it','OK','');
INSERT INTO lang VALUES ('old_sessions','it','Sessione piu\' vecchia di  <INPUT NAME=\"%1\" VALUE=\"\" CLASS=\"yesnoinput\"> giorni','');
INSERT INTO lang VALUES ('orig_disktype','it','Tipo Originale del disco','');
INSERT INTO lang VALUES ('orig_medianr','it','NuneroSupprto originale','');
INSERT INTO lang VALUES ('orig_trans','it','Traduzione originale (%1)','');
INSERT INTO lang VALUES ('orphans_found','it','trovati %1 orfano(i)','');
INSERT INTO lang VALUES ('other_pages','it','Altre pagine','');
INSERT INTO lang VALUES ('password','it','Password','');
INSERT INTO lang VALUES ('password_retype','it','riscrivi la password','');
INSERT INTO lang VALUES ('picture','it','Tipo colore','');
INSERT INTO lang VALUES ('preferences','it','Preferenze','');
INSERT INTO lang VALUES ('print','it','Stampa','');
INSERT INTO lang VALUES ('printer','it','Stampante','');
INSERT INTO lang VALUES ('printer_add_failed','it','Si e\' verificato un errore nell\'aggiungere questa stampante','');
INSERT INTO lang VALUES ('printer_add_success','it','Stampante aggiunte con successo','');
INSERT INTO lang VALUES ('printer_comment','it','Se desideri stampare su di un modulo (come per etichette PS) e\' necessario conoscere il metodo ri stampa della tua stampante','');
INSERT INTO lang VALUES ('printer_name','it','Nome','');
INSERT INTO lang VALUES ('printer_upd_failed','it','Aggiornamento non andato a buon fine per le seguenti stampanti %1
  ','');
INSERT INTO lang VALUES ('print_label','it','Stampa etichetta:','');
INSERT INTO lang VALUES ('pslabel','it','Ps etichetta','');
INSERT INTO lang VALUES ('pstpl_name','it','Nome maschera','');
INSERT INTO lang VALUES ('pstpl_type','it','Tipo di maschera','');
INSERT INTO lang VALUES ('read_access','it','Puo\' esaminare le immissioni','');
INSERT INTO lang VALUES ('read_access_short','it','up','');
INSERT INTO lang VALUES ('recalc_free','it','Ricalcolo tempo libero rimanente su questo supporto','');
INSERT INTO lang VALUES ('refresh_lang','it','Refresh della lingua','');
INSERT INTO lang VALUES ('refresh_lang_comment','it','Reinserisci nel db le frasi dal file della lingua','');
INSERT INTO lang VALUES ('region_code','it','Codice Regione','');
INSERT INTO lang VALUES ('remove_empty_media','it','Rimuovi i supporti vuoti','');
INSERT INTO lang VALUES ('remove_empty_media_comment','it','Rimuovere i media per mantenimento spazio libero quando viene cancellato l\'ultimo film che in essi contenuto?','');
INSERT INTO lang VALUES ('reset','it','Resetta','');
INSERT INTO lang VALUES ('restore_db_internal','it','Ricarica da un file di backup PVP','');
INSERT INTO lang VALUES ('rw_media','it','Supporto registrabile','');
INSERT INTO lang VALUES ('rw_media_comment','it','Supporto da lasciare libero per (finche\' non vi registri qualcosa)','');
INSERT INTO lang VALUES ('s/w','it','b/n','');
INSERT INTO lang VALUES ('save_lang_file','it','Salva la traduzione in un file','');
INSERT INTO lang VALUES ('scan_new_lang_comment','it','(Se hai creato il file con la tua lingua e lo hai messo nella directory setup phpVideoPro lo trovera\')','');
INSERT INTO lang VALUES ('scan_new_lang_files','it','Cerco nuovi file lingua?','');
INSERT INTO lang VALUES ('screen','it','Formato schermo','');
INSERT INTO lang VALUES ('search','it','Cerca','');
INSERT INTO lang VALUES ('search_movie','it','CercaFilm','');
INSERT INTO lang VALUES ('select_add_lang','it','Seleziona un ulteriore lingua da installare','');
INSERT INTO lang VALUES ('select_add_lang_comment','it','(l\'Inglese e\' gia\' installato e lo sara\' sempre - vedi prossima voce: Per le altre lingue che sono gia\' isntallate vedi prossima voce)','');
INSERT INTO lang VALUES ('select_primary_lang','it','Seleziona lingua principale','');
INSERT INTO lang VALUES ('select_primary_lang_comment','it','(per le frasi mancanti ci sara\' sempre un ricorso all\'Inglese)','');
INSERT INTO lang VALUES ('sel_target_lang','it','Selezione lingua in cui tradurre','');
INSERT INTO lang VALUES ('session','it','Sessione','');
INSERT INTO lang VALUES ('session_expired','it','La tua sessione e\' terminata','');
INSERT INTO lang VALUES ('session_purgetime','it','Dopo quanto tempo devo chiudere una sessione','');
INSERT INTO lang VALUES ('session_purgetime_comment','it','Per quanto tempo una sessione deve rimanere attiva se non vi sono attivita\' dell\'utente','');
INSERT INTO lang VALUES ('sess_dla','it','Ultimo accesso','');
INSERT INTO lang VALUES ('sess_end','it','Terminato','');
INSERT INTO lang VALUES ('sess_id','it','ID sessione','');
INSERT INTO lang VALUES ('sess_ip','it','IP remoto','');
INSERT INTO lang VALUES ('sess_start','it','Partito','');
INSERT INTO lang VALUES ('set_filter','it','Seleziona un filtro','');
INSERT INTO lang VALUES ('site_info','it','info sito','');
INSERT INTO lang VALUES ('site_info_comment','it','Quali informazioni sul sito elencare nella barra superiore del browser','');
INSERT INTO lang VALUES ('skip_intro','it','Saltare l\'introduzione per principianti?','');
INSERT INTO lang VALUES ('skip_intro_comment','it','Se saltare il testo introduttivo sulla pagina iniziale','');
INSERT INTO lang VALUES ('source','it','Proveniente da','');
INSERT INTO lang VALUES ('staff','it','Staff','');
INSERT INTO lang VALUES ('start_page','it','Pagina iniziale','');
INSERT INTO lang VALUES ('start_pvp','it','Avvia phpVideoPro','');
INSERT INTO lang VALUES ('state_active','it','Attivo','');
INSERT INTO lang VALUES ('state_inactive','it','Inattivo','');
INSERT INTO lang VALUES ('stats','it','Statistiche','');
INSERT INTO lang VALUES ('stat_categories','it','Categorie (usate/tutte)','');
INSERT INTO lang VALUES ('stat_counts','it','Conteggi','');
INSERT INTO lang VALUES ('stat_ranks','it','Posizione','');
INSERT INTO lang VALUES ('submit','it','Inserisci','');
INSERT INTO lang VALUES ('subtitle','it','Sottotitoli','');
INSERT INTO lang VALUES ('sure_to_delete','it','Sei sicuro di voler cancellare tutti i dati per %1','');
INSERT INTO lang VALUES ('tapelist_update_failed','it','Aggiornamento lista nastri non andata a buon fine.','');
INSERT INTO lang VALUES ('taperest','it','Gestisci il tempo disponibile','');
INSERT INTO lang VALUES ('taperest_absolute','it','Tempo resante(assoluto)','');
INSERT INTO lang VALUES ('taperest_filtered','it','Tempo restante (filtrato)','');
INSERT INTO lang VALUES ('target_trans','it','Traduzione per la lingua scelta (%1)','');
INSERT INTO lang VALUES ('techdata','it','Dati tecnici','');
INSERT INTO lang VALUES ('template_file','it','File maschere','');
INSERT INTO lang VALUES ('template_set','it','Elenco maschere','');
INSERT INTO lang VALUES ('time_left','it','rimangono %1 minuti','');
INSERT INTO lang VALUES ('title','it','Titolo','');
INSERT INTO lang VALUES ('tone','it','Formato audio','');
INSERT INTO lang VALUES ('top_offset','it','Margine superiore','');
INSERT INTO lang VALUES ('tplset_applicat','it','Applicat elenco maschere','');
INSERT INTO lang VALUES ('trans_code','it','Codice traduzione','');
INSERT INTO lang VALUES ('unit','it','Unita\' ','');
INSERT INTO lang VALUES ('unknown','it','Sconosciuto','');
INSERT INTO lang VALUES ('unset_filter','it','Deseleziona filtri','');
INSERT INTO lang VALUES ('update','it','Aggiorna','');
INSERT INTO lang VALUES ('update_failed','it','Aggiornamento voce non riuscito','');
INSERT INTO lang VALUES ('update_success','it','Modifica voce riuscita','');
INSERT INTO lang VALUES ('upd_access','it','Puo\' aggiornare le voci esistenti','');
INSERT INTO lang VALUES ('upd_access_short','it','agg','');
INSERT INTO lang VALUES ('upper_right_corner','it','Agolo superiore destro (x/y)','');
INSERT INTO lang VALUES ('user','it','Utente','');
INSERT INTO lang VALUES ('user_create_login_required','it','Devi specificare un nome utente!','');
INSERT INTO lang VALUES ('user_deleted','it','Utente %1, \"%2\" (%3) cancellato con successo!','');
INSERT INTO lang VALUES ('user_delete_failed','it','La cancellazione dell\'utente #%1, \"%2\" (%3) non e\' andata a buon fine!','');
INSERT INTO lang VALUES ('user_delete_report','it','Risultati del processo di cancellazione utenti.','');
INSERT INTO lang VALUES ('user_update_failed','it','Aggiornamento non adato a buon fine per i seguenti utenti: %1','');
INSERT INTO lang VALUES ('view','it','Vedi','');
INSERT INTO lang VALUES ('view_entry','it','Nostra voce %1','');
INSERT INTO lang VALUES ('warning','it','Attenzione','');
INSERT INTO lang VALUES ('week','it','Settimana','');
INSERT INTO lang VALUES ('welcome','it','Benvenuto in phpVideoPro','');
INSERT INTO lang VALUES ('wrong_date','it','La data %1 che hai specificato (%2) non e\' valida. Quando inserisci una data devi inserire  il giorno nel primo , il mese nel secondo e l\'anno nel terzo campo ed usare solo numeri. Se non conosci esattamente la data inserisci degli zero nei campi in questione. es.\"00\" \"02\"  \"2002\" significa porbabilmente in febbraio o \"00\" \"00\" \"0000\" significa \"qualche volta\"','');
INSERT INTO lang VALUES ('xfer_unknown_filetype','it','Questo tipo di file di Backup non e\' supportato da phpVideoPro','');
INSERT INTO lang VALUES ('xfer_wrong_mode','it','Errore del programma. Sei in una modalita\' errata per l\'operazione richiesta. La modalita\' richiesta e\'\" %1\", quella attuale e\' \"%2\". Per cortesia riporta all\'autore i dettagli di quanto successo.','');
INSERT INTO lang VALUES ('year','it','Anno','');
INSERT INTO lang VALUES ('yes','it','Si','');
