# MySQL table created by DBV

# delete table if already exists
DROP TABLE IF EXISTS bemerk;

# create a new table
CREATE table bemerk (
       FILMNR Char(7),
       BEMERK01 Char(70),
       BEMERK02 Char(70),
       BEMERK03 Char(70),
       BEMERK04 Char(70),
       BEMERK05 Char(70),
       BEMERK06 Char(70),
       BEMERK07 Char(70),
       BEMERK08 Char(70),
       BEMERK09 Char(70),
       BEMERK10 Char(70),
       BEMERK11 Char(70),
       BEMERK12 Char(70),
       BEMERK13 Char(70),
       BEMERK14 Char(70),
       BEMERK15 Char(70),
       BEMERK16 Char(70),
       BEMERK17 Char(70),
       BEMERK18 Char(70),
       BEMERK19 Char(70),
       BEMERK20 Char(70),
       BEMERK21 Char(70),
       BEMERK22 Char(70),
       BEMERK23 Char(70),
       BEMERK24 Char(70),
       BEMERK25 Char(70),
       BEMERK26 Char(70),
       BEMERK27 Char(70),
       BEMERK28 Char(70),
       BEMERK29 Char(70),
       BEMERK30 Char(70),
       BEMERK31 Char(70),
       BEMERK32 Char(70),
       BEMERK33 Char(70),
       BEMERK34 Char(70),
       BEMERK35 Char(70),
       BEMERK36 Char(70),
       BEMERK37 Char(70),
       BEMERK38 Char(70),
       BEMERK39 Char(70),
       BEMERK40 Char(70),
       BEMERK41 Char(70),
       BEMERK42 Char(70),
       BEMERK43 Char(70),
       BEMERK44 Char(70),
       BEMERK45 Char(70),
       BEMERK46 Char(70),
       BEMERK47 Char(70),
       BEMERK48 Char(70),
       BEMERK49 Char(70),
       BEMERK50 Char(70),
       BEMERK51 Char(70)
);

INSERT into bemerk Values ('0001-02','Man schreibt das Jahr 2019. StÑrker als es vielleicht','bereits heute der Fall ist, wird das Leben der Menschen','von den Medien beeinflu·t, die ihre Macht zur Unter-','stÅtzung einer diktatorischen Regierung einsetzen. Es','lassen sich durchaus Parallelen zu George Orwells \"1984\"','erkennen.','','Der Film ist eine Mischung aus Humor, Gewalt und - z.T.','brutalen - Action- Szenen.','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0003-01','Originaltitel: The Voyage Home','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0004-01','Nach einem Roman von H.G.Wells','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0006-01','Originaltitel: Enemy Mine','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0035-02','Englisches Original mit HollÑndischen Untertiteln','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0012-06','Untertitel: Die Ausbildung von Traditionen.','Stichworte: Mischna, Talmud, Rom, Byzanz, NazorÑer','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0013-02','Die Geschichte von Joseph und seinen BrÅdern als','Comic-Strip. \"Bibelstunde\" mit Witz und Pep!','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0018-01','\"Im Jahr 2017 ist die wahre Liebe nur Nostalgie. Der Mann','der Zeit  bevorzugt  die Kurven  eines vollelektronischen','Playmates,  das sich  Ñu·erlich  von einer richtigen Frau','nicht unterscheidet.  DafÅr  ist es bequem  und jederzeit','gefÅgig. Sam vergnÅgt sich mit Cherry 2000, bis sie eines','Tages durch einen unglÅcklichen Zustand Geist und GefÅhle','aufgibt. Sam macht sich auf die Suche... [nach einer neu-','en Cherry] ... und  trifft dabei  auf das Vollblutweib E.','Johnson. Mit ihr entdeckt er die lÑngst verloren geglaub-','te Liebe.','In Steve Jarnatts Endzeitvision spielt  David Andrews den','Mann auf der Suche nach einer Frau  aus Fleisch und Blut.','Dabei trifft er auf die kampflustigen, wohlgeformten Ama-','zonen  Melanie Griffith  und  \"Miss Welt  1985\",   Pamela','Gidley.\"','(aus: TV Movie 3/92)','Originaltitel: Cherry 2000','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0020-01','Originaltitel: Spacehunter - Adventures in the forbidden','Zone','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0007-14','vollstÑndig','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0007-15','vollstÑndig','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0020-02','Originaltitel: Damnation Alley','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0022-01','Rekonstruierte jiddische Originalfassung von 1937','(Originaltitel: Der Dybbuk) mit deutschen Untertiteln.','','Dieser Film gibt einen Einblick in das Leben chassidi-','scher Juden im alten Polen, sowohl was ihr Alltagsleben','als auch was ihre Ideenwelt betrifft.','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0023-01','\"Claude Lanzmanns Film  beschÑftigt sich  komromi·los mit','dem Unvorstellbaren,  der  Vernichtung  der  europÑischen','Juden wÑhrend des zweiten Weltkrieges.','Keine Archivaufnahmen von den Konzentrationslagern, dafÅr','Aussagen  von Åberlebenden Opfern des Holocaust,  die bis','an die Grenzen des ErtrÑglichen befragt werden.\"','(Nordtext)','','Original mit deutschen Untertiteln','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0024-01','Siehe 0023-01, \"Shoah I\". Der gesamte Dokumentarfilm','umfa·t 9 Stunden Sendezeit.','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0019-02','\"Man schreibt  das Jahr  2038.  Intergalaktische Konzerne','kÑmpfen  erbittert   um  wertvolle  Rohstoffmonde.    Der','Sicherheitsbeauftragte Felix Stone  soll das Verschwinden','von Fîrderrobotern auf dem Erzplaneten Moon 44 aufklÑren.','Dabei gerÑt er in ein gefÑhrliches Abenteuer...','Der 1989 entstandene Spielfilm  von  Roland Emmerich  ist','ein spannendes Science-Fiction-Abenteuer  mit brillianten','Spezialeffekten. [...]\"','(Videotext der ARD vom 14.03.1992)','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0023-02','\"Der Schriftsteller und Journalist  Ralph Giordano  zieht','Verbindung  zwischen  dem Holocaust  und der aufkommenden','AuslÑnderfeindlichkeit:  \''Ich habe nicht gedacht, da· wir','uns 1991  Åber all das  noch unterhalten mÅssen  und  da·','hier sogar  ein neuer Ausbruch von Fremdenha·,  von','Anti-semitismus, von Rassismus spÅrbar wird wie jetzt.\''\"','(Nordtext, 14.03.1992)','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0012-07','ausgehendes Mittelalter:','Spanien und Auszug aus Spanien; Amsterdam','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0026-01','englisches Original des Eddie- Murphy- Filmes \"Der Prinz','von Zamunda\". D.h.: Das \"Plappermaul\" ist hier unsynchro-','nisiert zu hîren!','','\"Der \''Prinz von Zamunda\'' reist inkognito in die Staaten,','um seine Traumfrau zu finden. Einmalige Gelegenheit,','Eddie Murphy\''s Mundwerk im unsynchronisierten Originalton','zu erleben.\"','(TV Spielfilm 6/92)','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0027-02','Originaltitel: Short Circuit 2','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0026-02','Engl. Original mit hollÑndischen Untertiteln','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0028-01','Englische Originalfassung mit niederlÑndischen','Untertiteln.','','Der Film entstand auf Grundlage des Buches \"Yentl, the','yeshiva boy\" von Isaac Bashevis Singer.','','Die AufnahmequalitÑt (visuell) ist zwar nicht','berauschend, der Film jedoch absolut sehenswert!','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0022-02','Jiddische Originalfassung mit deutschen Untertiteln.','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0030-01','Deutsche Fassung des amerikanischen Dramas \"The','Execution\".','','FÅnf Frauen, die das KZ Åberlebt haben, nehmen 40 Jahre','spÑter Rache an einem Nazi.','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0006-09','Mit eingeblendeten Info\''s Åber Shanice\''s \"Werdegang\"','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0010-02','Originaltitel: La collera del vento','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0033-02','Originaltitel: Beyond the Rising Moon','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0034-01','englische Originalfassung mit niederlÑndischen','Untertiteln.','Ende bei Timer 5056','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0029-02','Terence Hill spielt in diesem Film noch unter seinem','\"alten Namen\", Mario Girotti, mit.','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0014-02','Englische Originalfassung mit niederlÑndischen Unter-','titeln.','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0019-03','Lifemitschnitte sowie Videoclips von und mit AndrÇ Heller','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0036-01','Das \"Gleichnis vom verlorenen Sohn\" in ausgebauter Form.','','Originaltitel: The Prodigal','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0037-01','O: Robin Hood, Price of Thieves','','','','.','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0038-01','Originaltitel: Something Is Out There','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0039-01','Originaltitel: Raiders of the Lost Ark','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0039-02','Originaltitel: Indiana Jones and the Temple of Doom','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0040-01','Originaltitel: Good Morning, Vietnam','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0040-02','Originaltitel: Solarbabies','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0041-01','englische Originalfassung, wahrscheinlich nur leicht','gekÅrzt. Was in der deutschen Fassung fehlt, findet sich','hier - und umgekehrt. Beides zusammen ist dann vielleicht','vollstÑndig...','','Mitschnitt vom Channel XIX, New York. Kopie erhalten von:','Matthias Hîfchen, Buckower Damm 282, 1/47.','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0042-01','Pilotfilm zur Serie.','Originaltitel: The Curse of the Jackal','Produktion: George Lukas','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0043-01','Originaltitel: Cercasi gesó / L\''imposteur','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0044-01','Originaltitel: King of Kings','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0045-01','Originaltitel: King David','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0046-01','Originaltitel: Diamonds are forever','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0047-01','Originaltitel: Remo Williams: The Adventure Begins','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0048-01','Originaltitel: The Chosen','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0049-01','Zypern 1947: Rund 30.000 Juden sitzen hinter Stacheldraht','- die britische Regierung  verweigert ihnen  die Einreise','nach PalÑstina...','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0046-02','Originaltitel: The Spy Who Loved Me','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0047-02','Originaltitel: Live and Let Die','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0015-02','Originaltitel: Blade Runner','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0034-02','Originaltitel: Outland','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0052-01','Originaltitel: Brainstorm','Breitbildformat','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0048-02','\"Der alte Rabbiner Abraham (Shai K. Ophir) lebt mit sei-','ner Frau in einem Garten, der mit Hotelkloake bewÑssert','wird. Abraham hÑlt dieses zweifelhafte Paradies fÅr das','Zuhause eines Engels. Der vermeintliche Engel (Melanie','Griffith) ist ein junges MÑdchen, das vor einer Gruppe','Halbstarker in den Garten des Alten geflohen ist.','Die anspruchsvolle und unterhaltende Satire vermittelt','au·erdem auch einen Einblick in die Vorstellungswelt und','Kultur der orthodoxen Juden.\" (Videotext)','','Originaltitel: HaGan.','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0051-02','Originaltitel: Earth Star Voyager','','Beanie: Jason Michas','Sally : Julia Montgomery','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0050-02','Originaltitel: A View to a Kill','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0005-02','Originaltitel: The Empire Strikes Back','Erste Aufnahme in Mono vom 12.01.1992 (SAT*1) ausgetauscht','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0005-01','Originaltitel: Star Wars','Erstaufnahme in Mono vom 5.1.1992 (SAT*1) ausgetauscht.','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0003-02','\"Yankees\"','\"Wildwest im Weldraum\"','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0053-01','Originaltitel: For Your Eyes Only','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0053-02','Originaltitel: Blind Fury','Action zum Nachdenken','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0054-02','Originaltitel: The Man With the Golden Gun','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0054-01','Originaltitel: Never Say Never Again','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0055-01','Originaltitel: High Anxiety','','\"Nicht nur fÅr Hitchcock-Kenner ein Mordsspa·!\" (TV-Spielfilm)','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0055-02','Originaltitel: Silent Movie','','\"Ein Unikum der Filmgeschichte: Urkomisch!\" (TV-Spielfilm)','','Weitere Darsteller: Sid Caesar, Marcel Marceau','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0056-01','Originaltitel: Yeah! Yeah! Yeah!','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0063-02','Originaltitel: Star Trek II - The Wrath of Khan','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0063-01','Originaltitel: Star Trek - The Motion Picture','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0065-01','O: The Final Frontier','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0065-02','O: The undiscovered country','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0066-01','O: To Be or Not to Be','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0066-02','Video vom Abschlu·-Tanz','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0067-01','O: Logan\''s Run','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0073-01','O: Asterix et la surprise de Cesar','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0073-02','O: Asterix chez les Bretons','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0074-01','O: Dr. No','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0075-02','O: Love at first Bite','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0076-01','O: The Naked Gun: From the Files of Police Squad!','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0079-01','Pilotfilm sowie Season 1, Eps 1-6','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0080-01','Season 1, Eps 7-15','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0081-01','Season 1, Eps 16 - Season II, Eps 2','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0082-01','Season 2, Eps 3 - 11','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0083-01','Season 2, Eps 12 - 19','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0084-01','Season 2, Eps 20 - Season 3, Eps 5','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0074-02','O: The Living Daylights','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0085-01','Season 3 Eps 6 - 13','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0086-01','Season 3 Eps 14 - Season 4 Eps 1','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0087-01','Season 4 Eps 2 - 10','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0088-01','Season 4 Eps 11 - 20','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0089-01','Season 4 Eps 21 - Season 5 Eps 8','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0090-01','Season 5 Eps 9-20','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0091-01','Season 5 Eps 21-22','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0092-01','O: Dead Poet\''s Society','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0092-02','Nicht unbedingt lohnenswert.','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0093-01','O: The Distinguished Gentleman','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0095-01','O: Mounty Python\''s Life of Brian','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0095-02','O: Mr. Nanny','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0096-01','O: History of the World, Part I','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0097-01','\"Wer hat dem Rabbi den Koks geklaut?\"','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0093-02','O: The Naked Gun 2 1/2','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0045-03','Qumran-Bericht: Jesus ein Essener?','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0099-01','O: Mission Impossible','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0102-01','O: The Ten Commandments','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0103-01','O: Almost an Angel','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0103-02','O: Under Siege','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0104-01','Dolby Sourround','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0104-02','Dolby Sourround','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0096-02','O: The Pope Must Die','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0037-02','O: Stop! Or My Mom Will Shoot','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0091-02','spielt 5 Jahre nach GrÅndung der interstellaren Allianz (also 6 Jahre','nach Ende des gro·en Krieges gegen die Schatten).','Handlung: Die Drak planen einen Angriff auf die Erde...','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0091-03','spielt im Juli des Jahres 2263.','Auf der Suche nach dem ewigen Leben bringt ein Forscher etwas auf die','Station, was dieser sehr gefÑhrlich wird...','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0030-03','US-Raumfahrt: Der erste Mann auf dem Mond und wie er dahin kam','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0059-02','O: Battle Beyond the Stars','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0107-01','O: Schindler\''s List','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0108-01','O: Barb Wire','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0109-02','O: Best Defense','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0026-04','\"Best Video\" at MTV Europe Award 1999 in Dublin','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0026-05','Live at MTV Europe Award 1999 in Dublin','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0026-07','Live at MTV Europe Award 1999 in Dublin','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0037-07','Live','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0110-01','O: Guarding Tess','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0111-02','O: Hot Shots Take 2','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0112-01','Englisch mit deutschen Untertiteln','(Film komplett gesungen)','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0106-02','O: Scrooged','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0113-01','Dolby Sourround','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0108-02','Dolby Sourround','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0114-01','O: The Nutty Professor','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0097-02','O: The Frisco Kid','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0062-02','O: The Young Indiana Jones Chronicles: German East Africa, Early','November 1916','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0116-01','O: The Jackal','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0116-02','Englisches Original mit deutschen Untertiteln','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0117-01','O: Clear and Present Danger','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0102-02','O: A Stranger Among Us','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0118-01','O: Le cinquiäme elÇment','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0119-01','O: The Hunt for Red October','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0120-02','English Original','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0073-03','O: AstÇrix le Gaulois','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0121-01','vierteilige Dokumentation; vierter Teil leider nicht ganz vollstÑndig','(Anfang fehlt)','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('123-01','O: The Last Starfighter','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('119-02','Der GrÅne Ritter (S. Connery) fordert Kînig Artus samt der Tafelrunde','heraus. Gawain (M. O\''Keeffe) tritt fÅr seinen Herrn den Zweikampf an.','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0113-02','Den Waiapi gelingt es, ihre kulturelle Tradition zu wahren und','trotzdem die VorzÅge der westlichen Kultur zu nutzen','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0124-01','O: Tomorrow Never Dies','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
INSERT into bemerk Values ('0117-02','O: William Shakespeare\''s Romeo & Juliet','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');
