# MySQL table created by DBV

# delete table if already exists
DROP TABLE IF EXISTS kat;

# create a new table
CREATE table kat (
       KATE Char(15)
);

INSERT into kat Values ('Abenteuer');
INSERT into kat Values ('Action');
INSERT into kat Values ('Agentenfilm');
INSERT into kat Values ('Bibelfilm');
INSERT into kat Values ('Biographie');
INSERT into kat Values ('BÅhnenstÅck');
INSERT into kat Values ('Dokumentar');
INSERT into kat Values ('Dokumentarfilm');
INSERT into kat Values ('Drama');
INSERT into kat Values ('Fantasy');
INSERT into kat Values ('Feier');
INSERT into kat Values ('Gruselfilm');
INSERT into kat Values ('Historie');
INSERT into kat Values ('Horror');
INSERT into kat Values ('Judaistik');
INSERT into kat Values ('Kamera');
INSERT into kat Values ('Katastrophe');
INSERT into kat Values ('Kinder');
INSERT into kat Values ('Komîdie');
INSERT into kat Values ('Konzert');
INSERT into kat Values ('Krieg');
INSERT into kat Values ('Kriegsfilm');
INSERT into kat Values ('Krimi');
INSERT into kat Values ('Liebesfilm');
INSERT into kat Values ('MÑrchenfilm');
INSERT into kat Values ('Melodrama');
INSERT into kat Values ('Monumental');
INSERT into kat Values ('Monumentalfilm');
INSERT into kat Values ('Musical');
INSERT into kat Values ('Musik');
INSERT into kat Values ('Musik-Videoclip');
INSERT into kat Values ('Musikfilm');
INSERT into kat Values ('Naturfilm');
INSERT into kat Values ('Oper');
INSERT into kat Values ('Operette');
INSERT into kat Values ('Problemfilm');
INSERT into kat Values ('Reportage');
INSERT into kat Values ('Satire');
INSERT into kat Values ('Science Fiction');
INSERT into kat Values ('Show');
INSERT into kat Values ('Sonstige');
INSERT into kat Values ('Spionagefilm');
INSERT into kat Values ('Thriller');
INSERT into kat Values ('Tier');
INSERT into kat Values ('Tierfilm');
INSERT into kat Values ('Travestie');
INSERT into kat Values ('Urlaub');
INSERT into kat Values ('Weihnachten');
INSERT into kat Values ('Western');
INSERT into kat Values ('Western-Komîdie');
INSERT into kat Values ('Zeichentrick');
