# MySQL table created by DBV

# delete table if already exists
DROP TABLE IF EXISTS land;

# create a new table
CREATE table land (
       LAND Char(30)
);

INSERT into land Values ('Algerien');
INSERT into land Values ('Argentinien');
INSERT into land Values ('égypten');
INSERT into land Values ('Belgien');
INSERT into land Values ('Brasilien');
INSERT into land Values ('Bremen');
INSERT into land Values ('CSFR');
INSERT into land Values ('DÑnemark');
INSERT into land Values ('Deutschland');
INSERT into land Values ('England');
INSERT into land Values ('Finnland');
INSERT into land Values ('Frankreich');
INSERT into land Values ('Holland');
INSERT into land Values ('Indien');
INSERT into land Values ('Irland');
INSERT into land Values ('Israel');
INSERT into land Values ('Italien');
INSERT into land Values ('Japan');
INSERT into land Values ('Jugoslawien');
INSERT into land Values ('Kanada');
INSERT into land Values ('Kolumbien');
INSERT into land Values ('Korea');
INSERT into land Values ('ôsterreich');
INSERT into land Values ('Peru');
INSERT into land Values ('Philippinen');
INSERT into land Values ('Polen');
INSERT into land Values ('Portugal');
INSERT into land Values ('RumÑnien');
INSERT into land Values ('Schottland');
INSERT into land Values ('Schweden');
INSERT into land Values ('Schweiz');
INSERT into land Values ('Spanien');
INSERT into land Values ('TÅrkei');
INSERT into land Values ('USA');
INSERT into land Values ('UdSSR');
INSERT into land Values ('Ungarn');
